infix using "C:\COUNTRIES\ET41\ETBR41FL.dct"

label variable caseid   "Case Identification"
label variable bidx     "Birth column number"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Sample weight"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Current age - respondent"
label variable v013     "Age 5-year groups"
label variable v014     "Completeness of information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar      -NA"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v019a    "Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample stratum number"
label variable v023     "Sample domain"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "Field editor"
label variable v032     "Office editor"
label variable v033     "Ultimate area selection prob."
label variable v034     "Line number of husband"
label variable v040     "Cluster altitude in meters -NA"
label variable v042     "Household selection for hemoglobin"
label variable v043     "Selection for women's status module"
label variable v044     "Selection for domestic violence"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "Childhood place of residence"
label variable v104     "Years lived in place of res."
label variable v105     "Type of place of previous res."
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Has electricity"
label variable v120     "Has radio"
label variable v121     "Has television"
label variable v122     "Has refrigerator           -NA"
label variable v123     "Has bicycle"
label variable v124     "Has motorcycle/scooter"
label variable v125     "Has car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material         -NA"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity"
label variable v133     "Education in single years"
label variable v134     "De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members"
label variable v137     "Number of children 5 and under"
label variable v138     "Number of eligible women in HH"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of res."
label variable v141     "De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Has telephone"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable v155     "Literacy"
label variable v156     "Ever participated in a lite-NA"
label variable v157     "Frequency of reading newpaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared"
label variable v161     "Type of cooking fuel"
label variable v162     "Place for hand washing     -NA"
label variable v163     "Presence of water/tap in ho-NA"
label variable v164     "Presence of soap/ash/other -NA"
label variable v165     "Presence of basin in househ-NA"
label variable v166     "Results of salt iodine test-NA"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "Date of first birth (CMC)"
label variable v212     "Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "Time since last menstrual perd"
label variable v216     "Menstruated in last six weeks"
label variable v217     "Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current preg"
label variable v220     "Living children + curr preg 6+"
label variable v221     "Marriage to first birth int."
label variable v222     "Last birth to interview"
label variable v223     "Completeness of curr preg. inf"
label variable v224     "Entries in birth history"
label variable v225     "Current pregnancy wanted"
label variable v226     "Time since last period (comp)"
label variable v227     "Flag for last period"
label variable v228     "Ever had a terminated preg."
label variable v229     "Month pregnancy ended"
label variable v230     "Year pregnancy ended"
label variable v231     "CMC pregnancy ended"
label variable v232     "Completeness of last term. inf"
label variable v233     "Months when pregnancy ended"
label variable v234     "Other such pregnancies"
label variable v235     "Index last child prior to c-NA"
label variable v237     "Birth between last & interview"
label variable v238     "Births in last three years"
label variable v239     "Pregnancies terminated befo-NA"
label variable v240     "Month of last termination p-NA"
label variable v241     "Year of last termination pr-NA"
label variable v242     "CMC termination ended prior-NA"
label variable v243     "Completeness of last termin-NA"
label variable v310     "Living children at first use"
label variable v311     "Children at first use (grpd)"
label variable v312     "Current contraceptive method"
label variable v313     "Current use by method type"
label variable v315     "Month of start of use of me-NA"
label variable v316     "Year of start of use of met-NA"
label variable v317     "Date of start of use of met-NA"
label variable v318     "Completeness of information-NA"
label variable v319     "Years since sterilization  -NA"
label variable v320     "Age at sterilization       -NA"
label variable v321     "Marital duration at sterili-NA"
label variable v322     "Parity at sterilization    -NA"
label variable v326     "Last source for current users"
label variable v327     "Last source for users by type"
label variable v337     "Months of use of current me-NA"
label variable v359     "Last method disc. last 5 ye-NA"
label variable v360     "Reason of last discontinuat-NA"
label variable v361     "Pattern of use"
label variable v362     "Intention to use"
label variable v363     "Preferred future method"
label variable v364     "Contraceptive use & intention"
label variable v367     "Wanted last child"
label variable v375a    "Main reason not using a met-NA"
label variable v376     "Main reason not to use a meth."
label variable v376a    "Would ever use method if marr."
label variable v379     "Source known for any method"
label variable v380     "Source known for any method"
label variable v384a    "Heard FP on radio last months"
label variable v384b    "Heard FP on TV last months"
label variable v384c    "Heard FP newspaper last months"
label variable v393     "Visited by FP worker last 12m"
label variable v394     "Visited health facil. last 12m"
label variable v395     "At health facility, told of FP"
label variable v3a00a   "Source of FP for non-users:-NA"
label variable v3a00b   "Source of FP for non-users:-NA"
label variable v3a00c   "Source of FP for non-users:-NA"
label variable v3a00d   "Source of FP for non-users:-NA"
label variable v3a00e   "Source of FP for non-users:-NA"
label variable v3a00f   "Source of FP for non-users:-NA"
label variable v3a00g   "Source of FP for non-users:-NA"
label variable v3a00h   "Source of FP for non-users:-NA"
label variable v3a00i   "Source of FP for non-users:-NA"
label variable v3a00j   "Source of FP for non-users:-NA"
label variable v3a00k   "Source of FP for non-users:-NA"
label variable v3a00l   "Source of FP for non-users:-NA"
label variable v3a00m   "Source of FP for non-users:-NA"
label variable v3a00n   "Source of FP for non-users:-NA"
label variable v3a00o   "Source of FP for non-users:-NA"
label variable v3a00p   "Source of FP for non-users:-NA"
label variable v3a00q   "Source of FP for non-users:-NA"
label variable v3a00r   "Source of FP for non-users:-NA"
label variable v3a00s   "Source of FP for non-users:-NA"
label variable v3a00t   "Source of FP for non-users:-NA"
label variable v3a00u   "Source of FP for non-users:-NA"
label variable v3a00v   "Source of FP for non-users:-NA"
label variable v3a00w   "Source of FP for non-users:-NA"
label variable v3a00x   "Source of FP for non-users:-NA"
label variable v3a00y   "Source of FP for non-users:-NA"
label variable v3a00z   "Source of FP for non-users:-NA"
label variable v3a01    "Told sterilization would me-NA"
label variable v3a02    "Told about side effects    -NA"
label variable v3a03    "Told about side effects by -NA"
label variable v3a04    "Told how to deal with side -NA"
label variable v3a05    "Told about other FP methods-NA"
label variable v3a06    "Told about other FP methods-NA"
label variable v3a07    "First source for current method"
label variable v3a08a   "Reason not using: Not married"
label variable v3a08b   "Reason not using: Not having sex"
label variable v3a08c   "Reason not using: Infrequent sex"
label variable v3a08d   "Reason not using: Menopausal/hysterectomy"
label variable v3a08e   "Reason not using: Subfecund/infecund"
label variable v3a08f   "Reason not using: Postpartum amenorrheic"
label variable v3a08g   "Reason not using: Breastfeeding"
label variable v3a08h   "Reason not using: Fatalistic"
label variable v3a08i   "Reason not using: Respondent opposed"
label variable v3a08j   "Reason not using: Husband/partner opposed"
label variable v3a08k   "Reason not using: Others opposed"
label variable v3a08l   "Reason not using: Religious prohibition"
label variable v3a08m   "Reason not using: Knows no method"
label variable v3a08n   "Reason not using: Knows no source"
label variable v3a08o   "Reason not using: Health concerns"
label variable v3a08p   "Reason not using: Fear of side effects"
label variable v3a08q   "Reason not using: Lack of access/too far"
label variable v3a08r   "Reason not using: Costs too much"
label variable v3a08s   "Reason not using: Inconvenient to use"
label variable v3a08t   "Reason not using: Interferes with bodys processes"
label variable v3a08u   "Reason not using: Country s-NA"
label variable v3a08v   "Reason not using: Country s-NA"
label variable v3a08w   "Reason not using: Country s-NA"
label variable v3a08x   "Reason not using: Other"
label variable v3a08z   "Reason not using: Don't know"
label variable v401     "Last birth ceasarean section"
label variable v404     "Currently breastfeeding"
label variable v405     "Currently amenorrheic"
label variable v406     "Currently abstaining"
label variable v407     "Times breastfed during night"
label variable v408     "Times breastfed during day"
label variable v415     "Drank from bottle with nipple"
label variable v416     "Heard of oral rehydration"
label variable v417     "Entries in maternity table"
label variable v418     "Entries in health table"
label variable v419     "Entries in height/weight table"
label variable v420     "Measurer's code            -NA"
label variable v421     "Assistant measurer's code  -NA"
label variable v426     "When child put to breast"
label variable v437     "Respondent's weight (kilos-1d)"
label variable v438     "Respondent's height (cms-1d)"
label variable v439     "Ht/A Percentile (resp.)"
label variable v440     "Ht/A Standard deviations (resp"
label variable v441     "Ht/A Percent ref. median (resp"
label variable v442     "Wt/Ht Percent ref. median (DHS"
label variable v443     "Wt/Ht Percent ref. median (Fog"
label variable v444     "Wt/Ht Percent ref. median (WHO"
label variable v444a    "Wt/Ht Std deviations(resp) DHS"
label variable v445     "Body mass index for respondent"
label variable v446     "Rohrer's index for respondent"
label variable v447     "Result of measurement of resp."
label variable v447a    "Women's age in years from household report"
label variable v452a    "Under age 18 (HH report)   -NA"
label variable v452b    "Line no. of parent/caretake-NA"
label variable v452c    "Read consent statement     -NA"
label variable v453     "Hemoglobin level (g/dl - 1 -NA"
label variable v454     "Currently pregnant (househo-NA"
label variable v455     "Result of measuring (Hemogl-NA"
label variable v456     "Hemoglobin level adjusted b-NA"
label variable v457     "Anemia level               -NA"
label variable v458     "Agrees to referral         -NA"
label variable v459     "Have bednet for sleeping (household report)"
label variable v460     "Children under 5 slept unde-NA"
label variable v461     "Respondent slept under bedn-NA"
label variable v462     "Washed hands before preparing last meal"
label variable v463a    "Smokes cigarettes          -NA"
label variable v463b    "Smokes pipe                -NA"
label variable v463c    "Smokes other tobacco       -NA"
label variable v463d    "Smokes country specific    -NA"
label variable v463e    "Smokes country specific    -NA"
label variable v463f    "Smokes country specific    -NA"
label variable v463g    "Smokes country specific    -NA"
label variable v463z    "Smokes nothing             -NA"
label variable v464     "Number of cigarettes in las-NA"
label variable v465     "Disposal of youngest child's stools when not using toilet"
label variable v466     "When child is seriously ill, can decide whether med tx sough"
label variable v467a    "Getting medical help for se-NA"
label variable v467b    "Getting medical help for se-NA"
label variable v467c    "Getting medical help for se-NA"
label variable v467d    "Getting medical help for se-NA"
label variable v467e    "Getting medical help for se-NA"
label variable v467f    "Getting medical help for se-NA"
label variable v467g    "Getting medical help for se-NA"
label variable v468     "Columns used for Last Birth Only variables"
label variable v469a    "Times gave child plain water"
label variable v469b    "Times gave child sugar wate-NA"
label variable v469c    "Times gave child fruit juice"
label variable v469d    "Times gave child herbal tea-NA"
label variable v469e    "Times gave child powdered/t-NA"
label variable v469f    "Times gave child commercial-NA"
label variable v469g    "Times gave child fresh milk-NA"
label variable v469h    "Times given tinned, powdered or fresh animal milk"
label variable v469i    "Times given country specifi-NA"
label variable v469j    "Times given country specifi-NA"
label variable v469k    "Times given country specifi-NA"
label variable v469l    "Times gave child other liquid"
label variable v469m    "Times given pumpkin, carrot-NA"
label variable v469n    "Times given any green leafy-NA"
label variable v469o    "Times given mango, papaya or other Vit A rich fruits"
label variable v469p    "Times given other solid, se-NA"
label variable v469q    "Times given food made from local grain"
label variable v469r    "Times given food made from local roots/tuber"
label variable v469s    "Times gave child eggs, fish-NA"
label variable v469t    "Times gave child meat      -NA"
label variable v469u    "Times gave child other fruits/vegetables"
label variable v469v    "Times gave child meat, poultry, fish, shellfish, eggs"
label variable v469w    "Times gave child legumes (lentils, beans, peanuts)"
label variable v469x    "Times gave child cheese/yog-NA"
label variable v469y    "Times gave child foods made from oil, fat, butter"
label variable v469z    "Times gave child country sp-NA"
label variable v469xx   "Times gave child country sp-NA"
label variable v469xy   "Times gave child country sp-NA"
label variable v469xz   "Times gave child country sp-NA"
label variable v470a    "Last 7 days - plain water"
label variable v470b    "Last 7 days - sugar water  -NA"
label variable v470c    "Last 7 days - fruit juice"
label variable v470d    "Last 7 days -  herbal tea  -NA"
label variable v470e    "Last 7 days - powder/tinned-NA"
label variable v470f    "Last 7 days - commercially -NA"
label variable v470g    "Last 7 days -  fresh milk  -NA"
label variable v470h    "Last 7 days - tinned, powdered or fresh animal milk"
label variable v470i    "Last 7 days - country speci-NA"
label variable v470j    "Last 7 days - country speci-NA"
label variable v470k    "Last 7 days - country speci-NA"
label variable v470l    "Last 7 days -  other liquid"
label variable v470m    "Last 7 days - pumpkin, carr-NA"
label variable v470n    "Last 7 days - any green lea-NA"
label variable v470o    "Last 7 days - mango, papaya or other Vit A rich fruits"
label variable v470p    "Last 7 days - other solid, -NA"
label variable v470q    "Last 7 days - food made from local grain"
label variable v470r    "Last 7 days - food made from local roots/tuber"
label variable v470s    "Last 7 days - eggs, fish, p-NA"
label variable v470t    "Last 7 days - meat         -NA"
label variable v470u    "Last 7 days -  other fruits/vegetables"
label variable v470v    "Last 7 days -  meat, poultry, fish, shellfish, eggs"
label variable v470w    "Last 7 days - legumes (lentils, beans, peanuts)"
label variable v470x    "Last 7 days - cheese/yogurt-NA"
label variable v470y    "Last 7 days - foods made with oil, fat, butter"
label variable v470z    "Last 7 days - country speci-NA"
label variable v470xx   "Last 7 days - country speci-NA"
label variable v470xy   "Last 7 days - country speci-NA"
label variable v470xz   "Last 7 days - country speci-NA"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never marr."
label variable v503     "Number of unions"
label variable v504     "Husband lives in house"
label variable v505     "Number of other wives"
label variable v506     "Wife rank number"
label variable v507     "Month of first marriage"
label variable v508     "Year of first marriage"
label variable v509     "Date of first marriage (CMC)"
label variable v510     "Completeness of date inform."
label variable v511     "Age at first marriage"
label variable v512     "Years since first marriage"
label variable v513     "Marital duration (grouped)"
label variable v525     "Age at first intercourse"
label variable v527     "Time since last intercourse"
label variable v528     "Time since last intercourse(g)"
label variable v529     "Time since last intercourse(imputed)"
label variable v530     "Flag for V529"
label variable v531     "Age at first intercourse (imp)"
label variable v532     "Flag for V531"
label variable v535     "Have ever been married"
label variable v536     "Recent sexual activity"
label variable v537     "Months of abstinence"
label variable v602     "Fertility preference"
label variable v603     "Preferred waiting time"
label variable v604     "Preferred waiting time (grpd)"
label variable v605     "Desire for more children"
label variable v610     "Husband approves FP"
label variable v611     "Discussed FP with partner"
label variable v612     "Respondent approves FP"
label variable v613     "Ideal number of children"
label variable v614     "Ideal number of children (grp)"
label variable v616     "Time for future birth"
label variable v621     "Husbands desire for children"
label variable v623     "Exposure"
label variable v624     "Unmet need"
label variable v625     "Exposure (definition 2)"
label variable v626     "Unmet need (definition 2)"
label variable v627     "Ideal number of boys"
label variable v628     "Ideal number of girls"
label variable v629     "Ideal number of either sex"
label variable v630a    "Discussed FP with partner"
label variable v630b    "Discussed FP with mother"
label variable v630c    "Discussed FP with father"
label variable v630d    "Discussed FP with sister(s)"
label variable v630e    "Discussed FP with brother(s)"
label variable v630f    "Discussed FP with daughter(s)"
label variable v630g    "Discussed FP with mother-in-law"
label variable v630h    "Discussed FP with friends/nbrs"
label variable v630i    "Discussed FP with son(s)"
label variable v630j    "Discussed FP -country speci-NA"
label variable v630k    "Discussed FP -country speci-NA"
label variable v630l    "Discussed FP -country speci-NA"
label variable v630m    "Discussed FP -country speci-NA"
label variable v630n    "Discussed FP -country speci-NA"
label variable v630o    "Discussed FP -country speci-NA"
label variable v630x    "Discussed FP with others"
label variable v631     "Problem if became pregnant"
label variable v632     "Decision maker for using contraception"
label variable v633a    "Reason for not having sex: -NA"
label variable v633b    "Reason for not having sex: -NA"
label variable v633c    "Reason for not having sex: -NA"
label variable v633d    "Reason for not having sex: -NA"
label variable v633e    "Reason for not having sex: -NA"
label variable v633f    "Reason for not having sex: -NA"
label variable v633g    "Reason for not having sex: -NA"
label variable v701     "Partner's education level"
label variable v702     "Highest year of education"
label variable v704     "Partner's occupation"
label variable v705     "Partner's occupation"
label variable v714     "Respondent currently working"
label variable v715     "Husbands education-single yrs"
label variable v716     "Respondent's occupation"
label variable v717     "Respondent's occupation"
label variable v719     "Work for family, others, self"
label variable v721     "Works at home or away"
label variable v729     "Partner's educational attainm."
label variable v730     "Partners age"
label variable v731     "Worked in last 12 months"
label variable v732     "Employment all year/seasonal"
label variable v739     "Who decides how to spend money"
label variable v740     "Type of land where resp. works"
label variable v741     "Type of earnings for work"
label variable v742     "Portion of household expend-NA"
label variable v743a    "Final say on own health car-NA"
label variable v743b    "Final say on making large h-NA"
label variable v743c    "Final say on making househo-NA"
label variable v743d    "Final say on visits to fami-NA"
label variable v743e    "Final say on food to be coo-NA"
label variable v744a    "Wife beating justified if she goes out without telling him"
label variable v744b    "Wife beating justified if she neglects the children"
label variable v744c    "Wife beating justified if she argues with him"
label variable v744d    "Wife beating justified if she refuses to have sex with him"
label variable v744e    "Wife beating justified if she burns the food"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "Age at death"
label variable b7       "Age at death (months-imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval"
label variable b12      "Succeeding birth interval"
label variable b13      "Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable midx     "Index to birth history"
label variable m1       "Tetanus injections bef. birth"
label variable m2a      "Prenatal: doctor           -NA"
label variable m2b      "Prenatal: nurse/midwife    -NA"
label variable m2c      "Prenatal: auxiliary midwife-NA"
label variable m2d      "Prenatal: CS health professional"
label variable m2e      "Prenatal: CS health profess-NA"
label variable m2f      "Prenatal: trained birth att."
label variable m2g      "Prenatal: trad.birth attendant"
label variable m2h      "Prenatal: relative         -NA"
label variable m2i      "Prenatal: CS other person  -NA"
label variable m2j      "Prenatal: CS other person  -NA"
label variable m2k      "Prenatal: other resp (uncoded)"
label variable m2l      "Prenatal: CS other         -NA"
label variable m2m      "Prenatal: CS other         -NA"
label variable m2n      "Prenatal: no one"
label variable m3a      "Assistance: doctor         -NA"
label variable m3b      "Assistance: nurse/midwife  -NA"
label variable m3c      "Assistance: auxiliary midwi-NA"
label variable m3d      "Assistance: CS health professional"
label variable m3e      "Assistance: CS health profe-NA"
label variable m3f      "Assistance: trained birth att."
label variable m3g      "Assistance: trad.birth attend."
label variable m3h      "Assistance: relative, friend"
label variable m3i      "Assistance: CS other person-NA"
label variable m3j      "Assistance: CS other person-NA"
label variable m3k      "Assistance: other resp (uncod)"
label variable m3l      "Assistance: CS other       -NA"
label variable m3m      "Assistance: CS other       -NA"
label variable m3n      "Assistance: no one"
label variable m4       "Duration of breastfeeding"
label variable m5       "Months of breastfeeding"
label variable m6       "Duration of amenorrhea"
label variable m7       "Months of amenorrhea"
label variable m8       "Duration of abstinence"
label variable m9       "Months of abstinence"
label variable m10      "Time wanted pregnancy"
label variable m11      "Time would have waited"
label variable m13      "Timing of 1st antenatal check"
label variable m14      "Antenatal visits for pregnancy"
label variable m15      "Place of delivery"
label variable m17      "Delivery by caesarian section"
label variable m18      "Size of child at birth"
label variable m19      "Birth weight (kilos - 3 dec.)"
label variable m19a     "Weight at birth recall"
label variable m27      "Flag for breastfeeding"
label variable m28      "Flag for amenorrhea"
label variable m29      "Flag for abstinence"
label variable m34      "When child put to breast"
label variable m35      "Times breastfed during night"
label variable m36      "Times breastfed during day"
label variable m37a     "Times gave child plain water"
label variable m37b     "Times gave child sugar wate-NA"
label variable m37c     "Times gave child fruit juice"
label variable m37d     "Times gave child herbal tea-NA"
label variable m37e     "Times gave child powdered/t-NA"
label variable m37f     "Times gave child commercial-NA"
label variable m37g     "Times gave child fresh milk-NA"
label variable m37h     "Times given tinned, powdered or fresh animal milk"
label variable m37i     "Times given country specifi-NA"
label variable m37j     "Times given country specifi-NA"
label variable m37k     "Times given country specifi-NA"
label variable m37l     "Times gave child other liquid"
label variable m37m     "Times given pumpkin, carrot-NA"
label variable m37n     "Times given any green leafy-NA"
label variable m37o     "Times given mango, papaya or other Vit A rich fruits"
label variable m37p     "Times given other solid, se-NA"
label variable m37q     "Times given food made from local grain"
label variable m37r     "Times given food made from local roots/tuber"
label variable m37s     "Times gave child eggs, fish-NA"
label variable m37t     "Times gave child meat      -NA"
label variable m37u     "Times gave child other fruits/vegetables"
label variable m37v     "Times gave child meat, poultry, fish, shellfish, eggs"
label variable m37w     "Times gave child legumes (lentils, beans, peanuts)"
label variable m37x     "Times gave child cheese/yog-NA"
label variable m37y     "Times gave child foods made with oil, fat, butter"
label variable m37z     "Times gave child country sp-NA"
label variable m37xx    "Times gave child country sp-NA"
label variable m37xy    "Times gave child country sp-NA"
label variable m37xz    "Times gave child country sp-NA"
label variable m38      "Drank from bottle with nipple"
label variable m39      "Times ate solid, semi-solid or soft food yesterday"
label variable m40a     "Last 7 days - plain water"
label variable m40b     "Last 7 days - sugar water  -NA"
label variable m40c     "Last 7 days - fruit juice"
label variable m40d     "Last 7 days - herbal tea   -NA"
label variable m40e     "Last 7 days - powdered/tinn-NA"
label variable m40f     "Last 7 days - commercially -NA"
label variable m40g     "Last 7 days - fresh milk   -NA"
label variable m40h     "Last 7 days - tinned, powdered or fresh animal milk"
label variable m40i     "Last 7 days - country speci-NA"
label variable m40j     "Last 7 days - country speci-NA"
label variable m40k     "Last 7 days - country speci-NA"
label variable m40l     "Last 7 days - other liquid"
label variable m40m     "Last 7 days - pumpkin, carr-NA"
label variable m40n     "Last 7 days - any green lea-NA"
label variable m40o     "Last 7 days - mango, papaya or other Vit A rich fruits"
label variable m40p     "Last 7 days - other solid, -NA"
label variable m40q     "Last 7 days - food made from local grain"
label variable m40r     "Last 7 days - food made from local roots/tuber"
label variable m40s     "Last 7 days - eggs, fish, p-NA"
label variable m40t     "Last 7 days - meat         -NA"
label variable m40u     "Last 7 days - other fruits/vegetables"
label variable m40v     "Last 7 days - meat, poultry, fish, shellfish, eggs"
label variable m40w     "Last 7 days - legumes (lentils, beans, peanuts)"
label variable m40x     "Last 7 days - cheese/yogurt-NA"
label variable m40y     "Last 7 days - foods made with oil, fat, butter"
label variable m40z     "Last 7 days - country speci-NA"
label variable m40xx    "Last 7 days - country speci-NA"
label variable m40xy    "Last 7 days - country speci-NA"
label variable m40xz    "Last 7 days - country speci-NA"
label variable m41      "Months pregnant for last antenatal visit"
label variable m42a     "During pregnancy - weighed"
label variable m42b     "During pregnancy - height measured"
label variable m42c     "During pregnancy - blood pressure taken"
label variable m42d     "During pregnancy - urine sample taken"
label variable m42e     "During pregnancy - blood sample taken"
label variable m43      "Told about pregnancy complications"
label variable m44      "Told where to go for pregnancy complications"
label variable m45      "During pregancy, given or b-NA"
label variable m46      "Days tablets or syrup taken-NA"
label variable m47      "During pregnancy, had difficulty with daylight vision"
label variable m48      "During pregnancy, had difficulty with night blindness"
label variable m49a     "During pregnancy - took Fansidar for Malaria"
label variable m49b     "During pregnancy - took Chloroquine for Malaria"
label variable m49c     "During pregnancy - took Unknown Drug for Malaria"
label variable m49d     "During pregnancy - took proguanil for Malaria"
label variable m49e     "During pregnancy - took cou-NA"
label variable m49f     "During pregnancy - took cou-NA"
label variable m49g     "During pregnancy - took cou-NA"
label variable m49x     "During pregnancy - took other drug for Malaria"
label variable m49z     "During pregnancy - took no drug for Malaria"
label variable m50      "After birth, health professional checked health"
label variable m51      "Checkup after deliver timing"
label variable m52      "After birth, health professional checked health"
label variable m53      "Place for checkup"
label variable m54      "Received Vitamin A dose in first 2 months after delivery"
label variable m55a     "First 3 days, given milk ot-NA"
label variable m55b     "First 3 days, given plain w-NA"
label variable m55c     "First 3 days, given sugar/g-NA"
label variable m55d     "First 3 days, given gripe w-NA"
label variable m55e     "First 3 days, given sugar/s-NA"
label variable m55f     "First 3 days, given fruit j-NA"
label variable m55g     "First 3 days, given infant -NA"
label variable m55h     "First 3 days, given tea/inf-NA"
label variable m55i     "First 3 days, given honey  -NA"
label variable m55j     "First 3 days, given country-NA"
label variable m55k     "First 3 days, given country-NA"
label variable m55l     "First 3 days, given country-NA"
label variable m55m     "First 3 days, given country-NA"
label variable m55n     "First 3 days, given country-NA"
label variable m55x     "First 3 days, given other  -NA"
label variable m55z     "First 3 days, given nothing-NA"
label variable m56      "Sugar added to any of foods-NA"
label variable hidx     "Index to birth history"
label variable h1       "Has health card"
label variable h2       "Received BCG"
label variable h2d      "BCG day"
label variable h2m      "BCG month"
label variable h2y      "BCG year"
label variable h3       "Received DPT 1"
label variable h3d      "DPT 1 day"
label variable h3m      "DPT 1 month"
label variable h3y      "DPT 1 year"
label variable h4       "Received POLIO 1"
label variable h4d      "POLIO 1 day"
label variable h4m      "POLIO 1 month"
label variable h4y      "POLIO 1 year"
label variable h5       "Received DPT 2"
label variable h5d      "DPT 2 day"
label variable h5m      "DPT 2 month"
label variable h5y      "DPT 2 year"
label variable h6       "Received POLIO 2"
label variable h6d      "POLIO 2 day"
label variable h6m      "POLIO 2 month"
label variable h6y      "POLIO 2 year"
label variable h7       "Received DPT 3"
label variable h7d      "DPT 3 day"
label variable h7m      "DPT 3 month"
label variable h7y      "DPT 3 year"
label variable h8       "Received POLIO 3"
label variable h8d      "POLIO 3 day"
label variable h8m      "POLIO 3 month"
label variable h8y      "POLIO 3 year"
label variable h9       "Received MEASLES"
label variable h9d      "MEASLES day"
label variable h9m      "MEASLES month"
label variable h9y      "MEASLES year"
label variable h0       "Polio 0"
label variable h0d      "Polio 0 day"
label variable h0m      "POLIO 0 month"
label variable h0y      "POLIO 0 year"
label variable h10      "Ever had vaccination"
label variable h11      "Had diarrhea recently"
label variable h12a     "Diarrhea: government hosp."
label variable h12b     "Diarrhea: govt health center"
label variable h12c     "Diarrhea: govt health post"
label variable h12d     "Diarrhea: mobile clinic    -NA"
label variable h12e     "Diarrhea: comm. based outlet"
label variable h12f     "Diarrhea: CS: health station / clinic"
label variable h12g     "Diarrhea: CS other government"
label variable h12h     "Diarrhea: CS public sector -NA"
label variable h12i     "Diarrhea: other public sect-NA"
label variable h12j     "Diarrhea: private hosp/clin."
label variable h12k     "Diarrhea: private pharmacy"
label variable h12l     "Diarrhea: private doctor"
label variable h12m     "Diarrhea: private mobile cl-NA"
label variable h12n     "Diarrhea: comm. based outlet"
label variable h12o     "Diarrhea: CS NGO health facility"
label variable h12p     "Diarrhea: CS other NGO"
label variable h12q     "Diarrhea: CS other private medical"
label variable h12r     "Diarrhea: other med.priv se-NA"
label variable h12s     "Diarrhea: shop"
label variable h12t     "Diarrhea: traditional pract."
label variable h12u     "Diarrhea: CS drug vendor"
label variable h12v     "Diarrhea: CS country specic-NA"
label variable h12w     "Diarrhea: CS oth.priv secto-NA"
label variable h12x     "Diarrhea: Other"
label variable h12y     "Diarrhea: no treatment"
label variable h12z     "Diarrhea: medical treatment"
label variable h13      "Given oral rehydration"
label variable h14      "Given recommend. home solution"
label variable h15      "Given other pills or syrups"
label variable h15a     "Given antibiotics (CS)     -NA"
label variable h15b     "Given an injection"
label variable h15c     "Given an intravenous (IV)"
label variable h15d     "Given home remedy, herbal med."
label variable h15e     "Given CS other treatment   -NA"
label variable h15f     "Given CS other treatment   -NA"
label variable h15g     "Given CS other treatment  -NA"
label variable h15h     "Given CS other treatment   -NA"
label variable h20      "Given other treatment"
label variable h21a     "Given no treatment"
label variable h21      "Received any treatment"
label variable h22      "Had fever in last two weeks"
label variable h31      "Had cough in last two weeks"
label variable h31b     "Short, rapid breaths"
label variable h32a     "Fever/cough: government hosp."
label variable h32b     "Fever/cough: govt health cntr"
label variable h32c     "Fever/cough: govt health post"
label variable h32d     "Fever/cough: mobile clinic -NA"
label variable h32e     "Fever/cough: comm. based outlet"
label variable h32f     "Fever/cough: Health station / clinic"
label variable h32g     "Fever/cough: CS other public sector"
label variable h32h     "Fever/cough: CS public sect-NA"
label variable h32i     "Fever/cough: oth public sec-NA"
label variable h32j     "Fever/cough: private hosp/clin"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: private mobile-NA"
label variable h32n     "Fever/cough: NGO comm. based outlet"
label variable h32o     "Fever/cough: NGO health facility"
label variable h32p     "Fever/cough: NGO other"
label variable h32q     "Fever/cough: Other private medical"
label variable h32r     "Fever/cough: oth med.priv s-NA"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional pract"
label variable h32u     "Fever/cough: Drug vendor"
label variable h32v     "Fever/cough: CS oth.priv se-NA"
label variable h32w     "Fever/cough: CS oth.priv se-NA"
label variable h32x     "Fever/cough: Other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h33      "Received Vitamin A         -NA"
label variable h33d     "Vitamin A Day              -NA"
label variable h33m     "Vitamin A month            -NA"
label variable h33y     "Vitamin A year             -NA"
label variable h34      "Vitamin A in last 6 months"
label variable h35      "Any vaccinations in last 2 years part of campaign"
label variable h36a     "Vaccinated during Tikemt/Hidar 1990"
label variable h36b     "Vaccinated during Tikemt/Hidar 1991"
label variable h36c     "Vaccinated during Tikemt/Hidar 1992"
label variable h36d     "Vaccinated during Campaign -NA"
label variable h36e     "Vaccinated during Campaign -NA"
label variable h36f     "Vaccinated during Campaign -NA"
label variable h37a     "Fansidar taken for fever"
label variable h37b     "Chloroquine taken for fever"
label variable h37c     "Aspirin taken for fever"
label variable h37d     "Ibuprofen/acetaminophen taken for fever"
label variable h37e     "CS: quinine taken for fever"
label variable h37f     "CS: antibiotics taken for fever"
label variable h37g     "Country specific taken for -NA"
label variable h37h     "Country specific taken for -NA"
label variable h37x     "Other taken for fever"
label variable h37y     "Nothing taken for fever"
label variable h37z     "Don't know if or what was taken"
label variable h38      "Had diarrhea in last 2 weeks: Amount offered to drink"
label variable h39      "Had diarrhea in last 2 weeks: Amount offered to eat"
label variable hwidx    "Index to birth history"
label variable hw1      "Age in months"
label variable hw2      "Weight in kilograms (1 dec.)"
label variable hw3      "Height in centimeters (1 dec.)"
label variable hw4      "Ht/A Percentile"
label variable hw5      "Ht/A Standard deviations"
label variable hw6      "Ht/A Percent of ref. median"
label variable hw7      "Wt/A Percentile"
label variable hw8      "Wt/A Standard deviations"
label variable hw9      "Wt/A Percent of ref. median"
label variable hw10     "Wt/Ht Percentile"
label variable hw11     "Wt/Ht Standard deviations"
label variable hw12     "Wt/Ht Percent of ref. median"
label variable hw13     "Reason not measured"
label variable hw15     "Height: lying or standing"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line no. of parent/caretaker"
label variable hw52     "Read consent statement"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measuring (Hemoglobin)"
label variable hw56     "Hemoglobin level adjusted by altitud (g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable hw58     "Agrees to referral"
label variable sintdg   "Day of interview - Gregorian calendar"
label variable sintmg   "Month of interview - Gregorian calendar"
label variable sintyg   "Year of interview - Gregorian calendar"
label variable sintcg   "Date of interview (CMC) - Gregorian calendar"
label variable slan     "Language of questionnaire"
label variable sintv    "Interview language"
label variable sresp    "Respondent's language"
label variable strans   "Translator used"
label variable s101t    "Morning/evening"
label variable s101h    "Start of interview (hour)"
label variable s101m    "Start of interview (minutes)"
label variable s105mg   "Month of birth - Gregorian calendar"
label variable s105yg   "Year of birth - Gregorian calendar"
label variable s105cg   "Date of birth (CMC) - Gregorian calendar"
label variable s109     "Highest grade at that level"
label variable s227cg   "Date of conception (CMC) - gregorian calendar"
label variable s230ac   "Cmc last termination"
label variable s230af   "Date flag for Q230AC"
label variable s230b    "Month/years last pregancy ended"
label variable s230amg  "Month pregnancy ended - Gregorian calendar"
label variable s230ayg  "Year pregnancy ended - Gregorian calendar"
label variable s230acg  "Cmc last termination - Gregorian calendar"
label variable s230f    "Number of other non live pregnancies"
label variable s234     "Tetanus toxoid"
label variable s234a    "Has vaccination card"
label variable s234c    "Number of tetanus injections"
label variable sd234b1  "Day first tetanus toxoid - Ethiopian calendar"
label variable sm234b1  "Month first tetanus toxoid - Ethiopian calendar"
label variable sy234b1  "Year first tetanus toxoid - Ethiopian calendar"
label variable sd234b2  "Day second tetanus toxoid - Ethiopian calendar"
label variable sm234b2  "Month second tetanus toxoid - Ethiopian calendar"
label variable sy234b2  "Year second tetanus toxoid - Ethiopian calendar"
label variable sd234b3  "Day third tetanus toxoid - Ethiopian calendar"
label variable sm234b3  "Month third tetanus toxoid - Ethiopian calendar"
label variable sy234b3  "Year third tetanus toxoid - Ethiopian calendar"
label variable sd234b4  "Day fourth tetanus toxoid - Ethiopian calendar"
label variable sm234b4  "Month fourth tetanus toxoid - Ethiopian calendar"
label variable sy234b4  "Year fourth tetanus toxoid - Ethiopian calendar"
label variable sd234b5  "Day fifth tetanus toxoid - Ethiopian calendar"
label variable sm234b5  "Month fifth tetanus toxoid - Ethiopian calendar"
label variable sy234b5  "Year fifth tetanus toxoid - Ethiopian calendar"
label variable s312     "Brand name of pill"
label variable s319     "Last source of FP/where learned to use method"
label variable s319d    "How long to get to family planning place (minutes)"
label variable s329     "Place for family planning methods"
label variable s482     "Wash hands before feeding"
label variable s483     "Wash hands after cleaning child"
label variable s484     "Disposal of stools"
label variable s489     "Sought medical treatment when was sick"
label variable s489aa   "Care factors: does not know where to go"
label variable s489ab   "Care factors: does not get permission to go"
label variable s489ac   "Care factors: no money for treatment"
label variable s489ad   "Care factors: no health facility nearby"
label variable s489ae   "Care factors: no transport"
label variable s489af   "Care factors: does not want to go alone"
label variable s489ag   "Care factors: concern of no female health provider"
label variable s489ah   "Care factors: believed would recover soon"
label variable s489ai   "Care factors: sickness was not serious"
label variable s489aj   "Care factors: Scared of modern treatment"
label variable s489ak   "Care factors: used traditional treatment / drugs"
label variable s489al   "Care factors: did not feel sick"
label variable s489ax   "Care factors: other reasons"
label variable s508mg   "Date of first union (month) - Gregorian calendar"
label variable s508yg   "Date of first union (year) - Gregorian calendar"
label variable s508cg   "Date of first union (CMC) - Gregorian calendar"
label variable s617d    "Heard FP on pamphlet/posters"
label variable s617e    "Heard FP on community events"
label variable s702a    "Husband is able to read/write a sentence"
label variable s705     "Partner's highest grade"
label variable s712a    "Works throughout the year/season/once in a while"
label variable s1001aa  "From which source heard of AIDS - Radio"
label variable s1001ab  "From which source heard of AIDS - Television"
label variable s1001ac  "From which source heard of AIDS - Newspapers/magazines"
label variable s1001ad  "From which source heard of AIDS - Pamphlets/posters"
label variable s1001ae  "From which source heard of AIDS - Health workers"
label variable s1001af  "From which source heard of AIDS - Mosques/churches"
label variable s1001ag  "From which source heard of AIDS - Schools/teachers"
label variable s1001ah  "From which source heard of AIDS - Community event"
label variable s1001ai  "From which source heard of AIDS - Friends/relatives"
label variable s1001aj  "From which source heard of AIDS - Work place"
label variable s1001ak  "From which source heard of AIDS - Drama/performance"
label variable s1001ax  "From which source heard of AIDS - Other"
label variable s1005    "Person getting AIDS influenced by number of partners"
label variable s1006    "Sex with one partner increases or decreases chance of AIDS"
label variable s1008    "Protect from AIDS by using condom"
label variable s1013a   "AIDS transmit. during pregnancy"
label variable s1013b   "AIDS transmit. at delivery"
label variable s1013c   "AIDS transmit. during breastfeeding"
label variable s1013d   "AIDS transmit. during other times"
label variable s1013z   "AIDS transmit. - Don't know"
label variable s1106    "Intercourse with anyone else in last 12 months"
label variable s1111    "Knows source for condoms"
label variable s1112    "Source for condoms"
label variable s1114t   "Time interview ended"
label variable s1114h   "Hour interview ended"
label variable s1114m   "Minutes interview ended"
label variable idx92    "Index to birth history"
label variable s215mg   "Month of birth - Gregorian calendar"
label variable s215yg   "Year of birth - Gregorian calendar"
label variable s215cg   "Date of birth of child (CMC) - Gregorian calendar"
label variable idx94    "Index to birth history"
label variable s406a    "Stopped eating specific type of food"
label variable s406ba   "What did the respondent stop eating - milk"
label variable s406bb   "What did the respondent stop eating - cheese, butter"
label variable s406bc   "What did the respondent stop eating - meat"
label variable s406bd   "What did the respondent stop eating - vegetables"
label variable s406be   "What did the respondent stop eating - fruit"
label variable s406bx   "What did the respondent stop eating - other"
label variable s432c    "When was child exposed to sunlight"
label variable s440a    "Squeeze out and discarded first milk"
label variable s442a    "Reason stopped breastfeeding"
label variable s475c    "Other home made fluid"

#delimit ;
label define V007    
  1992 "***Undefined Label"
;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V023    
     1 "Tigray, urban"
     2 "Tigray, rural"
     3 "Afar, urban"
     4 "Afar, rural"
     5 "Amhara, urban"
     6 "Amhara, rural"
     7 "Oromiya, urban"
     8 "Oromiya, rural"
     9 "Somali, urban"
    10 "Somali, rural"
    11 "Ben-Gumz, urban"
    12 "Ben-Gumz, rural"
    13 "SNNP, urban"
    14 "SNNP, rural"
    15 "Gambela, urban"
    16 "Gambela, rural"
    17 "Harrari, urban"
    18 "Harrari, rural"
    19 "Addis, urban"
    20 "Dire Dawa, urban"
    21 "Dire Dawa, rural"
;
label define V024    
     1 "Tigray"
     2 "Affar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harari"
    14 "Addis"
    15 "Dire Dawa"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V028    
   999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
   999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in HH"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V043    
     0 "Woman not selected"
     1 "Woman selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "Tigray"
     2 "Affar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harari"
    14 "Addis"
    15 "Dire Dawa"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
    99 "Missing"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into compound"
    13 "Piped outside compound"
    20 "WATER FROM OPEN WELL"
    21 "Open well"
    22 "Open spring"
    23 "Covered well"
    24 "Covered spring"
    31 "River"
    32 "Pond/lake/dam"
    40 "SURFACE WATER"
    41 "Rainwater"
    96 "Other"
    97 "Not a de-jure resident"
;
label define V115    
   995 "One day or longer"
   996 "On premises"
   997 "Not dejure resident"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flush toilet"
    20 "PIT TOILET LATRINE"
    21 "Traditional pit latrine"
    22 "Improved (ventilated) pit latrine"
    30 "NO FACILITY"
    31 "No facility, bush, field"
    96 "OTHER"
    97 "Not de-jure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V122    
     7 "***Undefined Label"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V127    
    10 "NATURAL FLOOR"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY FLOOR"
    21 "Wood planks"
    22 "Reed, bamboo"
    30 "FINISHED FLOOR"
    31 "Parquet, polished wood"
    32 "Vinyl sheets/tiles"
    33 "Cement"
    34 "Cement tiles/brick"
    35 "Carpet"
    96 "Other"
    97 "Not de jure resident"
;
label define V128    
    99 "Missing"
;
label define V129    
    10 "NATURAL"
    20 "RUDIMENTARY"
    21 "Wood / mud"
    22 "Thatch"
    23 "Reed/Bamboo"
    24 "Plastic sheet"
    25 "Mobile roofs of nomads"
    30 "FINISHED"
    31 "Corrugated iron"
    32 "Cement / concrete"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V130    
     1 "Orthodox"
     2 "Catholic"
     3 "Protestant"
     4 "Moslem"
     5 "Traditional"
     6 "Other"
;
label define V131    
     1 "Affar"
     4 "Amharra"
    25 "Guragie"
    60 "Oromo"
    67 "Sidama"
    68 "Somalie"
    70 "Tigray (Tigraway)"
    72 "Welaita"
    96 "Other"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Tigray"
     2 "Affar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harari"
    14 "Addis"
    15 "Dire Dawa"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Grand-daughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "DK"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
;
label define V156    
     9 "Missing"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V161    
     1 "Electricity"
     2 "LPG/natural gas"
     3 "Biogas"
     4 "Kerosene"
     5 "Coal/lignite"
     6 "Charcoal"
     7 "Firewood/straw"
     8 "Dung"
    96 "Other"
    97 "Not dejure resident"
;
label define V162    
     7 "***Undefined Label"
;
label define V163    
     7 "***Undefined Label"
;
label define V164    
     7 "***Undefined Label"
;
label define V165    
     7 "***Undefined Label"
;
label define V166    
   999 "Missing"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "95, but per.returned"
     6 "96, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birt"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "DK"
;
label define V230    
  9997 "Inconsistent"
  9998 "DK"
;
label define V231    
  9997 "Inconsistent"
  9998 "DK"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     6 "***Undefined Label"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     9 "Missing"
;
label define V240    
    99 "Missing"
;
label define V241    
  9999 "Missing"
;
label define V242    
  9999 "Missing"
;
label define V310    
    99 "Missing"
;
label define V311    
     4 "4+"
     5 "Never used"
;
label define V312    
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    16 "***Undefined Label"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
;
label define V313    
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
;
label define V326    
    10 "PUBLIC"
    11 "Gov. hospital"
    12 "Gov. health center"
    13 "Gov. health station /clinic"
    14 "Gov. health post"
    15 "Gov. comm. based outlet"
    16 "Gov. other"
    20 "PRIVATE MEDICAL"
    21 "Priv. hospital"
    22 "Priv. doctor /clinic"
    23 "Priv. pharmacy"
    24 "Priv. other"
    25 "NGO: health facility"
    26 "NGO: comm. based outlet"
    27 "NGO: family guidance"
    28 "NGO: other"
    29 "***Undefined Label"
    30 "OTHER PRIVATE"
    31 "Drug vendor"
    32 "Shop"
    33 "Friend relative"
    36 "Other"
    95 "Did not consult"
    96 "OTHER"
    97 "***Undefined Label"
    98 "Don't know"
;
label define V327    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
;
label define V337    
   999 "Missing"
;
label define V359    
    99 "Missing"
;
label define V360    
    98 "***Undefined Label"
;
label define V361    
     1 "Currently using"
     2 "Used since last birth"
     3 "Used before last birth"
     4 "Never used"
;
label define V362    
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
;
label define V363    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    16 "***Undefined Label"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
;
label define V364    
     1 "Using modern method"
     2 "Using traditional method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define V367    
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
;
label define V375A   
    96 "***Undefined Label"
    98 "***Undefined Label"
;
label define V376    
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "***Undefined Label"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "***Undefined Label"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
;
label define V376A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V379    
    10 "PUBLIC"
    11 "Hospital"
    12 "Health center"
    13 "Health station/clinic"
    14 "Health post"
    15 "Community-based outlet"
    16 "Other government"
    20 "PRIVATE MEDICAL"
    21 "Private hospital"
    22 "Private doctor/clinic"
    23 "Pharmacy"
    24 "Other private medical"
    25 "NGO health facility"
    26 "NGO comm.-based outlet"
    27 "Family guidance"
    28 "Other NGO"
    29 "***Undefined Label"
    30 "PRIVATE OTHER"
    31 "Drug vendor"
    32 "Shop"
    33 "Friend/relative"
    36 "Other"
    95 "Did not consult source"
    96 "OTHER"
    97 "***Undefined Label"
    98 "Don't know"
;
label define V380    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
;
label define V384A   
     0 "No"
     1 "Yes"
;
label define V384B   
     0 "No"
     1 "Yes"
;
label define V384C   
     0 "No"
     1 "Yes"
;
label define V393    
     0 "No"
     1 "Yes"
;
label define V394    
     0 "No"
     1 "Yes"
;
label define V395    
     0 "No"
     1 "Yes"
;
label define V3A00A  
     9 "Missing"
;
label define V3A00B  
     9 "Missing"
;
label define V3A00C  
     9 "Missing"
;
label define V3A00D  
     9 "Missing"
;
label define V3A00E  
     9 "Missing"
;
label define V3A00F  
     9 "Missing"
;
label define V3A00G  
     9 "Missing"
;
label define V3A00H  
     9 "Missing"
;
label define V3A00I  
     9 "Missing"
;
label define V3A00J  
     9 "Missing"
;
label define V3A00K  
     9 "Missing"
;
label define V3A00L  
     9 "Missing"
;
label define V3A00M  
     9 "Missing"
;
label define V3A00N  
     9 "Missing"
;
label define V3A00O  
     9 "Missing"
;
label define V3A00P  
     9 "Missing"
;
label define V3A00Q  
     9 "Missing"
;
label define V3A00R  
     9 "Missing"
;
label define V3A00S  
     9 "Missing"
;
label define V3A00T  
     9 "Missing"
;
label define V3A00U  
     9 "Missing"
;
label define V3A00V  
     9 "Missing"
;
label define V3A00W  
     9 "Missing"
;
label define V3A00X  
     9 "Missing"
;
label define V3A00Y  
     9 "Missing"
;
label define V3A00Z  
     9 "Missing"
;
label define V3A01   
     8 "***Undefined Label"
;
label define V3A02   
     9 "Missing"
;
label define V3A03   
     9 "Missing"
;
label define V3A04   
     9 "Missing"
;
label define V3A05   
     9 "Missing"
;
label define V3A06   
     9 "Missing"
;
label define V3A07   
    10 "PUBLIC"
    11 "Hospital"
    12 "Health center"
    13 "Health station/clinic"
    14 "Health post"
    15 "Community-based outlet"
    16 "Other government"
    20 "PRIVATE MEDICAL"
    21 "Private hospital"
    22 "Private doctor/clinic"
    23 "Pharmacy"
    24 "Other private medical"
    25 "NGO health facility"
    26 "NGO comm.-based outlet"
    27 "Family guidance"
    28 "Other NGO"
    29 "***Undefined Label"
    30 "PRIVATE OTHER"
    31 "Drug vendor"
    32 "Shop"
    33 "Friend/relative"
    36 "Other"
    95 "Did not consult source"
    96 "OTHER"
    97 "***Undefined Label"
    98 "Don't know"
;
label define V3A08A  
     0 "No"
     1 "Not married"
;
label define V3A08B  
     0 "No"
     1 "Not having sex"
;
label define V3A08C  
     0 "No"
     1 "Infrequent sex"
;
label define V3A08D  
     0 "No"
     1 "Menopausal/hysterectomy"
;
label define V3A08E  
     0 "No"
     1 "Subfecund/infecund"
;
label define V3A08F  
     0 "No"
     1 "Postpartum amenorrheic"
;
label define V3A08G  
     0 "No"
     1 "Breastfeeding"
;
label define V3A08H  
     0 "No"
     1 "Fatalistic"
;
label define V3A08I  
     0 "No"
     1 "Respondent opposed"
;
label define V3A08J  
     0 "No"
     1 "Husband/partner opposed"
;
label define V3A08K  
     0 "No"
     1 "Others opposed"
;
label define V3A08L  
     0 "No"
     1 "Religious prohibition"
;
label define V3A08M  
     0 "No"
     1 "Knows no method"
;
label define V3A08N  
     0 "No"
     1 "Knows no source"
;
label define V3A08O  
     0 "No"
     1 "Health concerns"
;
label define V3A08P  
     0 "No"
     1 "Fear of side effects"
;
label define V3A08Q  
     0 "No"
     1 "Lack of access/too far"
;
label define V3A08R  
     0 "No"
     1 "Costs too much"
;
label define V3A08S  
     0 "No"
     1 "Inconvenient to use"
;
label define V3A08T  
     0 "No"
     1 "Interferes with bodys processes"
;
label define V3A08U  
     9 "Missing"
;
label define V3A08V  
     9 "Missing"
;
label define V3A08W  
     9 "Missing"
;
label define V3A08X  
     0 "No"
     1 "Other"
;
label define V3A08Z  
     0 "No"
     1 "Dont know"
;
label define V401    
     0 "No"
     1 "Yes"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
;
label define V408    
    96 "On demand"
;
label define V415    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V416    
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
;
label define V420    
   999 "Missing"
;
label define V421    
   999 "Missing"
;
label define V426    
     0 "Immediately"
;
label define V437    
  9999 "Missing"
;
label define V438    
  9999 "Missing"
;
label define V439    
  9998 "Flagged cases"
;
label define V440    
  9998 "Flagged cases"
;
label define V441    
 99998 "Flagged cases"
;
label define V442    
 99998 "Flagged cases"
;
label define V443    
 99998 "Flagged cases"
;
label define V444    
 99998 "Flagged cases"
;
label define V444A   
  9998 "Flagged cases"
;
label define V445    
  9998 "Flagged cases"
;
label define V446    
  9998 "Flagged cases"
;
label define V447    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
     7 "No measurement found in HH"
;
label define V452A   
     9 "Missing"
;
label define V452B   
    99 "Missing"
;
label define V452C   
     9 "Missing"
;
label define V453    
   999 "Missing"
;
label define V454    
     9 "Missing"
;
label define V455    
     9 "Missing"
;
label define V456    
   999 "Missing"
;
label define V457    
     9 "Missing"
;
label define V458    
     9 "Missing"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     9 "Missing"
;
label define V461    
     9 "Missing"
;
label define V462    
     0 "No"
     1 "Yes"
     2 "Never prepared meal"
;
label define V463A   
     9 "Missing"
;
label define V463B   
     9 "Missing"
;
label define V463C   
     9 "Missing"
;
label define V463D   
     9 "Missing"
;
label define V463E   
     9 "Missing"
;
label define V463F   
     9 "Missing"
;
label define V463G   
     9 "Missing"
;
label define V463Z   
     9 "Missing"
;
label define V464    
    98 "***Undefined Label"
;
label define V465    
     1 "Always use toilet/latrine"
     2 "Throw in toilet/latrine"
     3 "Throw outside the dwelling"
     4 "Throw outside the yard"
     5 "Bury in the yard"
     6 "Rinse away"
     7 "Use disposable diapers"
     8 "Use washable diapers"
     9 "Not disposed of"
    96 "Other"
;
label define V466    
     0 "No"
     1 "Yes"
     2 "Depends"
;
label define V467A   
     9 "Missing"
;
label define V467B   
     9 "Missing"
;
label define V467C   
     9 "Missing"
;
label define V467D   
     9 "Missing"
;
label define V467E   
     9 "Missing"
;
label define V467F   
     9 "Missing"
;
label define V467G   
     9 "Missing"
;
label define V468    
     0 "See specific questions"
     1 "Only last birth"
     2 "All columns"
;
label define V469A   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469B   
     9 "Missing"
;
label define V469C   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469D   
     9 "Missing"
;
label define V469E   
     9 "Missing"
;
label define V469F   
     9 "Missing"
;
label define V469G   
     9 "Missing"
;
label define V469H   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469I   
     9 "Missing"
;
label define V469J   
     9 "Missing"
;
label define V469K   
     9 "Missing"
;
label define V469L   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469M   
     9 "Missing"
;
label define V469N   
     9 "Missing"
;
label define V469O   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469P   
     9 "Missing"
;
label define V469Q   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469R   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469S   
     9 "Missing"
;
label define V469T   
     9 "Missing"
;
label define V469U   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469V   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469W   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469X   
     9 "Missing"
;
label define V469Y   
     0 "No"
     7 "7+"
     8 "DK"
;
label define V469Z   
     9 "Missing"
;
label define V469XX  
     9 "Missing"
;
label define V469XY  
     9 "Missing"
;
label define V469XZ  
     9 "Missing"
;
label define V470A   
     8 "DK"
;
label define V470B   
     9 "Missing"
;
label define V470C   
     0 "No"
     8 "DK"
;
label define V470D   
     9 "Missing"
;
label define V470E   
     9 "Missing"
;
label define V470F   
     9 "Missing"
;
label define V470G   
     9 "Missing"
;
label define V470H   
     0 "No"
     8 "DK"
;
label define V470I   
     9 "Missing"
;
label define V470J   
     9 "Missing"
;
label define V470K   
     9 "Missing"
;
label define V470L   
     0 "No"
     8 "DK"
;
label define V470M   
     9 "Missing"
;
label define V470N   
     9 "Missing"
;
label define V470O   
     0 "No"
     8 "DK"
;
label define V470P   
     9 "Missing"
;
label define V470Q   
     0 "No"
     8 "DK"
;
label define V470R   
     0 "No"
     8 "DK"
;
label define V470S   
     9 "Missing"
;
label define V470T   
     9 "Missing"
;
label define V470U   
     0 "No"
     8 "DK"
;
label define V470V   
     0 "No"
     8 "DK"
;
label define V470W   
     0 "No"
     8 "DK"
;
label define V470X   
     9 "Missing"
;
label define V470Y   
     0 "No"
     8 "DK"
;
label define V470Z   
     9 "Missing"
;
label define V470XX  
     9 "Missing"
;
label define V470XY  
     9 "Missing"
;
label define V470XZ  
     9 "Missing"
;
label define V501    
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define V502    
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define V503    
     1 "Once"
     2 "More than once"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
;
label define V505    
     0 "No other wives"
    98 "Don't know"
;
label define V506    
    98 "Don't know"
;
label define V510    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "***Undefined Label"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V525    
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define V527    
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define V529    
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V530    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birt"
;
label define V531    
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define V532    
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
;
label define V536    
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     2 "Not active in last 4 weeks - postpartum abst."
     3 "Not active in last 4 weeks - not postpartum abst."
;
label define V537    
    96 "Before last birth"
    97 "Inconsistent"
    98 "DK"
;
label define V602    
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Declared infecund"
     6 "Never had sex"
;
label define V603    
   992 "As God wishes"
   993 "After marriage"
   994 "Soon, now"
   995 "***Undefined Label"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define V604    
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define V605    
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
;
label define V610    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
;
label define V611    
     0 "Never"
     1 "Once or twice"
     2 "More often"
;
label define V612    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
;
label define V613    
    94 "Can't decide / never thought about it"
    95 "As God wishes"
    96 "Non-numeric response"
    98 "DK"
;
label define V614    
     6 "6+"
     7 "Non-numeric response"
;
label define V616    
   992 "As God wishes"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
;
label define V621    
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "DK"
;
label define V623    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
;
label define V624    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
;
label define V625    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
;
label define V626    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
;
label define V627    
    94 "Never thought about it"
    95 "As God wishes"
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define V628    
    94 "Never thought about it"
    95 "As God wishes"
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define V629    
    94 "Never thought about it"
    95 "As God wishes"
    96 "Other"
    97 "***Undefined Label"
    98 "DK"
;
label define V630A   
     0 "No"
     1 "Yes"
;
label define V630B   
     0 "No"
     1 "Yes"
;
label define V630C   
     0 "No"
     1 "Yes"
;
label define V630D   
     0 "No"
     1 "Yes"
;
label define V630E   
     0 "No"
     1 "Yes"
;
label define V630F   
     0 "No"
     1 "Yes"
;
label define V630G   
     0 "No"
     1 "Yes"
;
label define V630H   
     0 "No"
     1 "Yes"
;
label define V630I   
     0 "No"
     1 "Yes"
;
label define V630J   
     9 "Missing"
;
label define V630K   
     9 "Missing"
;
label define V630L   
     9 "Missing"
;
label define V630M   
     9 "Missing"
;
label define V630N   
     9 "Missing"
;
label define V630O   
     9 "Missing"
;
label define V630X   
     0 "No"
     1 "Yes"
;
label define V631    
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant /not having sex"
;
label define V632    
     1 "Mainly respondent"
     2 "Mainly husband, partner"
     3 "Joint decision"
     6 "Other"
;
label define V633A   
     8 "***Undefined Label"
;
label define V633B   
     8 "***Undefined Label"
;
label define V633C   
     8 "***Undefined Label"
;
label define V633D   
     8 "***Undefined Label"
;
label define V633E   
     8 "***Undefined Label"
;
label define V633F   
     8 "***Undefined Label"
;
label define V633G   
     8 "***Undefined Label"
;
label define V701    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define V702    
    98 "Don't know"
;
label define V704    
     0 "Student, pensioners"
    11 "Legislators and senior officials"
    12 "Corporate managers"
    13 "Other general managers"
    21 "Physical, mathemat., engineering science prof."
    22 "Life science and health prof."
    23 "Teaching professionals"
    24 "Other assoc. professionals"
    31 "Physical and engineering science ass. prof."
    32 "Life science and health assoc. prof."
    33 "Teaching assoc. prof."
    34 "Other assoc. prof."
    41 "Office clerks"
    42 "Customer service clerk"
    51 "Personal and protective service workers"
    52 "Models, sales persons and demonstrators"
    61 "Market oriented skilled agric. and fisher workers"
    62 "Subsistence agric. and fisher workers"
    71 "Extraction and building trade workers"
    72 "Metal, machin. and rel. trade workers"
    73 "Precision, handicraft, printing and rel. workers"
    74 "Other craft and related trade workers"
    81 "Stationary plant and related workers"
    82 "Machine operators and assemblers"
    83 "Drivers and Mobil plant operators"
    91 "Sales and service elementary occupation"
    92 "Agric. and fishery and rel. workers"
    93 "Labourers in mining, construction, manuf. and transport"
    96 "Other"
;
label define V705    
     0 "Did not work"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define V714    
     0 "No"
     1 "Yes"
;
label define V715    
    97 "Inconsistent"
    98 "Don't know"
;
label define V716    
     0 "Student, pensioners"
    11 "Legislators and senior officials"
    12 "Corporate managers"
    13 "Other general managers"
    21 "Physical, mathemat., engineering science prof."
    22 "Life science and health prof."
    23 "Teaching professionals"
    24 "Other assoc. professionals"
    31 "Physical and engineering science ass. prof."
    32 "Life science and health assoc. prof."
    33 "Teaching assoc. prof."
    34 "Other assoc. prof."
    41 "Office clerks"
    42 "Customer service clerk"
    51 "Personal and protective service workers"
    52 "Models, sales persons and demonstrators"
    61 "Market oriented skilled agric. and fisher workers"
    62 "Subsistence agric. and fisher workers"
    71 "Extraction and building trade workers"
    72 "Metal, machin. and rel. trade workers"
    73 "Precision, handicraft, printing and rel. workers"
    74 "Other craft and related trade workers"
    81 "Stationary plant and related workers"
    82 "Machine operators and assemblers"
    83 "Drivers and Mobil plant operators"
    91 "Sales and service elementary occupation"
    92 "Agric. and fishery and rel. workers"
    93 "Labourers in mining, construction, manuf. and transport"
    96 "Other"
;
label define V717    
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define V719    
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define V721    
     1 "At home"
     2 "Away"
;
label define V729    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define V730    
    96 "96+"
    97 "***Undefined Label"
    98 "DK"
;
label define V731    
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define V732    
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define V739    
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
;
label define V740    
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define V741    
     0 "Not paid"
     1 "Cash only"
     2 "Cash and kind"
     3 "In kind only"
;
label define V742    
     9 "Missing"
;
label define V743A   
     9 "Missing"
;
label define V743B   
     9 "Missing"
;
label define V743C   
     9 "Missing"
;
label define V743D   
     9 "Missing"
;
label define V743E   
     9 "Missing"
;
label define V744A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M1      
     0 "Received no inject."
     7 "7+"
     8 "Don't know"
;
label define M2A     
     9 "Missing"
;
label define M2B     
     9 "Missing"
;
label define M2C     
     9 "Missing"
;
label define M2D     
     0 "No"
     1 "Yes: CS health professional"
;
label define M2E     
     9 "Missing"
;
label define M2F     
     0 "No"
     1 "Yes: trained birth A"
;
label define M2G     
     0 "No"
     1 "Yes: trad.birth att."
;
label define M2H     
     9 "Missing"
;
label define M2I     
     9 "Missing"
;
label define M2J     
     9 "Missing"
;
label define M2K     
     0 "No"
     1 "Yes: other responses"
;
label define M2L     
     9 "Missing"
;
label define M2M     
     9 "Missing"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no one"
;
label define M3A     
     9 "Missing"
;
label define M3B     
     9 "Missing"
;
label define M3C     
     9 "Missing"
;
label define M3D     
     0 "No"
     1 "Yes: CS health professional"
;
label define M3E     
     9 "Missing"
;
label define M3F     
     0 "No"
     1 "Yes: trained birth A"
;
label define M3G     
     0 "No"
     1 "Yes: trad.birth att."
;
label define M3H     
     0 "No"
     1 "Yes: relative,friend"
;
label define M3I     
     9 "Missing"
;
label define M3J     
     9 "Missing"
;
label define M3K     
     0 "No"
     1 "Yes: other responses"
;
label define M3L     
     9 "Missing"
;
label define M3M     
     9 "Missing"
;
label define M3N     
     0 "No: some assistance"
     1 "Yes: no one"
;
label define M4      
    94 "Never breastfed"
    95 "Still breastfeeding"
    96 "Breastfed until died"
    97 "Inconsistent"
    98 "DK"
;
label define M5      
    94 "Never breastfed"
    97 "Inconsistent"
    98 "DK"
;
label define M6      
    96 "Period not returned"
    97 "Inconsistent"
    98 "DK"
;
label define M7      
    97 "Inconsistent"
    98 "DK"
;
label define M8      
    96 "Still abstaining"
    97 "Inconsistent"
    98 "DK"
;
label define M9      
    97 "Inconsistent"
    98 "DK"
;
label define M10     
     1 "Then"
     2 "Later"
     3 "No more"
;
label define M11     
   998 "DK"
;
label define M13     
    98 "DK"
;
label define M14     
     0 "No antenatal visits"
    98 "DK"
;
label define M15     
    10 "HOMES"
    11 "Respondents home"
    12 "Other home"
    13 "Forest / bush"
    20 "PUBLIC SECTOR"
    21 "Govt. hospital"
    22 "Govt. health center"
    23 "Govt. health post"
    26 "Other public"
    30 "PRIVATE SECTOR"
    31 "Private hosp/clinic"
    32 "Private doctor"
    33 "NGO health facility"
    36 "Other private medica"
    96 "OTHER"
;
label define M17     
     0 "No"
     1 "Yes"
;
label define M18     
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "DK"
;
label define M19     
  9996 "Not weighed at birth"
  9997 "***Undefined Label"
  9998 "DK"
;
label define M19A    
     0 "Not weighed"
     1 "From card"
     2 "From recall"
     9 "Special answers"
;
label define M27     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     3 "> age at death"
     4 "During preg in cal."
;
label define M28     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     3 "***Undefined Label"
     4 "During preg in cal."
;
label define M29     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     3 "***Undefined Label"
     4 "During preg in cal."
;
label define M34     
     0 "Immediately"
   100 "***Undefined Label"
   101 "Hours: 1"
   201 "Days: 1"
;
label define M35     
    96 "On demand"
;
label define M36     
    96 "On demand"
;
label define M37A    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37B    
     9 "Missing"
;
label define M37C    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37D    
     9 "Missing"
;
label define M37E    
     9 "Missing"
;
label define M37F    
     9 "Missing"
;
label define M37G    
     9 "Missing"
;
label define M37H    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37I    
     9 "Missing"
;
label define M37J    
     9 "Missing"
;
label define M37K    
     9 "Missing"
;
label define M37L    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37M    
     9 "Missing"
;
label define M37N    
     9 "Missing"
;
label define M37O    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37P    
     9 "Missing"
;
label define M37Q    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37R    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37S    
     9 "Missing"
;
label define M37T    
     9 "Missing"
;
label define M37U    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37V    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37W    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37X    
     9 "Missing"
;
label define M37Y    
     0 "No"
     7 "7+"
     8 "DK"
;
label define M37Z    
     9 "Missing"
;
label define M37XX   
     9 "Missing"
;
label define M37XY   
     9 "Missing"
;
label define M37XZ   
     9 "Missing"
;
label define M38     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define M39     
     0 "None"
     7 "7+"
     8 "DK"
;
label define M40A    
     8 "DK"
;
label define M40B    
     9 "Missing"
;
label define M40C    
     0 "No"
     8 "DK"
;
label define M40D    
     9 "Missing"
;
label define M40E    
     9 "Missing"
;
label define M40F    
     9 "Missing"
;
label define M40G    
     9 "Missing"
;
label define M40H    
     0 "No"
     8 "DK"
;
label define M40I    
     9 "Missing"
;
label define M40J    
     9 "Missing"
;
label define M40K    
     9 "Missing"
;
label define M40L    
     0 "No"
     8 "DK"
;
label define M40M    
     9 "Missing"
;
label define M40N    
     9 "Missing"
;
label define M40O    
     0 "No"
     8 "DK"
;
label define M40P    
     9 "Missing"
;
label define M40Q    
     0 "No"
     8 "DK"
;
label define M40R    
     0 "No"
     8 "DK"
;
label define M40S    
     9 "Missing"
;
label define M40T    
     9 "Missing"
;
label define M40U    
     0 "No"
     8 "DK"
;
label define M40V    
     0 "No"
     8 "DK"
;
label define M40W    
     0 "No"
     8 "DK"
;
label define M40X    
     9 "Missing"
;
label define M40Y    
     0 "No"
     8 "DK"
;
label define M40Z    
     9 "Missing"
;
label define M40XX   
     9 "Missing"
;
label define M40XY   
     9 "Missing"
;
label define M40XZ   
     9 "Missing"
;
label define M41     
    98 "Don't know"
;
label define M42A    
     0 "No"
     1 "Yes"
;
label define M42B    
     0 "No"
     1 "Yes"
;
label define M42C    
     0 "No"
     1 "Yes"
;
label define M42D    
     0 "No"
     1 "Yes"
;
label define M42E    
     0 "No"
     1 "Yes"
;
label define M43     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M44     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M45     
     8 "***Undefined Label"
;
label define M46     
   998 "***Undefined Label"
;
label define M47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M48     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49D    
     0 "No"
     1 "Yes, proguanil"
     8 "Don't know"
;
label define M49E    
     8 "***Undefined Label"
;
label define M49F    
     8 "***Undefined Label"
;
label define M49G    
     8 "***Undefined Label"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M50     
     0 "No"
     1 "Yes"
;
label define M51     
   100 "Same day"
   101 "1 day"
   201 "1 week"
   998 "Don't know"
;
label define M52     
    10 "HEALTH PROFESSIONAL"
    11 "Doctor"
    12 "Nurse/midwife"
    13 "Auxiliary midwife"
    14 "Health professional"
    15 "Trained traditional birth attendant"
    20 "OTHER PERSON"
    21 "Traditional birth attendant"
    96 "Other"
;
label define M53     
    10 "HOMES"
    11 "Respondents home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Govt. hospital"
    22 "Govt. health center"
    23 "Govt. health post"
    24 "Govt. health clinic"
    25 "***Undefined Label"
    26 "Other public"
    30 "PRIVATE SECTOR"
    31 "Private hosp/clinic"
    32 "Private doctor clinic"
    33 "NGO health facility"
    36 "Other private medica"
    96 "OTHER"
;
label define M54     
     0 "No"
     1 "Yes"
;
label define M55A    
     9 "Missing"
;
label define M55B    
     9 "Missing"
;
label define M55C    
     9 "Missing"
;
label define M55D    
     9 "Missing"
;
label define M55E    
     9 "Missing"
;
label define M55F    
     9 "Missing"
;
label define M55G    
     9 "Missing"
;
label define M55H    
     9 "Missing"
;
label define M55I    
     9 "Missing"
;
label define M55J    
     9 "Missing"
;
label define M55K    
     9 "Missing"
;
label define M55L    
     9 "Missing"
;
label define M55M    
     9 "Missing"
;
label define M55N    
     9 "Missing"
;
label define M55X    
     9 "Missing"
;
label define M55Z    
     9 "Missing"
;
label define M56     
     8 "***Undefined Label"
;
label define H1      
     0 "No card"
     1 "Yes, seen"
     2 "Yes, not seen"
     3 "No longer has card"
;
label define H2      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H2D     
    97 "Inconsistent"
    98 "DK"
;
label define H2M     
    97 "Inconsistent"
    98 "DK"
;
label define H2Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H3      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H3D     
    97 "Inconsistent"
    98 "DK"
;
label define H3M     
    97 "Inconsistent"
    98 "DK"
;
label define H3Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H4      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H4D     
    97 "Inconsistent"
    98 "DK"
;
label define H4M     
    97 "Inconsistent"
    98 "DK"
;
label define H4Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H5      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H5D     
    97 "Inconsistent"
    98 "DK"
;
label define H5M     
    97 "Inconsistent"
    98 "DK"
;
label define H5Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H6      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H6D     
    97 "Inconsistent"
    98 "DK"
;
label define H6M     
    97 "Inconsistent"
    98 "DK"
;
label define H6Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H7      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H7D     
    97 "Inconsistent"
    98 "DK"
;
label define H7M     
    97 "Inconsistent"
    98 "DK"
;
label define H7Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H8      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H8D     
    97 "Inconsistent"
    98 "DK"
;
label define H8M     
    97 "Inconsistent"
    98 "DK"
;
label define H8Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H9      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H9D     
    97 "Inconsistent"
    98 "DK"
;
label define H9M     
    97 "Inconsistent"
    98 "DK"
;
label define H9Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H0      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H0D     
    97 "Inconsistent"
    98 "DK"
;
label define H0M     
    97 "Inconsistent"
    98 "DK"
;
label define H0Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H10     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H11     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H12A    
     0 "No"
     1 "Government hospital"
;
label define H12B    
     0 "No"
     1 "Govt. health center"
;
label define H12C    
     0 "No"
     1 "Govt. health post"
;
label define H12D    
     9 "Missing"
;
label define H12E    
     0 "No"
     1 "Community based outlet"
;
label define H12F    
     0 "No"
     1 "CS health station / clinic"
;
label define H12G    
     0 "No"
     1 "CS: other government"
;
label define H12H    
     9 "Missing"
;
label define H12I    
     9 "Missing"
;
label define H12J    
     0 "No"
     1 "Private hosp./clinic"
;
label define H12K    
     0 "No"
     1 "Private pharmacy"
;
label define H12L    
     0 "No"
     1 "Private doctor"
;
label define H12M    
     9 "Missing"
;
label define H12N    
     0 "No"
     1 "Community based outlet"
;
label define H12O    
     0 "No"
     1 "CS NGO health facility"
;
label define H12P    
     0 "No"
     1 "CS other NGO"
;
label define H12Q    
     0 "No"
     1 "CS other private medical"
;
label define H12R    
     9 "Missing"
;
label define H12S    
     0 "No"
     1 "Shop"
;
label define H12T    
     0 "No"
     1 "Traditional pract."
;
label define H12U    
     0 "No"
     1 "CS drug vendor"
;
label define H12V    
     9 "Missing"
;
label define H12W    
     9 "Missing"
;
label define H12X    
     0 "No"
     1 "Other"
;
label define H12Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
;
label define H12Z    
     0 "No"
     1 "Yes: medical treatm."
;
label define H13     
     0 "No"
     1 "Yes: ORS - spontan."
     2 "Yes: ORS - probed"
     8 "Don't know"
;
label define H14     
     0 "No"
     1 "Yes: RHS - spontan."
     2 "Yes: RHS - probed"
     8 "Don't know"
;
label define H15     
     0 "No"
     1 "Yes: oth pill, syrup"
     8 "Don't know"
;
label define H15A    
     8 "***Undefined Label"
;
label define H15B    
     0 "No"
     1 "Yes: injection"
     8 "Don't know"
;
label define H15C    
     0 "No"
     1 "Yes: intravenous (IV)"
     8 "Don't know"
;
label define H15D    
     0 "No"
     1 "Yes: home rem, herb."
     8 "Don't know"
;
label define H15E    
     8 "***Undefined Label"
;
label define H15F    
     8 "***Undefined Label"
;
label define H15G    
     8 "***Undefined Label"
;
label define H15H    
     8 "***Undefined Label"
;
label define H20     
     0 "No"
     1 "Yes"
;
label define H21A    
     0 "No: received treatm."
     1 "Yes: no treatment"
     8 "DK"
;
label define H21     
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define H32A    
     0 "No"
     1 "Government hospital"
;
label define H32B    
     0 "No"
     1 "Govt. health center"
;
label define H32C    
     0 "No"
     1 "Govt. health post"
;
label define H32D    
     9 "Missing"
;
label define H32E    
     0 "No"
     1 "Community based outlet"
;
label define H32F    
     0 "No"
     1 "Health station /clinic"
;
label define H32G    
     0 "No"
     1 "Other public sector"
;
label define H32H    
     9 "Missing"
;
label define H32I    
     9 "Missing"
;
label define H32J    
     0 "No"
     1 "Private hosp./clinic"
;
label define H32K    
     0 "No"
     1 "Private pharmacy"
;
label define H32L    
     0 "No"
     1 "Private doctor"
;
label define H32M    
     9 "Missing"
;
label define H32N    
     0 "No"
     1 "NGO community health outlet"
;
label define H32O    
     0 "No"
     1 "NGO health facility"
;
label define H32P    
     0 "No"
     1 "NGO other"
;
label define H32Q    
     0 "No"
     1 "Other private medical"
;
label define H32R    
     9 "Missing"
;
label define H32S    
     0 "No"
     1 "Shop"
;
label define H32T    
     0 "No"
     1 "Traditional pract."
;
label define H32U    
     9 "Missing"
;
label define H32V    
     9 "Missing"
;
label define H32W    
     9 "Missing"
;
label define H32X    
     0 "No"
     1 "Other"
;
label define H32Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes: medical treatm."
;
label define H33     
     8 "***Undefined Label"
;
label define H33D    
    99 "Missing"
;
label define H33M    
    99 "Missing"
;
label define H33Y    
  9999 "Missing"
;
label define H34     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H35     
     0 "No"
     1 "Yes"
     2 "No vaccination in last 2 years"
     8 "Don't know"
;
label define H36A    
     0 "No"
     1 "Yes: Tikemt/Hidar 1990"
;
label define H36B    
     0 "No"
     1 "Yes: Tikemt/Hidar 1991"
;
label define H36C    
     0 "No"
     1 "Yes: Tikemt/Hidar 1992"
;
label define H36D    
     9 "Missing"
;
label define H36E    
     9 "Missing"
;
label define H36F    
     9 "Missing"
;
label define H37A    
     0 "No"
     1 "Yes"
;
label define H37B    
     0 "No"
     1 "Yes"
;
label define H37C    
     0 "No"
     1 "Yes"
;
label define H37D    
     0 "No"
     1 "Yes"
;
label define H37E    
     0 "No"
     1 "Yes: quinine"
;
label define H37F    
     0 "No"
     1 "Yes: antibiotics"
;
label define H37G    
     9 "Missing"
;
label define H37H    
     9 "Missing"
;
label define H37X    
     0 "No"
     1 "Yes"
;
label define H37Y    
     0 "No"
     1 "Yes, nothing taken"
;
label define H37Z    
     0 "No"
     1 "Yes, DK"
;
label define H38     
     0 "Nothing to drink"
     1 "***Undefined Label"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H39     
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define HW2     
   999 "Missing"
;
label define HW3     
  9999 "Missing"
;
label define HW4     
  9998 "Flagged cases"
;
label define HW5     
  9998 "Flagged cases"
;
label define HW6     
 99998 "Flagged cases"
;
label define HW7     
  9998 "Flagged cases"
;
label define HW8     
  9998 "Flagged cases"
;
label define HW9     
 99998 "Flagged cases"
;
label define HW10    
  9998 "Flagged cases"
;
label define HW11    
  9998 "Flagged cases"
;
label define HW12    
 99998 "Flagged cases"
;
label define HW13    
     0 "Measured"
     1 "Dead"
     2 "Sick"
     3 "Not present"
     4 "Refused"
     5 "Mother refused"
     6 "Other"
     7 "No measurement found in HH"
;
label define HW15    
     1 "Lying"
     2 "Standing"
;
label define HW16    
    97 "Inconsistent"
    98 "DK"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
;
label define HW53    
   999 "Missing"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     2 "***Undefined Label"
     3 "Not present"
     4 "Refused"
     5 "***Undefined Label"
     6 "Other"
     7 "No measurement found in HH"
;
label define HW56    
  9999 "Missing"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HW58    
     0 "No"
     1 "Yes"
;
label define SINTYG  
  2000 "***Undefined Label"
;
label define SLAN    
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
;
label define SINTV   
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
     7 "Gamogna"
     8 "Kefigna"
;
label define SRESP   
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
     7 "Gamogna"
     8 "Kefigna"
;
label define STRANS  
     0 "No"
     1 "Yes"
;
label define S101T   
     1 "Morning"
     2 "Evening"
;
label define S101H   
    97 "Inconsistent"
;
label define S101M   
    97 "Inconsistent"
;
label define S105MG  
    97 "Inconsistent"
    98 "DK month"
;
label define S105YG  
  9997 "Inconsistent"
  9998 "DK year"
;
label define S109    
    13 "Technical/vocational certificate"
    14 "University/college diploma"
    15 "University/college degree"
;
label define S230AF  
     1 "Month and year"
     2 "Month and time ago -y imp"
     3 "Year and time ago - m imp"
     4 "Y & time ago - y ignored"
     5 "Year - time ago, m imp"
     6 "Time ago - y, m imp"
     7 "Month - time ago, y imp"
     8 "None - all imp"
;
label define S230B   
   100 "Zero months"
   200 "Zero years"
   900 "Special answers"
;
label define S230AMG 
    97 "Inconsistent"
    98 "DK"
;
label define S230AYG 
  9997 "Inconsistent"
  9998 "DK"
;
label define S234    
     0 "No"
     1 "Yes"
;
label define S234A   
     1 "Yes, seen"
     2 "Yes, not seen"
     3 "No card"
;
label define S234C   
    98 "***Undefined Label"
;
label define SD234B1 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM234B1 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SY234B1 
     0 "Not given"
  4444 "Marked on card"
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SD234B2 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM234B2 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SY234B2 
     0 "Not given"
  4444 "Marked on card"
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SD234B3 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM234B3 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SY234B3 
     0 "Not given"
  4444 "Marked on card"
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SD234B4 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM234B4 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SY234B4 
     0 "Not given"
  4444 "Marked on card"
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SD234B5 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM234B5 
     0 "Not given"
    44 "Marked on card"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SY234B5 
     0 "Not given"
  4444 "Marked on card"
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define S312    
     1 "Microgynon"
     2 "Lo-Feminol"
     3 "Excluton"
     4 "Neogynon"
     5 "Nordette"
     6 "Prudence"
     7 "Choice"
    95 "No brand name"
    96 "Other"
    98 "Don't know"
;
label define S319    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Health station/clinic"
    14 "Health post"
    15 "Community based outlet"
    16 "Other public"
    20 "NGO"
    21 "NGO health facility"
    22 "Community based outlets"
    23 "Family guidance"
    26 "Other NGO"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private doctor/clinic"
    33 "Pharmacy"
    36 "Other private medical"
    40 "OTHER SOURCE"
    41 "Work place facility"
    42 "Drug vendor"
    43 "Shop"
    44 "Friend/relative"
    45 "***Undefined Label"
    46 "Other"
    95 "Did not consult source"
    98 "DK"
;
label define S319D   
   998 "DK"
;
label define S329    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Health station/clinic"
    14 "Health post"
    15 "Community based outlet"
    16 "Other public"
    20 "NGO"
    21 "NGO health facility"
    22 "Community based outlets"
    23 "NGO: Family Guidance"
    26 "Other NGO"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private doctor/clinic"
    33 "Pharmacy"
    36 "Other private medical"
    40 "OTHER SOURCE"
    41 "Work place facility"
    42 "Drug vendor"
    43 "Shop"
    44 "Friend/relative"
    45 "***Undefined Label"
    46 "Other"
;
label define S482    
     0 "No"
     1 "Yes"
;
label define S483    
     0 "No"
     1 "Yes"
;
label define S484    
     1 "Always use toilet, latrine"
     2 "Throw in the toilet, latrine"
     3 "Throw outside dwelling"
     4 "Throw outside the yard"
     5 "Bury in the yard"
     6 "Rinsed away"
     7 "Not disposed of"
    96 "Other"
;
label define S489    
     0 "No"
     1 "Yes"
;
label define S489AA  
     0 "No"
     1 "Yes - does not know"
;
label define S489AB  
     0 "No"
     1 "Yes"
;
label define S489AC  
     0 "No"
     1 "Yes"
;
label define S489AD  
     0 "No"
     1 "Yes"
;
label define S489AE  
     0 "No"
     1 "Yes"
;
label define S489AF  
     0 "No"
     1 "Yes"
;
label define S489AG  
     0 "No"
     1 "Yes"
;
label define S489AH  
     0 "No"
     1 "Yes - would recover soon"
;
label define S489AI  
     0 "No"
     1 "Yes - sickness was not serious"
;
label define S489AJ  
     0 "No"
     1 "Yes - scared of modern treatment"
;
label define S489AK  
     0 "No"
     1 "Yes - used traditional treatment / drugs"
;
label define S489AL  
     0 "No"
     1 "Yes - did not feel sick"
;
label define S489AX  
     0 "No"
     1 "Yes"
;
label define S508MG  
    97 "Inconsistent"
    98 "DK month"
;
label define S508YG  
  9997 "Inconsistent"
  9998 "DK year"
;
label define S617D   
     0 "No"
     1 "Yes"
;
label define S617E   
     0 "No"
     1 "Yes"
;
label define S702A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define S705    
    13 "Post secondary certificate"
    14 "University/colllege diploma"
    15 "University/college degree"
    98 "DK"
;
label define S712A   
     1 "Throughout the agricultural season"
     2 "Part of the agricultural season"
     3 "Once in a while"
;
label define S1001AA 
     0 "No"
     1 "Yes"
;
label define S1001AB 
     0 "No"
     1 "Yes"
;
label define S1001AC 
     0 "No"
     1 "Yes"
;
label define S1001AD 
     0 "No"
     1 "Yes"
;
label define S1001AE 
     0 "No"
     1 "Yes"
;
label define S1001AF 
     0 "No"
     1 "Yes"
;
label define S1001AG 
     0 "No"
     1 "Yes"
;
label define S1001AH 
     0 "No"
     1 "Yes"
;
label define S1001AI 
     0 "No"
     1 "Yes"
;
label define S1001AJ 
     0 "No"
     1 "Yes"
;
label define S1001AK 
     0 "No"
     1 "Yes"
;
label define S1001AX 
     0 "No"
     1 "Yes"
;
label define S1005   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define S1006   
     1 "Greater chance of AIDS"
     2 "Lesser chance of AIDS"
;
label define S1008   
     1 "Decreases chances"
     2 "Increases chances"
     3 "Doesn't make a difference"
     8 "DK"
;
label define S1013A  
     0 "No"
     1 "Yes"
;
label define S1013B  
     0 "No"
     1 "Yes"
;
label define S1013C  
     0 "No"
     1 "Yes"
;
label define S1013D  
     0 "No"
     1 "Yes"
;
label define S1013Z  
     0 "No"
     1 "Yes - DK"
;
label define S1106   
     0 "No"
     1 "Yes"
;
label define S1111   
     0 "No"
     1 "Yes"
;
label define S1112   
     0 "Does not know a place where to get  condoms"
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Health station/clinic"
    14 "Health post"
    15 "Community based outlet"
    16 "Other public"
    20 "NGO"
    21 "NGO health facility"
    22 "Community based outlets"
    23 "NGO: Family Guidance"
    26 "Other NGO"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital"
    32 "Private doctor/clinic"
    33 "Pharmacy"
    36 "Other private medical"
    40 "OTHER SOURCE"
    41 "Work place facility"
    42 "Drug vendor"
    43 "Shop"
    44 "Friend/relative"
    45 "***Undefined Label"
    46 "Other"
;
label define S1114T  
     1 "Morning"
     2 "Evening"
;
label define S1114H  
    97 "Inconsistent"
;
label define S1114M  
    99 "Missing"
;
label define S215MG  
    97 "Inconsistent"
    98 "DK"
;
label define S215YG  
  9997 "Inconsistent"
  9998 "DK"
;
label define S406A   
     0 "No"
     1 "Yes"
;
label define S406BA  
     0 "No"
     1 "Yes"
;
label define S406BB  
     0 "No"
     1 "Yes"
;
label define S406BC  
     0 "No"
     1 "Yes"
;
label define S406BD  
     0 "No"
     1 "Yes"
;
label define S406BE  
     0 "No"
     1 "Yes"
;
label define S406BX  
     0 "No"
     1 "Yes"
;
label define S432C   
     0 "Not started"
   100 "Days"
   200 "Weeks"
   300 "Months"
   900 "Special answers"
   998 "Don't know"
;
label define S440A   
     0 "No"
     1 "Yes"
;
label define S442A   
     1 "Mother ill/weak"
     2 "Child ill/weak"
     3 "Child died"
     4 "Nipple/breast problem"
     5 "Not enough milk"
     6 "Mother working"
     7 "Child refused"
     8 "Weaning age/age to stop"
     9 "Became pregnant"
    10 "Started to use contraception"
    96 "Other"
    97 "Inconsistent"
;
label define S475C   
     0 "No"
     1 "Yes"
     8 "DK"
;

#delimit cr
label values v007     V007    
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v020     V020    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v043     V043    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v103     V103    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v129     V129    
label values v130     V130    
label values v131     V131    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v162     V162    
label values v163     V163    
label values v164     V164    
label values v165     V165    
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v237     V237    
label values v311     V311    
label values v312     V312    
label values v313     V313    
label values v326     V326    
label values v327     V327    
label values v360     V360    
label values v361     V361    
label values v362     V362    
label values v363     V363    
label values v364     V364    
label values v367     V367    
label values v375a    V375A   
label values v376     V376    
label values v376a    V376A   
label values v379     V379    
label values v380     V380    
label values v384a    V384A   
label values v384b    V384B   
label values v384c    V384C   
label values v393     V393    
label values v394     V394    
label values v395     V395    
label values v3a01    V3A01   
label values v3a07    V3A07   
label values v3a08a   V3A08A  
label values v3a08b   V3A08B  
label values v3a08c   V3A08C  
label values v3a08d   V3A08D  
label values v3a08e   V3A08E  
label values v3a08f   V3A08F  
label values v3a08g   V3A08G  
label values v3a08h   V3A08H  
label values v3a08i   V3A08I  
label values v3a08j   V3A08J  
label values v3a08k   V3A08K  
label values v3a08l   V3A08L  
label values v3a08m   V3A08M  
label values v3a08n   V3A08N  
label values v3a08o   V3A08O  
label values v3a08p   V3A08P  
label values v3a08q   V3A08Q  
label values v3a08r   V3A08R  
label values v3a08s   V3A08S  
label values v3a08t   V3A08T  
label values v3a08x   V3A08X  
label values v3a08z   V3A08Z  
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v415     V415    
label values v416     V416    
label values v426     V426    
label values v439     V439    
label values v440     V440    
label values v441     V441    
label values v442     V442    
label values v443     V443    
label values v444     V444    
label values v444a    V444A   
label values v445     V445    
label values v446     V446    
label values v447     V447    
label values v459     V459    
label values v462     V462    
label values v464     V464    
label values v465     V465    
label values v466     V466    
label values v468     V468    
label values v469a    V469A   
label values v469c    V469C   
label values v469h    V469H   
label values v469l    V469L   
label values v469o    V469O   
label values v469q    V469Q   
label values v469r    V469R   
label values v469u    V469U   
label values v469v    V469V   
label values v469w    V469W   
label values v469y    V469Y   
label values v470a    V470A   
label values v470c    V470C   
label values v470h    V470H   
label values v470l    V470L   
label values v470o    V470O   
label values v470q    V470Q   
label values v470r    V470R   
label values v470u    V470U   
label values v470v    V470V   
label values v470w    V470W   
label values v470y    V470Y   
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v505     V505    
label values v506     V506    
label values v510     V510    
label values v513     V513    
label values v525     V525    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v531     V531    
label values v532     V532    
label values v535     V535    
label values v536     V536    
label values v537     V537    
label values v602     V602    
label values v603     V603    
label values v604     V604    
label values v605     V605    
label values v610     V610    
label values v611     V611    
label values v612     V612    
label values v613     V613    
label values v614     V614    
label values v616     V616    
label values v621     V621    
label values v623     V623    
label values v624     V624    
label values v625     V625    
label values v626     V626    
label values v627     V627    
label values v628     V628    
label values v629     V629    
label values v630a    V630A   
label values v630b    V630B   
label values v630c    V630C   
label values v630d    V630D   
label values v630e    V630E   
label values v630f    V630F   
label values v630g    V630G   
label values v630h    V630H   
label values v630i    V630I   
label values v630x    V630X   
label values v631     V631    
label values v632     V632    
label values v633a    V633A   
label values v633b    V633B   
label values v633c    V633C   
label values v633d    V633D   
label values v633e    V633E   
label values v633f    V633F   
label values v633g    V633G   
label values v701     V701    
label values v702     V702    
label values v704     V704    
label values v705     V705    
label values v714     V714    
label values v715     V715    
label values v716     V716    
label values v717     V717    
label values v719     V719    
label values v721     V721    
label values v729     V729    
label values v730     V730    
label values v731     V731    
label values v732     V732    
label values v739     V739    
label values v740     V740    
label values v741     V741    
label values v744a    V744A   
label values v744b    V744B   
label values v744c    V744C   
label values v744d    V744D   
label values v744e    V744E   
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values m1       M1      
label values m2d      M2D     
label values m2f      M2F     
label values m2g      M2G     
label values m2k      M2K     
label values m2n      M2N     
label values m3d      M3D     
label values m3f      M3F     
label values m3g      M3G     
label values m3h      M3H     
label values m3k      M3K     
label values m3n      M3N     
label values m4       M4      
label values m5       M5      
label values m6       M6      
label values m7       M7      
label values m8       M8      
label values m9       M9      
label values m10      M10     
label values m11      M11     
label values m13      M13     
label values m14      M14     
label values m15      M15     
label values m17      M17     
label values m18      M18     
label values m19      M19     
label values m19a     M19A    
label values m27      M27     
label values m28      M28     
label values m29      M29     
label values m34      M34     
label values m35      M35     
label values m36      M36     
label values m37a     M37A    
label values m37c     M37C    
label values m37h     M37H    
label values m37l     M37L    
label values m37o     M37O    
label values m37q     M37Q    
label values m37r     M37R    
label values m37u     M37U    
label values m37v     M37V    
label values m37w     M37W    
label values m37y     M37Y    
label values m38      M38     
label values m39      M39     
label values m40a     M40A    
label values m40c     M40C    
label values m40h     M40H    
label values m40l     M40L    
label values m40o     M40O    
label values m40q     M40Q    
label values m40r     M40R    
label values m40u     M40U    
label values m40v     M40V    
label values m40w     M40W    
label values m40y     M40Y    
label values m41      M41     
label values m42a     M42A    
label values m42b     M42B    
label values m42c     M42C    
label values m42d     M42D    
label values m42e     M42E    
label values m43      M43     
label values m44      M44     
label values m45      M45     
label values m46      M46     
label values m47      M47     
label values m48      M48     
label values m49a     M49A    
label values m49b     M49B    
label values m49c     M49C    
label values m49d     M49D    
label values m49e     M49E    
label values m49f     M49F    
label values m49g     M49G    
label values m49x     M49X    
label values m49z     M49Z    
label values m50      M50     
label values m51      M51     
label values m52      M52     
label values m53      M53     
label values m54      M54     
label values m56      M56     
label values h1       H1      
label values h2       H2      
label values h2d      H2D     
label values h2m      H2M     
label values h2y      H2Y     
label values h3       H3      
label values h3d      H3D     
label values h3m      H3M     
label values h3y      H3Y     
label values h4       H4      
label values h4d      H4D     
label values h4m      H4M     
label values h4y      H4Y     
label values h5       H5      
label values h5d      H5D     
label values h5m      H5M     
label values h5y      H5Y     
label values h6       H6      
label values h6d      H6D     
label values h6m      H6M     
label values h6y      H6Y     
label values h7       H7      
label values h7d      H7D     
label values h7m      H7M     
label values h7y      H7Y     
label values h8       H8      
label values h8d      H8D     
label values h8m      H8M     
label values h8y      H8Y     
label values h9       H9      
label values h9d      H9D     
label values h9m      H9M     
label values h9y      H9Y     
label values h0       H0      
label values h0d      H0D     
label values h0m      H0M     
label values h0y      H0Y     
label values h10      H10     
label values h11      H11     
label values h12a     H12A    
label values h12b     H12B    
label values h12c     H12C    
label values h12e     H12E    
label values h12f     H12F    
label values h12g     H12G    
label values h12j     H12J    
label values h12k     H12K    
label values h12l     H12L    
label values h12n     H12N    
label values h12o     H12O    
label values h12p     H12P    
label values h12q     H12Q    
label values h12s     H12S    
label values h12t     H12T    
label values h12u     H12U    
label values h12x     H12X    
label values h12y     H12Y    
label values h12z     H12Z    
label values h13      H13     
label values h14      H14     
label values h15      H15     
label values h15a     H15A    
label values h15b     H15B    
label values h15c     H15C    
label values h15d     H15D    
label values h15e     H15E    
label values h15f     H15F    
label values h15g     H15G    
label values h15h     H15H    
label values h20      H20     
label values h21a     H21A    
label values h21      H21     
label values h22      H22     
label values h31      H31     
label values h31b     H31B    
label values h32a     H32A    
label values h32b     H32B    
label values h32c     H32C    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32n     H32N    
label values h32o     H32O    
label values h32p     H32P    
label values h32q     H32Q    
label values h32s     H32S    
label values h32t     H32T    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h33      H33     
label values h34      H34     
label values h35      H35     
label values h36a     H36A    
label values h36b     H36B    
label values h36c     H36C    
label values h37a     H37A    
label values h37b     H37B    
label values h37c     H37C    
label values h37d     H37D    
label values h37e     H37E    
label values h37f     H37F    
label values h37x     H37X    
label values h37y     H37Y    
label values h37z     H37Z    
label values h38      H38     
label values h39      H39     
label values hw4      HW4     
label values hw5      HW5     
label values hw6      HW6     
label values hw7      HW7     
label values hw8      HW8     
label values hw9      HW9     
label values hw10     HW10    
label values hw11     HW11    
label values hw12     HW12    
label values hw13     HW13    
label values hw15     HW15    
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw55     HW55    
label values hw57     HW57    
label values hw58     HW58    
label values sintyg   SINTYG  
label values slan     SLAN    
label values sintv    SINTV   
label values sresp    SRESP   
label values strans   STRANS  
label values s101t    S101T   
label values s101h    S101H   
label values s101m    S101M   
label values s105mg   S105MG  
label values s105yg   S105YG  
label values s109     S109    
label values s230af   S230AF  
label values s230b    S230B   
label values s230amg  S230AMG 
label values s230ayg  S230AYG 
label values s234     S234    
label values s234a    S234A   
label values s234c    S234C   
label values sd234b1  SD234B1 
label values sm234b1  SM234B1 
label values sy234b1  SY234B1 
label values sd234b2  SD234B2 
label values sm234b2  SM234B2 
label values sy234b2  SY234B2 
label values sd234b3  SD234B3 
label values sm234b3  SM234B3 
label values sy234b3  SY234B3 
label values sd234b4  SD234B4 
label values sm234b4  SM234B4 
label values sy234b4  SY234B4 
label values sd234b5  SD234B5 
label values sm234b5  SM234B5 
label values sy234b5  SY234B5 
label values s312     S312    
label values s319     S319    
label values s319d    S319D   
label values s329     S329    
label values s482     S482    
label values s483     S483    
label values s484     S484    
label values s489     S489    
label values s489aa   S489AA  
label values s489ab   S489AB  
label values s489ac   S489AC  
label values s489ad   S489AD  
label values s489ae   S489AE  
label values s489af   S489AF  
label values s489ag   S489AG  
label values s489ah   S489AH  
label values s489ai   S489AI  
label values s489aj   S489AJ  
label values s489ak   S489AK  
label values s489al   S489AL  
label values s489ax   S489AX  
label values s508mg   S508MG  
label values s508yg   S508YG  
label values s617d    S617D   
label values s617e    S617E   
label values s702a    S702A   
label values s705     S705    
label values s712a    S712A   
label values s1001aa  S1001AA 
label values s1001ab  S1001AB 
label values s1001ac  S1001AC 
label values s1001ad  S1001AD 
label values s1001ae  S1001AE 
label values s1001af  S1001AF 
label values s1001ag  S1001AG 
label values s1001ah  S1001AH 
label values s1001ai  S1001AI 
label values s1001aj  S1001AJ 
label values s1001ak  S1001AK 
label values s1001ax  S1001AX 
label values s1005    S1005   
label values s1006    S1006   
label values s1008    S1008   
label values s1013a   S1013A  
label values s1013b   S1013B  
label values s1013c   S1013C  
label values s1013d   S1013D  
label values s1013z   S1013Z  
label values s1106    S1106   
label values s1111    S1111   
label values s1112    S1112   
label values s1114t   S1114T  
label values s1114h   S1114H  
label values s215mg   S215MG  
label values s215yg   S215YG  
label values s406a    S406A   
label values s406ba   S406BA  
label values s406bb   S406BB  
label values s406bc   S406BC  
label values s406bd   S406BD  
label values s406be   S406BE  
label values s406bx   S406BX  
label values s432c    S432C   
label values s440a    S440A   
label values s442a    S442A   
label values s475c    S475C   
