DATA LIST FILE='ETBR41FL.DAT' RECORDS = 1
 /
  CASEID      1-15   (A)
  BIDX       16-17  
  V000       18-20   (A)
  V001       21-28  
  V002       29-32  
  V003       33-35  
  V004       36-39  
  V005       40-47  
  V006       48-49  
  V007       50-53  
  V008       54-57  
  V009       58-59  
  V010       60-63  
  V011       64-67  
  V012       68-69  
  V013       70-70  
  V014       71-71  
  V015       72-72  
  V016       73-74  
  V017       75-78  
  V018       79-80  
  V019       81-82  
  V019A      83-83  
  V020       84-84  
  V021       85-88  
  V022       89-92  
  V023       93-94  
  V024       95-96  
  V025       97-97  
  V026       98-98  
  V027       99-99  
  V028      100-102 
  V029      103-104 
  V030      105-107 
  V031      108-110 
  V032      111-112 
  V033      113-120 
  V034      121-122 
  V040      123-126 
  V042      127-127 
  V043      128-128 
  V044      129-129 
  V101      130-131 
  V102      132-132 
  V103      133-133 
  V104      134-135 
  V105      136-136 
  V106      137-137 
  V107      138-139 
  V113      140-141 
  V115      142-144 
  V116      145-146 
  V119      147-147 
  V120      148-148 
  V121      149-149 
  V122      150-150 
  V123      151-151 
  V124      152-152 
  V125      153-153 
  V127      154-155 
  V128      156-157 
  V129      158-159 
  V130      160-160 
  V131      161-162 
  V133      163-164 
  V134      165-165 
  V135      166-166 
  V136      167-168 
  V137      169-170 
  V138      171-172 
  V139      173-174 
  V140      175-175 
  V141      176-176 
  V149      177-177 
  V150      178-179 
  V151      180-180 
  V152      181-182 
  V153      183-183 
  AWFACTT   184-188 
  AWFACTU   189-193 
  AWFACTR   194-198 
  AWFACTE   199-203 
  V155      204-204 
  V156      205-205 
  V157      206-206 
  V158      207-207 
  V159      208-208 
  V160      209-209 
  V161      210-211 
  V162      212-212 
  V163      213-213 
  V164      214-214 
  V165      215-215 
  V166      216-218 
  V201      219-220 
  V202      221-222 
  V203      223-224 
  V204      225-226 
  V205      227-228 
  V206      229-230 
  V207      231-232 
  V208      233-233 
  V209      234-234 
  V210      235-235 
  V211      236-239 
  V212      240-241 
  V213      242-242 
  V214      243-244 
  V215      245-247 
  V216      248-248 
  V217      249-249 
  V218      250-251 
  V219      252-253 
  V220      254-254 
  V221      255-257 
  V222      258-260 
  V223      261-261 
  V224      262-263 
  V225      264-264 
  V226      265-267 
  V227      268-268 
  V228      269-269 
  V229      270-271 
  V230      272-275 
  V231      276-279 
  V232      280-280 
  V233      281-282 
  V234      283-283 
  V235      284-285 
  V237      286-286 
  V238      287-287 
  V239      288-288 
  V240      289-290 
  V241      291-294 
  V242      295-298 
  V243      299-299 
  V310      300-301 
  V311      302-302 
  V312      303-304 
  V313      305-305 
  V315      306-307 
  V316      308-311 
  V317      312-315 
  V318      316-316 
  V319      317-317 
  V320      318-318 
  V321      319-319 
  V322      320-320 
  V326      321-322 
  V327      323-323 
  V337      324-326 
  V359      327-328 
  V360      329-330 
  V361      331-331 
  V362      332-332 
  V363      333-334 
  V364      335-335 
  V367      336-336 
  V375A     337-338 
  V376      339-340 
  V376A     341-341 
  V379      342-343 
  V380      344-344 
  V384A     345-345 
  V384B     346-346 
  V384C     347-347 
  V393      348-348 
  V394      349-349 
  V395      350-350 
  V3A00A    351-351 
  V3A00B    352-352 
  V3A00C    353-353 
  V3A00D    354-354 
  V3A00E    355-355 
  V3A00F    356-356 
  V3A00G    357-357 
  V3A00H    358-358 
  V3A00I    359-359 
  V3A00J    360-360 
  V3A00K    361-361 
  V3A00L    362-362 
  V3A00M    363-363 
  V3A00N    364-364 
  V3A00O    365-365 
  V3A00P    366-366 
  V3A00Q    367-367 
  V3A00R    368-368 
  V3A00S    369-369 
  V3A00T    370-370 
  V3A00U    371-371 
  V3A00V    372-372 
  V3A00W    373-373 
  V3A00X    374-374 
  V3A00Y    375-375 
  V3A00Z    376-376 
  V3A01     377-377 
  V3A02     378-378 
  V3A03     379-379 
  V3A04     380-380 
  V3A05     381-381 
  V3A06     382-382 
  V3A07     383-384 
  V3A08A    385-385 
  V3A08B    386-386 
  V3A08C    387-387 
  V3A08D    388-388 
  V3A08E    389-389 
  V3A08F    390-390 
  V3A08G    391-391 
  V3A08H    392-392 
  V3A08I    393-393 
  V3A08J    394-394 
  V3A08K    395-395 
  V3A08L    396-396 
  V3A08M    397-397 
  V3A08N    398-398 
  V3A08O    399-399 
  V3A08P    400-400 
  V3A08Q    401-401 
  V3A08R    402-402 
  V3A08S    403-403 
  V3A08T    404-404 
  V3A08U    405-405 
  V3A08V    406-406 
  V3A08W    407-407 
  V3A08X    408-408 
  V3A08Z    409-409 
  V401      410-410 
  V404      411-411 
  V405      412-412 
  V406      413-413 
  V407      414-415 
  V408      416-417 
  V415      418-418 
  V416      419-419 
  V417      420-420 
  V418      421-421 
  V419      422-422 
  V420      423-425 
  V421      426-428 
  V426      429-431 
  V437      432-435 
  V438      436-439 
  V439      440-443 
  V440      444-447 
  V441      448-452 
  V442      453-457 
  V443      458-462 
  V444      463-467 
  V444A     468-471 
  V445      472-475 
  V446      476-479 
  V447      480-480 
  V447A     481-482 
  V452A     483-483 
  V452B     484-485 
  V452C     486-486 
  V453      487-489 
  V454      490-490 
  V455      491-491 
  V456      492-494 
  V457      495-495 
  V458      496-496 
  V459      497-497 
  V460      498-498 
  V461      499-499 
  V462      500-500 
  V463A     501-501 
  V463B     502-502 
  V463C     503-503 
  V463D     504-504 
  V463E     505-505 
  V463F     506-506 
  V463G     507-507 
  V463Z     508-508 
  V464      509-510 
  V465      511-512 
  V466      513-513 
  V467A     514-514 
  V467B     515-515 
  V467C     516-516 
  V467D     517-517 
  V467E     518-518 
  V467F     519-519 
  V467G     520-520 
  V468      521-521 
  V469A     522-522 
  V469B     523-523 
  V469C     524-524 
  V469D     525-525 
  V469E     526-526 
  V469F     527-527 
  V469G     528-528 
  V469H     529-529 
  V469I     530-530 
  V469J     531-531 
  V469K     532-532 
  V469L     533-533 
  V469M     534-534 
  V469N     535-535 
  V469O     536-536 
  V469P     537-537 
  V469Q     538-538 
  V469R     539-539 
  V469S     540-540 
  V469T     541-541 
  V469U     542-542 
  V469V     543-543 
  V469W     544-544 
  V469X     545-545 
  V469Y     546-546 
  V469Z     547-547 
  V469XX    548-548 
  V469XY    549-549 
  V469XZ    550-550 
  V470A     551-551 
  V470B     552-552 
  V470C     553-553 
  V470D     554-554 
  V470E     555-555 
  V470F     556-556 
  V470G     557-557 
  V470H     558-558 
  V470I     559-559 
  V470J     560-560 
  V470K     561-561 
  V470L     562-562 
  V470M     563-563 
  V470N     564-564 
  V470O     565-565 
  V470P     566-566 
  V470Q     567-567 
  V470R     568-568 
  V470S     569-569 
  V470T     570-570 
  V470U     571-571 
  V470V     572-572 
  V470W     573-573 
  V470X     574-574 
  V470Y     575-575 
  V470Z     576-576 
  V470XX    577-577 
  V470XY    578-578 
  V470XZ    579-579 
  V501      580-580 
  V502      581-581 
  V503      582-582 
  V504      583-583 
  V505      584-585 
  V506      586-587 
  V507      588-589 
  V508      590-593 
  V509      594-597 
  V510      598-598 
  V511      599-600 
  V512      601-602 
  V513      603-603 
  V525      604-605 
  V527      606-608 
  V528      609-610 
  V529      611-613 
  V530      614-614 
  V531      615-616 
  V532      617-617 
  V535      618-618 
  V536      619-619 
  V537      620-621 
  V602      622-622 
  V603      623-625 
  V604      626-626 
  V605      627-627 
  V610      628-628 
  V611      629-629 
  V612      630-630 
  V613      631-632 
  V614      633-633 
  V616      634-636 
  V621      637-637 
  V623      638-638 
  V624      639-640 
  V625      641-641 
  V626      642-643 
  V627      644-645 
  V628      646-647 
  V629      648-649 
  V630A     650-650 
  V630B     651-651 
  V630C     652-652 
  V630D     653-653 
  V630E     654-654 
  V630F     655-655 
  V630G     656-656 
  V630H     657-657 
  V630I     658-658 
  V630J     659-659 
  V630K     660-660 
  V630L     661-661 
  V630M     662-662 
  V630N     663-663 
  V630O     664-664 
  V630X     665-665 
  V631      666-666 
  V632      667-667 
  V633A     668-668 
  V633B     669-669 
  V633C     670-670 
  V633D     671-671 
  V633E     672-672 
  V633F     673-673 
  V633G     674-674 
  V701      675-675 
  V702      676-677 
  V704      678-680 
  V705      681-682 
  V714      683-683 
  V715      684-685 
  V716      686-688 
  V717      689-690 
  V719      691-691 
  V721      692-692 
  V729      693-693 
  V730      694-695 
  V731      696-696 
  V732      697-697 
  V739      698-698 
  V740      699-699 
  V741      700-700 
  V742      701-701 
  V743A     702-702 
  V743B     703-703 
  V743C     704-704 
  V743D     705-705 
  V743E     706-706 
  V744A     707-707 
  V744B     708-708 
  V744C     709-709 
  V744D     710-710 
  V744E     711-711 
  BORD      712-713 
  B0        714-714 
  B1        715-716 
  B2        717-720 
  B3        721-724 
  B4        725-725 
  B5        726-726 
  B6        727-729 
  B7        730-732 
  B8        733-734 
  B9        735-735 
  B10       736-736 
  B11       737-739 
  B12       740-742 
  B13       743-743 
  B15       744-744 
  B16       745-746 
  MIDX      747-747 
  M1        748-748 
  M2A       749-749 
  M2B       750-750 
  M2C       751-751 
  M2D       752-752 
  M2E       753-753 
  M2F       754-754 
  M2G       755-755 
  M2H       756-756 
  M2I       757-757 
  M2J       758-758 
  M2K       759-759 
  M2L       760-760 
  M2M       761-761 
  M2N       762-762 
  M3A       763-763 
  M3B       764-764 
  M3C       765-765 
  M3D       766-766 
  M3E       767-767 
  M3F       768-768 
  M3G       769-769 
  M3H       770-770 
  M3I       771-771 
  M3J       772-772 
  M3K       773-773 
  M3L       774-774 
  M3M       775-775 
  M3N       776-776 
  M4        777-778 
  M5        779-780 
  M6        781-782 
  M7        783-784 
  M8        785-786 
  M9        787-788 
  M10       789-789 
  M11       790-792 
  M13       793-794 
  M14       795-796 
  M15       797-798 
  M17       799-799 
  M18       800-800 
  M19       801-804 
  M19A      805-805 
  M27       806-806 
  M28       807-807 
  M29       808-808 
  M34       809-811 
  M35       812-813 
  M36       814-815 
  M37A      816-816 
  M37B      817-817 
  M37C      818-818 
  M37D      819-819 
  M37E      820-820 
  M37F      821-821 
  M37G      822-822 
  M37H      823-823 
  M37I      824-824 
  M37J      825-825 
  M37K      826-826 
  M37L      827-827 
  M37M      828-828 
  M37N      829-829 
  M37O      830-830 
  M37P      831-831 
  M37Q      832-832 
  M37R      833-833 
  M37S      834-834 
  M37T      835-835 
  M37U      836-836 
  M37V      837-837 
  M37W      838-838 
  M37X      839-839 
  M37Y      840-840 
  M37Z      841-841 
  M37XX     842-842 
  M37XY     843-843 
  M37XZ     844-844 
  M38       845-845 
  M39       846-846 
  M40A      847-847 
  M40B      848-848 
  M40C      849-849 
  M40D      850-850 
  M40E      851-851 
  M40F      852-852 
  M40G      853-853 
  M40H      854-854 
  M40I      855-855 
  M40J      856-856 
  M40K      857-857 
  M40L      858-858 
  M40M      859-859 
  M40N      860-860 
  M40O      861-861 
  M40P      862-862 
  M40Q      863-863 
  M40R      864-864 
  M40S      865-865 
  M40T      866-866 
  M40U      867-867 
  M40V      868-868 
  M40W      869-869 
  M40X      870-870 
  M40Y      871-871 
  M40Z      872-872 
  M40XX     873-873 
  M40XY     874-874 
  M40XZ     875-875 
  M41       876-877 
  M42A      878-878 
  M42B      879-879 
  M42C      880-880 
  M42D      881-881 
  M42E      882-882 
  M43       883-883 
  M44       884-884 
  M45       885-885 
  M46       886-888 
  M47       889-889 
  M48       890-890 
  M49A      891-891 
  M49B      892-892 
  M49C      893-893 
  M49D      894-894 
  M49E      895-895 
  M49F      896-896 
  M49G      897-897 
  M49X      898-898 
  M49Z      899-899 
  M50       900-900 
  M51       901-903 
  M52       904-905 
  M53       906-907 
  M54       908-908 
  M55A      909-909 
  M55B      910-910 
  M55C      911-911 
  M55D      912-912 
  M55E      913-913 
  M55F      914-914 
  M55G      915-915 
  M55H      916-916 
  M55I      917-917 
  M55J      918-918 
  M55K      919-919 
  M55L      920-920 
  M55M      921-921 
  M55N      922-922 
  M55X      923-923 
  M55Z      924-924 
  M56       925-925 
  HIDX      926-926 
  H1        927-927 
  H2        928-928 
  H2D       929-930 
  H2M       931-932 
  H2Y       933-936 
  H3        937-937 
  H3D       938-939 
  H3M       940-941 
  H3Y       942-945 
  H4        946-946 
  H4D       947-948 
  H4M       949-950 
  H4Y       951-954 
  H5        955-955 
  H5D       956-957 
  H5M       958-959 
  H5Y       960-963 
  H6        964-964 
  H6D       965-966 
  H6M       967-968 
  H6Y       969-972 
  H7        973-973 
  H7D       974-975 
  H7M       976-977 
  H7Y       978-981 
  H8        982-982 
  H8D       983-984 
  H8M       985-986 
  H8Y       987-990 
  H9        991-991 
  H9D       992-993 
  H9M       994-995 
  H9Y       996-999 
  H0       1000-1000
  H0D      1001-1002
  H0M      1003-1004
  H0Y      1005-1008
  H10      1009-1009
  H11      1010-1010
  H12A     1011-1011
  H12B     1012-1012
  H12C     1013-1013
  H12D     1014-1014
  H12E     1015-1015
  H12F     1016-1016
  H12G     1017-1017
  H12H     1018-1018
  H12I     1019-1019
  H12J     1020-1020
  H12K     1021-1021
  H12L     1022-1022
  H12M     1023-1023
  H12N     1024-1024
  H12O     1025-1025
  H12P     1026-1026
  H12Q     1027-1027
  H12R     1028-1028
  H12S     1029-1029
  H12T     1030-1030
  H12U     1031-1031
  H12V     1032-1032
  H12W     1033-1033
  H12X     1034-1034
  H12Y     1035-1035
  H12Z     1036-1036
  H13      1037-1037
  H14      1038-1038
  H15      1039-1039
  H15A     1040-1040
  H15B     1041-1041
  H15C     1042-1042
  H15D     1043-1043
  H15E     1044-1044
  H15F     1045-1045
  H15G     1046-1046
  H15H     1047-1047
  H20      1048-1048
  H21A     1049-1049
  H21      1050-1050
  H22      1051-1051
  H31      1052-1052
  H31B     1053-1053
  H32A     1054-1054
  H32B     1055-1055
  H32C     1056-1056
  H32D     1057-1057
  H32E     1058-1058
  H32F     1059-1059
  H32G     1060-1060
  H32H     1061-1061
  H32I     1062-1062
  H32J     1063-1063
  H32K     1064-1064
  H32L     1065-1065
  H32M     1066-1066
  H32N     1067-1067
  H32O     1068-1068
  H32P     1069-1069
  H32Q     1070-1070
  H32R     1071-1071
  H32S     1072-1072
  H32T     1073-1073
  H32U     1074-1074
  H32V     1075-1075
  H32W     1076-1076
  H32X     1077-1077
  H32Y     1078-1078
  H32Z     1079-1079
  H33      1080-1080
  H33D     1081-1082
  H33M     1083-1084
  H33Y     1085-1088
  H34      1089-1089
  H35      1090-1090
  H36A     1091-1091
  H36B     1092-1092
  H36C     1093-1093
  H36D     1094-1094
  H36E     1095-1095
  H36F     1096-1096
  H37A     1097-1097
  H37B     1098-1098
  H37C     1099-1099
  H37D     1100-1100
  H37E     1101-1101
  H37F     1102-1102
  H37G     1103-1103
  H37H     1104-1104
  H37X     1105-1105
  H37Y     1106-1106
  H37Z     1107-1107
  H38      1108-1108
  H39      1109-1109
  HWIDX    1110-1110
  HW1      1111-1112
  HW2      1113-1115
  HW3      1116-1119
  HW4      1120-1123
  HW5      1124-1127
  HW6      1128-1132
  HW7      1133-1136
  HW8      1137-1140
  HW9      1141-1145
  HW10     1146-1149
  HW11     1150-1153
  HW12     1154-1158
  HW13     1159-1159
  HW15     1160-1160
  HW16     1161-1162
  HW17     1163-1164
  HW18     1165-1166
  HW19     1167-1170
  HW51     1171-1172
  HW52     1173-1173
  HW53     1174-1176
  HW55     1177-1177
  HW56     1178-1181
  HW57     1182-1182
  HW58     1183-1183
  SINTDG   1184-1185
  SINTMG   1186-1187
  SINTYG   1188-1191
  SINTCG   1192-1195
  SLAN     1196-1196
  SINTV    1197-1197
  SRESP    1198-1198
  STRANS   1199-1199
  S101T    1200-1200
  S101H    1201-1202
  S101M    1203-1204
  S105MG   1205-1206
  S105YG   1207-1210
  S105CG   1211-1214
  S109     1215-1216
  S227CG   1217-1220
  S230AC   1221-1224
  S230AF   1225-1225
  S230B    1226-1228
  S230AMG  1229-1230
  S230AYG  1231-1234
  S230ACG  1235-1238
  S230F    1239-1239
  S234     1240-1240
  S234A    1241-1241
  S234C    1242-1243
  SD234B1  1244-1245
  SM234B1  1246-1247
  SY234B1  1248-1251
  SD234B2  1252-1253
  SM234B2  1254-1255
  SY234B2  1256-1259
  SD234B3  1260-1261
  SM234B3  1262-1263
  SY234B3  1264-1267
  SD234B4  1268-1269
  SM234B4  1270-1271
  SY234B4  1272-1275
  SD234B5  1276-1277
  SM234B5  1278-1279
  SY234B5  1280-1283
  S312     1284-1285
  S319     1286-1287
  S319D    1288-1290
  S329     1291-1292
  S482     1293-1293
  S483     1294-1294
  S484     1295-1296
  S489     1297-1297
  S489AA   1298-1298
  S489AB   1299-1299
  S489AC   1300-1300
  S489AD   1301-1301
  S489AE   1302-1302
  S489AF   1303-1303
  S489AG   1304-1304
  S489AH   1305-1305
  S489AI   1306-1306
  S489AJ   1307-1307
  S489AK   1308-1308
  S489AL   1309-1309
  S489AX   1310-1310
  S508MG   1311-1312
  S508YG   1313-1316
  S508CG   1317-1320
  S617D    1321-1321
  S617E    1322-1322
  S702A    1323-1323
  S705     1324-1325
  S712A    1326-1326
  S1001AA  1327-1327
  S1001AB  1328-1328
  S1001AC  1329-1329
  S1001AD  1330-1330
  S1001AE  1331-1331
  S1001AF  1332-1332
  S1001AG  1333-1333
  S1001AH  1334-1334
  S1001AI  1335-1335
  S1001AJ  1336-1336
  S1001AK  1337-1337
  S1001AX  1338-1338
  S1005    1339-1339
  S1006    1340-1340
  S1008    1341-1341
  S1013A   1342-1342
  S1013B   1343-1343
  S1013C   1344-1344
  S1013D   1345-1345
  S1013Z   1346-1346
  S1106    1347-1347
  S1111    1348-1348
  S1112    1349-1350
  S1114T   1351-1351
  S1114H   1352-1353
  S1114M   1354-1355
  IDX92    1356-1357
  S215MG   1358-1359
  S215YG   1360-1363
  S215CG   1364-1367
  IDX94    1368-1368
  S406A    1369-1369
  S406BA   1370-1370
  S406BB   1371-1371
  S406BC   1372-1372
  S406BD   1373-1373
  S406BE   1374-1374
  S406BX   1375-1375
  S432C    1376-1378
  S440A    1379-1379
  S442A    1380-1381
  S475C    1382-1382
 .
VARIABLE LABELS
  CASEID   "Case Identification"
 /BIDX     "Birth column number"
 /V000     "Country code and phase"
 /V001     "Cluster number"
 /V002     "Household number"
 /V003     "Respondent's line number"
 /V004     "Ultimate area unit"
 /V005     "Sample weight"
 /V006     "Month of interview"
 /V007     "Year of interview"
 /V008     "Date of interview (CMC)"
 /V009     "Respondent's month of birth"
 /V010     "Respondent's year of birth"
 /V011     "Date of birth (CMC)"
 /V012     "Current age - respondent"
 /V013     "Age 5-year groups"
 /V014     "Completeness of information"
 /V015     "Result of individual interview"
 /V016     "Day of interview"
 /V017     "CMC start of calendar      -NA"
 /V018     "Row of month of interview"
 /V019     "Length of calendar"
 /V019A    "Number of calendar columns"
 /V020     "Ever-married sample"
 /V021     "Primary sampling unit"
 /V022     "Sample stratum number"
 /V023     "Sample domain"
 /V024     "Region"
 /V025     "Type of place of residence"
 /V026     "De facto place of residence"
 /V027     "Number of visits"
 /V028     "Interviewer identification"
 /V029     "Keyer identification"
 /V030     "Field supervisor"
 /V031     "Field editor"
 /V032     "Office editor"
 /V033     "Ultimate area selection prob."
 /V034     "Line number of husband"
 /V040     "Cluster altitude in meters -NA"
 /V042     "Household selection for hemoglobin"
 /V043     "Selection for women's status module"
 /V044     "Selection for domestic violence"
 /V101     "Region"
 /V102     "Type of place of residence"
 /V103     "Childhood place of residence"
 /V104     "Years lived in place of res."
 /V105     "Type of place of previous res."
 /V106     "Highest educational level"
 /V107     "Highest year of education"
 /V113     "Source of drinking water"
 /V115     "Time to get to water source"
 /V116     "Type of toilet facility"
 /V119     "Has electricity"
 /V120     "Has radio"
 /V121     "Has television"
 /V122     "Has refrigerator           -NA"
 /V123     "Has bicycle"
 /V124     "Has motorcycle/scooter"
 /V125     "Has car/truck"
 /V127     "Main floor material"
 /V128     "Main wall material         -NA"
 /V129     "Main roof material"
 /V130     "Religion"
 /V131     "Ethnicity"
 /V133     "Education in single years"
 /V134     "De facto place of residence"
 /V135     "Usual resident or visitor"
 /V136     "Number of household members"
 /V137     "Number of children 5 and under"
 /V138     "Number of eligible women in HH"
 /V139     "De jure region of residence"
 /V140     "De jure type of place of res."
 /V141     "De jure place of residence"
 /V149     "Educational attainment"
 /V150     "Relationship to household head"
 /V151     "Sex of household head"
 /V152     "Age of household head"
 /V153     "Has telephone"
 /AWFACTT  "All woman factor - total"
 /AWFACTU  "All woman factor - urban/rural"
 /AWFACTR  "All woman factor - regional"
 /AWFACTE  "All woman factor - educational"
 /V155     "Literacy"
 /V156     "Ever participated in a lite-NA"
 /V157     "Frequency of reading newpaper or magazine"
 /V158     "Frequency of listening to radio"
 /V159     "Frequency of watching television"
 /V160     "Toilet facilities shared"
 /V161     "Type of cooking fuel"
 /V162     "Place for hand washing     -NA"
 /V163     "Presence of water/tap in ho-NA"
 /V164     "Presence of soap/ash/other -NA"
 /V165     "Presence of basin in househ-NA"
 /V166     "Results of salt iodine test-NA"
 /V201     "Total children ever born"
 /V202     "Sons at home"
 /V203     "Daughters at home"
 /V204     "Sons elsewhere"
 /V205     "Daughters elsewhere"
 /V206     "Sons who have died"
 /V207     "Daughters who have died"
 /V208     "Births in last five years"
 /V209     "Births in past year"
 /V210     "Births in month of interview"
 /V211     "Date of first birth (CMC)"
 /V212     "Age of respondent at 1st birth"
 /V213     "Currently pregnant"
 /V214     "Duration of current pregnancy"
 /V215     "Time since last menstrual perd"
 /V216     "Menstruated in last six weeks"
 /V217     "Knowledge of ovulatory cycle"
 /V218     "Number of living children"
 /V219     "Living children + current preg"
 /V220     "Living children + curr preg 6+"
 /V221     "Marriage to first birth int."
 /V222     "Last birth to interview"
 /V223     "Completeness of curr preg. inf"
 /V224     "Entries in birth history"
 /V225     "Current pregnancy wanted"
 /V226     "Time since last period (comp)"
 /V227     "Flag for last period"
 /V228     "Ever had a terminated preg."
 /V229     "Month pregnancy ended"
 /V230     "Year pregnancy ended"
 /V231     "CMC pregnancy ended"
 /V232     "Completeness of last term. inf"
 /V233     "Months when pregnancy ended"
 /V234     "Other such pregnancies"
 /V235     "Index last child prior to c-NA"
 /V237     "Birth between last & interview"
 /V238     "Births in last three years"
 /V239     "Pregnancies terminated befo-NA"
 /V240     "Month of last termination p-NA"
 /V241     "Year of last termination pr-NA"
 /V242     "CMC termination ended prior-NA"
 /V243     "Completeness of last termin-NA"
 /V310     "Living children at first use"
 /V311     "Children at first use (grpd)"
 /V312     "Current contraceptive method"
 /V313     "Current use by method type"
 /V315     "Month of start of use of me-NA"
 /V316     "Year of start of use of met-NA"
 /V317     "Date of start of use of met-NA"
 /V318     "Completeness of information-NA"
 /V319     "Years since sterilization  -NA"
 /V320     "Age at sterilization       -NA"
 /V321     "Marital duration at sterili-NA"
 /V322     "Parity at sterilization    -NA"
 /V326     "Last source for current users"
 /V327     "Last source for users by type"
 /V337     "Months of use of current me-NA"
 /V359     "Last method disc. last 5 ye-NA"
 /V360     "Reason of last discontinuat-NA"
 /V361     "Pattern of use"
 /V362     "Intention to use"
 /V363     "Preferred future method"
 /V364     "Contraceptive use & intention"
 /V367     "Wanted last child"
 /V375A    "Main reason not using a met-NA"
 /V376     "Main reason not to use a meth."
 /V376A    "Would ever use method if marr."
 /V379     "Source known for any method"
 /V380     "Source known for any method"
 /V384A    "Heard FP on radio last months"
 /V384B    "Heard FP on TV last months"
 /V384C    "Heard FP newspaper last months"
 /V393     "Visited by FP worker last 12m"
 /V394     "Visited health facil. last 12m"
 /V395     "At health facility, told of FP"
 /V3A00A   "Source of FP for non-users:-NA"
 /V3A00B   "Source of FP for non-users:-NA"
 /V3A00C   "Source of FP for non-users:-NA"
 /V3A00D   "Source of FP for non-users:-NA"
 /V3A00E   "Source of FP for non-users:-NA"
 /V3A00F   "Source of FP for non-users:-NA"
 /V3A00G   "Source of FP for non-users:-NA"
 /V3A00H   "Source of FP for non-users:-NA"
 /V3A00I   "Source of FP for non-users:-NA"
 /V3A00J   "Source of FP for non-users:-NA"
 /V3A00K   "Source of FP for non-users:-NA"
 /V3A00L   "Source of FP for non-users:-NA"
 /V3A00M   "Source of FP for non-users:-NA"
 /V3A00N   "Source of FP for non-users:-NA"
 /V3A00O   "Source of FP for non-users:-NA"
 /V3A00P   "Source of FP for non-users:-NA"
 /V3A00Q   "Source of FP for non-users:-NA"
 /V3A00R   "Source of FP for non-users:-NA"
 /V3A00S   "Source of FP for non-users:-NA"
 /V3A00T   "Source of FP for non-users:-NA"
 /V3A00U   "Source of FP for non-users:-NA"
 /V3A00V   "Source of FP for non-users:-NA"
 /V3A00W   "Source of FP for non-users:-NA"
 /V3A00X   "Source of FP for non-users:-NA"
 /V3A00Y   "Source of FP for non-users:-NA"
 /V3A00Z   "Source of FP for non-users:-NA"
 /V3A01    "Told sterilization would me-NA"
 /V3A02    "Told about side effects    -NA"
 /V3A03    "Told about side effects by -NA"
 /V3A04    "Told how to deal with side -NA"
 /V3A05    "Told about other FP methods-NA"
 /V3A06    "Told about other FP methods-NA"
 /V3A07    "First source for current method"
 /V3A08A   "Reason not using: Not married"
 /V3A08B   "Reason not using: Not having sex"
 /V3A08C   "Reason not using: Infrequent sex"
 /V3A08D   "Reason not using: Menopausal/hysterectomy"
 /V3A08E   "Reason not using: Subfecund/infecund"
 /V3A08F   "Reason not using: Postpartum amenorrheic"
 /V3A08G   "Reason not using: Breastfeeding"
 /V3A08H   "Reason not using: Fatalistic"
 /V3A08I   "Reason not using: Respondent opposed"
 /V3A08J   "Reason not using: Husband/partner opposed"
 /V3A08K   "Reason not using: Others opposed"
 /V3A08L   "Reason not using: Religious prohibition"
 /V3A08M   "Reason not using: Knows no method"
 /V3A08N   "Reason not using: Knows no source"
 /V3A08O   "Reason not using: Health concerns"
 /V3A08P   "Reason not using: Fear of side effects"
 /V3A08Q   "Reason not using: Lack of access/too far"
 /V3A08R   "Reason not using: Costs too much"
 /V3A08S   "Reason not using: Inconvenient to use"
 /V3A08T   "Reason not using: Interferes with bodys processes"
 /V3A08U   "Reason not using: Country s-NA"
 /V3A08V   "Reason not using: Country s-NA"
 /V3A08W   "Reason not using: Country s-NA"
 /V3A08X   "Reason not using: Other"
 /V3A08Z   "Reason not using: Don't know"
 /V401     "Last birth ceasarean section"
 /V404     "Currently breastfeeding"
 /V405     "Currently amenorrheic"
 /V406     "Currently abstaining"
 /V407     "Times breastfed during night"
 /V408     "Times breastfed during day"
 /V415     "Drank from bottle with nipple"
 /V416     "Heard of oral rehydration"
 /V417     "Entries in maternity table"
 /V418     "Entries in health table"
 /V419     "Entries in height/weight table"
 /V420     "Measurer's code            -NA"
 /V421     "Assistant measurer's code  -NA"
 /V426     "When child put to breast"
 /V437     "Respondent's weight (kilos-1d)"
 /V438     "Respondent's height (cms-1d)"
 /V439     "Ht/A Percentile (resp.)"
 /V440     "Ht/A Standard deviations (resp"
 /V441     "Ht/A Percent ref. median (resp"
 /V442     "Wt/Ht Percent ref. median (DHS"
 /V443     "Wt/Ht Percent ref. median (Fog"
 /V444     "Wt/Ht Percent ref. median (WHO"
 /V444A    "Wt/Ht Std deviations(resp) DHS"
 /V445     "Body mass index for respondent"
 /V446     "Rohrer's index for respondent"
 /V447     "Result of measurement of resp."
 /V447A    "Women's age in years from household report"
 /V452A    "Under age 18 (HH report)   -NA"
 /V452B    "Line no. of parent/caretake-NA"
 /V452C    "Read consent statement     -NA"
 /V453     "Hemoglobin level (g/dl - 1 -NA"
 /V454     "Currently pregnant (househo-NA"
 /V455     "Result of measuring (Hemogl-NA"
 /V456     "Hemoglobin level adjusted b-NA"
 /V457     "Anemia level               -NA"
 /V458     "Agrees to referral         -NA"
 /V459     "Have bednet for sleeping (household report)"
 /V460     "Children under 5 slept unde-NA"
 /V461     "Respondent slept under bedn-NA"
 /V462     "Washed hands before preparing last meal"
 /V463A    "Smokes cigarettes          -NA"
 /V463B    "Smokes pipe                -NA"
 /V463C    "Smokes other tobacco       -NA"
 /V463D    "Smokes country specific    -NA"
 /V463E    "Smokes country specific    -NA"
 /V463F    "Smokes country specific    -NA"
 /V463G    "Smokes country specific    -NA"
 /V463Z    "Smokes nothing             -NA"
 /V464     "Number of cigarettes in las-NA"
 /V465     "Disposal of youngest child's stools when not using toilet"
 /V466     "When child is seriously ill, can decide whether med tx sough"
 /V467A    "Getting medical help for se-NA"
 /V467B    "Getting medical help for se-NA"
 /V467C    "Getting medical help for se-NA"
 /V467D    "Getting medical help for se-NA"
 /V467E    "Getting medical help for se-NA"
 /V467F    "Getting medical help for se-NA"
 /V467G    "Getting medical help for se-NA"
 /V468     "Columns used for Last Birth Only variables"
 /V469A    "Times gave child plain water"
 /V469B    "Times gave child sugar wate-NA"
 /V469C    "Times gave child fruit juice"
 /V469D    "Times gave child herbal tea-NA"
 /V469E    "Times gave child powdered/t-NA"
 /V469F    "Times gave child commercial-NA"
 /V469G    "Times gave child fresh milk-NA"
 /V469H    "Times given tinned, powdered or fresh animal milk"
 /V469I    "Times given country specifi-NA"
 /V469J    "Times given country specifi-NA"
 /V469K    "Times given country specifi-NA"
 /V469L    "Times gave child other liquid"
 /V469M    "Times given pumpkin, carrot-NA"
 /V469N    "Times given any green leafy-NA"
 /V469O    "Times given mango, papaya or other Vit A rich fruits"
 /V469P    "Times given other solid, se-NA"
 /V469Q    "Times given food made from local grain"
 /V469R    "Times given food made from local roots/tuber"
 /V469S    "Times gave child eggs, fish-NA"
 /V469T    "Times gave child meat      -NA"
 /V469U    "Times gave child other fruits/vegetables"
 /V469V    "Times gave child meat, poultry, fish, shellfish, eggs"
 /V469W    "Times gave child legumes (lentils, beans, peanuts)"
 /V469X    "Times gave child cheese/yog-NA"
 /V469Y    "Times gave child foods made from oil, fat, butter"
 /V469Z    "Times gave child country sp-NA"
 /V469XX   "Times gave child country sp-NA"
 /V469XY   "Times gave child country sp-NA"
 /V469XZ   "Times gave child country sp-NA"
 /V470A    "Last 7 days - plain water"
 /V470B    "Last 7 days - sugar water  -NA"
 /V470C    "Last 7 days - fruit juice"
 /V470D    "Last 7 days -  herbal tea  -NA"
 /V470E    "Last 7 days - powder/tinned-NA"
 /V470F    "Last 7 days - commercially -NA"
 /V470G    "Last 7 days -  fresh milk  -NA"
 /V470H    "Last 7 days - tinned, powdered or fresh animal milk"
 /V470I    "Last 7 days - country speci-NA"
 /V470J    "Last 7 days - country speci-NA"
 /V470K    "Last 7 days - country speci-NA"
 /V470L    "Last 7 days -  other liquid"
 /V470M    "Last 7 days - pumpkin, carr-NA"
 /V470N    "Last 7 days - any green lea-NA"
 /V470O    "Last 7 days - mango, papaya or other Vit A rich fruits"
 /V470P    "Last 7 days - other solid, -NA"
 /V470Q    "Last 7 days - food made from local grain"
 /V470R    "Last 7 days - food made from local roots/tuber"
 /V470S    "Last 7 days - eggs, fish, p-NA"
 /V470T    "Last 7 days - meat         -NA"
 /V470U    "Last 7 days -  other fruits/vegetables"
 /V470V    "Last 7 days -  meat, poultry, fish, shellfish, eggs"
 /V470W    "Last 7 days - legumes (lentils, beans, peanuts)"
 /V470X    "Last 7 days - cheese/yogurt-NA"
 /V470Y    "Last 7 days - foods made with oil, fat, butter"
 /V470Z    "Last 7 days - country speci-NA"
 /V470XX   "Last 7 days - country speci-NA"
 /V470XY   "Last 7 days - country speci-NA"
 /V470XZ   "Last 7 days - country speci-NA"
 /V501     "Current marital status"
 /V502     "Currently/formerly/never marr."
 /V503     "Number of unions"
 /V504     "Husband lives in house"
 /V505     "Number of other wives"
 /V506     "Wife rank number"
 /V507     "Month of first marriage"
 /V508     "Year of first marriage"
 /V509     "Date of first marriage (CMC)"
 /V510     "Completeness of date inform."
 /V511     "Age at first marriage"
 /V512     "Years since first marriage"
 /V513     "Marital duration (grouped)"
 /V525     "Age at first intercourse"
 /V527     "Time since last intercourse"
 /V528     "Time since last intercourse(g)"
 /V529     "Time since last intercourse(imputed)"
 /V530     "Flag for V529"
 /V531     "Age at first intercourse (imp)"
 /V532     "Flag for V531"
 /V535     "Have ever been married"
 /V536     "Recent sexual activity"
 /V537     "Months of abstinence"
 /V602     "Fertility preference"
 /V603     "Preferred waiting time"
 /V604     "Preferred waiting time (grpd)"
 /V605     "Desire for more children"
 /V610     "Husband approves FP"
 /V611     "Discussed FP with partner"
 /V612     "Respondent approves FP"
 /V613     "Ideal number of children"
 /V614     "Ideal number of children (grp)"
 /V616     "Time for future birth"
 /V621     "Husbands desire for children"
 /V623     "Exposure"
 /V624     "Unmet need"
 /V625     "Exposure (definition 2)"
 /V626     "Unmet need (definition 2)"
 /V627     "Ideal number of boys"
 /V628     "Ideal number of girls"
 /V629     "Ideal number of either sex"
 /V630A    "Discussed FP with partner"
 /V630B    "Discussed FP with mother"
 /V630C    "Discussed FP with father"
 /V630D    "Discussed FP with sister(s)"
 /V630E    "Discussed FP with brother(s)"
 /V630F    "Discussed FP with daughter(s)"
 /V630G    "Discussed FP with mother-in-law"
 /V630H    "Discussed FP with friends/nbrs"
 /V630I    "Discussed FP with son(s)"
 /V630J    "Discussed FP -country speci-NA"
 /V630K    "Discussed FP -country speci-NA"
 /V630L    "Discussed FP -country speci-NA"
 /V630M    "Discussed FP -country speci-NA"
 /V630N    "Discussed FP -country speci-NA"
 /V630O    "Discussed FP -country speci-NA"
 /V630X    "Discussed FP with others"
 /V631     "Problem if became pregnant"
 /V632     "Decision maker for using contraception"
 /V633A    "Reason for not having sex: -NA"
 /V633B    "Reason for not having sex: -NA"
 /V633C    "Reason for not having sex: -NA"
 /V633D    "Reason for not having sex: -NA"
 /V633E    "Reason for not having sex: -NA"
 /V633F    "Reason for not having sex: -NA"
 /V633G    "Reason for not having sex: -NA"
 /V701     "Partner's education level"
 /V702     "Highest year of education"
 /V704     "Partner's occupation"
 /V705     "Partner's occupation"
 /V714     "Respondent currently working"
 /V715     "Husbands education-single yrs"
 /V716     "Respondent's occupation"
 /V717     "Respondent's occupation"
 /V719     "Work for family, others, self"
 /V721     "Works at home or away"
 /V729     "Partner's educational attainm."
 /V730     "Partners age"
 /V731     "Worked in last 12 months"
 /V732     "Employment all year/seasonal"
 /V739     "Who decides how to spend money"
 /V740     "Type of land where resp. works"
 /V741     "Type of earnings for work"
 /V742     "Portion of household expend-NA"
 /V743A    "Final say on own health car-NA"
 /V743B    "Final say on making large h-NA"
 /V743C    "Final say on making househo-NA"
 /V743D    "Final say on visits to fami-NA"
 /V743E    "Final say on food to be coo-NA"
 /V744A    "Wife beating justified if she goes out without telling him"
 /V744B    "Wife beating justified if she neglects the children"
 /V744C    "Wife beating justified if she argues with him"
 /V744D    "Wife beating justified if she refuses to have sex with him"
 /V744E    "Wife beating justified if she burns the food"
 /BORD     "Birth order number"
 /B0       "Child is twin"
 /B1       "Month of birth"
 /B2       "Year of birth"
 /B3       "Date of birth (CMC)"
 /B4       "Sex of child"
 /B5       "Child is alive"
 /B6       "Age at death"
 /B7       "Age at death (months-imputed)"
 /B8       "Current age of child"
 /B9       "Child lives with whom"
 /B10      "Completeness of information"
 /B11      "Preceding birth interval"
 /B12      "Succeeding birth interval"
 /B13      "Flag for age at death"
 /B15      "Live birth between births"
 /B16      "Child's line number in household"
 /MIDX     "Index to birth history"
 /M1       "Tetanus injections bef. birth"
 /M2A      "Prenatal: doctor           -NA"
 /M2B      "Prenatal: nurse/midwife    -NA"
 /M2C      "Prenatal: auxiliary midwife-NA"
 /M2D      "Prenatal: CS health professional"
 /M2E      "Prenatal: CS health profess-NA"
 /M2F      "Prenatal: trained birth att."
 /M2G      "Prenatal: trad.birth attendant"
 /M2H      "Prenatal: relative         -NA"
 /M2I      "Prenatal: CS other person  -NA"
 /M2J      "Prenatal: CS other person  -NA"
 /M2K      "Prenatal: other resp (uncoded)"
 /M2L      "Prenatal: CS other         -NA"
 /M2M      "Prenatal: CS other         -NA"
 /M2N      "Prenatal: no one"
 /M3A      "Assistance: doctor         -NA"
 /M3B      "Assistance: nurse/midwife  -NA"
 /M3C      "Assistance: auxiliary midwi-NA"
 /M3D      "Assistance: CS health professional"
 /M3E      "Assistance: CS health profe-NA"
 /M3F      "Assistance: trained birth att."
 /M3G      "Assistance: trad.birth attend."
 /M3H      "Assistance: relative, friend"
 /M3I      "Assistance: CS other person-NA"
 /M3J      "Assistance: CS other person-NA"
 /M3K      "Assistance: other resp (uncod)"
 /M3L      "Assistance: CS other       -NA"
 /M3M      "Assistance: CS other       -NA"
 /M3N      "Assistance: no one"
 /M4       "Duration of breastfeeding"
 /M5       "Months of breastfeeding"
 /M6       "Duration of amenorrhea"
 /M7       "Months of amenorrhea"
 /M8       "Duration of abstinence"
 /M9       "Months of abstinence"
 /M10      "Time wanted pregnancy"
 /M11      "Time would have waited"
 /M13      "Timing of 1st antenatal check"
 /M14      "Antenatal visits for pregnancy"
 /M15      "Place of delivery"
 /M17      "Delivery by caesarian section"
 /M18      "Size of child at birth"
 /M19      "Birth weight (kilos - 3 dec.)"
 /M19A     "Weight at birth recall"
 /M27      "Flag for breastfeeding"
 /M28      "Flag for amenorrhea"
 /M29      "Flag for abstinence"
 /M34      "When child put to breast"
 /M35      "Times breastfed during night"
 /M36      "Times breastfed during day"
 /M37A     "Times gave child plain water"
 /M37B     "Times gave child sugar wate-NA"
 /M37C     "Times gave child fruit juice"
 /M37D     "Times gave child herbal tea-NA"
 /M37E     "Times gave child powdered/t-NA"
 /M37F     "Times gave child commercial-NA"
 /M37G     "Times gave child fresh milk-NA"
 /M37H     "Times given tinned, powdered or fresh animal milk"
 /M37I     "Times given country specifi-NA"
 /M37J     "Times given country specifi-NA"
 /M37K     "Times given country specifi-NA"
 /M37L     "Times gave child other liquid"
 /M37M     "Times given pumpkin, carrot-NA"
 /M37N     "Times given any green leafy-NA"
 /M37O     "Times given mango, papaya or other Vit A rich fruits"
 /M37P     "Times given other solid, se-NA"
 /M37Q     "Times given food made from local grain"
 /M37R     "Times given food made from local roots/tuber"
 /M37S     "Times gave child eggs, fish-NA"
 /M37T     "Times gave child meat      -NA"
 /M37U     "Times gave child other fruits/vegetables"
 /M37V     "Times gave child meat, poultry, fish, shellfish, eggs"
 /M37W     "Times gave child legumes (lentils, beans, peanuts)"
 /M37X     "Times gave child cheese/yog-NA"
 /M37Y     "Times gave child foods made with oil, fat, butter"
 /M37Z     "Times gave child country sp-NA"
 /M37XX    "Times gave child country sp-NA"
 /M37XY    "Times gave child country sp-NA"
 /M37XZ    "Times gave child country sp-NA"
 /M38      "Drank from bottle with nipple"
 /M39      "Times ate solid, semi-solid or soft food yesterday"
 /M40A     "Last 7 days - plain water"
 /M40B     "Last 7 days - sugar water  -NA"
 /M40C     "Last 7 days - fruit juice"
 /M40D     "Last 7 days - herbal tea   -NA"
 /M40E     "Last 7 days - powdered/tinn-NA"
 /M40F     "Last 7 days - commercially -NA"
 /M40G     "Last 7 days - fresh milk   -NA"
 /M40H     "Last 7 days - tinned, powdered or fresh animal milk"
 /M40I     "Last 7 days - country speci-NA"
 /M40J     "Last 7 days - country speci-NA"
 /M40K     "Last 7 days - country speci-NA"
 /M40L     "Last 7 days - other liquid"
 /M40M     "Last 7 days - pumpkin, carr-NA"
 /M40N     "Last 7 days - any green lea-NA"
 /M40O     "Last 7 days - mango, papaya or other Vit A rich fruits"
 /M40P     "Last 7 days - other solid, -NA"
 /M40Q     "Last 7 days - food made from local grain"
 /M40R     "Last 7 days - food made from local roots/tuber"
 /M40S     "Last 7 days - eggs, fish, p-NA"
 /M40T     "Last 7 days - meat         -NA"
 /M40U     "Last 7 days - other fruits/vegetables"
 /M40V     "Last 7 days - meat, poultry, fish, shellfish, eggs"
 /M40W     "Last 7 days - legumes (lentils, beans, peanuts)"
 /M40X     "Last 7 days - cheese/yogurt-NA"
 /M40Y     "Last 7 days - foods made with oil, fat, butter"
 /M40Z     "Last 7 days - country speci-NA"
 /M40XX    "Last 7 days - country speci-NA"
 /M40XY    "Last 7 days - country speci-NA"
 /M40XZ    "Last 7 days - country speci-NA"
 /M41      "Months pregnant for last antenatal visit"
 /M42A     "During pregnancy - weighed"
 /M42B     "During pregnancy - height measured"
 /M42C     "During pregnancy - blood pressure taken"
 /M42D     "During pregnancy - urine sample taken"
 /M42E     "During pregnancy - blood sample taken"
 /M43      "Told about pregnancy complications"
 /M44      "Told where to go for pregnancy complications"
 /M45      "During pregancy, given or b-NA"
 /M46      "Days tablets or syrup taken-NA"
 /M47      "During pregnancy, had difficulty with daylight vision"
 /M48      "During pregnancy, had difficulty with night blindness"
 /M49A     "During pregnancy - took Fansidar for Malaria"
 /M49B     "During pregnancy - took Chloroquine for Malaria"
 /M49C     "During pregnancy - took Unknown Drug for Malaria"
 /M49D     "During pregnancy - took proguanil for Malaria"
 /M49E     "During pregnancy - took cou-NA"
 /M49F     "During pregnancy - took cou-NA"
 /M49G     "During pregnancy - took cou-NA"
 /M49X     "During pregnancy - took other drug for Malaria"
 /M49Z     "During pregnancy - took no drug for Malaria"
 /M50      "After birth, health professional checked health"
 /M51      "Checkup after deliver timing"
 /M52      "After birth, health professional checked health"
 /M53      "Place for checkup"
 /M54      "Received Vitamin A dose in first 2 months after delivery"
 /M55A     "First 3 days, given milk ot-NA"
 /M55B     "First 3 days, given plain w-NA"
 /M55C     "First 3 days, given sugar/g-NA"
 /M55D     "First 3 days, given gripe w-NA"
 /M55E     "First 3 days, given sugar/s-NA"
 /M55F     "First 3 days, given fruit j-NA"
 /M55G     "First 3 days, given infant -NA"
 /M55H     "First 3 days, given tea/inf-NA"
 /M55I     "First 3 days, given honey  -NA"
 /M55J     "First 3 days, given country-NA"
 /M55K     "First 3 days, given country-NA"
 /M55L     "First 3 days, given country-NA"
 /M55M     "First 3 days, given country-NA"
 /M55N     "First 3 days, given country-NA"
 /M55X     "First 3 days, given other  -NA"
 /M55Z     "First 3 days, given nothing-NA"
 /M56      "Sugar added to any of foods-NA"
 /HIDX     "Index to birth history"
 /H1       "Has health card"
 /H2       "Received BCG"
 /H2D      "BCG day"
 /H2M      "BCG month"
 /H2Y      "BCG year"
 /H3       "Received DPT 1"
 /H3D      "DPT 1 day"
 /H3M      "DPT 1 month"
 /H3Y      "DPT 1 year"
 /H4       "Received POLIO 1"
 /H4D      "POLIO 1 day"
 /H4M      "POLIO 1 month"
 /H4Y      "POLIO 1 year"
 /H5       "Received DPT 2"
 /H5D      "DPT 2 day"
 /H5M      "DPT 2 month"
 /H5Y      "DPT 2 year"
 /H6       "Received POLIO 2"
 /H6D      "POLIO 2 day"
 /H6M      "POLIO 2 month"
 /H6Y      "POLIO 2 year"
 /H7       "Received DPT 3"
 /H7D      "DPT 3 day"
 /H7M      "DPT 3 month"
 /H7Y      "DPT 3 year"
 /H8       "Received POLIO 3"
 /H8D      "POLIO 3 day"
 /H8M      "POLIO 3 month"
 /H8Y      "POLIO 3 year"
 /H9       "Received MEASLES"
 /H9D      "MEASLES day"
 /H9M      "MEASLES month"
 /H9Y      "MEASLES year"
 /H0       "Polio 0"
 /H0D      "Polio 0 day"
 /H0M      "POLIO 0 month"
 /H0Y      "POLIO 0 year"
 /H10      "Ever had vaccination"
 /H11      "Had diarrhea recently"
 /H12A     "Diarrhea: government hosp."
 /H12B     "Diarrhea: govt health center"
 /H12C     "Diarrhea: govt health post"
 /H12D     "Diarrhea: mobile clinic    -NA"
 /H12E     "Diarrhea: comm. based outlet"
 /H12F     "Diarrhea: CS: health station / clinic"
 /H12G     "Diarrhea: CS other government"
 /H12H     "Diarrhea: CS public sector -NA"
 /H12I     "Diarrhea: other public sect-NA"
 /H12J     "Diarrhea: private hosp/clin."
 /H12K     "Diarrhea: private pharmacy"
 /H12L     "Diarrhea: private doctor"
 /H12M     "Diarrhea: private mobile cl-NA"
 /H12N     "Diarrhea: comm. based outlet"
 /H12O     "Diarrhea: CS NGO health facility"
 /H12P     "Diarrhea: CS other NGO"
 /H12Q     "Diarrhea: CS other private medical"
 /H12R     "Diarrhea: other med.priv se-NA"
 /H12S     "Diarrhea: shop"
 /H12T     "Diarrhea: traditional pract."
 /H12U     "Diarrhea: CS drug vendor"
 /H12V     "Diarrhea: CS country specic-NA"
 /H12W     "Diarrhea: CS oth.priv secto-NA"
 /H12X     "Diarrhea: Other"
 /H12Y     "Diarrhea: no treatment"
 /H12Z     "Diarrhea: medical treatment"
 /H13      "Given oral rehydration"
 /H14      "Given recommend. home solution"
 /H15      "Given other pills or syrups"
 /H15A     "Given antibiotics (CS)     -NA"
 /H15B     "Given an injection"
 /H15C     "Given an intravenous (IV)"
 /H15D     "Given home remedy, herbal med."
 /H15E     "Given CS other treatment   -NA"
 /H15F     "Given CS other treatment   -NA"
 /H15G     "Given CS other treatment  -NA"
 /H15H     "Given CS other treatment   -NA"
 /H20      "Given other treatment"
 /H21A     "Given no treatment"
 /H21      "Received any treatment"
 /H22      "Had fever in last two weeks"
 /H31      "Had cough in last two weeks"
 /H31B     "Short, rapid breaths"
 /H32A     "Fever/cough: government hosp."
 /H32B     "Fever/cough: govt health cntr"
 /H32C     "Fever/cough: govt health post"
 /H32D     "Fever/cough: mobile clinic -NA"
 /H32E     "Fever/cough: comm. based outlet"
 /H32F     "Fever/cough: Health station / clinic"
 /H32G     "Fever/cough: CS other public sector"
 /H32H     "Fever/cough: CS public sect-NA"
 /H32I     "Fever/cough: oth public sec-NA"
 /H32J     "Fever/cough: private hosp/clin"
 /H32K     "Fever/cough: private pharmacy"
 /H32L     "Fever/cough: private doctor"
 /H32M     "Fever/cough: private mobile-NA"
 /H32N     "Fever/cough: NGO comm. based outlet"
 /H32O     "Fever/cough: NGO health facility"
 /H32P     "Fever/cough: NGO other"
 /H32Q     "Fever/cough: Other private medical"
 /H32R     "Fever/cough: oth med.priv s-NA"
 /H32S     "Fever/cough: shop"
 /H32T     "Fever/cough: traditional pract"
 /H32U     "Fever/cough: Drug vendor"
 /H32V     "Fever/cough: CS oth.priv se-NA"
 /H32W     "Fever/cough: CS oth.priv se-NA"
 /H32X     "Fever/cough: Other"
 /H32Y     "Fever/cough: no treatment"
 /H32Z     "Fever/cough: medical treatment"
 /H33      "Received Vitamin A         -NA"
 /H33D     "Vitamin A Day              -NA"
 /H33M     "Vitamin A month            -NA"
 /H33Y     "Vitamin A year             -NA"
 /H34      "Vitamin A in last 6 months"
 /H35      "Any vaccinations in last 2 years part of campaign"
 /H36A     "Vaccinated during Tikemt/Hidar 1990"
 /H36B     "Vaccinated during Tikemt/Hidar 1991"
 /H36C     "Vaccinated during Tikemt/Hidar 1992"
 /H36D     "Vaccinated during Campaign -NA"
 /H36E     "Vaccinated during Campaign -NA"
 /H36F     "Vaccinated during Campaign -NA"
 /H37A     "Fansidar taken for fever"
 /H37B     "Chloroquine taken for fever"
 /H37C     "Aspirin taken for fever"
 /H37D     "Ibuprofen/acetaminophen taken for fever"
 /H37E     "CS: quinine taken for fever"
 /H37F     "CS: antibiotics taken for fever"
 /H37G     "Country specific taken for -NA"
 /H37H     "Country specific taken for -NA"
 /H37X     "Other taken for fever"
 /H37Y     "Nothing taken for fever"
 /H37Z     "Don't know if or what was taken"
 /H38      "Had diarrhea in last 2 weeks: Amount offered to drink"
 /H39      "Had diarrhea in last 2 weeks: Amount offered to eat"
 /HWIDX    "Index to birth history"
 /HW1      "Age in months"
 /HW2      "Weight in kilograms (1 dec.)"
 /HW3      "Height in centimeters (1 dec.)"
 /HW4      "Ht/A Percentile"
 /HW5      "Ht/A Standard deviations"
 /HW6      "Ht/A Percent of ref. median"
 /HW7      "Wt/A Percentile"
 /HW8      "Wt/A Standard deviations"
 /HW9      "Wt/A Percent of ref. median"
 /HW10     "Wt/Ht Percentile"
 /HW11     "Wt/Ht Standard deviations"
 /HW12     "Wt/Ht Percent of ref. median"
 /HW13     "Reason not measured"
 /HW15     "Height: lying or standing"
 /HW16     "Day of birth of child"
 /HW17     "Date measured (day)"
 /HW18     "Date measured (month)"
 /HW19     "Date measured (year)"
 /HW51     "Line no. of parent/caretaker"
 /HW52     "Read consent statement"
 /HW53     "Hemoglobin level (g/dl - 1 decimal)"
 /HW55     "Result of measuring (Hemoglobin)"
 /HW56     "Hemoglobin level adjusted by altitud (g/dl - 1 decimal)"
 /HW57     "Anemia level"
 /HW58     "Agrees to referral"
 /SINTDG   "Day of interview - Gregorian calendar"
 /SINTMG   "Month of interview - Gregorian calendar"
 /SINTYG   "Year of interview - Gregorian calendar"
 /SINTCG   "Date of interview (CMC) - Gregorian calendar"
 /SLAN     "Language of questionnaire"
 /SINTV    "Interview language"
 /SRESP    "Respondent's language"
 /STRANS   "Translator used"
 /S101T    "Morning/evening"
 /S101H    "Start of interview (hour)"
 /S101M    "Start of interview (minutes)"
 /S105MG   "Month of birth - Gregorian calendar"
 /S105YG   "Year of birth - Gregorian calendar"
 /S105CG   "Date of birth (CMC) - Gregorian calendar"
 /S109     "Highest grade at that level"
 /S227CG   "Date of conception (CMC) - gregorian calendar"
 /S230AC   "Cmc last termination"
 /S230AF   "Date flag for Q230AC"
 /S230B    "Month/years last pregancy ended"
 /S230AMG  "Month pregnancy ended - Gregorian calendar"
 /S230AYG  "Year pregnancy ended - Gregorian calendar"
 /S230ACG  "Cmc last termination - Gregorian calendar"
 /S230F    "Number of other non live pregnancies"
 /S234     "Tetanus toxoid"
 /S234A    "Has vaccination card"
 /S234C    "Number of tetanus injections"
 /SD234B1  "Day first tetanus toxoid - Ethiopian calendar"
 /SM234B1  "Month first tetanus toxoid - Ethiopian calendar"
 /SY234B1  "Year first tetanus toxoid - Ethiopian calendar"
 /SD234B2  "Day second tetanus toxoid - Ethiopian calendar"
 /SM234B2  "Month second tetanus toxoid - Ethiopian calendar"
 /SY234B2  "Year second tetanus toxoid - Ethiopian calendar"
 /SD234B3  "Day third tetanus toxoid - Ethiopian calendar"
 /SM234B3  "Month third tetanus toxoid - Ethiopian calendar"
 /SY234B3  "Year third tetanus toxoid - Ethiopian calendar"
 /SD234B4  "Day fourth tetanus toxoid - Ethiopian calendar"
 /SM234B4  "Month fourth tetanus toxoid - Ethiopian calendar"
 /SY234B4  "Year fourth tetanus toxoid - Ethiopian calendar"
 /SD234B5  "Day fifth tetanus toxoid - Ethiopian calendar"
 /SM234B5  "Month fifth tetanus toxoid - Ethiopian calendar"
 /SY234B5  "Year fifth tetanus toxoid - Ethiopian calendar"
 /S312     "Brand name of pill"
 /S319     "Last source of FP/where learned to use method"
 /S319D    "How long to get to family planning place (minutes)"
 /S329     "Place for family planning methods"
 /S482     "Wash hands before feeding"
 /S483     "Wash hands after cleaning child"
 /S484     "Disposal of stools"
 /S489     "Sought medical treatment when was sick"
 /S489AA   "Care factors: does not know where to go"
 /S489AB   "Care factors: does not get permission to go"
 /S489AC   "Care factors: no money for treatment"
 /S489AD   "Care factors: no health facility nearby"
 /S489AE   "Care factors: no transport"
 /S489AF   "Care factors: does not want to go alone"
 /S489AG   "Care factors: concern of no female health provider"
 /S489AH   "Care factors: believed would recover soon"
 /S489AI   "Care factors: sickness was not serious"
 /S489AJ   "Care factors: Scared of modern treatment"
 /S489AK   "Care factors: used traditional treatment / drugs"
 /S489AL   "Care factors: did not feel sick"
 /S489AX   "Care factors: other reasons"
 /S508MG   "Date of first union (month) - Gregorian calendar"
 /S508YG   "Date of first union (year) - Gregorian calendar"
 /S508CG   "Date of first union (CMC) - Gregorian calendar"
 /S617D    "Heard FP on pamphlet/posters"
 /S617E    "Heard FP on community events"
 /S702A    "Husband is able to read/write a sentence"
 /S705     "Partner's highest grade"
 /S712A    "Works throughout the year/season/once in a while"
 /S1001AA  "From which source heard of AIDS - Radio"
 /S1001AB  "From which source heard of AIDS - Television"
 /S1001AC  "From which source heard of AIDS - Newspapers/magazines"
 /S1001AD  "From which source heard of AIDS - Pamphlets/posters"
 /S1001AE  "From which source heard of AIDS - Health workers"
 /S1001AF  "From which source heard of AIDS - Mosques/churches"
 /S1001AG  "From which source heard of AIDS - Schools/teachers"
 /S1001AH  "From which source heard of AIDS - Community event"
 /S1001AI  "From which source heard of AIDS - Friends/relatives"
 /S1001AJ  "From which source heard of AIDS - Work place"
 /S1001AK  "From which source heard of AIDS - Drama/performance"
 /S1001AX  "From which source heard of AIDS - Other"
 /S1005    "Person getting AIDS influenced by number of partners"
 /S1006    "Sex with one partner increases or decreases chance of AIDS"
 /S1008    "Protect from AIDS by using condom"
 /S1013A   "AIDS transmit. during pregnancy"
 /S1013B   "AIDS transmit. at delivery"
 /S1013C   "AIDS transmit. during breastfeeding"
 /S1013D   "AIDS transmit. during other times"
 /S1013Z   "AIDS transmit. - Don't know"
 /S1106    "Intercourse with anyone else in last 12 months"
 /S1111    "Knows source for condoms"
 /S1112    "Source for condoms"
 /S1114T   "Time interview ended"
 /S1114H   "Hour interview ended"
 /S1114M   "Minutes interview ended"
 /IDX92    "Index to birth history"
 /S215MG   "Month of birth - Gregorian calendar"
 /S215YG   "Year of birth - Gregorian calendar"
 /S215CG   "Date of birth of child (CMC) - Gregorian calendar"
 /IDX94    "Index to birth history"
 /S406A    "Stopped eating specific type of food"
 /S406BA   "What did the respondent stop eating - milk"
 /S406BB   "What did the respondent stop eating - cheese, butter"
 /S406BC   "What did the respondent stop eating - meat"
 /S406BD   "What did the respondent stop eating - vegetables"
 /S406BE   "What did the respondent stop eating - fruit"
 /S406BX   "What did the respondent stop eating - other"
 /S432C    "When was child exposed to sunlight"
 /S440A    "Squeeze out and discarded first milk"
 /S442A    "Reason stopped breastfeeding"
 /S475C    "Other home made fluid"
 .
MISSING VALUE
  V026     (9)
 /V028     (999)
 /V029     (99)
 /V030     (999)
 /V031     (999)
 /V032     (99)
 /V034     (99)
 /V103     (9)
 /V104     (99)
 /V105     (9)
 /V106     (9)
 /V107     (99)
 /V113     (99)
 /V115     (999)
 /V116     (99)
 /V119     (9)
 /V120     (9)
 /V121     (9)
 /V122     (9)
 /V123     (9)
 /V124     (9)
 /V125     (9)
 /V127     (99)
 /V128     (99)
 /V129     (99)
 /V130     (9)
 /V131     (99)
 /V133     (99)
 /V134     (9)
 /V135     (9)
 /V139     (99)
 /V140     (9)
 /V141     (9)
 /V149     (9)
 /V150     (99)
 /V152     (99)
 /V153     (9)
 /V155     (9)
 /V156     (9)
 /V157     (9)
 /V158     (9)
 /V159     (9)
 /V160     (9)
 /V161     (99)
 /V162     (9)
 /V163     (9)
 /V164     (9)
 /V165     (9)
 /V166     (999)
 /V215     (999)
 /V217     (9)
 /V225     (9)
 /V226     (999)
 /V228     (9)
 /V229     (99)
 /V230     (9999)
 /V231     (9999)
 /V233     (99)
 /V234     (9)
 /V237     (9)
 /V239     (9)
 /V240     (99)
 /V241     (9999)
 /V242     (9999)
 /V310     (99)
 /V311     (9)
 /V312     (99)
 /V313     (9)
 /V326     (99)
 /V327     (9)
 /V337     (999)
 /V359     (99)
 /V360     (99)
 /V362     (9)
 /V363     (99)
 /V367     (9)
 /V375A    (99)
 /V376     (99)
 /V376A    (9)
 /V379     (99)
 /V380     (9)
 /V384A    (9)
 /V384B    (9)
 /V384C    (9)
 /V393     (9)
 /V394     (9)
 /V395     (9)
 /V3A00A   (9)
 /V3A00B   (9)
 /V3A00C   (9)
 /V3A00D   (9)
 /V3A00E   (9)
 /V3A00F   (9)
 /V3A00G   (9)
 /V3A00H   (9)
 /V3A00I   (9)
 /V3A00J   (9)
 /V3A00K   (9)
 /V3A00L   (9)
 /V3A00M   (9)
 /V3A00N   (9)
 /V3A00O   (9)
 /V3A00P   (9)
 /V3A00Q   (9)
 /V3A00R   (9)
 /V3A00S   (9)
 /V3A00T   (9)
 /V3A00U   (9)
 /V3A00V   (9)
 /V3A00W   (9)
 /V3A00X   (9)
 /V3A00Y   (9)
 /V3A00Z   (9)
 /V3A01    (9)
 /V3A02    (9)
 /V3A03    (9)
 /V3A04    (9)
 /V3A05    (9)
 /V3A06    (9)
 /V3A07    (99)
 /V3A08A   (9)
 /V3A08B   (9)
 /V3A08C   (9)
 /V3A08D   (9)
 /V3A08E   (9)
 /V3A08F   (9)
 /V3A08G   (9)
 /V3A08H   (9)
 /V3A08I   (9)
 /V3A08J   (9)
 /V3A08K   (9)
 /V3A08L   (9)
 /V3A08M   (9)
 /V3A08N   (9)
 /V3A08O   (9)
 /V3A08P   (9)
 /V3A08Q   (9)
 /V3A08R   (9)
 /V3A08S   (9)
 /V3A08T   (9)
 /V3A08U   (9)
 /V3A08V   (9)
 /V3A08W   (9)
 /V3A08X   (9)
 /V3A08Z   (9)
 /V401     (9)
 /V407     (99)
 /V408     (99)
 /V415     (9)
 /V416     (9)
 /V420     (999)
 /V421     (999)
 /V426     (999)
 /V437     (9999)
 /V438     (9999)
 /V439     (9999)
 /V440     (9999)
 /V441     (99999)
 /V442     (99999)
 /V443     (99999)
 /V444     (99999)
 /V444A    (9999)
 /V445     (9999)
 /V446     (9999)
 /V447     (9)
 /V452A    (9)
 /V452B    (99)
 /V452C    (9)
 /V453     (999)
 /V454     (9)
 /V455     (9)
 /V456     (999)
 /V457     (9)
 /V458     (9)
 /V459     (9)
 /V460     (9)
 /V461     (9)
 /V462     (9)
 /V463A    (9)
 /V463B    (9)
 /V463C    (9)
 /V463D    (9)
 /V463E    (9)
 /V463F    (9)
 /V463G    (9)
 /V463Z    (9)
 /V464     (99)
 /V465     (99)
 /V466     (9)
 /V467A    (9)
 /V467B    (9)
 /V467C    (9)
 /V467D    (9)
 /V467E    (9)
 /V467F    (9)
 /V467G    (9)
 /V469A    (9)
 /V469B    (9)
 /V469C    (9)
 /V469D    (9)
 /V469E    (9)
 /V469F    (9)
 /V469G    (9)
 /V469H    (9)
 /V469I    (9)
 /V469J    (9)
 /V469K    (9)
 /V469L    (9)
 /V469M    (9)
 /V469N    (9)
 /V469O    (9)
 /V469P    (9)
 /V469Q    (9)
 /V469R    (9)
 /V469S    (9)
 /V469T    (9)
 /V469U    (9)
 /V469V    (9)
 /V469W    (9)
 /V469X    (9)
 /V469Y    (9)
 /V469Z    (9)
 /V469XX   (9)
 /V469XY   (9)
 /V469XZ   (9)
 /V470A    (9)
 /V470B    (9)
 /V470C    (9)
 /V470D    (9)
 /V470E    (9)
 /V470F    (9)
 /V470G    (9)
 /V470H    (9)
 /V470I    (9)
 /V470J    (9)
 /V470K    (9)
 /V470L    (9)
 /V470M    (9)
 /V470N    (9)
 /V470O    (9)
 /V470P    (9)
 /V470Q    (9)
 /V470R    (9)
 /V470S    (9)
 /V470T    (9)
 /V470U    (9)
 /V470V    (9)
 /V470W    (9)
 /V470X    (9)
 /V470Y    (9)
 /V470Z    (9)
 /V470XX   (9)
 /V470XY   (9)
 /V470XZ   (9)
 /V501     (9)
 /V502     (9)
 /V503     (9)
 /V504     (9)
 /V505     (99)
 /V506     (99)
 /V525     (99)
 /V527     (999)
 /V528     (99)
 /V529     (999)
 /V531     (99)
 /V535     (9)
 /V536     (9)
 /V537     (99)
 /V602     (9)
 /V603     (999)
 /V604     (9)
 /V605     (9)
 /V610     (9)
 /V611     (9)
 /V612     (9)
 /V613     (99)
 /V616     (999)
 /V621     (9)
 /V623     (9)
 /V624     (99)
 /V625     (9)
 /V626     (99)
 /V627     (99)
 /V628     (99)
 /V629     (99)
 /V630A    (9)
 /V630B    (9)
 /V630C    (9)
 /V630D    (9)
 /V630E    (9)
 /V630F    (9)
 /V630G    (9)
 /V630H    (9)
 /V630I    (9)
 /V630J    (9)
 /V630K    (9)
 /V630L    (9)
 /V630M    (9)
 /V630N    (9)
 /V630O    (9)
 /V630X    (9)
 /V631     (9)
 /V632     (9)
 /V633A    (9)
 /V633B    (9)
 /V633C    (9)
 /V633D    (9)
 /V633E    (9)
 /V633F    (9)
 /V633G    (9)
 /V701     (9)
 /V702     (99)
 /V704     (999)
 /V705     (99)
 /V714     (9)
 /V715     (99)
 /V716     (999)
 /V717     (99)
 /V719     (9)
 /V721     (9)
 /V729     (9)
 /V730     (99)
 /V731     (9)
 /V732     (9)
 /V739     (9)
 /V740     (9)
 /V741     (9)
 /V742     (9)
 /V743A    (9)
 /V743B    (9)
 /V743C    (9)
 /V743D    (9)
 /V743E    (9)
 /V744A    (9)
 /V744B    (9)
 /V744C    (9)
 /V744D    (9)
 /V744E    (9)
 /B6       (999)
 /B9       (9)
 /B15      (9)
 /B16      (99)
 /M1       (9)
 /M2A      (9)
 /M2B      (9)
 /M2C      (9)
 /M2D      (9)
 /M2E      (9)
 /M2F      (9)
 /M2G      (9)
 /M2H      (9)
 /M2I      (9)
 /M2J      (9)
 /M2K      (9)
 /M2L      (9)
 /M2M      (9)
 /M2N      (9)
 /M3A      (9)
 /M3B      (9)
 /M3C      (9)
 /M3D      (9)
 /M3E      (9)
 /M3F      (9)
 /M3G      (9)
 /M3H      (9)
 /M3I      (9)
 /M3J      (9)
 /M3K      (9)
 /M3L      (9)
 /M3M      (9)
 /M3N      (9)
 /M4       (99)
 /M5       (99)
 /M6       (99)
 /M7       (99)
 /M8       (99)
 /M9       (99)
 /M10      (9)
 /M11      (999)
 /M13      (99)
 /M14      (99)
 /M15      (99)
 /M17      (9)
 /M18      (9)
 /M19      (9999)
 /M34      (999)
 /M35      (99)
 /M36      (99)
 /M37A     (9)
 /M37B     (9)
 /M37C     (9)
 /M37D     (9)
 /M37E     (9)
 /M37F     (9)
 /M37G     (9)
 /M37H     (9)
 /M37I     (9)
 /M37J     (9)
 /M37K     (9)
 /M37L     (9)
 /M37M     (9)
 /M37N     (9)
 /M37O     (9)
 /M37P     (9)
 /M37Q     (9)
 /M37R     (9)
 /M37S     (9)
 /M37T     (9)
 /M37U     (9)
 /M37V     (9)
 /M37W     (9)
 /M37X     (9)
 /M37Y     (9)
 /M37Z     (9)
 /M37XX    (9)
 /M37XY    (9)
 /M37XZ    (9)
 /M38      (9)
 /M39      (9)
 /M40A     (9)
 /M40B     (9)
 /M40C     (9)
 /M40D     (9)
 /M40E     (9)
 /M40F     (9)
 /M40G     (9)
 /M40H     (9)
 /M40I     (9)
 /M40J     (9)
 /M40K     (9)
 /M40L     (9)
 /M40M     (9)
 /M40N     (9)
 /M40O     (9)
 /M40P     (9)
 /M40Q     (9)
 /M40R     (9)
 /M40S     (9)
 /M40T     (9)
 /M40U     (9)
 /M40V     (9)
 /M40W     (9)
 /M40X     (9)
 /M40Y     (9)
 /M40Z     (9)
 /M40XX    (9)
 /M40XY    (9)
 /M40XZ    (9)
 /M41      (99)
 /M42A     (9)
 /M42B     (9)
 /M42C     (9)
 /M42D     (9)
 /M42E     (9)
 /M43      (9)
 /M44      (9)
 /M45      (9)
 /M46      (999)
 /M47      (9)
 /M48      (9)
 /M49A     (9)
 /M49B     (9)
 /M49C     (9)
 /M49D     (9)
 /M49E     (9)
 /M49F     (9)
 /M49G     (9)
 /M49X     (9)
 /M49Z     (9)
 /M50      (9)
 /M51      (999)
 /M52      (99)
 /M53      (99)
 /M54      (9)
 /M55A     (9)
 /M55B     (9)
 /M55C     (9)
 /M55D     (9)
 /M55E     (9)
 /M55F     (9)
 /M55G     (9)
 /M55H     (9)
 /M55I     (9)
 /M55J     (9)
 /M55K     (9)
 /M55L     (9)
 /M55M     (9)
 /M55N     (9)
 /M55X     (9)
 /M55Z     (9)
 /M56      (9)
 /H1       (9)
 /H2       (9)
 /H2D      (99)
 /H2M      (99)
 /H2Y      (9999)
 /H3       (9)
 /H3D      (99)
 /H3M      (99)
 /H3Y      (9999)
 /H4       (9)
 /H4D      (99)
 /H4M      (99)
 /H4Y      (9999)
 /H5       (9)
 /H5D      (99)
 /H5M      (99)
 /H5Y      (9999)
 /H6       (9)
 /H6D      (99)
 /H6M      (99)
 /H6Y      (9999)
 /H7       (9)
 /H7D      (99)
 /H7M      (99)
 /H7Y      (9999)
 /H8       (9)
 /H8D      (99)
 /H8M      (99)
 /H8Y      (9999)
 /H9       (9)
 /H9D      (99)
 /H9M      (99)
 /H9Y      (9999)
 /H0       (9)
 /H0D      (99)
 /H0M      (99)
 /H0Y      (9999)
 /H10      (9)
 /H11      (9)
 /H12A     (9)
 /H12B     (9)
 /H12C     (9)
 /H12D     (9)
 /H12E     (9)
 /H12F     (9)
 /H12G     (9)
 /H12H     (9)
 /H12I     (9)
 /H12J     (9)
 /H12K     (9)
 /H12L     (9)
 /H12M     (9)
 /H12N     (9)
 /H12O     (9)
 /H12P     (9)
 /H12Q     (9)
 /H12R     (9)
 /H12S     (9)
 /H12T     (9)
 /H12U     (9)
 /H12V     (9)
 /H12W     (9)
 /H12X     (9)
 /H12Y     (9)
 /H12Z     (9)
 /H13      (9)
 /H14      (9)
 /H15      (9)
 /H15A     (9)
 /H15B     (9)
 /H15C     (9)
 /H15D     (9)
 /H15E     (9)
 /H15F     (9)
 /H15G     (9)
 /H15H     (9)
 /H20      (9)
 /H21A     (9)
 /H21      (9)
 /H22      (9)
 /H31      (9)
 /H31B     (9)
 /H32A     (9)
 /H32B     (9)
 /H32C     (9)
 /H32D     (9)
 /H32E     (9)
 /H32F     (9)
 /H32G     (9)
 /H32H     (9)
 /H32I     (9)
 /H32J     (9)
 /H32K     (9)
 /H32L     (9)
 /H32M     (9)
 /H32N     (9)
 /H32O     (9)
 /H32P     (9)
 /H32Q     (9)
 /H32R     (9)
 /H32S     (9)
 /H32T     (9)
 /H32U     (9)
 /H32V     (9)
 /H32W     (9)
 /H32X     (9)
 /H32Y     (9)
 /H32Z     (9)
 /H33      (9)
 /H33D     (99)
 /H33M     (99)
 /H33Y     (9999)
 /H34      (9)
 /H35      (9)
 /H36A     (9)
 /H36B     (9)
 /H36C     (9)
 /H36D     (9)
 /H36E     (9)
 /H36F     (9)
 /H37A     (9)
 /H37B     (9)
 /H37C     (9)
 /H37D     (9)
 /H37E     (9)
 /H37F     (9)
 /H37G     (9)
 /H37H     (9)
 /H37X     (9)
 /H37Y     (9)
 /H37Z     (9)
 /H38      (9)
 /H39      (9)
 /HW2      (999)
 /HW3      (9999)
 /HW4      (9999)
 /HW5      (9999)
 /HW6      (99999)
 /HW7      (9999)
 /HW8      (9999)
 /HW9      (99999)
 /HW10     (9999)
 /HW11     (9999)
 /HW12     (99999)
 /HW13     (9)
 /HW15     (9)
 /HW16     (99)
 /HW52     (9)
 /HW53     (999)
 /HW55     (9)
 /HW56     (9999)
 /HW57     (9)
 /HW58     (9)
 /SLAN     (9)
 /SINTV    (9)
 /SRESP    (9)
 /STRANS   (9)
 /S101T    (9)
 /S101H    (99)
 /S101M    (99)
 /S105MG   (99)
 /S105YG   (9999)
 /S109     (99)
 /S230AMG  (99)
 /S230AYG  (9999)
 /S234     (9)
 /S234A    (9)
 /S234C    (99)
 /S312     (99)
 /S319     (99)
 /S319D    (999)
 /S329     (99)
 /S482     (9)
 /S483     (9)
 /S484     (99)
 /S489     (9)
 /S489AA   (9)
 /S489AB   (9)
 /S489AC   (9)
 /S489AD   (9)
 /S489AE   (9)
 /S489AF   (9)
 /S489AG   (9)
 /S489AH   (9)
 /S489AI   (9)
 /S489AJ   (9)
 /S489AK   (9)
 /S489AL   (9)
 /S489AX   (9)
 /S508MG   (99)
 /S508YG   (9999)
 /S617D    (9)
 /S617E    (9)
 /S702A    (9)
 /S705     (99)
 /S712A    (9)
 /S1001AA  (9)
 /S1001AB  (9)
 /S1001AC  (9)
 /S1001AD  (9)
 /S1001AE  (9)
 /S1001AF  (9)
 /S1001AG  (9)
 /S1001AH  (9)
 /S1001AI  (9)
 /S1001AJ  (9)
 /S1001AK  (9)
 /S1001AX  (9)
 /S1005    (9)
 /S1006    (9)
 /S1008    (9)
 /S1013A   (9)
 /S1013B   (9)
 /S1013C   (9)
 /S1013D   (9)
 /S1013Z   (9)
 /S1106    (9)
 /S1111    (9)
 /S1112    (99)
 /S1114T   (9)
 /S1114H   (99)
 /S1114M   (99)
 /S215MG   (99)
 /S215YG   (9999)
 /S406A    (9)
 /S406BA   (9)
 /S406BB   (9)
 /S406BC   (9)
 /S406BD   (9)
 /S406BE   (9)
 /S406BX   (9)
 /S432C    (999)
 /S440A    (9)
 /S442A    (99)
 /S475C    (9)
 .
VALUE LABELS
  V007    
   1992 ""
 /V013    
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
 /V014    
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /V015    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
 /V018    
      0 "No calendar"
 /V019    
      0 "No calendar"
 /V020    
      0 "All woman sample"
      1 "Ever married sample"
 /V023    
      1 "Tigray, urban"
      2 "Tigray, rural"
      3 "Afar, urban"
      4 "Afar, rural"
      5 "Amhara, urban"
      6 "Amhara, rural"
      7 "Oromiya, urban"
      8 "Oromiya, rural"
      9 "Somali, urban"
     10 "Somali, rural"
     11 "Ben-Gumz, urban"
     12 "Ben-Gumz, rural"
     13 "SNNP, urban"
     14 "SNNP, rural"
     15 "Gambela, urban"
     16 "Gambela, rural"
     17 "Harrari, urban"
     18 "Harrari, rural"
     19 "Addis, urban"
     20 "Dire Dawa, urban"
     21 "Dire Dawa, rural"
 /V024    
      1 "Tigray"
      2 "Affar"
      3 "Amhara"
      4 "Oromiya"
      5 "Somali"
      6 "Ben-Gumz"
      7 "SNNP"
     12 "Gambela"
     13 "Harari"
     14 "Addis"
     15 "Dire Dawa"
 /V025    
      1 "Urban"
      2 "Rural"
 /V026    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
 /V034    
      0 "Husband not in HH"
 /V042    
      0 "Not selected"
      1 "Selected"
 /V043    
      0 "Woman not selected"
      1 "Woman selected"
 /V044    
      0 "Woman not selected"
      1 "Woman selected and interviewed"
      2 "Woman selected, but privacy not possible"
      3 "Woman selected, but not interviewed"
 /V101    
      1 "Tigray"
      2 "Affar"
      3 "Amhara"
      4 "Oromiya"
      5 "Somali"
      6 "Ben-Gumz"
      7 "SNNP"
     12 "Gambela"
     13 "Harari"
     14 "Addis"
     15 "Dire Dawa"
 /V102    
      1 "Urban"
      2 "Rural"
 /V103    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
 /V104    
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
 /V105    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
 /V106    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
 /V113    
     10 "PIPED WATER"
     11 "Piped into dwelling"
     12 "Piped into compound"
     13 "Piped outside compound"
     20 "WATER FROM OPEN WELL"
     21 "Open well"
     22 "Open spring"
     23 "Covered well"
     24 "Covered spring"
     31 "River"
     32 "Pond/lake/dam"
     40 "SURFACE WATER"
     41 "Rainwater"
     96 "Other"
     97 "Not a de-jure resident"
 /V115    
    995 "One day or longer"
    996 "On premises"
    997 "Not dejure resident"
 /V116    
     10 "FLUSH TOILET"
     11 "Flush toilet"
     20 "PIT TOILET LATRINE"
     21 "Traditional pit latrine"
     22 "Improved (ventilated) pit latrine"
     30 "NO FACILITY"
     31 "No facility, bush, field"
     96 "OTHER"
     97 "Not de-jure resident"
 /V119    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V120    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V121    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V122    
      7 ""
 /V123    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V124    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V125    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V127    
     10 "NATURAL FLOOR"
     11 "Earth, sand"
     12 "Dung"
     20 "RUDIMENTARY FLOOR"
     21 "Wood planks"
     22 "Reed, bamboo"
     30 "FINISHED FLOOR"
     31 "Parquet, polished wood"
     32 "Vinyl sheets/tiles"
     33 "Cement"
     34 "Cement tiles/brick"
     35 "Carpet"
     96 "Other"
     97 "Not de jure resident"
 /V129    
     10 "NATURAL"
     20 "RUDIMENTARY"
     21 "Wood / mud"
     22 "Thatch"
     23 "Reed/Bamboo"
     24 "Plastic sheet"
     25 "Mobile roofs of nomads"
     30 "FINISHED"
     31 "Corrugated iron"
     32 "Cement / concrete"
     96 "OTHER"
     97 "Not dejure resident"
 /V130    
      1 "Orthodox"
      2 "Catholic"
      3 "Protestant"
      4 "Moslem"
      5 "Traditional"
      6 "Other"
 /V131    
      1 "Affar"
      4 "Amharra"
     25 "Guragie"
     60 "Oromo"
     67 "Sidama"
     68 "Somalie"
     70 "Tigray (Tigraway)"
     72 "Welaita"
     96 "Other"
 /V133    
     97 "Inconsistent"
 /V134    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
 /V135    
      1 "Usual resident"
      2 "Visitor"
 /V139    
      0 "Abroad"
      1 "Tigray"
      2 "Affar"
      3 "Amhara"
      4 "Oromiya"
      5 "Somali"
      6 "Ben-Gumz"
      7 "SNNP"
     12 "Gambela"
     13 "Harari"
     14 "Addis"
     15 "Dire Dawa"
     97 "Not dejure resident"
 /V140    
      0 "Abroad"
      1 "Urban"
      2 "Rural"
      7 "Not dejure resident"
 /V141    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
      7 "Not dejure resident"
 /V149    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
 /V150    
      1 "Head"
      2 "Wife"
      3 "Daughter"
      4 "Daughter-in-law"
      5 "Grand-daughter"
      6 "Mother"
      7 "Mother-in-law"
      8 "Sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "DK"
 /V151    
      1 "Male"
      2 "Female"
 /V152    
     97 "97+"
     98 "DK"
 /V153    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V155    
      0 "Cannot read at all"
      1 "Able to read only parts of sentence"
      2 "Able to read whole sentence"
      3 "No card with required language"
 /V157    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
 /V158    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
 /V159    
      0 "Not at all"
      1 "Less than once a week"
      2 "At least once a week"
      3 "Almost every day"
 /V160    
      0 "No"
      1 "Yes"
      7 "Not dejure resident"
 /V161    
      1 "Electricity"
      2 "LPG/natural gas"
      3 "Biogas"
      4 "Kerosene"
      5 "Coal/lignite"
      6 "Charcoal"
      7 "Firewood/straw"
      8 "Dung"
     96 "Other"
     97 "Not dejure resident"
 /V162    
      7 ""
 /V163    
      7 ""
 /V164    
      7 ""
 /V165    
      7 ""
 /V213    
      0 "No or unsure"
      1 "Yes"
 /V215    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
 /V216    
      0 "No"
      1 "Yes"
 /V217    
      1 "During her period"
      2 "After period ended"
      3 "Middle of the cycle"
      4 "Before period begins"
      5 "At any time"
      6 "Other"
      8 "Don't know"
 /V220    
      6 "6+"
 /V221    
    996 "Negative interval"
 /V223    
      7 "Month - exact date"
      8 "None - date placed"
 /V225    
      1 "Then"
      2 "Later"
      3 "Not at all"
 /V226    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
 /V227    
      0 "No flag"
      1 "N > int. since birth"
      2 "N + amen. > interval"
      3 "N, but per. not ret."
      4 "95, but no birth"
      5 "95, but per.returned"
      6 "96, but per.returned"
      7 "N, last per. in preg"
      8 "96, had children"
      9 "N, per.bef.last birt"
 /V228    
      0 "No"
      1 "Yes"
 /V229    
     97 "Inconsistent"
     98 "DK"
 /V230    
   9997 "Inconsistent"
   9998 "DK"
 /V231    
   9997 "Inconsistent"
   9998 "DK"
 /V232    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      6 ""
      7 "Month"
      8 "None"
 /V233    
     97 "Inconsistent"
     98 "Don't know"
 /V234    
      0 "No"
      1 "Yes"
 /V237    
      0 "No"
      1 "Yes"
 /V311    
      4 "4+"
      5 "Never used"
 /V312    
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     16 ""
     17 "Specific method 1"
     18 "Specific method 2"
     19 "Specific method 3"
     20 "Specific method 4"
 /V313    
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
 /V326    
     10 "PUBLIC"
     11 "Gov. hospital"
     12 "Gov. health center"
     13 "Gov. health station /clinic"
     14 "Gov. health post"
     15 "Gov. comm. based outlet"
     16 "Gov. other"
     20 "PRIVATE MEDICAL"
     21 "Priv. hospital"
     22 "Priv. doctor /clinic"
     23 "Priv. pharmacy"
     24 "Priv. other"
     25 "NGO: health facility"
     26 "NGO: comm. based outlet"
     27 "NGO: family guidance"
     28 "NGO: other"
     29 ""
     30 "OTHER PRIVATE"
     31 "Drug vendor"
     32 "Shop"
     33 "Friend relative"
     36 "Other"
     95 "Did not consult"
     96 "OTHER"
     97 ""
     98 "Don't know"
 /V327    
      1 "Govt Clinical/Pharm"
      2 "Govt Home/Comm deliv"
      3 "NGO"
      4 "Private Clin/Deliv"
      5 "Private Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
 /V360    
     98 ""
 /V361    
      1 "Currently using"
      2 "Used since last birth"
      3 "Used before last birth"
      4 "Never used"
 /V362    
      1 "In next 12 months"
      2 "Use later"
      3 "Unsure about timing"
      4 "Unsure about use"
      5 "Does not intend"
      6 "Never had sex"
 /V363    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Lactational amenorrhea"
     14 "Female condom"
     15 "Foam or jelly"
     16 ""
     17 "Specific method 1"
     18 "Specific method 2"
     19 "Specific method 3"
     20 "Specific method 4"
     98 "Don't know"
 /V364    
      1 "Using modern method"
      2 "Using traditional method"
      3 "Non-user intend to"
      4 "Does not intend to"
      5 "Never had sex"
 /V367    
      1 "Wanted then"
      2 "Wanted later"
      3 "Wanted no more"
 /V375A   
     96 ""
     98 ""
 /V376    
     11 "Not married"
     20 "FERTILITY-RELATED"
     21 ""
     22 "Infrequent sex"
     23 "Menopausal, hyster."
     24 "Subfecund, infecund"
     25 ""
     26 "Wants more children"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibit."
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fear side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interfere with body"
     96 "Other"
     98 "DK"
 /V376A   
      0 "No"
      1 "Yes"
      8 "DK"
 /V379    
     10 "PUBLIC"
     11 "Hospital"
     12 "Health center"
     13 "Health station/clinic"
     14 "Health post"
     15 "Community-based outlet"
     16 "Other government"
     20 "PRIVATE MEDICAL"
     21 "Private hospital"
     22 "Private doctor/clinic"
     23 "Pharmacy"
     24 "Other private medical"
     25 "NGO health facility"
     26 "NGO comm.-based outlet"
     27 "Family guidance"
     28 "Other NGO"
     29 ""
     30 "PRIVATE OTHER"
     31 "Drug vendor"
     32 "Shop"
     33 "Friend/relative"
     36 "Other"
     95 "Did not consult source"
     96 "OTHER"
     97 ""
     98 "Don't know"
 /V380    
      1 "Govt Clinical/Pharm"
      2 "Govt Home/Comm deliv"
      3 "NGO"
      4 "Private Clin/Deliv"
      5 "Private Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
 /V384A   
      0 "No"
      1 "Yes"
 /V384B   
      0 "No"
      1 "Yes"
 /V384C   
      0 "No"
      1 "Yes"
 /V393    
      0 "No"
      1 "Yes"
 /V394    
      0 "No"
      1 "Yes"
 /V395    
      0 "No"
      1 "Yes"
 /V3A01   
      8 ""
 /V3A07   
     10 "PUBLIC"
     11 "Hospital"
     12 "Health center"
     13 "Health station/clinic"
     14 "Health post"
     15 "Community-based outlet"
     16 "Other government"
     20 "PRIVATE MEDICAL"
     21 "Private hospital"
     22 "Private doctor/clinic"
     23 "Pharmacy"
     24 "Other private medical"
     25 "NGO health facility"
     26 "NGO comm.-based outlet"
     27 "Family guidance"
     28 "Other NGO"
     29 ""
     30 "PRIVATE OTHER"
     31 "Drug vendor"
     32 "Shop"
     33 "Friend/relative"
     36 "Other"
     95 "Did not consult source"
     96 "OTHER"
     97 ""
     98 "Don't know"
 /V3A08A  
      0 "No"
      1 "Not married"
 /V3A08B  
      0 "No"
      1 "Not having sex"
 /V3A08C  
      0 "No"
      1 "Infrequent sex"
 /V3A08D  
      0 "No"
      1 "Menopausal/hysterectomy"
 /V3A08E  
      0 "No"
      1 "Subfecund/infecund"
 /V3A08F  
      0 "No"
      1 "Postpartum amenorrheic"
 /V3A08G  
      0 "No"
      1 "Breastfeeding"
 /V3A08H  
      0 "No"
      1 "Fatalistic"
 /V3A08I  
      0 "No"
      1 "Respondent opposed"
 /V3A08J  
      0 "No"
      1 "Husband/partner opposed"
 /V3A08K  
      0 "No"
      1 "Others opposed"
 /V3A08L  
      0 "No"
      1 "Religious prohibition"
 /V3A08M  
      0 "No"
      1 "Knows no method"
 /V3A08N  
      0 "No"
      1 "Knows no source"
 /V3A08O  
      0 "No"
      1 "Health concerns"
 /V3A08P  
      0 "No"
      1 "Fear of side effects"
 /V3A08Q  
      0 "No"
      1 "Lack of access/too far"
 /V3A08R  
      0 "No"
      1 "Costs too much"
 /V3A08S  
      0 "No"
      1 "Inconvenient to use"
 /V3A08T  
      0 "No"
      1 "Interferes with bodys processes"
 /V3A08X  
      0 "No"
      1 "Other"
 /V3A08Z  
      0 "No"
      1 "Dont know"
 /V401    
      0 "No"
      1 "Yes"
 /V404    
      0 "No"
      1 "Yes"
 /V405    
      0 "No"
      1 "Yes"
 /V406    
      0 "No"
      1 "Yes"
 /V407    
     96 "On demand"
 /V408    
     96 "On demand"
 /V415    
      0 "No"
      1 "Yes"
      8 "DK"
 /V416    
      0 "Never heard of"
      1 "Used ORS"
      2 "Heard of ORS"
 /V426    
      0 "Immediately"
 /V439    
   9998 "Flagged cases"
 /V440    
   9998 "Flagged cases"
 /V441    
  99998 "Flagged cases"
 /V442    
  99998 "Flagged cases"
 /V443    
  99998 "Flagged cases"
 /V444    
  99998 "Flagged cases"
 /V444A   
   9998 "Flagged cases"
 /V445    
   9998 "Flagged cases"
 /V446    
   9998 "Flagged cases"
 /V447    
      0 "Measured"
      3 "Not present"
      4 "Refused"
      5 ""
      6 "Other"
      7 "No measurement found in HH"
 /V459    
      0 "No"
      1 "Yes"
 /V462    
      0 "No"
      1 "Yes"
      2 "Never prepared meal"
 /V464    
     98 ""
 /V465    
      1 "Always use toilet/latrine"
      2 "Throw in toilet/latrine"
      3 "Throw outside the dwelling"
      4 "Throw outside the yard"
      5 "Bury in the yard"
      6 "Rinse away"
      7 "Use disposable diapers"
      8 "Use washable diapers"
      9 "Not disposed of"
     96 "Other"
 /V466    
      0 "No"
      1 "Yes"
      2 "Depends"
 /V468    
      0 "See specific questions"
      1 "Only last birth"
      2 "All columns"
 /V469A   
      0 "No"
      7 "7+"
      8 "DK"
 /V469C   
      0 "No"
      7 "7+"
      8 "DK"
 /V469H   
      0 "No"
      7 "7+"
      8 "DK"
 /V469L   
      0 "No"
      7 "7+"
      8 "DK"
 /V469O   
      0 "No"
      7 "7+"
      8 "DK"
 /V469Q   
      0 "No"
      7 "7+"
      8 "DK"
 /V469R   
      0 "No"
      7 "7+"
      8 "DK"
 /V469U   
      0 "No"
      7 "7+"
      8 "DK"
 /V469V   
      0 "No"
      7 "7+"
      8 "DK"
 /V469W   
      0 "No"
      7 "7+"
      8 "DK"
 /V469Y   
      0 "No"
      7 "7+"
      8 "DK"
 /V470A   
      8 "DK"
 /V470C   
      0 "No"
      8 "DK"
 /V470H   
      0 "No"
      8 "DK"
 /V470L   
      0 "No"
      8 "DK"
 /V470O   
      0 "No"
      8 "DK"
 /V470Q   
      0 "No"
      8 "DK"
 /V470R   
      0 "No"
      8 "DK"
 /V470U   
      0 "No"
      8 "DK"
 /V470V   
      0 "No"
      8 "DK"
 /V470W   
      0 "No"
      8 "DK"
 /V470Y   
      0 "No"
      8 "DK"
 /V501    
      0 "Never married"
      1 "Married"
      2 "Living together"
      3 "Widowed"
      4 "Divorced"
      5 "Not living together"
 /V502    
      0 "Never married"
      1 "Currently married"
      2 "Formerly married"
 /V503    
      1 "Once"
      2 "More than once"
 /V504    
      1 "Living with her"
      2 "Staying elsewhere"
 /V505    
      0 "No other wives"
     98 "Don't know"
 /V506    
     98 "Don't know"
 /V510    
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 ""
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /V513    
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
 /V525    
      0 "Not had intercourse"
     96 "At first union"
     97 "Inconsistent"
     98 "Don't know"
 /V527    
    100 "<1 day ago"
    101 "Days: 1"
    201 "Weeks: 1"
    301 "Months: 1"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
 /V528    
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
 /V529    
    100 "<1 day ago"
    101 "Days: 1"
    201 "Weeks: 1"
    301 "Months: 1"
    401 "Years: 1"
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
 /V530    
      0 "No flag"
      1 "N > int. since birth"
      2 "N + abst. > interval"
      3 "N, but sex not res."
      4 "96, but no birth"
      5 "96, but curr.preg."
      6 "96, but resumed sex"
      7 "N, last sex bef preg"
      8 "N, inconsis 4 weeks"
      9 "N, sex bef last birt"
 /V531    
      0 "Not had intercourse"
     97 "Inconsistent"
     98 "Don't know"
 /V532    
      0 "No flag"
      1 "After interview"
      2 "After concep >= 1 yr"
      3 "After concep < 1 yr"
      4 "At marr, never marr"
      5 "At marr,after concep"
      6 "After marriage"
 /V535    
      0 "No"
      1 "Formerly married"
      2 "Lived with a man"
 /V536    
      0 "Never had intercourse"
      1 "Active in last 4 weeks"
      2 "Not active in last 4 weeks - postpartum abst."
      3 "Not active in last 4 weeks - not postpartum abst."
 /V537    
     96 "Before last birth"
     97 "Inconsistent"
     98 "DK"
 /V602    
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized"
      5 "Declared infecund"
      6 "Never had sex"
 /V603    
    992 "As God wishes"
    993 "After marriage"
    994 "Soon, now"
    995 ""
    996 "Other, Non-numeric"
    997 "Inconsistent"
    998 "Don't know"
 /V604    
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
 /V605    
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized"
      7 "Declared infecund"
      8 "Never had sex"
 /V610    
      0 "Disapproves"
      1 "Approves"
      8 "Don't know"
 /V611    
      0 "Never"
      1 "Once or twice"
      2 "More often"
 /V612    
      0 "Disapproves"
      1 "Approves"
      8 "Don't know"
 /V613    
     94 "Can't decide / never thought about it"
     95 "As God wishes"
     96 "Non-numeric response"
     98 "DK"
 /V614    
      6 "6+"
      7 "Non-numeric response"
 /V616    
    992 "As God wishes"
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "DK"
 /V621    
      1 "Both want same"
      2 "Husband wants more"
      3 "Husband wants fewer"
      8 "DK"
 /V623    
      0 "Fecund"
      1 "Pregnant"
      2 "Amenorrheic"
      3 "Infecund, menopausal"
 /V624    
      0 "Never had sex"
      1 "Unmet need to space"
      2 "Unmet need to limit"
      3 "Using to space"
      4 "Using to limit"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "Desire birth < 2 yrs"
      8 "No sex, want to wait"
      9 "Infecund, menopausal"
 /V625    
      0 "Fecund"
      1 "Pregnant"
      2 "Amenorrheic"
      3 "Infecund, menopausal"
 /V626    
      0 "Never had sex"
      1 "Unmet need to space"
      2 "Unmet need to limit"
      3 "Using to space"
      4 "Using to limit"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "Desire birth < 2 yrs"
      8 "No sex, want to wait"
      9 "Infecund, menopausal"
 /V627    
     94 "Never thought about it"
     95 "As God wishes"
     96 "Other"
     97 ""
     98 "DK"
 /V628    
     94 "Never thought about it"
     95 "As God wishes"
     96 "Other"
     97 ""
     98 "DK"
 /V629    
     94 "Never thought about it"
     95 "As God wishes"
     96 "Other"
     97 ""
     98 "DK"
 /V630A   
      0 "No"
      1 "Yes"
 /V630B   
      0 "No"
      1 "Yes"
 /V630C   
      0 "No"
      1 "Yes"
 /V630D   
      0 "No"
      1 "Yes"
 /V630E   
      0 "No"
      1 "Yes"
 /V630F   
      0 "No"
      1 "Yes"
 /V630G   
      0 "No"
      1 "Yes"
 /V630H   
      0 "No"
      1 "Yes"
 /V630I   
      0 "No"
      1 "Yes"
 /V630X   
      0 "No"
      1 "Yes"
 /V631    
      1 "Big problem"
      2 "Small problem"
      3 "No problem"
      4 "Says she can't get pregnant /not having sex"
 /V632    
      1 "Mainly respondent"
      2 "Mainly husband, partner"
      3 "Joint decision"
      6 "Other"
 /V633A   
      8 ""
 /V633B   
      8 ""
 /V633C   
      8 ""
 /V633D   
      8 ""
 /V633E   
      8 ""
 /V633F   
      8 ""
 /V633G   
      8 ""
 /V701    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
 /V702    
     98 "Don't know"
 /V704    
      0 "Student, pensioners"
     11 "Legislators and senior officials"
     12 "Corporate managers"
     13 "Other general managers"
     21 "Physical, mathemat., engineering science prof."
     22 "Life science and health prof."
     23 "Teaching professionals"
     24 "Other assoc. professionals"
     31 "Physical and engineering science ass. prof."
     32 "Life science and health assoc. prof."
     33 "Teaching assoc. prof."
     34 "Other assoc. prof."
     41 "Office clerks"
     42 "Customer service clerk"
     51 "Personal and protective service workers"
     52 "Models, sales persons and demonstrators"
     61 "Market oriented skilled agric. and fisher workers"
     62 "Subsistence agric. and fisher workers"
     71 "Extraction and building trade workers"
     72 "Metal, machin. and rel. trade workers"
     73 "Precision, handicraft, printing and rel. workers"
     74 "Other craft and related trade workers"
     81 "Stationary plant and related workers"
     82 "Machine operators and assemblers"
     83 "Drivers and Mobil plant operators"
     91 "Sales and service elementary occupation"
     92 "Agric. and fishery and rel. workers"
     93 "Labourers in mining, construction, manuf. and transport"
     96 "Other"
 /V705    
      0 "Did not work"
      1 "Prof., Tech., Manag."
      2 "Clerical"
      3 "Sales"
      4 "Agric-self employed"
      5 "Agric-employee"
      6 "Household & domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
 /V714    
      0 "No"
      1 "Yes"
 /V715    
     97 "Inconsistent"
     98 "Don't know"
 /V716    
      0 "Student, pensioners"
     11 "Legislators and senior officials"
     12 "Corporate managers"
     13 "Other general managers"
     21 "Physical, mathemat., engineering science prof."
     22 "Life science and health prof."
     23 "Teaching professionals"
     24 "Other assoc. professionals"
     31 "Physical and engineering science ass. prof."
     32 "Life science and health assoc. prof."
     33 "Teaching assoc. prof."
     34 "Other assoc. prof."
     41 "Office clerks"
     42 "Customer service clerk"
     51 "Personal and protective service workers"
     52 "Models, sales persons and demonstrators"
     61 "Market oriented skilled agric. and fisher workers"
     62 "Subsistence agric. and fisher workers"
     71 "Extraction and building trade workers"
     72 "Metal, machin. and rel. trade workers"
     73 "Precision, handicraft, printing and rel. workers"
     74 "Other craft and related trade workers"
     81 "Stationary plant and related workers"
     82 "Machine operators and assemblers"
     83 "Drivers and Mobil plant operators"
     91 "Sales and service elementary occupation"
     92 "Agric. and fishery and rel. workers"
     93 "Labourers in mining, construction, manuf. and transport"
     96 "Other"
 /V717    
      0 "Not working"
      1 "Prof., Tech., Manag."
      2 "Clerical"
      3 "Sales"
      4 "Agric-self employed"
      5 "Agric-employee"
      6 "Household & domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
 /V719    
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
 /V721    
      1 "At home"
      2 "Away"
 /V729    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
 /V730    
     96 "96+"
     97 ""
     98 "DK"
 /V731    
      0 "No"
      1 "In the past year"
      2 "Currently working"
 /V732    
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
 /V739    
      1 "Respondent alone"
      2 "Respondent and husband/partner"
      3 "Respondent and other person"
      4 "Husband/partner alone"
      5 "Someone else"
 /V740    
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
 /V741    
      0 "Not paid"
      1 "Cash only"
      2 "Cash and kind"
      3 "In kind only"
 /V744A   
      0 "No"
      1 "Yes"
      8 "Don't know"
 /V744B   
      0 "No"
      1 "Yes"
      8 "Don't know"
 /V744C   
      0 "No"
      1 "Yes"
      8 "Don't know"
 /V744D   
      0 "No"
      1 "Yes"
      8 "Don't know"
 /V744E   
      0 "No"
      1 "Yes"
      8 "Don't know"
 /B0      
      0 "Single birth"
      1 "1st of multiple"
      2 "2nd of multiple"
      3 "3rd of multiple"
      4 "4th of multiple"
      5 "5th of multiple"
 /B4      
      1 "Male"
      2 "Female"
 /B5      
      0 "No"
      1 "Yes"
 /B6      
    997 "Inconsistent"
    998 "Don't know"
 /B9      
      0 "Respondent"
      1 "Father"
      2 "Other relative"
      3 "Someone else"
      4 "Lives elsewhere"
 /B10     
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /B13     
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
 /B15     
      0 "No"
      1 "Yes"
 /B16     
      0 "Not listed in household"
 /M1      
      0 "Received no inject."
      7 "7+"
      8 "Don't know"
 /M2D     
      0 "No"
      1 "Yes: CS health professional"
 /M2F     
      0 "No"
      1 "Yes: trained birth A"
 /M2G     
      0 "No"
      1 "Yes: trad.birth att."
 /M2K     
      0 "No"
      1 "Yes: other responses"
 /M2N     
      0 "No: some care"
      1 "Yes: no one"
 /M3D     
      0 "No"
      1 "Yes: CS health professional"
 /M3F     
      0 "No"
      1 "Yes: trained birth A"
 /M3G     
      0 "No"
      1 "Yes: trad.birth att."
 /M3H     
      0 "No"
      1 "Yes: relative,friend"
 /M3K     
      0 "No"
      1 "Yes: other responses"
 /M3N     
      0 "No: some assistance"
      1 "Yes: no one"
 /M4      
     94 "Never breastfed"
     95 "Still breastfeeding"
     96 "Breastfed until died"
     97 "Inconsistent"
     98 "DK"
 /M5      
     94 "Never breastfed"
     97 "Inconsistent"
     98 "DK"
 /M6      
     96 "Period not returned"
     97 "Inconsistent"
     98 "DK"
 /M7      
     97 "Inconsistent"
     98 "DK"
 /M8      
     96 "Still abstaining"
     97 "Inconsistent"
     98 "DK"
 /M9      
     97 "Inconsistent"
     98 "DK"
 /M10     
      1 "Then"
      2 "Later"
      3 "No more"
 /M11     
    998 "DK"
 /M13     
     98 "DK"
 /M14     
      0 "No antenatal visits"
     98 "DK"
 /M15     
     10 "HOMES"
     11 "Respondents home"
     12 "Other home"
     13 "Forest / bush"
     20 "PUBLIC SECTOR"
     21 "Govt. hospital"
     22 "Govt. health center"
     23 "Govt. health post"
     26 "Other public"
     30 "PRIVATE SECTOR"
     31 "Private hosp/clinic"
     32 "Private doctor"
     33 "NGO health facility"
     36 "Other private medica"
     96 "OTHER"
 /M17     
      0 "No"
      1 "Yes"
 /M18     
      1 "Very large"
      2 "Larger than average"
      3 "Average"
      4 "Smaller than average"
      5 "Very small"
      8 "DK"
 /M19     
   9996 "Not weighed at birth"
   9997 ""
   9998 "DK"
 /M19A    
      0 "Not weighed"
      1 "From card"
      2 "From recall"
      9 "Special answers"
 /M27     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 "> age at death"
      4 "During preg in cal."
 /M28     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 ""
      4 "During preg in cal."
 /M29     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 ""
      4 "During preg in cal."
 /M34     
      0 "Immediately"
    100 ""
    101 "Hours: 1"
    201 "Days: 1"
 /M35     
     96 "On demand"
 /M36     
     96 "On demand"
 /M37A    
      0 "No"
      7 "7+"
      8 "DK"
 /M37C    
      0 "No"
      7 "7+"
      8 "DK"
 /M37H    
      0 "No"
      7 "7+"
      8 "DK"
 /M37L    
      0 "No"
      7 "7+"
      8 "DK"
 /M37O    
      0 "No"
      7 "7+"
      8 "DK"
 /M37Q    
      0 "No"
      7 "7+"
      8 "DK"
 /M37R    
      0 "No"
      7 "7+"
      8 "DK"
 /M37U    
      0 "No"
      7 "7+"
      8 "DK"
 /M37V    
      0 "No"
      7 "7+"
      8 "DK"
 /M37W    
      0 "No"
      7 "7+"
      8 "DK"
 /M37Y    
      0 "No"
      7 "7+"
      8 "DK"
 /M38     
      0 "No"
      1 "Yes"
      8 "DK"
 /M39     
      0 "None"
      7 "7+"
      8 "DK"
 /M40A    
      8 "DK"
 /M40C    
      0 "No"
      8 "DK"
 /M40H    
      0 "No"
      8 "DK"
 /M40L    
      0 "No"
      8 "DK"
 /M40O    
      0 "No"
      8 "DK"
 /M40Q    
      0 "No"
      8 "DK"
 /M40R    
      0 "No"
      8 "DK"
 /M40U    
      0 "No"
      8 "DK"
 /M40V    
      0 "No"
      8 "DK"
 /M40W    
      0 "No"
      8 "DK"
 /M40Y    
      0 "No"
      8 "DK"
 /M41     
     98 "Don't know"
 /M42A    
      0 "No"
      1 "Yes"
 /M42B    
      0 "No"
      1 "Yes"
 /M42C    
      0 "No"
      1 "Yes"
 /M42D    
      0 "No"
      1 "Yes"
 /M42E    
      0 "No"
      1 "Yes"
 /M43     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M44     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M45     
      8 ""
 /M46     
    998 ""
 /M47     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M48     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M49A    
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M49B    
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M49C    
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M49D    
      0 "No"
      1 "Yes, proguanil"
      8 "Don't know"
 /M49E    
      8 ""
 /M49F    
      8 ""
 /M49G    
      8 ""
 /M49X    
      0 "No"
      1 "Yes"
      8 "Don't know"
 /M49Z    
      0 "No"
      1 "Yes, took no drug"
      8 "Don't know"
 /M50     
      0 "No"
      1 "Yes"
 /M51     
    100 "Same day"
    101 "1 day"
    201 "1 week"
    998 "Don't know"
 /M52     
     10 "HEALTH PROFESSIONAL"
     11 "Doctor"
     12 "Nurse/midwife"
     13 "Auxiliary midwife"
     14 "Health professional"
     15 "Trained traditional birth attendant"
     20 "OTHER PERSON"
     21 "Traditional birth attendant"
     96 "Other"
 /M53     
     10 "HOMES"
     11 "Respondents home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Govt. hospital"
     22 "Govt. health center"
     23 "Govt. health post"
     24 "Govt. health clinic"
     25 ""
     26 "Other public"
     30 "PRIVATE SECTOR"
     31 "Private hosp/clinic"
     32 "Private doctor clinic"
     33 "NGO health facility"
     36 "Other private medica"
     96 "OTHER"
 /M54     
      0 "No"
      1 "Yes"
 /M56     
      8 ""
 /H1      
      0 "No card"
      1 "Yes, seen"
      2 "Yes, not seen"
      3 "No longer has card"
 /H2      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H2D     
     97 "Inconsistent"
     98 "DK"
 /H2M     
     97 "Inconsistent"
     98 "DK"
 /H2Y     
   9997 "Inconsistent"
   9998 "DK"
 /H3      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H3D     
     97 "Inconsistent"
     98 "DK"
 /H3M     
     97 "Inconsistent"
     98 "DK"
 /H3Y     
   9997 "Inconsistent"
   9998 "DK"
 /H4      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H4D     
     97 "Inconsistent"
     98 "DK"
 /H4M     
     97 "Inconsistent"
     98 "DK"
 /H4Y     
   9997 "Inconsistent"
   9998 "DK"
 /H5      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H5D     
     97 "Inconsistent"
     98 "DK"
 /H5M     
     97 "Inconsistent"
     98 "DK"
 /H5Y     
   9997 "Inconsistent"
   9998 "DK"
 /H6      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H6D     
     97 "Inconsistent"
     98 "DK"
 /H6M     
     97 "Inconsistent"
     98 "DK"
 /H6Y     
   9997 "Inconsistent"
   9998 "DK"
 /H7      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H7D     
     97 "Inconsistent"
     98 "DK"
 /H7M     
     97 "Inconsistent"
     98 "DK"
 /H7Y     
   9997 "Inconsistent"
   9998 "DK"
 /H8      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H8D     
     97 "Inconsistent"
     98 "DK"
 /H8M     
     97 "Inconsistent"
     98 "DK"
 /H8Y     
   9997 "Inconsistent"
   9998 "DK"
 /H9      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H9D     
     97 "Inconsistent"
     98 "DK"
 /H9M     
     97 "Inconsistent"
     98 "DK"
 /H9Y     
   9997 "Inconsistent"
   9998 "DK"
 /H0      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H0D     
     97 "Inconsistent"
     98 "DK"
 /H0M     
     97 "Inconsistent"
     98 "DK"
 /H0Y     
   9997 "Inconsistent"
   9998 "DK"
 /H10     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /H11     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
 /H12A    
      0 "No"
      1 "Government hospital"
 /H12B    
      0 "No"
      1 "Govt. health center"
 /H12C    
      0 "No"
      1 "Govt. health post"
 /H12E    
      0 "No"
      1 "Community based outlet"
 /H12F    
      0 "No"
      1 "CS health station / clinic"
 /H12G    
      0 "No"
      1 "CS: other government"
 /H12J    
      0 "No"
      1 "Private hosp./clinic"
 /H12K    
      0 "No"
      1 "Private pharmacy"
 /H12L    
      0 "No"
      1 "Private doctor"
 /H12N    
      0 "No"
      1 "Community based outlet"
 /H12O    
      0 "No"
      1 "CS NGO health facility"
 /H12P    
      0 "No"
      1 "CS other NGO"
 /H12Q    
      0 "No"
      1 "CS other private medical"
 /H12S    
      0 "No"
      1 "Shop"
 /H12T    
      0 "No"
      1 "Traditional pract."
 /H12U    
      0 "No"
      1 "CS drug vendor"
 /H12X    
      0 "No"
      1 "Other"
 /H12Y    
      0 "No: received treatm."
      1 "Yes: no treatment"
 /H12Z    
      0 "No"
      1 "Yes: medical treatm."
 /H13     
      0 "No"
      1 "Yes: ORS - spontan."
      2 "Yes: ORS - probed"
      8 "Don't know"
 /H14     
      0 "No"
      1 "Yes: RHS - spontan."
      2 "Yes: RHS - probed"
      8 "Don't know"
 /H15     
      0 "No"
      1 "Yes: oth pill, syrup"
      8 "Don't know"
 /H15A    
      8 ""
 /H15B    
      0 "No"
      1 "Yes: injection"
      8 "Don't know"
 /H15C    
      0 "No"
      1 "Yes: intravenous (IV)"
      8 "Don't know"
 /H15D    
      0 "No"
      1 "Yes: home rem, herb."
      8 "Don't know"
 /H15E    
      8 ""
 /H15F    
      8 ""
 /H15G    
      8 ""
 /H15H    
      8 ""
 /H20     
      0 "No"
      1 "Yes"
 /H21A    
      0 "No: received treatm."
      1 "Yes: no treatment"
      8 "DK"
 /H21     
      0 "No"
      1 "Yes"
 /H22     
      0 "No"
      1 "Yes"
      8 "DK"
 /H31     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
 /H31B    
      0 "No"
      1 "Yes"
      8 "DK"
 /H32A    
      0 "No"
      1 "Government hospital"
 /H32B    
      0 "No"
      1 "Govt. health center"
 /H32C    
      0 "No"
      1 "Govt. health post"
 /H32E    
      0 "No"
      1 "Community based outlet"
 /H32F    
      0 "No"
      1 "Health station /clinic"
 /H32G    
      0 "No"
      1 "Other public sector"
 /H32J    
      0 "No"
      1 "Private hosp./clinic"
 /H32K    
      0 "No"
      1 "Private pharmacy"
 /H32L    
      0 "No"
      1 "Private doctor"
 /H32N    
      0 "No"
      1 "NGO community health outlet"
 /H32O    
      0 "No"
      1 "NGO health facility"
 /H32P    
      0 "No"
      1 "NGO other"
 /H32Q    
      0 "No"
      1 "Other private medical"
 /H32S    
      0 "No"
      1 "Shop"
 /H32T    
      0 "No"
      1 "Traditional pract."
 /H32X    
      0 "No"
      1 "Other"
 /H32Y    
      0 "No: received treatm."
      1 "Yes: no treatment"
 /H32Z    
      0 "No"
      1 "Yes: medical treatm."
 /H33     
      8 ""
 /H34     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /H35     
      0 "No"
      1 "Yes"
      2 "No vaccination in last 2 years"
      8 "Don't know"
 /H36A    
      0 "No"
      1 "Yes: Tikemt/Hidar 1990"
 /H36B    
      0 "No"
      1 "Yes: Tikemt/Hidar 1991"
 /H36C    
      0 "No"
      1 "Yes: Tikemt/Hidar 1992"
 /H37A    
      0 "No"
      1 "Yes"
 /H37B    
      0 "No"
      1 "Yes"
 /H37C    
      0 "No"
      1 "Yes"
 /H37D    
      0 "No"
      1 "Yes"
 /H37E    
      0 "No"
      1 "Yes: quinine"
 /H37F    
      0 "No"
      1 "Yes: antibiotics"
 /H37X    
      0 "No"
      1 "Yes"
 /H37Y    
      0 "No"
      1 "Yes, nothing taken"
 /H37Z    
      0 "No"
      1 "Yes, DK"
 /H38     
      0 "Nothing to drink"
      1 ""
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
 /H39     
      0 "Stopped food"
      1 "Never gave food"
      2 "Much less"
      3 "Somewhat less"
      4 "About the same"
      5 "More"
      8 "Don't know"
 /HW4     
   9998 "Flagged cases"
 /HW5     
   9998 "Flagged cases"
 /HW6     
  99998 "Flagged cases"
 /HW7     
   9998 "Flagged cases"
 /HW8     
   9998 "Flagged cases"
 /HW9     
  99998 "Flagged cases"
 /HW10    
   9998 "Flagged cases"
 /HW11    
   9998 "Flagged cases"
 /HW12    
  99998 "Flagged cases"
 /HW13    
      0 "Measured"
      1 "Dead"
      2 "Sick"
      3 "Not present"
      4 "Refused"
      5 "Mother refused"
      6 "Other"
      7 "No measurement found in HH"
 /HW15    
      1 "Lying"
      2 "Standing"
 /HW16    
     97 "Inconsistent"
     98 "DK"
 /HW51    
      0 "Not in household"
 /HW52    
      1 "Granted"
      2 "Refused"
 /HW55    
      0 "Measured"
      1 "Dead"
      2 ""
      3 "Not present"
      4 "Refused"
      5 ""
      6 "Other"
      7 "No measurement found in HH"
 /HW57    
      1 "Severe"
      2 "Moderate"
      3 "Mild"
      4 "Not anemic"
 /HW58    
      0 "No"
      1 "Yes"
 /SINTYG  
   2000 ""
 /SLAN    
      1 "Amarigna"
      2 "Oromigna"
      3 "Tigrigna"
      4 "Somaligna"
      5 "Afarigna"
      6 "Other"
 /SINTV   
      1 "Amarigna"
      2 "Oromigna"
      3 "Tigrigna"
      4 "Somaligna"
      5 "Afarigna"
      6 "Other"
      7 "Gamogna"
      8 "Kefigna"
 /SRESP   
      1 "Amarigna"
      2 "Oromigna"
      3 "Tigrigna"
      4 "Somaligna"
      5 "Afarigna"
      6 "Other"
      7 "Gamogna"
      8 "Kefigna"
 /STRANS  
      0 "No"
      1 "Yes"
 /S101T   
      1 "Morning"
      2 "Evening"
 /S101H   
     97 "Inconsistent"
 /S101M   
     97 "Inconsistent"
 /S105MG  
     97 "Inconsistent"
     98 "DK month"
 /S105YG  
   9997 "Inconsistent"
   9998 "DK year"
 /S109    
     13 "Technical/vocational certificate"
     14 "University/college diploma"
     15 "University/college degree"
 /S230AF  
      1 "Month and year"
      2 "Month and time ago -y imp"
      3 "Year and time ago - m imp"
      4 "Y & time ago - y ignored"
      5 "Year - time ago, m imp"
      6 "Time ago - y, m imp"
      7 "Month - time ago, y imp"
      8 "None - all imp"
 /S230B   
    100 "Zero months"
    200 "Zero years"
    900 "Special answers"
 /S230AMG 
     97 "Inconsistent"
     98 "DK"
 /S230AYG 
   9997 "Inconsistent"
   9998 "DK"
 /S234    
      0 "No"
      1 "Yes"
 /S234A   
      1 "Yes, seen"
      2 "Yes, not seen"
      3 "No card"
 /S234C   
     98 ""
 /SD234B1 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SM234B1 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SY234B1 
      0 "Not given"
   4444 "Marked on card"
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 /SD234B2 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SM234B2 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SY234B2 
      0 "Not given"
   4444 "Marked on card"
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 /SD234B3 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SM234B3 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SY234B3 
      0 "Not given"
   4444 "Marked on card"
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 /SD234B4 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SM234B4 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SY234B4 
      0 "Not given"
   4444 "Marked on card"
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 /SD234B5 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SM234B5 
      0 "Not given"
     44 "Marked on card"
     97 "Inconsistent"
     98 "DK"
     99 "Missing"
 /SY234B5 
      0 "Not given"
   4444 "Marked on card"
   9997 "Inconsistent"
   9998 "DK"
   9999 "Missing"
 /S312    
      1 "Microgynon"
      2 "Lo-Feminol"
      3 "Excluton"
      4 "Neogynon"
      5 "Nordette"
      6 "Prudence"
      7 "Choice"
     95 "No brand name"
     96 "Other"
     98 "Don't know"
 /S319    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Health station/clinic"
     14 "Health post"
     15 "Community based outlet"
     16 "Other public"
     20 "NGO"
     21 "NGO health facility"
     22 "Community based outlets"
     23 "Family guidance"
     26 "Other NGO"
     30 "PRIVATE MEDICAL SECTOR"
     31 "Private hospital"
     32 "Private doctor/clinic"
     33 "Pharmacy"
     36 "Other private medical"
     40 "OTHER SOURCE"
     41 "Work place facility"
     42 "Drug vendor"
     43 "Shop"
     44 "Friend/relative"
     45 ""
     46 "Other"
     95 "Did not consult source"
     98 "DK"
 /S319D   
    998 "DK"
 /S329    
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Health station/clinic"
     14 "Health post"
     15 "Community based outlet"
     16 "Other public"
     20 "NGO"
     21 "NGO health facility"
     22 "Community based outlets"
     23 "NGO: Family Guidance"
     26 "Other NGO"
     30 "PRIVATE MEDICAL SECTOR"
     31 "Private hospital"
     32 "Private doctor/clinic"
     33 "Pharmacy"
     36 "Other private medical"
     40 "OTHER SOURCE"
     41 "Work place facility"
     42 "Drug vendor"
     43 "Shop"
     44 "Friend/relative"
     45 ""
     46 "Other"
 /S482    
      0 "No"
      1 "Yes"
 /S483    
      0 "No"
      1 "Yes"
 /S484    
      1 "Always use toilet, latrine"
      2 "Throw in the toilet, latrine"
      3 "Throw outside dwelling"
      4 "Throw outside the yard"
      5 "Bury in the yard"
      6 "Rinsed away"
      7 "Not disposed of"
     96 "Other"
 /S489    
      0 "No"
      1 "Yes"
 /S489AA  
      0 "No"
      1 "Yes - does not know"
 /S489AB  
      0 "No"
      1 "Yes"
 /S489AC  
      0 "No"
      1 "Yes"
 /S489AD  
      0 "No"
      1 "Yes"
 /S489AE  
      0 "No"
      1 "Yes"
 /S489AF  
      0 "No"
      1 "Yes"
 /S489AG  
      0 "No"
      1 "Yes"
 /S489AH  
      0 "No"
      1 "Yes - would recover soon"
 /S489AI  
      0 "No"
      1 "Yes - sickness was not serious"
 /S489AJ  
      0 "No"
      1 "Yes - scared of modern treatment"
 /S489AK  
      0 "No"
      1 "Yes - used traditional treatment / drugs"
 /S489AL  
      0 "No"
      1 "Yes - did not feel sick"
 /S489AX  
      0 "No"
      1 "Yes"
 /S508MG  
     97 "Inconsistent"
     98 "DK month"
 /S508YG  
   9997 "Inconsistent"
   9998 "DK year"
 /S617D   
      0 "No"
      1 "Yes"
 /S617E   
      0 "No"
      1 "Yes"
 /S702A   
      0 "No"
      1 "Yes"
      8 "DK"
 /S705    
     13 "Post secondary certificate"
     14 "University/colllege diploma"
     15 "University/college degree"
     98 "DK"
 /S712A   
      1 "Throughout the agricultural season"
      2 "Part of the agricultural season"
      3 "Once in a while"
 /S1001AA 
      0 "No"
      1 "Yes"
 /S1001AB 
      0 "No"
      1 "Yes"
 /S1001AC 
      0 "No"
      1 "Yes"
 /S1001AD 
      0 "No"
      1 "Yes"
 /S1001AE 
      0 "No"
      1 "Yes"
 /S1001AF 
      0 "No"
      1 "Yes"
 /S1001AG 
      0 "No"
      1 "Yes"
 /S1001AH 
      0 "No"
      1 "Yes"
 /S1001AI 
      0 "No"
      1 "Yes"
 /S1001AJ 
      0 "No"
      1 "Yes"
 /S1001AK 
      0 "No"
      1 "Yes"
 /S1001AX 
      0 "No"
      1 "Yes"
 /S1005   
      0 "No"
      1 "Yes"
      8 "DK"
 /S1006   
      1 "Greater chance of AIDS"
      2 "Lesser chance of AIDS"
 /S1008   
      1 "Decreases chances"
      2 "Increases chances"
      3 "Doesn't make a difference"
      8 "DK"
 /S1013A  
      0 "No"
      1 "Yes"
 /S1013B  
      0 "No"
      1 "Yes"
 /S1013C  
      0 "No"
      1 "Yes"
 /S1013D  
      0 "No"
      1 "Yes"
 /S1013Z  
      0 "No"
      1 "Yes - DK"
 /S1106   
      0 "No"
      1 "Yes"
 /S1111   
      0 "No"
      1 "Yes"
 /S1112   
      0 "Does not know a place where to get  condoms"
     10 "PUBLIC SECTOR"
     11 "Government hospital"
     12 "Government health center"
     13 "Health station/clinic"
     14 "Health post"
     15 "Community based outlet"
     16 "Other public"
     20 "NGO"
     21 "NGO health facility"
     22 "Community based outlets"
     23 "NGO: Family Guidance"
     26 "Other NGO"
     30 "PRIVATE MEDICAL SECTOR"
     31 "Private hospital"
     32 "Private doctor/clinic"
     33 "Pharmacy"
     36 "Other private medical"
     40 "OTHER SOURCE"
     41 "Work place facility"
     42 "Drug vendor"
     43 "Shop"
     44 "Friend/relative"
     45 ""
     46 "Other"
 /S1114T  
      1 "Morning"
      2 "Evening"
 /S1114H  
     97 "Inconsistent"
 /S215MG  
     97 "Inconsistent"
     98 "DK"
 /S215YG  
   9997 "Inconsistent"
   9998 "DK"
 /S406A   
      0 "No"
      1 "Yes"
 /S406BA  
      0 "No"
      1 "Yes"
 /S406BB  
      0 "No"
      1 "Yes"
 /S406BC  
      0 "No"
      1 "Yes"
 /S406BD  
      0 "No"
      1 "Yes"
 /S406BE  
      0 "No"
      1 "Yes"
 /S406BX  
      0 "No"
      1 "Yes"
 /S432C   
      0 "Not started"
    100 "Days"
    200 "Weeks"
    300 "Months"
    900 "Special answers"
    998 "Don't know"
 /S440A   
      0 "No"
      1 "Yes"
 /S442A   
      1 "Mother ill/weak"
      2 "Child ill/weak"
      3 "Child died"
      4 "Nipple/breast problem"
      5 "Not enough milk"
      6 "Mother working"
      7 "Child refused"
      8 "Weaning age/age to stop"
      9 "Became pregnant"
     10 "Started to use contraception"
     96 "Other"
     97 "Inconsistent"
 /S475C   
      0 "No"
      1 "Yes"
      8 "DK"
 .
 EXECUTE.
execute.
save outfile='ETBR41FL.SAV'.
