infix using ETMR41FL.dct

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview (Ethiopian calendar)"
label variable mv007    "Year of interview (Ethiopian calendar)"
label variable mv008    "Date of interview (CMC Ethiopian calendar)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv033    "Ultimate area selection prob."
label variable mv034_1  "Line numbers of wives, partners"
label variable mv034a_1 "Wife or partner            -NA"
label variable mv034_2  "Line numbers of wives, partners"
label variable mv034a_2 "Wife or partner            -NA"
label variable mv034_3  "Line numbers of wives, partners"
label variable mv034a_3 "Wife or partner            -NA"
label variable mv034_4  "Line numbers of wives, partners"
label variable mv034a_4 "Wife or partner            -NA"
label variable mv034_5  "Line numbers of wives, partners"
label variable mv034a_5 "Wife or partner            -NA"
label variable mv034_6  "Line numbers of wives, partners"
label variable mv034a_6 "Wife or partner            -NA"
label variable mv034_7  "Line numbers of wives, partners"
label variable mv034a_7 "Wife or partner            -NA"
label variable mv034_8  "Line numbers of wives, partners"
label variable mv034a_8 "Wife or partner            -NA"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residence"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous res."
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "MV167participated in a lite-NA"
label variable mv157    "Frequency of reading newpaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in las-NA"
label variable mv168    "Away for more than one mont-NA"
label variable mv463a   "Smokes cigarettes          -NA"
label variable mv463b   "Smokes pipe                -NA"
label variable mv463c   "Smokes other tobacco       -NA"
label variable mv463d   "Smokes country specific    -NA"
label variable mv463e   "Smokes country specific    -NA"
label variable mv463f   "Smokes country specific    -NA"
label variable mv463g   "Smokes country specific    -NA"
label variable mv463z   "Smokes nothing             -NA"
label variable mv464    "Number of cigarettes in las-NA"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home               -NA"
label variable mv203    "Daughters at home          -NA"
label variable mv204    "Sons elsewhere             -NA"
label variable mv205    "Daughters elsewhere        -NA"
label variable mv206    "Sons who have died         -NA"
label variable mv207    "Daughters who have died    -NA"
label variable mv212    "Age of respondent at 1st bi-NA"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycl-NA"
label variable mv218    "Number of living children"
label variable mv225    "Current pregnancy wanted"
label variable mv245    "Women fathered children wit-NA"
label variable mv246    "Married to mother when firs-NA"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable mv304_01 "Knows method"
label variable mv305_01 "Ever used method"
label variable mv307_01 "Method currently used"
label variable m304a_02 "Type of method"
label variable mv304_02 "Knows method"
label variable mv305_02 "Ever used method"
label variable mv307_02 "Method currently used"
label variable m304a_03 "Type of method"
label variable mv304_03 "Knows method"
label variable mv305_03 "Ever used method"
label variable mv307_03 "Method currently used"
label variable m304a_04 "Type of method"
label variable mv304_04 "Knows method"
label variable mv305_04 "Ever used method"
label variable mv307_04 "Method currently used"
label variable m304a_05 "Type of method"
label variable mv304_05 "Knows method"
label variable mv305_05 "Ever used method"
label variable mv307_05 "Method currently used"
label variable m304a_06 "Type of method"
label variable mv304_06 "Knows method"
label variable mv305_06 "Ever used method"
label variable mv307_06 "Method currently used"
label variable m304a_07 "Type of method"
label variable mv304_07 "Knows method"
label variable mv305_07 "Ever used method"
label variable mv307_07 "Method currently used"
label variable m304a_08 "Type of method"
label variable mv304_08 "Knows method"
label variable mv305_08 "Ever used method"
label variable mv307_08 "Method currently used"
label variable m304a_09 "Type of method"
label variable mv304_09 "Knows method"
label variable mv305_09 "Ever used method"
label variable mv307_09 "Method currently used"
label variable m304a_10 "Type of method"
label variable mv304_10 "Knows method"
label variable mv305_10 "Ever used method"
label variable mv307_10 "Method currently used"
label variable m304a_11 "Type of method"
label variable mv304_11 "Knows method"
label variable mv305_11 "Ever used method"
label variable mv307_11 "Method currently used"
label variable m304a_12 "Type of method"
label variable mv304_12 "Knows method"
label variable mv305_12 "Ever used method"
label variable mv307_12 "Method currently used"
label variable m304a_13 "Type of method"
label variable mv304_13 "Knows method"
label variable mv305_13 "Ever used method"
label variable mv307_13 "Method currently used"
label variable m304a_14 "Type of method"
label variable mv304_14 "Knows method"
label variable mv305_14 "Ever used method"
label variable mv307_14 "Method currently used"
label variable m304a_15 "Type of method"
label variable mv304_15 "Knows method"
label variable mv305_15 "Ever used method"
label variable mv307_15 "Method currently used"
label variable m304a_16 "Type of method"
label variable mv304_16 "Knows method"
label variable mv305_16 "Ever used method"
label variable mv307_16 "Method currently used"
label variable m304a_17 "Type of method"
label variable mv304_17 "Knows method"
label variable mv305_17 "Ever used method"
label variable mv307_17 "Method currently used"
label variable m304a_18 "Type of method"
label variable mv304_18 "Knows method"
label variable mv305_18 "Ever used method"
label variable mv307_18 "Method currently used"
label variable m304a_19 "Type of method"
label variable mv304_19 "Knows method"
label variable mv305_19 "Ever used method"
label variable mv307_19 "Method currently used"
label variable m304a_20 "Type of method"
label variable mv304_20 "Knows method"
label variable mv305_20 "Ever used method"
label variable mv307_20 "Method currently used"
label variable mv312    "Current contraceptive method"
label variable mv312a   "Most recent contraceptive method"
label variable mv312b   "Contraceptive method with other woman"
label variable mv312c   "Contraceptive method with o-NA"
label variable mv313    "Current use by method type"
label variable mv313a   "Most recent use by method type"
label variable mv313b   "Method use by method type with other woman"
label variable mv313c   "Method use by method type w-NA"
label variable mv361    "Pattern of use"
label variable mv362    "Intention to use"
label variable mv363    "Preferred future method    -NA"
label variable mv364    "Contraceptive use & intention"
label variable mv367    "Wanted last child"
label variable mv375a   "Main reason not using a met-NA"
label variable mv375b   "Main reason not using a met-NA"
label variable mv375c   "Main reason not using a met-NA"
label variable mv376    "Main reason not to use a meth."
label variable mv376a   "Would ever use method if ma-NA"
label variable mv384a   "Heard FP on radio last months"
label variable mv384b   "Heard FP on TV last months"
label variable mv384c   "Heard FP newspaper last months"
label variable mv396    "Can a woman who is breastfe-NA"
label variable mv3b0_1  "Method                     -NA"
label variable mv3b1_1  "Method is suitable for coup-NA"
label variable mv3b2a_1 "Advantages: Simple to use  -NA"
label variable mv3b2b_1 "Advantages: Effective      -NA"
label variable mv3b2c_1 "Advantages: Affordable     -NA"
label variable mv3b2d_1 "Advantages: No/few side eff-NA"
label variable mv3b2e_1 "Advantages: Can stop childr-NA"
label variable mv3b2f_1 "Advantages: no need for med-NA"
label variable mv3b2g_1 "Advantages: No risk of gett-NA"
label variable mv3b2h_1 "Advantages: Once inserted, -NA"
label variable mv3b2i_1 "Advantages: Country specifi-NA"
label variable mv3b2j_1 "Advantages: Country specifi-NA"
label variable mv3b2k_1 "Advantages: Country specifi-NA"
label variable mv3b2l_1 "Advantages: Country specifi-NA"
label variable mv3b2x_1 "Advantages: Other          -NA"
label variable mv3b2z_1 "Advantages: Don't know     -NA"
label variable mv3b3a_1 "Disadvantages: Too expensiv-NA"
label variable mv3b3b_1 "Disadvantages: Against reli-NA"
label variable mv3b3c_1 "Disadvantages: May harm wom-NA"
label variable mv3b3d_1 "Disadvantages: Has side eff-NA"
label variable mv3b3e_1 "Disadvantages: Increases pr-NA"
label variable mv3b3f_1 "Disadvantages: Can cause st-NA"
label variable mv3b3g_1 "Disadvantages: Method can f-NA"
label variable mv3b3h_1 "Disadvantages: Baby in dang-NA"
label variable mv3b3i_1 "Disadvantages: Involves doc-NA"
label variable mv3b3j_1 "Disadvantages: Can lead to -NA"
label variable mv3b3k_1 "Disadvantages: Country spec-NA"
label variable mv3b3l_1 "Disadvantages: Country spec-NA"
label variable mv3b3m_1 "Disadvantages: Country spec-NA"
label variable mv3b3n_1 "Disadvantages: Country spec-NA"
label variable mv3b3x_1 "Disadvantages: Other       -NA"
label variable mv3b3z_1 "Disadvantages: Don't know  -NA"
label variable mv3b0_2  "Method                     -NA"
label variable mv3b1_2  "Method is suitable for coup-NA"
label variable mv3b2a_2 "Advantages: Simple to use  -NA"
label variable mv3b2b_2 "Advantages: Effective      -NA"
label variable mv3b2c_2 "Advantages: Affordable     -NA"
label variable mv3b2d_2 "Advantages: No/few side eff-NA"
label variable mv3b2e_2 "Advantages: Can stop childr-NA"
label variable mv3b2f_2 "Advantages: no need for med-NA"
label variable mv3b2g_2 "Advantages: No risk of gett-NA"
label variable mv3b2h_2 "Advantages: Once inserted, -NA"
label variable mv3b2i_2 "Advantages: Country specifi-NA"
label variable mv3b2j_2 "Advantages: Country specifi-NA"
label variable mv3b2k_2 "Advantages: Country specifi-NA"
label variable mv3b2l_2 "Advantages: Country specifi-NA"
label variable mv3b2x_2 "Advantages: Other          -NA"
label variable mv3b2z_2 "Advantages: Don't know     -NA"
label variable mv3b3a_2 "Disadvantages: Too expensiv-NA"
label variable mv3b3b_2 "Disadvantages: Against reli-NA"
label variable mv3b3c_2 "Disadvantages: May harm wom-NA"
label variable mv3b3d_2 "Disadvantages: Has side eff-NA"
label variable mv3b3e_2 "Disadvantages: Increases pr-NA"
label variable mv3b3f_2 "Disadvantages: Can cause st-NA"
label variable mv3b3g_2 "Disadvantages: Method can f-NA"
label variable mv3b3h_2 "Disadvantages: Baby in dang-NA"
label variable mv3b3i_2 "Disadvantages: Involves doc-NA"
label variable mv3b3j_2 "Disadvantages: Can lead to -NA"
label variable mv3b3k_2 "Disadvantages: Country spec-NA"
label variable mv3b3l_2 "Disadvantages: Country spec-NA"
label variable mv3b3m_2 "Disadvantages: Country spec-NA"
label variable mv3b3n_2 "Disadvantages: Country spec-NA"
label variable mv3b3x_2 "Disadvantages: Other       -NA"
label variable mv3b3z_2 "Disadvantages: Don't know  -NA"
label variable mv3b0_3  "Method                     -NA"
label variable mv3b1_3  "Method is suitable for coup-NA"
label variable mv3b2a_3 "Advantages: Simple to use  -NA"
label variable mv3b2b_3 "Advantages: Effective      -NA"
label variable mv3b2c_3 "Advantages: Affordable     -NA"
label variable mv3b2d_3 "Advantages: No/few side eff-NA"
label variable mv3b2e_3 "Advantages: Can stop childr-NA"
label variable mv3b2f_3 "Advantages: no need for med-NA"
label variable mv3b2g_3 "Advantages: No risk of gett-NA"
label variable mv3b2h_3 "Advantages: Once inserted, -NA"
label variable mv3b2i_3 "Advantages: Country specifi-NA"
label variable mv3b2j_3 "Advantages: Country specifi-NA"
label variable mv3b2k_3 "Advantages: Country specifi-NA"
label variable mv3b2l_3 "Advantages: Country specifi-NA"
label variable mv3b2x_3 "Advantages: Other          -NA"
label variable mv3b2z_3 "Advantages: Don't know     -NA"
label variable mv3b3a_3 "Disadvantages: Too expensiv-NA"
label variable mv3b3b_3 "Disadvantages: Against reli-NA"
label variable mv3b3c_3 "Disadvantages: May harm wom-NA"
label variable mv3b3d_3 "Disadvantages: Has side eff-NA"
label variable mv3b3e_3 "Disadvantages: Increases pr-NA"
label variable mv3b3f_3 "Disadvantages: Can cause st-NA"
label variable mv3b3g_3 "Disadvantages: Method can f-NA"
label variable mv3b3h_3 "Disadvantages: Baby in dang-NA"
label variable mv3b3i_3 "Disadvantages: Involves doc-NA"
label variable mv3b3j_3 "Disadvantages: Can lead to -NA"
label variable mv3b3k_3 "Disadvantages: Country spec-NA"
label variable mv3b3l_3 "Disadvantages: Country spec-NA"
label variable mv3b3m_3 "Disadvantages: Country spec-NA"
label variable mv3b3n_3 "Disadvantages: Country spec-NA"
label variable mv3b3x_3 "Disadvantages: Other       -NA"
label variable mv3b3z_3 "Disadvantages: Don't know  -NA"
label variable mv3b0_4  "Method                     -NA"
label variable mv3b1_4  "Method is suitable for coup-NA"
label variable mv3b2a_4 "Advantages: Simple to use  -NA"
label variable mv3b2b_4 "Advantages: Effective      -NA"
label variable mv3b2c_4 "Advantages: Affordable     -NA"
label variable mv3b2d_4 "Advantages: No/few side eff-NA"
label variable mv3b2e_4 "Advantages: Can stop childr-NA"
label variable mv3b2f_4 "Advantages: no need for med-NA"
label variable mv3b2g_4 "Advantages: No risk of gett-NA"
label variable mv3b2h_4 "Advantages: Once inserted, -NA"
label variable mv3b2i_4 "Advantages: Country specifi-NA"
label variable mv3b2j_4 "Advantages: Country specifi-NA"
label variable mv3b2k_4 "Advantages: Country specifi-NA"
label variable mv3b2l_4 "Advantages: Country specifi-NA"
label variable mv3b2x_4 "Advantages: Other          -NA"
label variable mv3b2z_4 "Advantages: Don't know     -NA"
label variable mv3b3a_4 "Disadvantages: Too expensiv-NA"
label variable mv3b3b_4 "Disadvantages: Against reli-NA"
label variable mv3b3c_4 "Disadvantages: May harm wom-NA"
label variable mv3b3d_4 "Disadvantages: Has side eff-NA"
label variable mv3b3e_4 "Disadvantages: Increases pr-NA"
label variable mv3b3f_4 "Disadvantages: Can cause st-NA"
label variable mv3b3g_4 "Disadvantages: Method can f-NA"
label variable mv3b3h_4 "Disadvantages: Baby in dang-NA"
label variable mv3b3i_4 "Disadvantages: Involves doc-NA"
label variable mv3b3j_4 "Disadvantages: Can lead to -NA"
label variable mv3b3k_4 "Disadvantages: Country spec-NA"
label variable mv3b3l_4 "Disadvantages: Country spec-NA"
label variable mv3b3m_4 "Disadvantages: Country spec-NA"
label variable mv3b3n_4 "Disadvantages: Country spec-NA"
label variable mv3b3x_4 "Disadvantages: Other       -NA"
label variable mv3b3z_4 "Disadvantages: Don't know  -NA"
label variable mv3b0_5  "Method                     -NA"
label variable mv3b1_5  "Method is suitable for coup-NA"
label variable mv3b2a_5 "Advantages: Simple to use  -NA"
label variable mv3b2b_5 "Advantages: Effective      -NA"
label variable mv3b2c_5 "Advantages: Affordable     -NA"
label variable mv3b2d_5 "Advantages: No/few side eff-NA"
label variable mv3b2e_5 "Advantages: Can stop childr-NA"
label variable mv3b2f_5 "Advantages: no need for med-NA"
label variable mv3b2g_5 "Advantages: No risk of gett-NA"
label variable mv3b2h_5 "Advantages: Once inserted, -NA"
label variable mv3b2i_5 "Advantages: Country specifi-NA"
label variable mv3b2j_5 "Advantages: Country specifi-NA"
label variable mv3b2k_5 "Advantages: Country specifi-NA"
label variable mv3b2l_5 "Advantages: Country specifi-NA"
label variable mv3b2x_5 "Advantages: Other          -NA"
label variable mv3b2z_5 "Advantages: Don't know     -NA"
label variable mv3b3a_5 "Disadvantages: Too expensiv-NA"
label variable mv3b3b_5 "Disadvantages: Against reli-NA"
label variable mv3b3c_5 "Disadvantages: May harm wom-NA"
label variable mv3b3d_5 "Disadvantages: Has side eff-NA"
label variable mv3b3e_5 "Disadvantages: Increases pr-NA"
label variable mv3b3f_5 "Disadvantages: Can cause st-NA"
label variable mv3b3g_5 "Disadvantages: Method can f-NA"
label variable mv3b3h_5 "Disadvantages: Baby in dang-NA"
label variable mv3b3i_5 "Disadvantages: Involves doc-NA"
label variable mv3b3j_5 "Disadvantages: Can lead to -NA"
label variable mv3b3k_5 "Disadvantages: Country spec-NA"
label variable mv3b3l_5 "Disadvantages: Country spec-NA"
label variable mv3b3m_5 "Disadvantages: Country spec-NA"
label variable mv3b3n_5 "Disadvantages: Country spec-NA"
label variable mv3b3x_5 "Disadvantages: Other       -NA"
label variable mv3b3z_5 "Disadvantages: Don't know  -NA"
label variable mv3b11   "Age at first use of condom -NA"
label variable mv3b12a  "Reason of first condom use:-NA"
label variable mv3b12b  "Reason of first condom use:-NA"
label variable mv3b12c  "Reason of first condom use:-NA"
label variable mv3b12d  "Reason of first condom use:-NA"
label variable mv3b12e  "Reason of first condom use:-NA"
label variable mv3b12f  "Reason of first condom use:-NA"
label variable mv3b12g  "Reason of first condom use:-NA"
label variable mv3b12h  "Reason of first condom use:-NA"
label variable mv3b12x  "Reason of first condom use:-NA"
label variable mv3b13   "Frequency of use of condom -NA"
label variable mv3b14a  "Timing of use: On partner's-NA"
label variable mv3b14b  "Timing of use: During partn-NA"
label variable mv3b14c  "Timing of use: When not usi-NA"
label variable mv3b14d  "Timing of use: With a stran-NA"
label variable mv3b14e  "Timing of use: With a comme-NA"
label variable mv3b14f  "Timing of use: With anyone -NA"
label variable mv3b14g  "Timing of use: With wife/re-NA"
label variable mv3b14h  "Timing of use: Country spec-NA"
label variable mv3b14i  "Timing of use: Country spec-NA"
label variable mv3b14j  "Timing of use: Country spec-NA"
label variable mv3b14x  "Timing of use: Other       -NA"
label variable mv3b15a  "Problems with condom: Too e-NA"
label variable mv3b15b  "Problems with condom: Embar-NA"
label variable mv3b15c  "Problems with condom: Diffi-NA"
label variable mv3b15d  "Problems with condom: Diffi-NA"
label variable mv3b15e  "Problems with condom: Spoil-NA"
label variable mv3b15f  "Problems with condom: Dimin-NA"
label variable mv3b15g  "Problems with condom: Wife/-NA"
label variable mv3b15h  "Problems with condom: Wife/-NA"
label variable mv3b15i  "Problems with condom: Incon-NA"
label variable mv3b15j  "Problems with condom: Condo-NA"
label variable mv3b15k  "Problems with condom: Count-NA"
label variable mv3b15l  "Problems with condom: Count-NA"
label variable mv3b15m  "Problems with condom: Count-NA"
label variable mv3b15x  "Problems with condom: Other-NA"
label variable mv3b15y  "Problems with condom: No pr-NA"
label variable mv3b16   "Brand of condom            -NA"
label variable mv3b17   "Source of condoms          -NA"
label variable mv3b18   "Cost of condom's packet    -NA"
label variable mv3b19   "Number of condom in each pa-NA"
label variable mv3b20   "Affordability of condoms   -NA"
label variable mv3b21a  "Diminish a man's sexual ple-NA"
label variable mv3b21b  "Inconvenient to use        -NA"
label variable mv3b21c  "Can be reused              -NA"
label variable mv3b21d  "Protects against disease   -NA"
label variable mv3b21e  "Women has no right to tell -NA"
label variable mv3b22   "Consider getting sterilized-NA"
label variable mv3b23a  "Benefits of male sterilizat-NA"
label variable mv3b23b  "Benefits of male sterilizat-NA"
label variable mv3b23c  "Benefits of male sterilizat-NA"
label variable mv3b23d  "Benefits of male sterilizat-NA"
label variable mv3b23e  "Benefits of male sterilizat-NA"
label variable mv3b23f  "Benefits of male sterilizat-NA"
label variable mv3b23g  "Benefits of male sterilizat-NA"
label variable mv3b23h  "Benefits of male sterilizat-NA"
label variable mv3b23i  "Benefits of male sterilizat-NA"
label variable mv3b23j  "Benefits of male sterilizat-NA"
label variable mv3b23k  "Benefits of male sterilizat-NA"
label variable mv3b23x  "Benefits of male sterilizat-NA"
label variable mv3b24a  "Reason never consider steri-NA"
label variable mv3b24b  "Reason never consider steri-NA"
label variable mv3b24c  "Reason never consider steri-NA"
label variable mv3b24d  "Reason never consider steri-NA"
label variable mv3b24e  "Reason never consider steri-NA"
label variable mv3b24f  "Reason never consider steri-NA"
label variable mv3b24g  "Reason never consider steri-NA"
label variable mv3b24h  "Reason never consider steri-NA"
label variable mv3b24i  "Reason never consider steri-NA"
label variable mv3b24j  "Reason never consider steri-NA"
label variable mv3b24k  "Reason never consider steri-NA"
label variable mv3b24l  "Reason never consider steri-NA"
label variable mv3b24x  "Reason never consider steri-NA"
label variable mv3b25a  "Contraception is woman's bu-NA"
label variable mv3b25b  "Sterilized women become pro-NA"
label variable mv3b25c  "To a man equivalent to bein-NA"
label variable mv3b25d  "Woman can get pregnant, so -NA"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv505    "Number of wives, partners"
label variable mv505a   "Number of wives"
label variable mv505b   "Number of live-in partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse"
label variable mv527    "Time since last intercourse"
label variable mv531    "Age at first intercourse (imp)"
label variable mv532    "Flag for MV531"
label variable mv534    "Have a regular sex partner"
label variable mv534a   "One or more regular partner-NA"
label variable mv535    "Have ever been married"
label variable mv536    "Recent sexual activity"
label variable mv538    "Total wives, partners ever -NA"
label variable mv539    "Other regular sexual partne-NA"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv610    "Wife approves FP           -NA"
label variable mv611    "Discussed FP with partner  -NA"
label variable mv612    "Respondent approves FP"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "Wifes desire for children  -NA"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv630a   "Discussed FP with partner  -NA"
label variable mv630b   "Discussed FP with mother   -NA"
label variable mv630c   "Discussed FP with father   -NA"
label variable mv630d   "Discussed FP with sister(s)-NA"
label variable mv630e   "Discussed FP with brother(s-NA"
label variable mv630f   "Discussed FP with daughter(-NA"
label variable mv630g   "Discussed FP with mother-in-NA"
label variable mv630h   "Discussed FP with friends/n-NA"
label variable mv630i   "Discussed FP with son(s)   -NA"
label variable mv630j   "Discussed FP with father-in-NA"
label variable mv630k   "Discussed FP -country speci-NA"
label variable mv630l   "Discussed FP -country speci-NA"
label variable mv630m   "Discussed FP -country speci-NA"
label variable mv630n   "Discussed FP -country speci-NA"
label variable mv630o   "Discussed FP -country speci-NA"
label variable mv630x   "Discussed FP with others   -NA"
label variable mv631    "Problem if became pregnant -NA"
label variable mv633a   "Reason for not having sex: -NA"
label variable mv633b   "Reason for not having sex: -NA"
label variable mv633c   "Reason for not having sex: -NA"
label variable mv633d   "Reason for not having sex: -NA"
label variable mv633e   "Reason for not having sex: -NA"
label variable mv633f   "Reason for not having sex: -NA"
label variable mv633g   "Reason for not having sex: -NA"
label variable mv634a   "Husband has right to: get a-NA"
label variable mv634b   "Husband has right to: refus-NA"
label variable mv634c   "Husband has right to: use f-NA"
label variable mv634d   "Husband has right to: have -NA"
label variable mv635    "Wife number would prefer ne-NA"
label variable mv636    "Planning to have children w-NA"
label variable mv637    "Plan to take another wife  -NA"
label variable mv638    "Main reason may take anothe-NA"
label variable mv640_1  "Sequence number of partners-NA"
label variable mv641_1  "Line number of wive/partner-NA"
label variable mv642_1  "Partner currently pregnant -NA"
label variable mv643_1  "Current pregnancy wanted   -NA"
label variable mv644_1  "Problem if became pregnant -NA"
label variable mv645_1  "Wifes desire for children  -NA"
label variable mv646_1  "Discussed FP with partner  -NA"
label variable mv647_1  "Wife approves FP           -NA"
label variable mv640_2  "Sequence number of partners-NA"
label variable mv641_2  "Line number of wive/partner-NA"
label variable mv642_2  "Partner currently pregnant -NA"
label variable mv643_2  "Current pregnancy wanted   -NA"
label variable mv644_2  "Problem if became pregnant -NA"
label variable mv645_2  "Wifes desire for children  -NA"
label variable mv646_2  "Discussed FP with partner  -NA"
label variable mv647_2  "Wife approves FP           -NA"
label variable mv640_3  "Sequence number of partners-NA"
label variable mv641_3  "Line number of wive/partner-NA"
label variable mv642_3  "Partner currently pregnant -NA"
label variable mv643_3  "Current pregnancy wanted   -NA"
label variable mv644_3  "Problem if became pregnant -NA"
label variable mv645_3  "Wifes desire for children  -NA"
label variable mv646_3  "Discussed FP with partner  -NA"
label variable mv647_3  "Wife approves FP           -NA"
label variable mv640_4  "Sequence number of partners-NA"
label variable mv641_4  "Line number of wive/partner-NA"
label variable mv642_4  "Partner currently pregnant -NA"
label variable mv643_4  "Current pregnancy wanted   -NA"
label variable mv644_4  "Problem if became pregnant -NA"
label variable mv645_4  "Wifes desire for children  -NA"
label variable mv646_4  "Discussed FP with partner  -NA"
label variable mv647_4  "Wife approves FP           -NA"
label variable mv640_5  "Sequence number of partners-NA"
label variable mv641_5  "Line number of wive/partner-NA"
label variable mv642_5  "Partner currently pregnant -NA"
label variable mv643_5  "Current pregnancy wanted   -NA"
label variable mv644_5  "Problem if became pregnant -NA"
label variable mv645_5  "Wifes desire for children  -NA"
label variable mv646_5  "Discussed FP with partner  -NA"
label variable mv647_5  "Wife approves FP           -NA"
label variable mv640_6  "Sequence number of partners-NA"
label variable mv641_6  "Line number of wive/partner-NA"
label variable mv642_6  "Partner currently pregnant -NA"
label variable mv643_6  "Current pregnancy wanted   -NA"
label variable mv644_6  "Problem if became pregnant -NA"
label variable mv645_6  "Wifes desire for children  -NA"
label variable mv646_6  "Discussed FP with partner  -NA"
label variable mv647_6  "Wife approves FP           -NA"
label variable mv640_7  "Sequence number of partners-NA"
label variable mv641_7  "Line number of wive/partner-NA"
label variable mv642_7  "Partner currently pregnant -NA"
label variable mv643_7  "Current pregnancy wanted   -NA"
label variable mv644_7  "Problem if became pregnant -NA"
label variable mv645_7  "Wifes desire for children  -NA"
label variable mv646_7  "Discussed FP with partner  -NA"
label variable mv647_7  "Wife approves FP           -NA"
label variable mv640_8  "Sequence number of partners-NA"
label variable mv641_8  "Line number of wive/partner-NA"
label variable mv642_8  "Partner currently pregnant -NA"
label variable mv643_8  "Current pregnancy wanted   -NA"
label variable mv644_8  "Problem if became pregnant -NA"
label variable mv645_8  "Wifes desire for children  -NA"
label variable mv646_8  "Discussed FP with partner  -NA"
label variable mv647_8  "Wife approves FP           -NA"
label variable mv648    "Discussed FP with health wo-NA"
label variable mv649a   "Interest in avoiding unwant-NA"
label variable mv649b   "Interest in helping partner-NA"
label variable mv649c   "Interest in helping care fo-NA"
label variable mv714    "Respondent currently working"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, se-NA"
label variable mv721    "Works at home or away      -NA"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasona-NA"
label variable mv733    "Months worked in last 12 mo-NA"
label variable mv740    "Type of land where resp. wo-NA"
label variable mv741    "Type of earnings for work  -NA"
label variable mv742    "Portion of household expend-NA"
label variable mv743a   "Final say on own health car-NA"
label variable mv743b   "Final say on making large h-NA"
label variable mv743c   "Final say on making househo-NA"
label variable mv743d   "Final say on visits to fami-NA"
label variable mv743e   "Final say on food to be coo-NA"
label variable mv743f   "Final say on deciding what -NA"
label variable mv743g   "Final say on deciding how m-NA"
label variable mv744a   "Wife beating justified if she goes out without telling him"
label variable mv744b   "Wife beating justified if she neglects the children"
label variable mv744c   "Wife beating justified if she argues with him"
label variable mv744d   "Wife beating justified if she refuses to have sex with him"
label variable mv744e   "Wife beating justified if she burns the food"
label variable mv745    "Activity last 12 months    -NA"
label variable mv750    "Heard sexual transmit. disease"
label variable mv751    "Ever heard of AIDS"
label variable mv753    "Ways to avoid AIDS"
label variable mv754a   "AIDS: Safe sex             -NA"
label variable mv754b   "AIDS: abstain from sex"
label variable mv754c   "AIDS: use condoms during sex"
label variable mv754d   "AIDS: only one sex partner"
label variable mv754e   "AIDS: avoid sex prostitutes"
label variable mv754f   "AIDS: avoid sex homosexuals"
label variable mv754g   "AIDS: avoid blood transfusions"
label variable mv754h   "AIDS: avoid injections"
label variable mv754i   "AIDS: avoid kissing"
label variable mv754j   "AIDS: avoid mosquito bites"
label variable mv754k   "AIDS: protection trad. healer"
label variable mv754l   "AIDS: Limit number of sex partners"
label variable mv754m   "AIDS: Avoid partners who have many partners"
label variable mv754n   "AIDS: Avoid sex with intravenous drug users"
label variable mv754o   "AIDS: avoid sharing razor blades with AIDS patient"
label variable mv754p   "AIDS: Avoid sharing household utensils"
label variable mv754q   "AIDS: country specific     -NA"
label variable mv754r   "AIDS: country specific     -NA"
label variable mv754s   "AIDS: country specific     -NA"
label variable mv754t   "AIDS: country specific     -NA"
label variable mv754u   "AIDS: country specific     -NA"
label variable mv754v   "AIDS: country specific     -NA"
label variable mv754x   "AIDS: other responses"
label variable mv754z   "AIDS: DK ways to avoid AIDS"
label variable mv754cp  "Reduce chances of AIDS by always using condoms during sex"
label variable mv754dp  "Reduce chance of AIDS: have 1 sex partner with no oth partnr"
label variable mv754jp  "Get AIDS from mosquito bite-NA"
label variable mv754wp  "Get AIDS by sharing food wi-NA"
label variable mv756    "Can a healthy person have AIDS"
label variable mv759a   "Acceptable to discuss AIDS -NA"
label variable mv759b   "Acceptable to discuss AIDS -NA"
label variable mv759c   "Acceptable to discuss AIDS -NA"
label variable mv759d   "Acceptable to discuss AIDS:-NA"
label variable mv759e   "Acceptable to discuss AIDS:-NA"
label variable mv759f   "Acceptable to discuss AIDS:-NA"
label variable mv759g   "Acceptable to discuss AIDS:-NA"
label variable mv759h   "Acceptable to discuss AIDS:-NA"
label variable mv759i   "Acceptable to discuss AIDS:-NA"
label variable mv761    "Last intercourse used condom"
label variable mv761b   "Intercourse with other woman (1) used condom"
label variable mv761c   "Intercourse with other woma-NA"
label variable mv761d   "Intercourse for money used condom"
label variable mv762aa  "Source for condoms: Governm-NA"
label variable mv762ab  "Source for condoms: Governm-NA"
label variable mv762ac  "Source for condoms: Family -NA"
label variable mv762ad  "Source for condoms: Mobile -NA"
label variable mv762ae  "Source for condoms: Public -NA"
label variable mv762af  "Source for condoms: Other p-NA"
label variable mv762ag  "Source for condoms: Public -NA"
label variable mv762ah  "Source for condoms: Public -NA"
label variable mv762ai  "Source for condoms: Public -NA"
label variable mv762aj  "Source for condoms: Private-NA"
label variable mv762ak  "Source for condoms: Pharmac-NA"
label variable mv762al  "Source for condoms: Private-NA"
label variable mv762am  "Source for condoms: Private-NA"
label variable mv762an  "Source for condoms: Private-NA"
label variable mv762ao  "Source for condoms: Other p-NA"
label variable mv762ap  "Source for condoms: Private-NA"
label variable mv762aq  "Source for condoms: Private-NA"
label variable mv762ar  "Source for condoms: Private-NA"
label variable mv762as  "Source for condoms: Shop   -NA"
label variable mv762at  "Source for condoms: Church -NA"
label variable mv762au  "Source for condoms: Friends-NA"
label variable mv762av  "Source for condoms: CS     -NA"
label variable mv762aw  "Source for condoms: CS     -NA"
label variable mv762ax  "Source for condoms: Other  -NA"
label variable mv762az  "Source for condoms: DK sour-NA"
label variable mv762ba  "Source for female condoms: -NA"
label variable mv762bb  "Source for female condoms: -NA"
label variable mv762bc  "Source for female condoms: -NA"
label variable mv762bd  "Source for female condoms: -NA"
label variable mv762be  "Source for female condoms: -NA"
label variable mv762bf  "Source for female condoms: -NA"
label variable mv762bg  "Source for female condoms: -NA"
label variable mv762bh  "Source for female condoms: -NA"
label variable mv762bi  "Source for female condoms: -NA"
label variable mv762bj  "Source for female condoms: -NA"
label variable mv762bk  "Source for female condoms: -NA"
label variable mv762bl  "Source for female condoms: -NA"
label variable mv762bm  "Source for female condoms: -NA"
label variable mv762bn  "Source for female condoms: -NA"
label variable mv762bo  "Source for female condoms: -NA"
label variable mv762bp  "Source for female condoms: -NA"
label variable mv762bq  "Source for female condoms: -NA"
label variable mv762br  "Source for female condoms: -NA"
label variable mv762bs  "Source for female condoms: -NA"
label variable mv762bt  "Source for female condoms: -NA"
label variable mv762bu  "Source for female condoms: -NA"
label variable mv762bv  "Source for female condoms: -NA"
label variable mv762bw  "Source for female condoms: -NA"
label variable mv762bx  "Source for female condoms: -NA"
label variable mv762bz  "Source for female condoms: -NA"
label variable mv763a   "Had any STD in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "Last 12 months had CS STD  -NA"
label variable mv763e   "Last 12 months had CS STD  -NA"
label variable mv763f   "Last 12 months had CS STD  -NA"
label variable mv763g   "Past 12 months had CS STD  -NA"
label variable mv765a   "Last sex reason used a condom"
label variable mv765b   "Sex with other woman (1) reason used a condom"
label variable mv765c   "Sex with other woman (2) re-NA"
label variable mv766a   "No. other than wife had sex in last 12 months"
label variable mv766b   "No. had sex including wife in last 12 months"
label variable mv767a   "Relationship with last sex partner"
label variable mv767b   "Relationship with other sex partner (1)"
label variable mv767c   "Relationship with other sex-NA"
label variable mv768a   "Length of time knows last partner"
label variable mv768b   "Length of time knows other partner (1)"
label variable mv768c   "Length of time knows other -NA"
label variable mv769    "Could get a condom         -NA"
label variable mv769a   "Could get a female condom  -NA"
label variable mv770    "Seek advice for last disease"
label variable mv770a   "Seek advise: clinic/hospital/private doctor"
label variable mv770b   "Seek advise: traditional he-NA"
label variable mv770c   "Seek advise: Shop/pharmacy"
label variable mv770d   "Seek advise: Friends/relati-NA"
label variable mv770e   "Seek advise: CS            -NA"
label variable mv770f   "Seek advise: CS            -NA"
label variable mv770g   "Seek advise: CS            -NA"
label variable mv770h   "Seek advise: CS            -NA"
label variable mv770i   "Seek advise: CS            -NA"
label variable mv771    "Advise partner when had disease"
label variable mv772    "Tried to avoid infecting partner"
label variable mv773a   "What done: no sexual intercourse"
label variable mv773b   "What done: used condoms"
label variable mv773c   "What done: took medicines  -NA"
label variable mv773d   "What done: CS : wash penis before sex"
label variable mv773e   "What done: CS: reduce frequency of sexual intercourse"
label variable mv773f   "What done: country specific-NA"
label variable mv773x   "What done: other"
label variable mv774    "AIDS transmitted from mother to child"
label variable mv774a   "AIDS transmit. during pregnancy"
label variable mv774b   "AIDS transmit. during delivery"
label variable mv774c   "AIDS transmit. by breastfeeding"
label variable mv775    "Knows someone who has or died of AIDS"
label variable mv776    "Spoken with spouse about avoiding AIDS"
label variable mv777    "Allowed to keep AIDS infection secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "Person with AIDS allowed to-NA"
label variable mv780    "Should children be taught a-NA"
label variable mv781    "Ever been tested for AIDS"
label variable mv782    "Want to be tested for AIDS"
label variable mv783    "Know a place to get AIDS te-NA"
label variable mv784    "Where to get an AIDS test  -NA"
label variable mv785    "Heard about other STDs"
label variable mv785a   "Man's symptoms of STI"
label variable mv785b   "Man's symptoms of STI"
label variable mv785c   "Man's symptoms of STI"
label variable mv785d   "Man's symptoms of STI"
label variable mv785e   "Man's symptoms of STI"
label variable mv785f   "Man's symptoms of STI"
label variable mv785g   "Man's symptoms of STI"
label variable mv785h   "Man's symptoms of STI"
label variable mv785i   "Man's symptoms of STI      -NA"
label variable mv785j   "Man's symptoms of STI"
label variable mv785k   "Man's symptoms of STI"
label variable mv785l   "Man's symptoms of STI"
label variable mv785m   "Man's symptoms of STI: backpain"
label variable mv785n   "Man's symptoms of STI: problems walking"
label variable mv785o   "Man's symptoms of STI: sores / warts on face"
label variable mv785p   "Man's symptoms of STI: sores / warts on body"
label variable mv785q   "Man's symptoms of STI      -NA"
label variable mv785x   "Man's symptoms of STI"
label variable mv785y   "Man's symptoms of STI"
label variable mv785z   "Man's symptoms of STI"
label variable mv786a   "Woman's symptoms of STI"
label variable mv786b   "Woman's symptoms of STI"
label variable mv786c   "Woman's symptoms of STI"
label variable mv786d   "Woman's symptoms of STI"
label variable mv786e   "Woman's symptoms of STI"
label variable mv786f   "Woman's symptoms of STI"
label variable mv786g   "Woman's symptoms of STI"
label variable mv786h   "Woman's symptoms of STI"
label variable mv786i   "Woman's symptoms of STI    -NA"
label variable mv786j   "Woman's symptoms of STI"
label variable mv786k   "Woman's symptoms of STI"
label variable mv786l   "Woman's symptoms of STI"
label variable mv786m   "Woman's symptoms of STI: backpain"
label variable mv786n   "Woman's symptoms of STI: problems walking"
label variable mv786o   "Woman's symptoms of STI: sores / warts on face"
label variable mv786p   "Woman's symptoms of STI: sores /warts on body"
label variable mv786q   "Woman's symptoms of STI    -NA"
label variable mv786x   "Woman's symptoms of STI"
label variable mv786y   "Woman's symptoms of STI"
label variable mv786z   "Woman's symptoms of STI"
label variable mv787    "Number of days drunk alcoho-NA"
label variable mv788    "Number of days gotten drunk-NA"
label variable mv789    "Number of injections in las-NA"
label variable mv790    "Person who gave last inject-NA"
label variable mv791    "Ever paid for sex"
label variable mv792    "Time since last paid for sex"
label variable smintdg  "Day of interview - gregorian calendar"
label variable smintmg  "Month of interview - gregorian calendar"
label variable smintyg  "Year of interview - gregorian calendar"
label variable smintcg  "Date of interview (CMC) - gregorian calendar"
label variable smlan    "Language of questionnaire"
label variable smintv   "Interview language"
label variable smresp   "Respondent's language"
label variable smtrans  "Translator used"
label variable sm101t   "Start of interview: time of day"
label variable sm101h   "Start of interview (hour)"
label variable sm101m   "Start of interview (minutes)"
label variable sm105mg  "Month of birth - gregorian calendar"
label variable sm105yg  "Year of birth - gregorian calendar"
label variable sm105cg  "Date of birth (CMC) - gregorian calendar"
label variable sm109    "Highest grade at that level"
label variable sm203    "Children at home"
label variable sm205    "Children away"
label variable sm207    "Children who have died"
label variable sm211m   "Month of birth of last child (EThiopian calendar)"
label variable sm211y   "Year of birth of last child (Ethiopian calendar)"
label variable sm211c   "CMC - Month of birth of last child (Ethiopian calendar)"
label variable sm211mg  "Month of birth of last child - gregorian calendar"
label variable sm211yg  "Year of birth of last child - gregorian calendar"
label variable sm211cg  "CMC - Month of birth of last child - gregorian calendar"
label variable sm214    "How much longer would have waited (number)"
label variable sm309    "Brand of condoms"
label variable sm310    "Use more condoms than a year ago"
label variable sm311    "Main reason using more condoms"
label variable sm312    "Main reason not using a method"
label variable sm410mg  "Date of first union (month) (gregorian calendar)"
label variable sm410yg  "Date of first union (year) (Gregorian calendar)"
label variable sm410cg  "Date of first union (CMC) - gregorian calendar"
label variable sm411c   "Age at first union(calculated)"
label variable sm512d   "Saw FP on pamphlet or poster last months"
label variable sm512e   "Heard FP comminity events last few months"
label variable sm518a   "Presence of children < 10"
label variable sm518b   "Presence of spouse"
label variable sm518c   "Presence of other males"
label variable sm518d   "Presence of other females"
label variable sm606a   "Method used during last intercourse: female sterilization"
label variable sm606b   "Method used during last intercourse: male sterilization"
label variable sm606c   "Method used during last intercourse: pill"
label variable sm606d   "Method used during last intercourse: IUD"
label variable sm606e   "Method used during last intercourse: injections"
label variable sm606f   "Method used during last intercourse: implants"
label variable sm606g   "Method used during last intercourse: condom"
label variable sm606h   "Method used during last intercourse: periodic abstinence"
label variable sm606i   "Method used during last intercourse: periodic abstinence"
label variable sm606j   "Method used during last intercourse: withdrawal"
label variable sm606x   "Method used during last intercourse: other"
label variable sm613a   "Method last sex with 'other' woman: female sterilization"
label variable sm613b   "Method last sex with 'other' woman: male sterilization"
label variable sm613c   "Method last sex with 'other' woman: pill"
label variable sm613d   "Method last sex with 'other' woman: IUD"
label variable sm613e   "Method last sex with 'other' woman: injections"
label variable sm613f   "Method last sex with 'other' woman: implants"
label variable sm613g   "Method last sex with 'other' woman: condom"
label variable sm613h   "Method last sex with 'other' woman: diaphragm/foam/jelly"
label variable sm613i   "Method last sex with 'other' woman: periodic abstinence"
label variable sm613j   "Method last sex with 'other' woman: withdrawal"
label variable sm613x   "Method last sex with 'other' woman: other"
label variable sm701aa  "From which source heard of AIDS - Radio"
label variable sm701ab  "From which source heard of AIDS - Television"
label variable sm701ac  "From which source heard of AIDS - Newspapers/magazines"
label variable sm701ad  "From which source heard of AIDS - Pamphlets/posters"
label variable sm701ae  "From which source heard of AIDS - Health workers"
label variable sm701af  "From which source heard of AIDS - Mosques/churches"
label variable sm701ag  "From which source heard of AIDS - Schools/teachers"
label variable sm701ah  "From which source heard of AIDS - Community event"
label variable sm701ai  "From which source heard of AIDS - Friends/relatives"
label variable sm701aj  "From which source heard of AIDS - Work place"
label variable sm701ak  "From which source heard of AIDS - Drama/performance"
label variable sm701ax  "From which source heard of AIDS - Other"
label variable sm705    "Number of partners and chance of getting AIDS"
label variable sm708    "Use of condoms and chances of getting AIDS"
label variable sm712a   "Aids transm. from mother to child: during pregnancy"
label variable sm712b   "Aids transm. from mother to child: at delivery"
label variable sm712c   "Aids transm. from mother to child: during breastfeeding"
label variable sm712d   "Aids transm. from mother to child: other times"
label variable sm712z   "Aids transm. from mother to child: Don't know"
label variable sm733    "Where sought treatment"
label variable sm736t   "Timing of interview"
label variable sm736h   "End of interview (hour)"
label variable sm736m   "End of interview (minutes)"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
     9 "Missing"
;
label define MV023   
     1 "Tigray, urban"
     2 "Tigray, rural"
     3 "Afar, urban"
     4 "Afar, rural"
     5 "Amhara, urban"
     6 "Amhara, rural"
     7 "Oromiya, urban"
     8 "Oromiya, rural"
     9 "Somali, urban"
    10 "Somali, rural"
    11 "Ben-Gumz, urban"
    12 "Ben-Gumz, rural"
    13 "SNNP, urban"
    14 "SNNP, rural"
    15 "Gambela, urban"
    16 "Gambela, rural"
    17 "Harrari, urban"
    18 "Harrari, rural"
    19 "Addis, urban"
    20 "Dire Dawa, urban"
    21 "Dire Dawa, rural"
;
label define MV024   
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harrari"
    14 "Addis"
    15 "Dire Dawa"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV034   
     0 "Wife not in HH"
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
     9 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
    99 "Missing"
;
label define MV101   
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harrari"
    14 "Addis"
    15 "Dire Dawa"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;
label define MV130   
     1 "Orthodox"
     2 "Catholic"
     3 "Protestant"
     4 "Moslem"
     5 "Traditional"
     6 "Other"
     9 "Missing"
;
label define MV131   
     1 "Affar"
     4 "Amharra"
    25 "Guragie"
    60 "Oromo"
    67 "Sidama"
    68 "Somalie"
    70 "Tigray (Tigraway)"
    72 "Welaita"
    96 "Other"
;
label define MV133   
    97 "Inconsistent"
    99 "Missing"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
     9 "Missing"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     9 "Missing"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "DK"
    99 "Missing"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     9 "Missing"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
     9 "Missing"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
     9 "Missing"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
     9 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
     9 "Missing"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
     9 "Missing"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     8 "Not asked"
     9 "Missing"
;
label define MV305   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV307   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
    99 "Missing"
;
label define MV312A  
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
    99 "Missing"
;
label define MV312B  
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
    99 "Missing"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
     9 "Missing"
;
label define MV313A  
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
     9 "Missing"
;
label define MV313B  
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
     9 "Missing"
;
label define MV361   
     1 "Currently using"
     2 "Used in last 12 months"
     3 "Ever used"
     4 "Never used"
;
label define MV362   
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
     9 "Missing"
;
label define MV364   
     1 "Using modern method"
     2 "Using traditional method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define MV367   
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
     9 "Missing"
;
label define MV376   
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV384A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     9 "Missing"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
     9 "Missing"
;
label define MV503   
     1 "Once"
     2 "More than once"
     9 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV531   
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV534   
     0 "No sexual partner"
     1 "Regular sexual partner"
     2 "Occasional sexual partner"
     9 "Missing"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Lived with a woman"
     9 "Missing"
;
label define MV536   
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
     9 "Missing"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infecund"
     6 "Never had sex"
     7 "Man declared infecund"
     9 "Missing"
;
label define MV603   
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
     9 "Missing"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
     9 "Missing"
;
label define MV612   
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define MV613   
    95 "As God wishes"
    96 "Non-numeric response"
    98 "DK"
    99 "Missing"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
   999 "Missing"
;
label define MV627   
    95 "As God wishes"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV628   
    95 "As God wishes"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV629   
    95 "As God wishes"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV641   
     0 "Wife not in HH"
    99 "Missing"
;
label define MV714   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV716   
     0 "Student, pensioners"
    11 "Legislators and senior officials"
    12 "Corporate managers"
    13 "Other general managers"
    21 "Physical, mathemat., engineering science prof."
    22 "Life science and health prof."
    23 "Teaching professionals"
    24 "Other assoc. professionals"
    31 "Physical and engineering science ass. prof."
    32 "Life science and health assoc. prof."
    33 "Teaching assoc. prof."
    34 "Other assoc. prof."
    41 "Office clerks"
    42 "Customer service clerk"
    51 "Personal and protective service workers"
    52 "Models, sales persons and demonstrators"
    61 "Market oriented skilled agric. and fisher workers"
    62 "Subsistence agric. and fisher workers"
    71 "Extraction and building trade workers"
    72 "Metal, machin. and rel. trade workers"
    73 "Precision, handicraft, printing and rel. workers"
    74 "Other craft and related trade workers"
    81 "Stationary plant and related workers"
    82 "Machine operators and assemblers"
    83 "Drivers and Mobil plant operators"
    91 "Sales and service elementary occupation"
    92 "Agric. and fishery and rel. workers"
    93 "Labourers in mining, construction, manuf. and transport"
    96 "Other"
   999 "Missing"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
     9 "Missing"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV751   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV753   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV754B  
     0 "No"
     1 "Abstain from sex"
     8 "DK"
     9 "Missing"
;
label define MV754C  
     0 "No"
     1 "Condoms during sex"
     8 "DK"
     9 "Missing"
;
label define MV754D  
     0 "No"
     1 "Only one sex partner"
     8 "DK"
     9 "Missing"
;
label define MV754E  
     0 "No"
     1 "Avoid prostitutes"
     8 "DK"
     9 "Missing"
;
label define MV754F  
     0 "No"
     1 "Avoid homosexuals"
     8 "DK"
     9 "Missing"
;
label define MV754G  
     0 "No"
     1 "Avoid blood transfus"
     8 "DK"
     9 "Missing"
;
label define MV754H  
     0 "No"
     1 "Avoid injections"
     8 "DK"
     9 "Missing"
;
label define MV754I  
     0 "No"
     1 "Avoid kissing"
     8 "DK"
     9 "Missing"
;
label define MV754J  
     0 "No"
     1 "Avoid mosquito bites"
     8 "DK"
     9 "Missing"
;
label define MV754K  
     0 "No"
     1 "Seek trad. healing"
     8 "DK"
     9 "Missing"
;
label define MV754L  
     0 "No"
     1 "Limit number of sex partners"
     8 "DK"
     9 "Missing"
;
label define MV754M  
     0 "No"
     1 "Avoid partners who have many partners"
     8 "DK"
     9 "Missing"
;
label define MV754N  
     0 "No"
     1 "Avoid sex with intravenous drug users"
     8 "DK"
     9 "Missing"
;
label define MV754O  
     0 "No"
     1 "Avoid sharing razor blades with AIDS patient"
     8 "DK"
     9 "Missing"
;
label define MV754P  
     0 "No"
     1 "Avoid sharing household utensils"
     8 "DK"
     9 "Missing"
;
label define MV754X  
     0 "No"
     1 "Other responses"
     8 "DK"
     9 "Missing"
;
label define MV754Z  
     0 "No: knows ways"
     1 "Yes: DK ways"
     9 "Missing"
;
label define MV754CP 
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
     9 "Missing"
;
label define MV754DP 
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partnr with no oth partner"
     8 "Don't know"
     9 "Missing"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV761D  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV765A  
     0 "Did not use condom"
     1 "To prevent STD"
     2 "To avoid pregnancy"
     3 "Avoid both STD and pregnancy"
     4 "Does not trust partner"
     5 "Partner requested/insisted"
     6 "Other"
     8 "Don't know"
     9 "Missing"
;
label define MV765B  
     0 "Did not use condom"
     1 "To prevent STD"
     2 "To avoid pregnancy"
     3 "Avoid both STD and pregnancy"
     4 "Does not trust partner"
     5 "Partner requested/insisted"
     6 "Other"
     8 "Don't know"
     9 "Missing"
;
label define MV766A  
    98 "DK"
    99 "Missing"
;
label define MV766B  
    98 "DK"
    99 "Missing"
;
label define MV767A  
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
    96 "Other"
    99 "Missing"
;
label define MV767B  
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
    96 "Other"
    99 "Missing"
;
label define MV768A  
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
   999 "Missing"
;
label define MV768B  
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
   999 "Missing"
;
label define MV770   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV770A  
     0 "No"
     1 "Clinic/hospital/private doctor"
     9 "Missing"
;
label define MV770C  
     0 "No"
     1 "Shop/pharmacy"
     9 "Missing"
;
label define MV771   
     0 "No"
     1 "Yes"
     2 "Some/not all"
     3 "No partner"
     9 "Missing"
;
label define MV772   
     0 "No"
     1 "Yes"
     2 "Partner already infect"
     3 "Not having sex at the time"
     9 "Missing"
;
label define MV773A  
     0 "No"
     1 "No sexual intercourse"
     2 "Partner already infected"
     3 "Not having sex at the time"
     9 "Missing"
;
label define MV773B  
     0 "No"
     1 "Used condoms"
     2 "Partner already infected"
     3 "Not having sex at the time"
     9 "Missing"
;
label define MV773D  
     0 "No"
     1 "CS: wash penis before sex"
     2 "Partner already infected"
     3 "Not having sex at the time"
     9 "Missing"
;
label define MV773E  
     0 "No"
     1 "CS: Reduce frequency of sexual intercourse"
     2 "Partner already infected"
     3 "Not having sex at the time"
     9 "Missing"
;
label define MV773X  
     0 "No"
     1 "Other"
     9 "Missing"
;
label define MV774   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV776   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV781   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV782   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MV785   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV785A  
     0 "No"
     1 "Abdominal pain"
     9 "Missing"
;
label define MV785B  
     0 "No"
     1 "Genital discharge/dripping"
     9 "Missing"
;
label define MV785C  
     0 "No"
     1 "Foul smelling discharge"
     9 "Missing"
;
label define MV785D  
     0 "No"
     1 "Burning pain during urination"
     9 "Missing"
;
label define MV785E  
     0 "No"
     1 "Redness/inflamation"
     9 "Missing"
;
label define MV785F  
     0 "No"
     1 "Swelling"
     9 "Missing"
;
label define MV785G  
     0 "No"
     1 "Sores/ulcers"
     9 "Missing"
;
label define MV785H  
     0 "No"
     1 "Warts"
     9 "Missing"
;
label define MV785J  
     0 "No"
     1 "Blood in urine"
     9 "Missing"
;
label define MV785K  
     0 "No"
     1 "Weight loss"
     9 "Missing"
;
label define MV785L  
     0 "No"
     1 "Impotence"
     9 "Missing"
;
label define MV785M  
     0 "No"
     1 "Backpain"
     9 "Missing"
;
label define MV785N  
     0 "No"
     1 "Problems walking"
     9 "Missing"
;
label define MV785O  
     0 "No"
     1 "Sores / warts on face"
     9 "Missing"
;
label define MV785P  
     0 "No"
     1 "Sores / warts on body"
     9 "Missing"
;
label define MV785X  
     0 "No"
     1 "Other"
     9 "Missing"
;
label define MV785Y  
     0 "Yes, has symptoms"
     1 "No symptoms"
     9 "Missing"
;
label define MV785Z  
     0 "Knows symptoms"
     1 "Don't know symptoms"
     9 "Missing"
;
label define MV786A  
     0 "No"
     1 "Abdominal pain"
     9 "Missing"
;
label define MV786B  
     0 "No"
     1 "Genital discharge"
     9 "Missing"
;
label define MV786C  
     0 "No"
     1 "Foul smelling discharge"
     9 "Missing"
;
label define MV786D  
     0 "No"
     1 "Buring pain during urination"
     9 "Missing"
;
label define MV786E  
     0 "No"
     1 "Redness/inflamation"
     9 "Missing"
;
label define MV786F  
     0 "No"
     1 "Swelling"
     9 "Missing"
;
label define MV786G  
     0 "No"
     1 "Sores/ulcers"
     9 "Missing"
;
label define MV786H  
     0 "No"
     1 "Warts"
     9 "Missing"
;
label define MV786J  
     0 "No"
     1 "Blood in urine"
     9 "Missing"
;
label define MV786K  
     0 "No"
     1 "Weight loss"
     9 "Missing"
;
label define MV786L  
     0 "No"
     1 "Hard to get pregnant"
     9 "Missing"
;
label define MV786M  
     0 "No"
     1 "Backpain"
     9 "Missing"
;
label define MV786N  
     0 "No"
     1 "Problems walking"
     9 "Missing"
;
label define MV786O  
     0 "No"
     1 "Sores / warts on face"
     9 "Missing"
;
label define MV786P  
     0 "No"
     1 "Sores / warts on body"
     9 "Missing"
;
label define MV786X  
     0 "No"
     1 "Other"
     9 "Missing"
;
label define MV786Y  
     0 "Yes has symptoms"
     1 "No symptoms"
     9 "Missing"
;
label define MV786Z  
     0 "Knows symptoms"
     1 "Don't know symptoms"
     9 "Missing"
;
label define MV791   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV792   
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
   998 "Don't know"
   999 "Missing"
;
label define SMLAN   
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
     9 "Missing"
;
label define SMINTV  
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
     9 "Missing"
;
label define SMRESP  
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
     9 "Missing"
;
label define SMTRANS 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM101T  
     1 "Morning"
     2 "Evening"
     9 "Missing"
;
label define SM101H  
    97 "Inconsistent"
    99 "Missing"
;
label define SM101M  
    97 "Inconsistent"
    99 "Missing"
;
label define SM105MG 
    97 "Inconsistent"
    98 "DK month"
    99 "Missing"
;
label define SM105YG 
  9997 "Inconsistent"
  9998 "DK year"
  9999 "Missing"
;
label define SM211M  
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM211Y  
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SM211MG 
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define SM211YG 
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define SM214   
   101 "1 month"
   201 "1 year"
   998 "DK"
   999 "Missing"
;
label define SM309   
     1 "Hiwot"
     2 "Sensations"
     3 "Durex"
     4 "Rose"
    95 "No brand name"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define SM310   
     1 "More"
     2 "Same"
     3 "Fewer"
     9 "Missing"
;
label define SM311   
     1 "Fear of getting AIDS"
     2 "Fear of getting other STD's"
     3 "Family planning"
     4 "Less expensive now"
     5 "More available now"
     6 "Increased sexual activity"
     7 "Other"
     8 "DK"
     9 "Missing"
;
label define SM312   
    11 "Not married"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    41 "Knows no method"
    42 "Knows no source"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define SM410MG 
    97 "Inconsistent"
    98 "DK month"
    99 "Missing"
;
label define SM410YG 
  9997 "Inconsistent"
  9998 "DK year"
  9999 "Missing"
;
label define SM512D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM512E  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM518A  
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
     9 "Missing"
;
label define SM518B  
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
     9 "Missing"
;
label define SM518C  
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
     9 "Missing"
;
label define SM518D  
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
     9 "Missing"
;
label define SM606A  
     0 "No"
     1 "Method used: female sterilization"
     8 "Don't know"
     9 "Missing"
;
label define SM606B  
     0 "No"
     1 "Method used: male sterilization"
     8 "Don't know"
     9 "Missing"
;
label define SM606C  
     0 "No"
     1 "Method used: pill"
     8 "Don't know"
     9 "Missing"
;
label define SM606D  
     0 "No"
     1 "Method used: IUD"
     8 "Don't know"
     9 "Missing"
;
label define SM606E  
     0 "No"
     1 "Method used: injections"
     8 "Don't know"
     9 "Missing"
;
label define SM606F  
     0 "No"
     1 "Method used: implants"
     8 "Don't know"
     9 "Missing"
;
label define SM606G  
     0 "No"
     1 "Method used: condom"
     8 "Don't know"
     9 "Missing"
;
label define SM606H  
     0 "No"
     1 "Method used: periodic abstinence"
     8 "Don't know"
     9 "Missing"
;
label define SM606I  
     0 "No"
     1 "Method used: periodic abstinence"
     8 "Don't know"
     9 "Missing"
;
label define SM606J  
     0 "No"
     1 "Method used: withdrawal"
     8 "Don't know"
     9 "Missing"
;
label define SM606X  
     0 "No"
     1 "Method used: other"
     8 "Don't know"
     9 "Missing"
;
label define SM613A  
     0 "No"
     1 "Method last sex with 'other' woman: female sterilization"
     8 "Don't know"
     9 "Missing"
;
label define SM613B  
     0 "No"
     1 "Method last sex with 'other' woman: male sterilization"
     8 "Don't know"
     9 "Missing"
;
label define SM613C  
     0 "No"
     1 "Method last sex with 'other' woman: pill"
     8 "Don't know"
     9 "Missing"
;
label define SM613D  
     0 "No"
     1 "Method last sex with 'other' woman: IUD"
     8 "Don't know"
     9 "Missing"
;
label define SM613E  
     0 "No"
     1 "Method last sex with 'other' woman: injections"
     8 "Don't know"
     9 "Missing"
;
label define SM613F  
     0 "No"
     1 "Method last sex with 'other' woman: implants"
     8 "Don't know"
     9 "Missing"
;
label define SM613G  
     0 "No"
     1 "Method last sex with 'other' woman: condom"
     8 "Don't know"
     9 "Missing"
;
label define SM613H  
     0 "No"
     1 "Method last sex with 'other' woman: diaphragm/foam/jelly"
     8 "Don't know"
     9 "Missing"
;
label define SM613I  
     0 "No"
     1 "Method last sex with 'other' woman: periodic abstinence"
     8 "Don't know"
     9 "Missing"
;
label define SM613J  
     0 "No"
     1 "Method last sex with 'other' woman: withdrawal"
     8 "Don't know"
     9 "Missing"
;
label define SM613X  
     0 "No"
     1 "Method last sex with 'other' woman: other"
     8 "Don't know"
     9 "Missing"
;
label define SM701AA 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AB 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AC 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AD 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AE 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AF 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AG 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AH 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AI 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AJ 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AK 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM701AX 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM705   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define SM708   
     1 "Decreases"
     2 "Increases"
     3 "No difference"
     8 "DK/Unsure"
     9 "Missing"
;
label define SM712A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM712B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM712C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM712D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM712Z  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SM733   
    11 "Government hospital"
    12 "Government health center"
    13 "Government health station/clinic"
    14 "Health post"
    16 "Other public"
    21 "NGO health facility"
    26 "Other NGO"
    31 "Private hosp."
    32 "Private doctor"
    33 "Pharmacy"
    36 "Other private medical"
    41 "Work place facility"
    96 "Other"
    99 "Missing"
;
label define SM736T  
     1 "Morning"
     2 "Evening"
;
label define SM736H  
    97 "Inconsistent"
    99 "Missing"
;
label define SM736M  
    97 "Inconsistent"
    99 "Missing"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv213    MV213   
label values mv225    MV225   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values mv304_01 MV304   
label values mv305_01 MV305   
label values mv307_01 MV307   
label values m304a_02 M304A   
label values mv304_02 MV304   
label values mv305_02 MV305   
label values mv307_02 MV307   
label values m304a_03 M304A   
label values mv304_03 MV304   
label values mv305_03 MV305   
label values mv307_03 MV307   
label values m304a_04 M304A   
label values mv304_04 MV304   
label values mv305_04 MV305   
label values mv307_04 MV307   
label values m304a_05 M304A   
label values mv304_05 MV304   
label values mv305_05 MV305   
label values mv307_05 MV307   
label values m304a_06 M304A   
label values mv304_06 MV304   
label values mv305_06 MV305   
label values mv307_06 MV307   
label values m304a_07 M304A   
label values mv304_07 MV304   
label values mv305_07 MV305   
label values mv307_07 MV307   
label values m304a_08 M304A   
label values mv304_08 MV304   
label values mv305_08 MV305   
label values mv307_08 MV307   
label values m304a_09 M304A   
label values mv304_09 MV304   
label values mv305_09 MV305   
label values mv307_09 MV307   
label values m304a_10 M304A   
label values mv304_10 MV304   
label values mv305_10 MV305   
label values mv307_10 MV307   
label values m304a_11 M304A   
label values mv304_11 MV304   
label values mv305_11 MV305   
label values mv307_11 MV307   
label values m304a_12 M304A   
label values mv304_12 MV304   
label values mv305_12 MV305   
label values mv307_12 MV307   
label values m304a_13 M304A   
label values mv304_13 MV304   
label values mv305_13 MV305   
label values mv307_13 MV307   
label values m304a_14 M304A   
label values mv304_14 MV304   
label values mv305_14 MV305   
label values mv307_14 MV307   
label values m304a_15 M304A   
label values mv304_15 MV304   
label values mv305_15 MV305   
label values mv307_15 MV307   
label values m304a_16 M304A   
label values mv304_16 MV304   
label values mv305_16 MV305   
label values mv307_16 MV307   
label values m304a_17 M304A   
label values mv304_17 MV304   
label values mv305_17 MV305   
label values mv307_17 MV307   
label values m304a_18 M304A   
label values mv304_18 MV304   
label values mv305_18 MV305   
label values mv307_18 MV307   
label values m304a_19 M304A   
label values mv304_19 MV304   
label values mv305_19 MV305   
label values mv307_19 MV307   
label values m304a_20 M304A   
label values mv304_20 MV304   
label values mv305_20 MV305   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv312a   MV312A  
label values mv312b   MV312B  
label values mv313    MV313   
label values mv313a   MV313A  
label values mv313b   MV313B  
label values mv361    MV361   
label values mv362    MV362   
label values mv364    MV364   
label values mv367    MV367   
label values mv376    MV376   
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv531    MV531   
label values mv532    MV532   
label values mv534    MV534   
label values mv535    MV535   
label values mv536    MV536   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv612    MV612   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv641_1  MV641   
label values mv641_2  MV641   
label values mv641_3  MV641   
label values mv641_4  MV641   
label values mv641_5  MV641   
label values mv641_6  MV641   
label values mv641_7  MV641   
label values mv641_8  MV641   
label values mv714    MV714   
label values mv716    MV716   
label values mv717    MV717   
label values mv731    MV731   
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv750    MV750   
label values mv751    MV751   
label values mv753    MV753   
label values mv754b   MV754B  
label values mv754c   MV754C  
label values mv754d   MV754D  
label values mv754e   MV754E  
label values mv754f   MV754F  
label values mv754g   MV754G  
label values mv754h   MV754H  
label values mv754i   MV754I  
label values mv754j   MV754J  
label values mv754k   MV754K  
label values mv754l   MV754L  
label values mv754m   MV754M  
label values mv754n   MV754N  
label values mv754o   MV754O  
label values mv754p   MV754P  
label values mv754x   MV754X  
label values mv754z   MV754Z  
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761d   MV761D  
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv765a   MV765A  
label values mv765b   MV765B  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770c   MV770C  
label values mv771    MV771   
label values mv772    MV772   
label values mv773a   MV773A  
label values mv773b   MV773B  
label values mv773d   MV773D  
label values mv773e   MV773E  
label values mv773x   MV773X  
label values mv774    MV774   
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv776    MV776   
label values mv777    MV777   
label values mv778    MV778   
label values mv781    MV781   
label values mv782    MV782   
label values mv785    MV785   
label values mv785a   MV785A  
label values mv785b   MV785B  
label values mv785c   MV785C  
label values mv785d   MV785D  
label values mv785e   MV785E  
label values mv785f   MV785F  
label values mv785g   MV785G  
label values mv785h   MV785H  
label values mv785j   MV785J  
label values mv785k   MV785K  
label values mv785l   MV785L  
label values mv785m   MV785M  
label values mv785n   MV785N  
label values mv785o   MV785O  
label values mv785p   MV785P  
label values mv785x   MV785X  
label values mv785y   MV785Y  
label values mv785z   MV785Z  
label values mv786a   MV786A  
label values mv786b   MV786B  
label values mv786c   MV786C  
label values mv786d   MV786D  
label values mv786e   MV786E  
label values mv786f   MV786F  
label values mv786g   MV786G  
label values mv786h   MV786H  
label values mv786j   MV786J  
label values mv786k   MV786K  
label values mv786l   MV786L  
label values mv786m   MV786M  
label values mv786n   MV786N  
label values mv786o   MV786O  
label values mv786p   MV786P  
label values mv786x   MV786X  
label values mv786y   MV786Y  
label values mv786z   MV786Z  
label values mv791    MV791   
label values mv792    MV792   
label values smlan    SMLAN   
label values smintv   SMINTV  
label values smresp   SMRESP  
label values smtrans  SMTRANS 
label values sm101t   SM101T  
label values sm101h   SM101H  
label values sm101m   SM101M  
label values sm105mg  SM105MG 
label values sm105yg  SM105YG 
label values sm211m   SM211M  
label values sm211y   SM211Y  
label values sm211mg  SM211MG 
label values sm211yg  SM211YG 
label values sm214    SM214   
label values sm309    SM309   
label values sm310    SM310   
label values sm311    SM311   
label values sm312    SM312   
label values sm410mg  SM410MG 
label values sm410yg  SM410YG 
label values sm512d   SM512D  
label values sm512e   SM512E  
label values sm518a   SM518A  
label values sm518b   SM518B  
label values sm518c   SM518C  
label values sm518d   SM518D  
label values sm606a   SM606A  
label values sm606b   SM606B  
label values sm606c   SM606C  
label values sm606d   SM606D  
label values sm606e   SM606E  
label values sm606f   SM606F  
label values sm606g   SM606G  
label values sm606h   SM606H  
label values sm606i   SM606I  
label values sm606j   SM606J  
label values sm606x   SM606X  
label values sm613a   SM613A  
label values sm613b   SM613B  
label values sm613c   SM613C  
label values sm613d   SM613D  
label values sm613e   SM613E  
label values sm613f   SM613F  
label values sm613g   SM613G  
label values sm613h   SM613H  
label values sm613i   SM613I  
label values sm613j   SM613J  
label values sm613x   SM613X  
label values sm701aa  SM701AA 
label values sm701ab  SM701AB 
label values sm701ac  SM701AC 
label values sm701ad  SM701AD 
label values sm701ae  SM701AE 
label values sm701af  SM701AF 
label values sm701ag  SM701AG 
label values sm701ah  SM701AH 
label values sm701ai  SM701AI 
label values sm701aj  SM701AJ 
label values sm701ak  SM701AK 
label values sm701ax  SM701AX 
label values sm705    SM705   
label values sm708    SM708   
label values sm712a   SM712A  
label values sm712b   SM712B  
label values sm712c   SM712C  
label values sm712d   SM712D  
label values sm712z   SM712Z  
label values sm733    SM733   
label values sm736t   SM736T  
label values sm736h   SM736H  
label values sm736m   SM736M  
