DATA LIST FILE='ETMR41FL.DAT' RECORDS=1
/
 MCASEID     1-15   (A)
 MV000      16-18   (A)
 MV001      19-26
 MV002      27-30
 MV003      31-33
 MV004      34-37
 MV005      38-45
 MV006      46-47
 MV007      48-51
 MV008      52-55
 MV009      56-57
 MV010      58-61
 MV011      62-65
 MV012      66-67
 MV013      68-69
 MV014      70-70
 MV015      71-71
 MV016      72-73
 MV021      74-77
 MV022      78-81
 MV023      82-83
 MV024      84-85
 MV025      86-86
 MV026      87-87
 MV027      88-88
 MV028      89-91
 MV029      92-93
 MV030      94-96
 MV031      97-99
 MV032     100-101
 MV033     102-109
 MV034$1   110-111
 MV034A$1  112-112
 MV034$2   113-114
 MV034A$2  115-115
 MV034$3   116-117
 MV034A$3  118-118
 MV034$4   119-120
 MV034A$4  121-121
 MV034$5   122-123
 MV034A$5  124-124
 MV034$6   125-126
 MV034A$6  127-127
 MV034$7   128-129
 MV034A$7  130-130
 MV034$8   131-132
 MV034A$8  133-133
 MV035     134-134
 MV801     135-138
 MV802     139-142
 MV803     143-144
 MV101     145-146
 MV102     147-147
 MV103     148-148
 MV104     149-150
 MV105     151-151
 MV106     152-152
 MV107     153-154
 MV130     155-155
 MV131     156-157
 MV133     158-159
 MV134     160-160
 MV135     161-161
 MV136     162-163
 MV138     164-165
 MV149     166-166
 MV150     167-168
 MV151     169-169
 MV152     170-171
 MV155     172-172
 MV156     173-173
 MV157     174-174
 MV158     175-175
 MV159     176-176
 MV167     177-178
 MV168     179-179
 MV463A    180-180
 MV463B    181-181
 MV463C    182-182
 MV463D    183-183
 MV463E    184-184
 MV463F    185-185
 MV463G    186-186
 MV463Z    187-187
 MV464     188-189
 MV201     190-191
 MV202     192-193
 MV203     194-195
 MV204     196-197
 MV205     198-199
 MV206     200-201
 MV207     202-203
 MV212     204-205
 MV213     206-206
 MV217     207-207
 MV218     208-209
 MV225     210-210
 MV245     211-212
 MV246     213-213
 MV301     214-214
 MV302     215-215
 M304A$01  216-216
 MV304$01  217-217
 MV305$01  218-218
 MV307$01  219-219
 M304A$02  220-220
 MV304$02  221-221
 MV305$02  222-222
 MV307$02  223-223
 M304A$03  224-224
 MV304$03  225-225
 MV305$03  226-226
 MV307$03  227-227
 M304A$04  228-228
 MV304$04  229-229
 MV305$04  230-230
 MV307$04  231-231
 M304A$05  232-232
 MV304$05  233-233
 MV305$05  234-234
 MV307$05  235-235
 M304A$06  236-236
 MV304$06  237-237
 MV305$06  238-238
 MV307$06  239-239
 M304A$07  240-240
 MV304$07  241-241
 MV305$07  242-242
 MV307$07  243-243
 M304A$08  244-244
 MV304$08  245-245
 MV305$08  246-246
 MV307$08  247-247
 M304A$09  248-248
 MV304$09  249-249
 MV305$09  250-250
 MV307$09  251-251
 M304A$10  252-252
 MV304$10  253-253
 MV305$10  254-254
 MV307$10  255-255
 M304A$11  256-256
 MV304$11  257-257
 MV305$11  258-258
 MV307$11  259-259
 M304A$12  260-260
 MV304$12  261-261
 MV305$12  262-262
 MV307$12  263-263
 M304A$13  264-264
 MV304$13  265-265
 MV305$13  266-266
 MV307$13  267-267
 M304A$14  268-268
 MV304$14  269-269
 MV305$14  270-270
 MV307$14  271-271
 M304A$15  272-272
 MV304$15  273-273
 MV305$15  274-274
 MV307$15  275-275
 M304A$16  276-276
 MV304$16  277-277
 MV305$16  278-278
 MV307$16  279-279
 M304A$17  280-280
 MV304$17  281-281
 MV305$17  282-282
 MV307$17  283-283
 M304A$18  284-284
 MV304$18  285-285
 MV305$18  286-286
 MV307$18  287-287
 M304A$19  288-288
 MV304$19  289-289
 MV305$19  290-290
 MV307$19  291-291
 M304A$20  292-292
 MV304$20  293-293
 MV305$20  294-294
 MV307$20  295-295
 MV312     296-297
 MV312A    298-299
 MV312B    300-301
 MV312C    302-303
 MV313     304-304
 MV313A    305-305
 MV313B    306-306
 MV313C    307-307
 MV361     308-308
 MV362     309-309
 MV363     310-311
 MV364     312-312
 MV367     313-313
 MV375A    314-315
 MV375B    316-317
 MV375C    318-319
 MV376     320-321
 MV376A    322-322
 MV384A    323-323
 MV384B    324-324
 MV384C    325-325
 MV396     326-326
 MV3B0$1   327-327
 MV3B1$1   328-328
 MV3B2A$1  329-329
 MV3B2B$1  330-330
 MV3B2C$1  331-331
 MV3B2D$1  332-332
 MV3B2E$1  333-333
 MV3B2F$1  334-334
 MV3B2G$1  335-335
 MV3B2H$1  336-336
 MV3B2I$1  337-337
 MV3B2J$1  338-338
 MV3B2K$1  339-339
 MV3B2L$1  340-340
 MV3B2X$1  341-341
 MV3B2Z$1  342-342
 MV3B3A$1  343-343
 MV3B3B$1  344-344
 MV3B3C$1  345-345
 MV3B3D$1  346-346
 MV3B3E$1  347-347
 MV3B3F$1  348-348
 MV3B3G$1  349-349
 MV3B3H$1  350-350
 MV3B3I$1  351-351
 MV3B3J$1  352-352
 MV3B3K$1  353-353
 MV3B3L$1  354-354
 MV3B3M$1  355-355
 MV3B3N$1  356-356
 MV3B3X$1  357-357
 MV3B3Z$1  358-358
 MV3B0$2   359-359
 MV3B1$2   360-360
 MV3B2A$2  361-361
 MV3B2B$2  362-362
 MV3B2C$2  363-363
 MV3B2D$2  364-364
 MV3B2E$2  365-365
 MV3B2F$2  366-366
 MV3B2G$2  367-367
 MV3B2H$2  368-368
 MV3B2I$2  369-369
 MV3B2J$2  370-370
 MV3B2K$2  371-371
 MV3B2L$2  372-372
 MV3B2X$2  373-373
 MV3B2Z$2  374-374
 MV3B3A$2  375-375
 MV3B3B$2  376-376
 MV3B3C$2  377-377
 MV3B3D$2  378-378
 MV3B3E$2  379-379
 MV3B3F$2  380-380
 MV3B3G$2  381-381
 MV3B3H$2  382-382
 MV3B3I$2  383-383
 MV3B3J$2  384-384
 MV3B3K$2  385-385
 MV3B3L$2  386-386
 MV3B3M$2  387-387
 MV3B3N$2  388-388
 MV3B3X$2  389-389
 MV3B3Z$2  390-390
 MV3B0$3   391-391
 MV3B1$3   392-392
 MV3B2A$3  393-393
 MV3B2B$3  394-394
 MV3B2C$3  395-395
 MV3B2D$3  396-396
 MV3B2E$3  397-397
 MV3B2F$3  398-398
 MV3B2G$3  399-399
 MV3B2H$3  400-400
 MV3B2I$3  401-401
 MV3B2J$3  402-402
 MV3B2K$3  403-403
 MV3B2L$3  404-404
 MV3B2X$3  405-405
 MV3B2Z$3  406-406
 MV3B3A$3  407-407
 MV3B3B$3  408-408
 MV3B3C$3  409-409
 MV3B3D$3  410-410
 MV3B3E$3  411-411
 MV3B3F$3  412-412
 MV3B3G$3  413-413
 MV3B3H$3  414-414
 MV3B3I$3  415-415
 MV3B3J$3  416-416
 MV3B3K$3  417-417
 MV3B3L$3  418-418
 MV3B3M$3  419-419
 MV3B3N$3  420-420
 MV3B3X$3  421-421
 MV3B3Z$3  422-422
 MV3B0$4   423-423
 MV3B1$4   424-424
 MV3B2A$4  425-425
 MV3B2B$4  426-426
 MV3B2C$4  427-427
 MV3B2D$4  428-428
 MV3B2E$4  429-429
 MV3B2F$4  430-430
 MV3B2G$4  431-431
 MV3B2H$4  432-432
 MV3B2I$4  433-433
 MV3B2J$4  434-434
 MV3B2K$4  435-435
 MV3B2L$4  436-436
 MV3B2X$4  437-437
 MV3B2Z$4  438-438
 MV3B3A$4  439-439
 MV3B3B$4  440-440
 MV3B3C$4  441-441
 MV3B3D$4  442-442
 MV3B3E$4  443-443
 MV3B3F$4  444-444
 MV3B3G$4  445-445
 MV3B3H$4  446-446
 MV3B3I$4  447-447
 MV3B3J$4  448-448
 MV3B3K$4  449-449
 MV3B3L$4  450-450
 MV3B3M$4  451-451
 MV3B3N$4  452-452
 MV3B3X$4  453-453
 MV3B3Z$4  454-454
 MV3B0$5   455-455
 MV3B1$5   456-456
 MV3B2A$5  457-457
 MV3B2B$5  458-458
 MV3B2C$5  459-459
 MV3B2D$5  460-460
 MV3B2E$5  461-461
 MV3B2F$5  462-462
 MV3B2G$5  463-463
 MV3B2H$5  464-464
 MV3B2I$5  465-465
 MV3B2J$5  466-466
 MV3B2K$5  467-467
 MV3B2L$5  468-468
 MV3B2X$5  469-469
 MV3B2Z$5  470-470
 MV3B3A$5  471-471
 MV3B3B$5  472-472
 MV3B3C$5  473-473
 MV3B3D$5  474-474
 MV3B3E$5  475-475
 MV3B3F$5  476-476
 MV3B3G$5  477-477
 MV3B3H$5  478-478
 MV3B3I$5  479-479
 MV3B3J$5  480-480
 MV3B3K$5  481-481
 MV3B3L$5  482-482
 MV3B3M$5  483-483
 MV3B3N$5  484-484
 MV3B3X$5  485-485
 MV3B3Z$5  486-486
 MV3B11    487-488
 MV3B12A   489-489
 MV3B12B   490-490
 MV3B12C   491-491
 MV3B12D   492-492
 MV3B12E   493-493
 MV3B12F   494-494
 MV3B12G   495-495
 MV3B12H   496-496
 MV3B12X   497-497
 MV3B13    498-498
 MV3B14A   499-499
 MV3B14B   500-500
 MV3B14C   501-501
 MV3B14D   502-502
 MV3B14E   503-503
 MV3B14F   504-504
 MV3B14G   505-505
 MV3B14H   506-506
 MV3B14I   507-507
 MV3B14J   508-508
 MV3B14X   509-509
 MV3B15A   510-510
 MV3B15B   511-511
 MV3B15C   512-512
 MV3B15D   513-513
 MV3B15E   514-514
 MV3B15F   515-515
 MV3B15G   516-516
 MV3B15H   517-517
 MV3B15I   518-518
 MV3B15J   519-519
 MV3B15K   520-520
 MV3B15L   521-521
 MV3B15M   522-522
 MV3B15X   523-523
 MV3B15Y   524-524
 MV3B16    525-526
 MV3B17    527-528
 MV3B18    529-534
 MV3B19    535-537
 MV3B20    538-538
 MV3B21A   539-539
 MV3B21B   540-540
 MV3B21C   541-541
 MV3B21D   542-542
 MV3B21E   543-543
 MV3B22    544-544
 MV3B23A   545-545
 MV3B23B   546-546
 MV3B23C   547-547
 MV3B23D   548-548
 MV3B23E   549-549
 MV3B23F   550-550
 MV3B23G   551-551
 MV3B23H   552-552
 MV3B23I   553-553
 MV3B23J   554-554
 MV3B23K   555-555
 MV3B23X   556-556
 MV3B24A   557-557
 MV3B24B   558-558
 MV3B24C   559-559
 MV3B24D   560-560
 MV3B24E   561-561
 MV3B24F   562-562
 MV3B24G   563-563
 MV3B24H   564-564
 MV3B24I   565-565
 MV3B24J   566-566
 MV3B24K   567-567
 MV3B24L   568-568
 MV3B24X   569-569
 MV3B25A   570-570
 MV3B25B   571-571
 MV3B25C   572-572
 MV3B25D   573-573
 MV501     574-574
 MV502     575-575
 MV503     576-576
 MV505     577-578
 MV505A    579-580
 MV505B    581-582
 MV507     583-584
 MV508     585-588
 MV509     589-592
 MV510     593-593
 MV511     594-595
 MV512     596-597
 MV513     598-598
 MV525     599-600
 MV527     601-603
 MV531     604-605
 MV532     606-606
 MV534     607-607
 MV534A    608-608
 MV535     609-609
 MV536     610-610
 MV538     611-612
 MV539     613-613
 MV602     614-614
 MV603     615-617
 MV604     618-618
 MV605     619-619
 MV610     620-620
 MV611     621-621
 MV612     622-622
 MV613     623-624
 MV614     625-625
 MV616     626-628
 MV621     629-629
 MV627     630-631
 MV628     632-633
 MV629     634-635
 MV630A    636-636
 MV630B    637-637
 MV630C    638-638
 MV630D    639-639
 MV630E    640-640
 MV630F    641-641
 MV630G    642-642
 MV630H    643-643
 MV630I    644-644
 MV630J    645-645
 MV630K    646-646
 MV630L    647-647
 MV630M    648-648
 MV630N    649-649
 MV630O    650-650
 MV630X    651-651
 MV631     652-652
 MV633A    653-653
 MV633B    654-654
 MV633C    655-655
 MV633D    656-656
 MV633E    657-657
 MV633F    658-658
 MV633G    659-659
 MV634A    660-660
 MV634B    661-661
 MV634C    662-662
 MV634D    663-663
 MV635     664-664
 MV636     665-665
 MV637     666-666
 MV638     667-668
 MV640$1   669-669
 MV641$1   670-671
 MV642$1   672-672
 MV643$1   673-673
 MV644$1   674-674
 MV645$1   675-675
 MV646$1   676-676
 MV647$1   677-677
 MV640$2   678-678
 MV641$2   679-680
 MV642$2   681-681
 MV643$2   682-682
 MV644$2   683-683
 MV645$2   684-684
 MV646$2   685-685
 MV647$2   686-686
 MV640$3   687-687
 MV641$3   688-689
 MV642$3   690-690
 MV643$3   691-691
 MV644$3   692-692
 MV645$3   693-693
 MV646$3   694-694
 MV647$3   695-695
 MV640$4   696-696
 MV641$4   697-698
 MV642$4   699-699
 MV643$4   700-700
 MV644$4   701-701
 MV645$4   702-702
 MV646$4   703-703
 MV647$4   704-704
 MV640$5   705-705
 MV641$5   706-707
 MV642$5   708-708
 MV643$5   709-709
 MV644$5   710-710
 MV645$5   711-711
 MV646$5   712-712
 MV647$5   713-713
 MV640$6   714-714
 MV641$6   715-716
 MV642$6   717-717
 MV643$6   718-718
 MV644$6   719-719
 MV645$6   720-720
 MV646$6   721-721
 MV647$6   722-722
 MV640$7   723-723
 MV641$7   724-725
 MV642$7   726-726
 MV643$7   727-727
 MV644$7   728-728
 MV645$7   729-729
 MV646$7   730-730
 MV647$7   731-731
 MV640$8   732-732
 MV641$8   733-734
 MV642$8   735-735
 MV643$8   736-736
 MV644$8   737-737
 MV645$8   738-738
 MV646$8   739-739
 MV647$8   740-740
 MV648     741-741
 MV649A    742-742
 MV649B    743-743
 MV649C    744-744
 MV714     745-745
 MV716     746-748
 MV717     749-750
 MV719     751-751
 MV721     752-752
 MV731     753-753
 MV732     754-754
 MV733     755-756
 MV740     757-757
 MV741     758-758
 MV742     759-759
 MV743A    760-760
 MV743B    761-761
 MV743C    762-762
 MV743D    763-763
 MV743E    764-764
 MV743F    765-765
 MV743G    766-766
 MV744A    767-767
 MV744B    768-768
 MV744C    769-769
 MV744D    770-770
 MV744E    771-771
 MV745     772-773
 MV750     774-774
 MV751     775-775
 MV753     776-776
 MV754A    777-777
 MV754B    778-778
 MV754C    779-779
 MV754D    780-780
 MV754E    781-781
 MV754F    782-782
 MV754G    783-783
 MV754H    784-784
 MV754I    785-785
 MV754J    786-786
 MV754K    787-787
 MV754L    788-788
 MV754M    789-789
 MV754N    790-790
 MV754O    791-791
 MV754P    792-792
 MV754Q    793-793
 MV754R    794-794
 MV754S    795-795
 MV754T    796-796
 MV754U    797-797
 MV754V    798-798
 MV754X    799-799
 MV754Z    800-800
 MV754CP   801-801
 MV754DP   802-802
 MV754JP   803-803
 MV754WP   804-804
 MV756     805-805
 MV759A    806-806
 MV759B    807-807
 MV759C    808-808
 MV759D    809-809
 MV759E    810-810
 MV759F    811-811
 MV759G    812-812
 MV759H    813-813
 MV759I    814-814
 MV761     815-815
 MV761B    816-816
 MV761C    817-817
 MV761D    818-818
 MV762AA   819-819
 MV762AB   820-820
 MV762AC   821-821
 MV762AD   822-822
 MV762AE   823-823
 MV762AF   824-824
 MV762AG   825-825
 MV762AH   826-826
 MV762AI   827-827
 MV762AJ   828-828
 MV762AK   829-829
 MV762AL   830-830
 MV762AM   831-831
 MV762AN   832-832
 MV762AO   833-833
 MV762AP   834-834
 MV762AQ   835-835
 MV762AR   836-836
 MV762AS   837-837
 MV762AT   838-838
 MV762AU   839-839
 MV762AV   840-840
 MV762AW   841-841
 MV762AX   842-842
 MV762AZ   843-843
 MV762BA   844-844
 MV762BB   845-845
 MV762BC   846-846
 MV762BD   847-847
 MV762BE   848-848
 MV762BF   849-849
 MV762BG   850-850
 MV762BH   851-851
 MV762BI   852-852
 MV762BJ   853-853
 MV762BK   854-854
 MV762BL   855-855
 MV762BM   856-856
 MV762BN   857-857
 MV762BO   858-858
 MV762BP   859-859
 MV762BQ   860-860
 MV762BR   861-861
 MV762BS   862-862
 MV762BT   863-863
 MV762BU   864-864
 MV762BV   865-865
 MV762BW   866-866
 MV762BX   867-867
 MV762BZ   868-868
 MV763A    869-869
 MV763B    870-870
 MV763C    871-871
 MV763D    872-872
 MV763E    873-873
 MV763F    874-874
 MV763G    875-875
 MV765A    876-876
 MV765B    877-877
 MV765C    878-878
 MV766A    879-880
 MV766B    881-882
 MV767A    883-884
 MV767B    885-886
 MV767C    887-888
 MV768A    889-891
 MV768B    892-894
 MV768C    895-897
 MV769     898-898
 MV769A    899-899
 MV770     900-900
 MV770A    901-901
 MV770B    902-902
 MV770C    903-903
 MV770D    904-904
 MV770E    905-905
 MV770F    906-906
 MV770G    907-907
 MV770H    908-908
 MV770I    909-909
 MV771     910-910
 MV772     911-911
 MV773A    912-912
 MV773B    913-913
 MV773C    914-914
 MV773D    915-915
 MV773E    916-916
 MV773F    917-917
 MV773X    918-918
 MV774     919-919
 MV774A    920-920
 MV774B    921-921
 MV774C    922-922
 MV775     923-923
 MV776     924-924
 MV777     925-925
 MV778     926-926
 MV779     927-927
 MV780     928-928
 MV781     929-929
 MV782     930-930
 MV783     931-931
 MV784     932-933
 MV785     934-934
 MV785A    935-935
 MV785B    936-936
 MV785C    937-937
 MV785D    938-938
 MV785E    939-939
 MV785F    940-940
 MV785G    941-941
 MV785H    942-942
 MV785I    943-943
 MV785J    944-944
 MV785K    945-945
 MV785L    946-946
 MV785M    947-947
 MV785N    948-948
 MV785O    949-949
 MV785P    950-950
 MV785Q    951-951
 MV785X    952-952
 MV785Y    953-953
 MV785Z    954-954
 MV786A    955-955
 MV786B    956-956
 MV786C    957-957
 MV786D    958-958
 MV786E    959-959
 MV786F    960-960
 MV786G    961-961
 MV786H    962-962
 MV786I    963-963
 MV786J    964-964
 MV786K    965-965
 MV786L    966-966
 MV786M    967-967
 MV786N    968-968
 MV786O    969-969
 MV786P    970-970
 MV786Q    971-971
 MV786X    972-972
 MV786Y    973-973
 MV786Z    974-974
 MV787     975-976
 MV788     977-978
 MV789     979-980
 MV790     981-981
 MV791     982-982
 MV792     983-985
 SMINTDG   986-987
 SMINTMG   988-989
 SMINTYG   990-993
 SMINTCG   994-997
 SMLAN     998-998
 SMINTV    999-999
 SMRESP   1000-1000
 SMTRANS  1001-1001
 SM101T   1002-1002
 SM101H   1003-1004
 SM101M   1005-1006
 SM105MG  1007-1008
 SM105YG  1009-1012
 SM105CG  1013-1016
 SM109    1017-1018
 SM203    1019-1020
 SM205    1021-1022
 SM207    1023-1024
 SM211M   1025-1026
 SM211Y   1027-1030
 SM211C   1031-1034
 SM211MG  1035-1036
 SM211YG  1037-1040
 SM211CG  1041-1044
 SM214    1045-1047
 SM309    1048-1049
 SM310    1050-1050
 SM311    1051-1051
 SM312    1052-1053
 SM410MG  1054-1055
 SM410YG  1056-1059
 SM410CG  1060-1063
 SM411C   1064-1065
 SM512D   1066-1066
 SM512E   1067-1067
 SM518A   1068-1068
 SM518B   1069-1069
 SM518C   1070-1070
 SM518D   1071-1071
 SM606A   1072-1072
 SM606B   1073-1073
 SM606C   1074-1074
 SM606D   1075-1075
 SM606E   1076-1076
 SM606F   1077-1077
 SM606G   1078-1078
 SM606H   1079-1079
 SM606I   1080-1080
 SM606J   1081-1081
 SM606X   1082-1082
 SM613A   1083-1083
 SM613B   1084-1084
 SM613C   1085-1085
 SM613D   1086-1086
 SM613E   1087-1087
 SM613F   1088-1088
 SM613G   1089-1089
 SM613H   1090-1090
 SM613I   1091-1091
 SM613J   1092-1092
 SM613X   1093-1093
 SM701AA  1094-1094
 SM701AB  1095-1095
 SM701AC  1096-1096
 SM701AD  1097-1097
 SM701AE  1098-1098
 SM701AF  1099-1099
 SM701AG  1100-1100
 SM701AH  1101-1101
 SM701AI  1102-1102
 SM701AJ  1103-1103
 SM701AK  1104-1104
 SM701AX  1105-1105
 SM705    1106-1106
 SM708    1107-1107
 SM712A   1108-1108
 SM712B   1109-1109
 SM712C   1110-1110
 SM712D   1111-1111
 SM712Z   1112-1112
 SM733    1113-1114
 SM736T   1115-1115
 SM736H   1116-1117
 SM736M   1118-1119
.
VARIABLE LABELS
 MCASEID  "Case Identification"
/MV000    "Country code and phase"
/MV001    "Cluster number"
/MV002    "Household number"
/MV003    "Respondent's line number"
/MV004    "Ultimate area unit"
/MV005    "Sample weight"
/MV006    "Month of interview (Ethiopian calendar)"
/MV007    "Year of interview (Ethiopian calendar)"
/MV008    "Date of interview (CMC Ethiopian calendar)"
/MV009    "Respondent's month of birth"
/MV010    "Respondent's year of birth"
/MV011    "Date of birth (CMC)"
/MV012    "Current age - respondent"
/MV013    "Age 5-year groups"
/MV014    "Completeness of information"
/MV015    "Result of individual interview"
/MV016    "Day of interview"
/MV021    "Primary sampling unit"
/MV022    "Sample stratum number"
/MV023    "Sample domain"
/MV024    "Region"
/MV025    "Type of place of residence"
/MV026    "De facto place of residence"
/MV027    "Number of visits"
/MV028    "Interviewer identification"
/MV029    "Keyer identification"
/MV030    "Field supervisor"
/MV031    "Field editor"
/MV032    "Office editor"
/MV033    "Ultimate area selection prob."
/MV034$1  "Line numbers of wives, partners"
/MV034A$1 "Wife or partner            -NA"
/MV034$2  "Line numbers of wives, partners"
/MV034A$2 "Wife or partner            -NA"
/MV034$3  "Line numbers of wives, partners"
/MV034A$3 "Wife or partner            -NA"
/MV034$4  "Line numbers of wives, partners"
/MV034A$4 "Wife or partner            -NA"
/MV034$5  "Line numbers of wives, partners"
/MV034A$5 "Wife or partner            -NA"
/MV034$6  "Line numbers of wives, partners"
/MV034A$6 "Wife or partner            -NA"
/MV034$7  "Line numbers of wives, partners"
/MV034A$7 "Wife or partner            -NA"
/MV034$8  "Line numbers of wives, partners"
/MV034A$8 "Wife or partner            -NA"
/MV035    "Number of wives, partners"
/MV801    "Time interview started"
/MV802    "Time interview ended"
/MV803    "Length of interview in minutes"
/MV101    "Region"
/MV102    "Type of place of residence"
/MV103    "Childhood place of residence"
/MV104    "Years lived in place of res."
/MV105    "Type of place of previous res."
/MV106    "Highest educational level"
/MV107    "Highest year of education"
/MV130    "Religion"
/MV131    "Ethnicity"
/MV133    "Education in single years"
/MV134    "De facto place of residence"
/MV135    "Usual resident or visitor"
/MV136    "Number of household members"
/MV138    "Number of eligible men in HH"
/MV149    "Educational attainment"
/MV150    "Relationship to household head"
/MV151    "Sex of household head"
/MV152    "Age of household head"
/MV155    "Literacy"
/MV156    "MV167participated in a lite-NA"
/MV157    "Frequency of reading newpaper or magazine"
/MV158    "Frequency of listening to radio"
/MV159    "Frequency of watching television"
/MV167    "Times away from home in las-NA"
/MV168    "Away for more than one mont-NA"
/MV463A   "Smokes cigarettes          -NA"
/MV463B   "Smokes pipe                -NA"
/MV463C   "Smokes other tobacco       -NA"
/MV463D   "Smokes country specific    -NA"
/MV463E   "Smokes country specific    -NA"
/MV463F   "Smokes country specific    -NA"
/MV463G   "Smokes country specific    -NA"
/MV463Z   "Smokes nothing             -NA"
/MV464    "Number of cigarettes in las-NA"
/MV201    "Total children ever born"
/MV202    "Sons at home               -NA"
/MV203    "Daughters at home          -NA"
/MV204    "Sons elsewhere             -NA"
/MV205    "Daughters elsewhere        -NA"
/MV206    "Sons who have died         -NA"
/MV207    "Daughters who have died    -NA"
/MV212    "Age of respondent at 1st bi-NA"
/MV213    "Partner currently pregnant"
/MV217    "Knowledge of ovulatory cycl-NA"
/MV218    "Number of living children"
/MV225    "Current pregnancy wanted"
/MV245    "Women fathered children wit-NA"
/MV246    "Married to mother when firs-NA"
/MV301    "Knowledge of any method"
/MV302    "Ever use of any method"
/M304A$01 "Type of method"
/MV304$01 "Knows method"
/MV305$01 "Ever used method"
/MV307$01 "Method currently used"
/M304A$02 "Type of method"
/MV304$02 "Knows method"
/MV305$02 "Ever used method"
/MV307$02 "Method currently used"
/M304A$03 "Type of method"
/MV304$03 "Knows method"
/MV305$03 "Ever used method"
/MV307$03 "Method currently used"
/M304A$04 "Type of method"
/MV304$04 "Knows method"
/MV305$04 "Ever used method"
/MV307$04 "Method currently used"
/M304A$05 "Type of method"
/MV304$05 "Knows method"
/MV305$05 "Ever used method"
/MV307$05 "Method currently used"
/M304A$06 "Type of method"
/MV304$06 "Knows method"
/MV305$06 "Ever used method"
/MV307$06 "Method currently used"
/M304A$07 "Type of method"
/MV304$07 "Knows method"
/MV305$07 "Ever used method"
/MV307$07 "Method currently used"
/M304A$08 "Type of method"
/MV304$08 "Knows method"
/MV305$08 "Ever used method"
/MV307$08 "Method currently used"
/M304A$09 "Type of method"
/MV304$09 "Knows method"
/MV305$09 "Ever used method"
/MV307$09 "Method currently used"
/M304A$10 "Type of method"
/MV304$10 "Knows method"
/MV305$10 "Ever used method"
/MV307$10 "Method currently used"
/M304A$11 "Type of method"
/MV304$11 "Knows method"
/MV305$11 "Ever used method"
/MV307$11 "Method currently used"
/M304A$12 "Type of method"
/MV304$12 "Knows method"
/MV305$12 "Ever used method"
/MV307$12 "Method currently used"
/M304A$13 "Type of method"
/MV304$13 "Knows method"
/MV305$13 "Ever used method"
/MV307$13 "Method currently used"
/M304A$14 "Type of method"
/MV304$14 "Knows method"
/MV305$14 "Ever used method"
/MV307$14 "Method currently used"
/M304A$15 "Type of method"
/MV304$15 "Knows method"
/MV305$15 "Ever used method"
/MV307$15 "Method currently used"
/M304A$16 "Type of method"
/MV304$16 "Knows method"
/MV305$16 "Ever used method"
/MV307$16 "Method currently used"
/M304A$17 "Type of method"
/MV304$17 "Knows method"
/MV305$17 "Ever used method"
/MV307$17 "Method currently used"
/M304A$18 "Type of method"
/MV304$18 "Knows method"
/MV305$18 "Ever used method"
/MV307$18 "Method currently used"
/M304A$19 "Type of method"
/MV304$19 "Knows method"
/MV305$19 "Ever used method"
/MV307$19 "Method currently used"
/M304A$20 "Type of method"
/MV304$20 "Knows method"
/MV305$20 "Ever used method"
/MV307$20 "Method currently used"
/MV312    "Current contraceptive method"
/MV312A   "Most recent contraceptive method"
/MV312B   "Contraceptive method with other woman"
/MV312C   "Contraceptive method with o-NA"
/MV313    "Current use by method type"
/MV313A   "Most recent use by method type"
/MV313B   "Method use by method type with other woman"
/MV313C   "Method use by method type w-NA"
/MV361    "Pattern of use"
/MV362    "Intention to use"
/MV363    "Preferred future method    -NA"
/MV364    "Contraceptive use & intention"
/MV367    "Wanted last child"
/MV375A   "Main reason not using a met-NA"
/MV375B   "Main reason not using a met-NA"
/MV375C   "Main reason not using a met-NA"
/MV376    "Main reason not to use a meth."
/MV376A   "Would ever use method if ma-NA"
/MV384A   "Heard FP on radio last months"
/MV384B   "Heard FP on TV last months"
/MV384C   "Heard FP newspaper last months"
/MV396    "Can a woman who is breastfe-NA"
/MV3B0$1  "Method                     -NA"
/MV3B1$1  "Method is suitable for coup-NA"
/MV3B2A$1 "Advantages: Simple to use  -NA"
/MV3B2B$1 "Advantages: Effective      -NA"
/MV3B2C$1 "Advantages: Affordable     -NA"
/MV3B2D$1 "Advantages: No/few side eff-NA"
/MV3B2E$1 "Advantages: Can stop childr-NA"
/MV3B2F$1 "Advantages: no need for med-NA"
/MV3B2G$1 "Advantages: No risk of gett-NA"
/MV3B2H$1 "Advantages: Once inserted, -NA"
/MV3B2I$1 "Advantages: Country specifi-NA"
/MV3B2J$1 "Advantages: Country specifi-NA"
/MV3B2K$1 "Advantages: Country specifi-NA"
/MV3B2L$1 "Advantages: Country specifi-NA"
/MV3B2X$1 "Advantages: Other          -NA"
/MV3B2Z$1 "Advantages: Don't know     -NA"
/MV3B3A$1 "Disadvantages: Too expensiv-NA"
/MV3B3B$1 "Disadvantages: Against reli-NA"
/MV3B3C$1 "Disadvantages: May harm wom-NA"
/MV3B3D$1 "Disadvantages: Has side eff-NA"
/MV3B3E$1 "Disadvantages: Increases pr-NA"
/MV3B3F$1 "Disadvantages: Can cause st-NA"
/MV3B3G$1 "Disadvantages: Method can f-NA"
/MV3B3H$1 "Disadvantages: Baby in dang-NA"
/MV3B3I$1 "Disadvantages: Involves doc-NA"
/MV3B3J$1 "Disadvantages: Can lead to -NA"
/MV3B3K$1 "Disadvantages: Country spec-NA"
/MV3B3L$1 "Disadvantages: Country spec-NA"
/MV3B3M$1 "Disadvantages: Country spec-NA"
/MV3B3N$1 "Disadvantages: Country spec-NA"
/MV3B3X$1 "Disadvantages: Other       -NA"
/MV3B3Z$1 "Disadvantages: Don't know  -NA"
/MV3B0$2  "Method                     -NA"
/MV3B1$2  "Method is suitable for coup-NA"
/MV3B2A$2 "Advantages: Simple to use  -NA"
/MV3B2B$2 "Advantages: Effective      -NA"
/MV3B2C$2 "Advantages: Affordable     -NA"
/MV3B2D$2 "Advantages: No/few side eff-NA"
/MV3B2E$2 "Advantages: Can stop childr-NA"
/MV3B2F$2 "Advantages: no need for med-NA"
/MV3B2G$2 "Advantages: No risk of gett-NA"
/MV3B2H$2 "Advantages: Once inserted, -NA"
/MV3B2I$2 "Advantages: Country specifi-NA"
/MV3B2J$2 "Advantages: Country specifi-NA"
/MV3B2K$2 "Advantages: Country specifi-NA"
/MV3B2L$2 "Advantages: Country specifi-NA"
/MV3B2X$2 "Advantages: Other          -NA"
/MV3B2Z$2 "Advantages: Don't know     -NA"
/MV3B3A$2 "Disadvantages: Too expensiv-NA"
/MV3B3B$2 "Disadvantages: Against reli-NA"
/MV3B3C$2 "Disadvantages: May harm wom-NA"
/MV3B3D$2 "Disadvantages: Has side eff-NA"
/MV3B3E$2 "Disadvantages: Increases pr-NA"
/MV3B3F$2 "Disadvantages: Can cause st-NA"
/MV3B3G$2 "Disadvantages: Method can f-NA"
/MV3B3H$2 "Disadvantages: Baby in dang-NA"
/MV3B3I$2 "Disadvantages: Involves doc-NA"
/MV3B3J$2 "Disadvantages: Can lead to -NA"
/MV3B3K$2 "Disadvantages: Country spec-NA"
/MV3B3L$2 "Disadvantages: Country spec-NA"
/MV3B3M$2 "Disadvantages: Country spec-NA"
/MV3B3N$2 "Disadvantages: Country spec-NA"
/MV3B3X$2 "Disadvantages: Other       -NA"
/MV3B3Z$2 "Disadvantages: Don't know  -NA"
/MV3B0$3  "Method                     -NA"
/MV3B1$3  "Method is suitable for coup-NA"
/MV3B2A$3 "Advantages: Simple to use  -NA"
/MV3B2B$3 "Advantages: Effective      -NA"
/MV3B2C$3 "Advantages: Affordable     -NA"
/MV3B2D$3 "Advantages: No/few side eff-NA"
/MV3B2E$3 "Advantages: Can stop childr-NA"
/MV3B2F$3 "Advantages: no need for med-NA"
/MV3B2G$3 "Advantages: No risk of gett-NA"
/MV3B2H$3 "Advantages: Once inserted, -NA"
/MV3B2I$3 "Advantages: Country specifi-NA"
/MV3B2J$3 "Advantages: Country specifi-NA"
/MV3B2K$3 "Advantages: Country specifi-NA"
/MV3B2L$3 "Advantages: Country specifi-NA"
/MV3B2X$3 "Advantages: Other          -NA"
/MV3B2Z$3 "Advantages: Don't know     -NA"
/MV3B3A$3 "Disadvantages: Too expensiv-NA"
/MV3B3B$3 "Disadvantages: Against reli-NA"
/MV3B3C$3 "Disadvantages: May harm wom-NA"
/MV3B3D$3 "Disadvantages: Has side eff-NA"
/MV3B3E$3 "Disadvantages: Increases pr-NA"
/MV3B3F$3 "Disadvantages: Can cause st-NA"
/MV3B3G$3 "Disadvantages: Method can f-NA"
/MV3B3H$3 "Disadvantages: Baby in dang-NA"
/MV3B3I$3 "Disadvantages: Involves doc-NA"
/MV3B3J$3 "Disadvantages: Can lead to -NA"
/MV3B3K$3 "Disadvantages: Country spec-NA"
/MV3B3L$3 "Disadvantages: Country spec-NA"
/MV3B3M$3 "Disadvantages: Country spec-NA"
/MV3B3N$3 "Disadvantages: Country spec-NA"
/MV3B3X$3 "Disadvantages: Other       -NA"
/MV3B3Z$3 "Disadvantages: Don't know  -NA"
/MV3B0$4  "Method                     -NA"
/MV3B1$4  "Method is suitable for coup-NA"
/MV3B2A$4 "Advantages: Simple to use  -NA"
/MV3B2B$4 "Advantages: Effective      -NA"
/MV3B2C$4 "Advantages: Affordable     -NA"
/MV3B2D$4 "Advantages: No/few side eff-NA"
/MV3B2E$4 "Advantages: Can stop childr-NA"
/MV3B2F$4 "Advantages: no need for med-NA"
/MV3B2G$4 "Advantages: No risk of gett-NA"
/MV3B2H$4 "Advantages: Once inserted, -NA"
/MV3B2I$4 "Advantages: Country specifi-NA"
/MV3B2J$4 "Advantages: Country specifi-NA"
/MV3B2K$4 "Advantages: Country specifi-NA"
/MV3B2L$4 "Advantages: Country specifi-NA"
/MV3B2X$4 "Advantages: Other          -NA"
/MV3B2Z$4 "Advantages: Don't know     -NA"
/MV3B3A$4 "Disadvantages: Too expensiv-NA"
/MV3B3B$4 "Disadvantages: Against reli-NA"
/MV3B3C$4 "Disadvantages: May harm wom-NA"
/MV3B3D$4 "Disadvantages: Has side eff-NA"
/MV3B3E$4 "Disadvantages: Increases pr-NA"
/MV3B3F$4 "Disadvantages: Can cause st-NA"
/MV3B3G$4 "Disadvantages: Method can f-NA"
/MV3B3H$4 "Disadvantages: Baby in dang-NA"
/MV3B3I$4 "Disadvantages: Involves doc-NA"
/MV3B3J$4 "Disadvantages: Can lead to -NA"
/MV3B3K$4 "Disadvantages: Country spec-NA"
/MV3B3L$4 "Disadvantages: Country spec-NA"
/MV3B3M$4 "Disadvantages: Country spec-NA"
/MV3B3N$4 "Disadvantages: Country spec-NA"
/MV3B3X$4 "Disadvantages: Other       -NA"
/MV3B3Z$4 "Disadvantages: Don't know  -NA"
/MV3B0$5  "Method                     -NA"
/MV3B1$5  "Method is suitable for coup-NA"
/MV3B2A$5 "Advantages: Simple to use  -NA"
/MV3B2B$5 "Advantages: Effective      -NA"
/MV3B2C$5 "Advantages: Affordable     -NA"
/MV3B2D$5 "Advantages: No/few side eff-NA"
/MV3B2E$5 "Advantages: Can stop childr-NA"
/MV3B2F$5 "Advantages: no need for med-NA"
/MV3B2G$5 "Advantages: No risk of gett-NA"
/MV3B2H$5 "Advantages: Once inserted, -NA"
/MV3B2I$5 "Advantages: Country specifi-NA"
/MV3B2J$5 "Advantages: Country specifi-NA"
/MV3B2K$5 "Advantages: Country specifi-NA"
/MV3B2L$5 "Advantages: Country specifi-NA"
/MV3B2X$5 "Advantages: Other          -NA"
/MV3B2Z$5 "Advantages: Don't know     -NA"
/MV3B3A$5 "Disadvantages: Too expensiv-NA"
/MV3B3B$5 "Disadvantages: Against reli-NA"
/MV3B3C$5 "Disadvantages: May harm wom-NA"
/MV3B3D$5 "Disadvantages: Has side eff-NA"
/MV3B3E$5 "Disadvantages: Increases pr-NA"
/MV3B3F$5 "Disadvantages: Can cause st-NA"
/MV3B3G$5 "Disadvantages: Method can f-NA"
/MV3B3H$5 "Disadvantages: Baby in dang-NA"
/MV3B3I$5 "Disadvantages: Involves doc-NA"
/MV3B3J$5 "Disadvantages: Can lead to -NA"
/MV3B3K$5 "Disadvantages: Country spec-NA"
/MV3B3L$5 "Disadvantages: Country spec-NA"
/MV3B3M$5 "Disadvantages: Country spec-NA"
/MV3B3N$5 "Disadvantages: Country spec-NA"
/MV3B3X$5 "Disadvantages: Other       -NA"
/MV3B3Z$5 "Disadvantages: Don't know  -NA"
/MV3B11   "Age at first use of condom -NA"
/MV3B12A  "Reason of first condom use:-NA"
/MV3B12B  "Reason of first condom use:-NA"
/MV3B12C  "Reason of first condom use:-NA"
/MV3B12D  "Reason of first condom use:-NA"
/MV3B12E  "Reason of first condom use:-NA"
/MV3B12F  "Reason of first condom use:-NA"
/MV3B12G  "Reason of first condom use:-NA"
/MV3B12H  "Reason of first condom use:-NA"
/MV3B12X  "Reason of first condom use:-NA"
/MV3B13   "Frequency of use of condom -NA"
/MV3B14A  "Timing of use: On partner's-NA"
/MV3B14B  "Timing of use: During partn-NA"
/MV3B14C  "Timing of use: When not usi-NA"
/MV3B14D  "Timing of use: With a stran-NA"
/MV3B14E  "Timing of use: With a comme-NA"
/MV3B14F  "Timing of use: With anyone -NA"
/MV3B14G  "Timing of use: With wife/re-NA"
/MV3B14H  "Timing of use: Country spec-NA"
/MV3B14I  "Timing of use: Country spec-NA"
/MV3B14J  "Timing of use: Country spec-NA"
/MV3B14X  "Timing of use: Other       -NA"
/MV3B15A  "Problems with condom: Too e-NA"
/MV3B15B  "Problems with condom: Embar-NA"
/MV3B15C  "Problems with condom: Diffi-NA"
/MV3B15D  "Problems with condom: Diffi-NA"
/MV3B15E  "Problems with condom: Spoil-NA"
/MV3B15F  "Problems with condom: Dimin-NA"
/MV3B15G  "Problems with condom: Wife/-NA"
/MV3B15H  "Problems with condom: Wife/-NA"
/MV3B15I  "Problems with condom: Incon-NA"
/MV3B15J  "Problems with condom: Condo-NA"
/MV3B15K  "Problems with condom: Count-NA"
/MV3B15L  "Problems with condom: Count-NA"
/MV3B15M  "Problems with condom: Count-NA"
/MV3B15X  "Problems with condom: Other-NA"
/MV3B15Y  "Problems with condom: No pr-NA"
/MV3B16   "Brand of condom            -NA"
/MV3B17   "Source of condoms          -NA"
/MV3B18   "Cost of condom's packet    -NA"
/MV3B19   "Number of condom in each pa-NA"
/MV3B20   "Affordability of condoms   -NA"
/MV3B21A  "Diminish a man's sexual ple-NA"
/MV3B21B  "Inconvenient to use        -NA"
/MV3B21C  "Can be reused              -NA"
/MV3B21D  "Protects against disease   -NA"
/MV3B21E  "Women has no right to tell -NA"
/MV3B22   "Consider getting sterilized-NA"
/MV3B23A  "Benefits of male sterilizat-NA"
/MV3B23B  "Benefits of male sterilizat-NA"
/MV3B23C  "Benefits of male sterilizat-NA"
/MV3B23D  "Benefits of male sterilizat-NA"
/MV3B23E  "Benefits of male sterilizat-NA"
/MV3B23F  "Benefits of male sterilizat-NA"
/MV3B23G  "Benefits of male sterilizat-NA"
/MV3B23H  "Benefits of male sterilizat-NA"
/MV3B23I  "Benefits of male sterilizat-NA"
/MV3B23J  "Benefits of male sterilizat-NA"
/MV3B23K  "Benefits of male sterilizat-NA"
/MV3B23X  "Benefits of male sterilizat-NA"
/MV3B24A  "Reason never consider steri-NA"
/MV3B24B  "Reason never consider steri-NA"
/MV3B24C  "Reason never consider steri-NA"
/MV3B24D  "Reason never consider steri-NA"
/MV3B24E  "Reason never consider steri-NA"
/MV3B24F  "Reason never consider steri-NA"
/MV3B24G  "Reason never consider steri-NA"
/MV3B24H  "Reason never consider steri-NA"
/MV3B24I  "Reason never consider steri-NA"
/MV3B24J  "Reason never consider steri-NA"
/MV3B24K  "Reason never consider steri-NA"
/MV3B24L  "Reason never consider steri-NA"
/MV3B24X  "Reason never consider steri-NA"
/MV3B25A  "Contraception is woman's bu-NA"
/MV3B25B  "Sterilized women become pro-NA"
/MV3B25C  "To a man equivalent to bein-NA"
/MV3B25D  "Woman can get pregnant, so -NA"
/MV501    "Current marital status"
/MV502    "Currently/formerly/never marr."
/MV503    "Number of unions"
/MV505    "Number of wives, partners"
/MV505A   "Number of wives"
/MV505B   "Number of live-in partners"
/MV507    "Month of first marriage"
/MV508    "Year of first marriage"
/MV509    "Date of first marriage (CMC)"
/MV510    "Completeness of date inform."
/MV511    "Age at first marriage"
/MV512    "Years since first marriage"
/MV513    "Marital duration (grouped)"
/MV525    "Age at first intercourse"
/MV527    "Time since last intercourse"
/MV531    "Age at first intercourse (imp)"
/MV532    "Flag for MV531"
/MV534    "Have a regular sex partner"
/MV534A   "One or more regular partner-NA"
/MV535    "Have ever been married"
/MV536    "Recent sexual activity"
/MV538    "Total wives, partners ever -NA"
/MV539    "Other regular sexual partne-NA"
/MV602    "Fertility preference"
/MV603    "Preferred waiting time"
/MV604    "Preferred waiting time (grpd)"
/MV605    "Desire for more children"
/MV610    "Wife approves FP           -NA"
/MV611    "Discussed FP with partner  -NA"
/MV612    "Respondent approves FP"
/MV613    "Ideal number of children"
/MV614    "Ideal number of children (grp)"
/MV616    "Time for future birth"
/MV621    "Wifes desire for children  -NA"
/MV627    "Ideal number of boys"
/MV628    "Ideal number of girls"
/MV629    "Ideal number of either sex"
/MV630A   "Discussed FP with partner  -NA"
/MV630B   "Discussed FP with mother   -NA"
/MV630C   "Discussed FP with father   -NA"
/MV630D   "Discussed FP with sister(s)-NA"
/MV630E   "Discussed FP with brother(s-NA"
/MV630F   "Discussed FP with daughter(-NA"
/MV630G   "Discussed FP with mother-in-NA"
/MV630H   "Discussed FP with friends/n-NA"
/MV630I   "Discussed FP with son(s)   -NA"
/MV630J   "Discussed FP with father-in-NA"
/MV630K   "Discussed FP -country speci-NA"
/MV630L   "Discussed FP -country speci-NA"
/MV630M   "Discussed FP -country speci-NA"
/MV630N   "Discussed FP -country speci-NA"
/MV630O   "Discussed FP -country speci-NA"
/MV630X   "Discussed FP with others   -NA"
/MV631    "Problem if became pregnant -NA"
/MV633A   "Reason for not having sex: -NA"
/MV633B   "Reason for not having sex: -NA"
/MV633C   "Reason for not having sex: -NA"
/MV633D   "Reason for not having sex: -NA"
/MV633E   "Reason for not having sex: -NA"
/MV633F   "Reason for not having sex: -NA"
/MV633G   "Reason for not having sex: -NA"
/MV634A   "Husband has right to: get a-NA"
/MV634B   "Husband has right to: refus-NA"
/MV634C   "Husband has right to: use f-NA"
/MV634D   "Husband has right to: have -NA"
/MV635    "Wife number would prefer ne-NA"
/MV636    "Planning to have children w-NA"
/MV637    "Plan to take another wife  -NA"
/MV638    "Main reason may take anothe-NA"
/MV640$1  "Sequence number of partners-NA"
/MV641$1  "Line number of wive/partner-NA"
/MV642$1  "Partner currently pregnant -NA"
/MV643$1  "Current pregnancy wanted   -NA"
/MV644$1  "Problem if became pregnant -NA"
/MV645$1  "Wifes desire for children  -NA"
/MV646$1  "Discussed FP with partner  -NA"
/MV647$1  "Wife approves FP           -NA"
/MV640$2  "Sequence number of partners-NA"
/MV641$2  "Line number of wive/partner-NA"
/MV642$2  "Partner currently pregnant -NA"
/MV643$2  "Current pregnancy wanted   -NA"
/MV644$2  "Problem if became pregnant -NA"
/MV645$2  "Wifes desire for children  -NA"
/MV646$2  "Discussed FP with partner  -NA"
/MV647$2  "Wife approves FP           -NA"
/MV640$3  "Sequence number of partners-NA"
/MV641$3  "Line number of wive/partner-NA"
/MV642$3  "Partner currently pregnant -NA"
/MV643$3  "Current pregnancy wanted   -NA"
/MV644$3  "Problem if became pregnant -NA"
/MV645$3  "Wifes desire for children  -NA"
/MV646$3  "Discussed FP with partner  -NA"
/MV647$3  "Wife approves FP           -NA"
/MV640$4  "Sequence number of partners-NA"
/MV641$4  "Line number of wive/partner-NA"
/MV642$4  "Partner currently pregnant -NA"
/MV643$4  "Current pregnancy wanted   -NA"
/MV644$4  "Problem if became pregnant -NA"
/MV645$4  "Wifes desire for children  -NA"
/MV646$4  "Discussed FP with partner  -NA"
/MV647$4  "Wife approves FP           -NA"
/MV640$5  "Sequence number of partners-NA"
/MV641$5  "Line number of wive/partner-NA"
/MV642$5  "Partner currently pregnant -NA"
/MV643$5  "Current pregnancy wanted   -NA"
/MV644$5  "Problem if became pregnant -NA"
/MV645$5  "Wifes desire for children  -NA"
/MV646$5  "Discussed FP with partner  -NA"
/MV647$5  "Wife approves FP           -NA"
/MV640$6  "Sequence number of partners-NA"
/MV641$6  "Line number of wive/partner-NA"
/MV642$6  "Partner currently pregnant -NA"
/MV643$6  "Current pregnancy wanted   -NA"
/MV644$6  "Problem if became pregnant -NA"
/MV645$6  "Wifes desire for children  -NA"
/MV646$6  "Discussed FP with partner  -NA"
/MV647$6  "Wife approves FP           -NA"
/MV640$7  "Sequence number of partners-NA"
/MV641$7  "Line number of wive/partner-NA"
/MV642$7  "Partner currently pregnant -NA"
/MV643$7  "Current pregnancy wanted   -NA"
/MV644$7  "Problem if became pregnant -NA"
/MV645$7  "Wifes desire for children  -NA"
/MV646$7  "Discussed FP with partner  -NA"
/MV647$7  "Wife approves FP           -NA"
/MV640$8  "Sequence number of partners-NA"
/MV641$8  "Line number of wive/partner-NA"
/MV642$8  "Partner currently pregnant -NA"
/MV643$8  "Current pregnancy wanted   -NA"
/MV644$8  "Problem if became pregnant -NA"
/MV645$8  "Wifes desire for children  -NA"
/MV646$8  "Discussed FP with partner  -NA"
/MV647$8  "Wife approves FP           -NA"
/MV648    "Discussed FP with health wo-NA"
/MV649A   "Interest in avoiding unwant-NA"
/MV649B   "Interest in helping partner-NA"
/MV649C   "Interest in helping care fo-NA"
/MV714    "Respondent currently working"
/MV716    "Respondent's occupation"
/MV717    "Respondent's occupation"
/MV719    "Work for family, others, se-NA"
/MV721    "Works at home or away      -NA"
/MV731    "Worked in last 12 months"
/MV732    "Employment all year/seasona-NA"
/MV733    "Months worked in last 12 mo-NA"
/MV740    "Type of land where resp. wo-NA"
/MV741    "Type of earnings for work  -NA"
/MV742    "Portion of household expend-NA"
/MV743A   "Final say on own health car-NA"
/MV743B   "Final say on making large h-NA"
/MV743C   "Final say on making househo-NA"
/MV743D   "Final say on visits to fami-NA"
/MV743E   "Final say on food to be coo-NA"
/MV743F   "Final say on deciding what -NA"
/MV743G   "Final say on deciding how m-NA"
/MV744A   "Wife beating justified if she goes out without telling him"
/MV744B   "Wife beating justified if she neglects the children"
/MV744C   "Wife beating justified if she argues with him"
/MV744D   "Wife beating justified if she refuses to have sex with him"
/MV744E   "Wife beating justified if she burns the food"
/MV745    "Activity last 12 months    -NA"
/MV750    "Heard sexual transmit. disease"
/MV751    "Ever heard of AIDS"
/MV753    "Ways to avoid AIDS"
/MV754A   "AIDS: Safe sex             -NA"
/MV754B   "AIDS: abstain from sex"
/MV754C   "AIDS: use condoms during sex"
/MV754D   "AIDS: only one sex partner"
/MV754E   "AIDS: avoid sex prostitutes"
/MV754F   "AIDS: avoid sex homosexuals"
/MV754G   "AIDS: avoid blood transfusions"
/MV754H   "AIDS: avoid injections"
/MV754I   "AIDS: avoid kissing"
/MV754J   "AIDS: avoid mosquito bites"
/MV754K   "AIDS: protection trad. healer"
/MV754L   "AIDS: Limit number of sex partners"
/MV754M   "AIDS: Avoid partners who have many partners"
/MV754N   "AIDS: Avoid sex with intravenous drug users"
/MV754O   "AIDS: avoid sharing razor blades with AIDS patient"
/MV754P   "AIDS: Avoid sharing household utensils"
/MV754Q   "AIDS: country specific     -NA"
/MV754R   "AIDS: country specific     -NA"
/MV754S   "AIDS: country specific     -NA"
/MV754T   "AIDS: country specific     -NA"
/MV754U   "AIDS: country specific     -NA"
/MV754V   "AIDS: country specific     -NA"
/MV754X   "AIDS: other responses"
/MV754Z   "AIDS: DK ways to avoid AIDS"
/MV754CP  "Reduce chances of AIDS by always using condoms during sex"
/MV754DP  "Reduce chance of AIDS: have 1 sex partner with no oth partnr"
/MV754JP  "Get AIDS from mosquito bite-NA"
/MV754WP  "Get AIDS by sharing food wi-NA"
/MV756    "Can a healthy person have AIDS"
/MV759A   "Acceptable to discuss AIDS -NA"
/MV759B   "Acceptable to discuss AIDS -NA"
/MV759C   "Acceptable to discuss AIDS -NA"
/MV759D   "Acceptable to discuss AIDS:-NA"
/MV759E   "Acceptable to discuss AIDS:-NA"
/MV759F   "Acceptable to discuss AIDS:-NA"
/MV759G   "Acceptable to discuss AIDS:-NA"
/MV759H   "Acceptable to discuss AIDS:-NA"
/MV759I   "Acceptable to discuss AIDS:-NA"
/MV761    "Last intercourse used condom"
/MV761B   "Intercourse with other woman (1) used condom"
/MV761C   "Intercourse with other woma-NA"
/MV761D   "Intercourse for money used condom"
/MV762AA  "Source for condoms: Governm-NA"
/MV762AB  "Source for condoms: Governm-NA"
/MV762AC  "Source for condoms: Family -NA"
/MV762AD  "Source for condoms: Mobile -NA"
/MV762AE  "Source for condoms: Public -NA"
/MV762AF  "Source for condoms: Other p-NA"
/MV762AG  "Source for condoms: Public -NA"
/MV762AH  "Source for condoms: Public -NA"
/MV762AI  "Source for condoms: Public -NA"
/MV762AJ  "Source for condoms: Private-NA"
/MV762AK  "Source for condoms: Pharmac-NA"
/MV762AL  "Source for condoms: Private-NA"
/MV762AM  "Source for condoms: Private-NA"
/MV762AN  "Source for condoms: Private-NA"
/MV762AO  "Source for condoms: Other p-NA"
/MV762AP  "Source for condoms: Private-NA"
/MV762AQ  "Source for condoms: Private-NA"
/MV762AR  "Source for condoms: Private-NA"
/MV762AS  "Source for condoms: Shop   -NA"
/MV762AT  "Source for condoms: Church -NA"
/MV762AU  "Source for condoms: Friends-NA"
/MV762AV  "Source for condoms: CS     -NA"
/MV762AW  "Source for condoms: CS     -NA"
/MV762AX  "Source for condoms: Other  -NA"
/MV762AZ  "Source for condoms: DK sour-NA"
/MV762BA  "Source for female condoms: -NA"
/MV762BB  "Source for female condoms: -NA"
/MV762BC  "Source for female condoms: -NA"
/MV762BD  "Source for female condoms: -NA"
/MV762BE  "Source for female condoms: -NA"
/MV762BF  "Source for female condoms: -NA"
/MV762BG  "Source for female condoms: -NA"
/MV762BH  "Source for female condoms: -NA"
/MV762BI  "Source for female condoms: -NA"
/MV762BJ  "Source for female condoms: -NA"
/MV762BK  "Source for female condoms: -NA"
/MV762BL  "Source for female condoms: -NA"
/MV762BM  "Source for female condoms: -NA"
/MV762BN  "Source for female condoms: -NA"
/MV762BO  "Source for female condoms: -NA"
/MV762BP  "Source for female condoms: -NA"
/MV762BQ  "Source for female condoms: -NA"
/MV762BR  "Source for female condoms: -NA"
/MV762BS  "Source for female condoms: -NA"
/MV762BT  "Source for female condoms: -NA"
/MV762BU  "Source for female condoms: -NA"
/MV762BV  "Source for female condoms: -NA"
/MV762BW  "Source for female condoms: -NA"
/MV762BX  "Source for female condoms: -NA"
/MV762BZ  "Source for female condoms: -NA"
/MV763A   "Had any STD in last 12 months"
/MV763B   "Had genital sore/ulcer in last 12 months"
/MV763C   "Had genital discharge in last 12 months"
/MV763D   "Last 12 months had CS STD  -NA"
/MV763E   "Last 12 months had CS STD  -NA"
/MV763F   "Last 12 months had CS STD  -NA"
/MV763G   "Past 12 months had CS STD  -NA"
/MV765A   "Last sex reason used a condom"
/MV765B   "Sex with other woman (1) reason used a condom"
/MV765C   "Sex with other woman (2) re-NA"
/MV766A   "No. other than wife had sex in last 12 months"
/MV766B   "No. had sex including wife in last 12 months"
/MV767A   "Relationship with last sex partner"
/MV767B   "Relationship with other sex partner (1)"
/MV767C   "Relationship with other sex-NA"
/MV768A   "Length of time knows last partner"
/MV768B   "Length of time knows other partner (1)"
/MV768C   "Length of time knows other -NA"
/MV769    "Could get a condom         -NA"
/MV769A   "Could get a female condom  -NA"
/MV770    "Seek advice for last disease"
/MV770A   "Seek advise: clinic/hospital/private doctor"
/MV770B   "Seek advise: traditional he-NA"
/MV770C   "Seek advise: Shop/pharmacy"
/MV770D   "Seek advise: Friends/relati-NA"
/MV770E   "Seek advise: CS            -NA"
/MV770F   "Seek advise: CS            -NA"
/MV770G   "Seek advise: CS            -NA"
/MV770H   "Seek advise: CS            -NA"
/MV770I   "Seek advise: CS            -NA"
/MV771    "Advise partner when had disease"
/MV772    "Tried to avoid infecting partner"
/MV773A   "What done: no sexual intercourse"
/MV773B   "What done: used condoms"
/MV773C   "What done: took medicines  -NA"
/MV773D   "What done: CS : wash penis before sex"
/MV773E   "What done: CS: reduce frequency of sexual intercourse"
/MV773F   "What done: country specific-NA"
/MV773X   "What done: other"
/MV774    "AIDS transmitted from mother to child"
/MV774A   "AIDS transmit. during pregnancy"
/MV774B   "AIDS transmit. during delivery"
/MV774C   "AIDS transmit. by breastfeeding"
/MV775    "Knows someone who has or died of AIDS"
/MV776    "Spoken with spouse about avoiding AIDS"
/MV777    "Allowed to keep AIDS infection secret"
/MV778    "Willing to care for relative with AIDS"
/MV779    "Person with AIDS allowed to-NA"
/MV780    "Should children be taught a-NA"
/MV781    "Ever been tested for AIDS"
/MV782    "Want to be tested for AIDS"
/MV783    "Know a place to get AIDS te-NA"
/MV784    "Where to get an AIDS test  -NA"
/MV785    "Heard about other STDs"
/MV785A   "Man's symptoms of STI"
/MV785B   "Man's symptoms of STI"
/MV785C   "Man's symptoms of STI"
/MV785D   "Man's symptoms of STI"
/MV785E   "Man's symptoms of STI"
/MV785F   "Man's symptoms of STI"
/MV785G   "Man's symptoms of STI"
/MV785H   "Man's symptoms of STI"
/MV785I   "Man's symptoms of STI      -NA"
/MV785J   "Man's symptoms of STI"
/MV785K   "Man's symptoms of STI"
/MV785L   "Man's symptoms of STI"
/MV785M   "Man's symptoms of STI: backpain"
/MV785N   "Man's symptoms of STI: problems walking"
/MV785O   "Man's symptoms of STI: sores / warts on face"
/MV785P   "Man's symptoms of STI: sores / warts on body"
/MV785Q   "Man's symptoms of STI      -NA"
/MV785X   "Man's symptoms of STI"
/MV785Y   "Man's symptoms of STI"
/MV785Z   "Man's symptoms of STI"
/MV786A   "Woman's symptoms of STI"
/MV786B   "Woman's symptoms of STI"
/MV786C   "Woman's symptoms of STI"
/MV786D   "Woman's symptoms of STI"
/MV786E   "Woman's symptoms of STI"
/MV786F   "Woman's symptoms of STI"
/MV786G   "Woman's symptoms of STI"
/MV786H   "Woman's symptoms of STI"
/MV786I   "Woman's symptoms of STI    -NA"
/MV786J   "Woman's symptoms of STI"
/MV786K   "Woman's symptoms of STI"
/MV786L   "Woman's symptoms of STI"
/MV786M   "Woman's symptoms of STI: backpain"
/MV786N   "Woman's symptoms of STI: problems walking"
/MV786O   "Woman's symptoms of STI: sores / warts on face"
/MV786P   "Woman's symptoms of STI: sores /warts on body"
/MV786Q   "Woman's symptoms of STI    -NA"
/MV786X   "Woman's symptoms of STI"
/MV786Y   "Woman's symptoms of STI"
/MV786Z   "Woman's symptoms of STI"
/MV787    "Number of days drunk alcoho-NA"
/MV788    "Number of days gotten drunk-NA"
/MV789    "Number of injections in las-NA"
/MV790    "Person who gave last inject-NA"
/MV791    "Ever paid for sex"
/MV792    "Time since last paid for sex"
/SMINTDG  "Day of interview - gregorian calendar"
/SMINTMG  "Month of interview - gregorian calendar"
/SMINTYG  "Year of interview - gregorian calendar"
/SMINTCG  "Date of interview (CMC) - gregorian calendar"
/SMLAN    "Language of questionnaire"
/SMINTV   "Interview language"
/SMRESP   "Respondent's language"
/SMTRANS  "Translator used"
/SM101T   "Start of interview: time of day"
/SM101H   "Start of interview (hour)"
/SM101M   "Start of interview (minutes)"
/SM105MG  "Month of birth - gregorian calendar"
/SM105YG  "Year of birth - gregorian calendar"
/SM105CG  "Date of birth (CMC) - gregorian calendar"
/SM109    "Highest grade at that level"
/SM203    "Children at home"
/SM205    "Children away"
/SM207    "Children who have died"
/SM211M   "Month of birth of last child (EThiopian calendar)"
/SM211Y   "Year of birth of last child (Ethiopian calendar)"
/SM211C   "CMC - Month of birth of last child (Ethiopian calendar)"
/SM211MG  "Month of birth of last child - gregorian calendar"
/SM211YG  "Year of birth of last child - gregorian calendar"
/SM211CG  "CMC - Month of birth of last child - gregorian calendar"
/SM214    "How much longer would have waited (number)"
/SM309    "Brand of condoms"
/SM310    "Use more condoms than a year ago"
/SM311    "Main reason using more condoms"
/SM312    "Main reason not using a method"
/SM410MG  "Date of first union (month) (gregorian calendar)"
/SM410YG  "Date of first union (year) (Gregorian calendar)"
/SM410CG  "Date of first union (CMC) - gregorian calendar"
/SM411C   "Age at first union(calculated)"
/SM512D   "Saw FP on pamphlet or poster last months"
/SM512E   "Heard FP comminity events last few months"
/SM518A   "Presence of children < 10"
/SM518B   "Presence of spouse"
/SM518C   "Presence of other males"
/SM518D   "Presence of other females"
/SM606A   "Method used during last intercourse: female sterilization"
/SM606B   "Method used during last intercourse: male sterilization"
/SM606C   "Method used during last intercourse: pill"
/SM606D   "Method used during last intercourse: IUD"
/SM606E   "Method used during last intercourse: injections"
/SM606F   "Method used during last intercourse: implants"
/SM606G   "Method used during last intercourse: condom"
/SM606H   "Method used during last intercourse: periodic abstinence"
/SM606I   "Method used during last intercourse: periodic abstinence"
/SM606J   "Method used during last intercourse: withdrawal"
/SM606X   "Method used during last intercourse: other"
/SM613A   'Method last sex with "other" woman: female sterilization'
/SM613B   'Method last sex with "other" woman: male sterilization'
/SM613C   'Method last sex with "other" woman: pill'
/SM613D   'Method last sex with "other" woman: IUD'
/SM613E   'Method last sex with "other" woman: injections'
/SM613F   'Method last sex with "other" woman: implants'
/SM613G   'Method last sex with "other" woman: condom'
/SM613H   'Method last sex with "other" woman: diaphragm/foam/jelly'
/SM613I   'Method last sex with "other" woman: periodic abstinence'
/SM613J   'Method last sex with "other" woman: withdrawal'
/SM613X   'Method last sex with "other" woman: other'
/SM701AA  "From which source heard of AIDS - Radio"
/SM701AB  "From which source heard of AIDS - Television"
/SM701AC  "From which source heard of AIDS - Newspapers/magazines"
/SM701AD  "From which source heard of AIDS - Pamphlets/posters"
/SM701AE  "From which source heard of AIDS - Health workers"
/SM701AF  "From which source heard of AIDS - Mosques/churches"
/SM701AG  "From which source heard of AIDS - Schools/teachers"
/SM701AH  "From which source heard of AIDS - Community event"
/SM701AI  "From which source heard of AIDS - Friends/relatives"
/SM701AJ  "From which source heard of AIDS - Work place"
/SM701AK  "From which source heard of AIDS - Drama/performance"
/SM701AX  "From which source heard of AIDS - Other"
/SM705    "Number of partners and chance of getting AIDS"
/SM708    "Use of condoms and chances of getting AIDS"
/SM712A   "Aids transm. from mother to child: during pregnancy"
/SM712B   "Aids transm. from mother to child: at delivery"
/SM712C   "Aids transm. from mother to child: during breastfeeding"
/SM712D   "Aids transm. from mother to child: other times"
/SM712Z   "Aids transm. from mother to child: Don't know"
/SM733    "Where sought treatment"
/SM736T   "Timing of interview"
/SM736H   "End of interview (hour)"
/SM736M   "End of interview (minutes)"
.
MISSING VALUE
 MV015    (9)
/MV026    (9)
/MV028    (999)
/MV029    (99)
/MV030    (999)
/MV031    (999)
/MV032    (99)
/MV034$1  (99)
/MV034A$1 (9)
/MV034$2  (99)
/MV034A$2 (9)
/MV034$3  (99)
/MV034A$3 (9)
/MV034$4  (99)
/MV034A$4 (9)
/MV034$5  (99)
/MV034A$5 (9)
/MV034$6  (99)
/MV034A$6 (9)
/MV034$7  (99)
/MV034A$7 (9)
/MV034$8  (99)
/MV034A$8 (9)
/MV035    (9)
/MV801    (9999)
/MV802    (9999)
/MV803    (99)
/MV103    (9)
/MV104    (99)
/MV105    (9)
/MV106    (9)
/MV107    (99)
/MV130    (9)
/MV133    (99)
/MV134    (9)
/MV135    (9)
/MV149    (9)
/MV150    (99)
/MV152    (99)
/MV155    (9)
/MV156    (9)
/MV157    (9)
/MV158    (9)
/MV159    (9)
/MV167    (99)
/MV168    (9)
/MV463A   (9)
/MV463B   (9)
/MV463C   (9)
/MV463D   (9)
/MV463E   (9)
/MV463F   (9)
/MV463G   (9)
/MV463Z   (9)
/MV464    (99)
/MV213    (9)
/MV217    (9)
/MV225    (9)
/MV245    (99)
/MV246    (9)
/MV304$01 (9)
/MV305$01 (9)
/MV307$01 (9)
/MV304$02 (9)
/MV305$02 (9)
/MV307$02 (9)
/MV304$03 (9)
/MV305$03 (9)
/MV307$03 (9)
/MV304$04 (9)
/MV305$04 (9)
/MV307$04 (9)
/MV304$05 (9)
/MV305$05 (9)
/MV307$05 (9)
/MV304$06 (9)
/MV305$06 (9)
/MV307$06 (9)
/MV304$07 (9)
/MV305$07 (9)
/MV307$07 (9)
/MV304$08 (9)
/MV305$08 (9)
/MV307$08 (9)
/MV304$09 (9)
/MV305$09 (9)
/MV307$09 (9)
/MV304$10 (9)
/MV305$10 (9)
/MV307$10 (9)
/MV304$11 (9)
/MV305$11 (9)
/MV307$11 (9)
/MV304$12 (9)
/MV305$12 (9)
/MV307$12 (9)
/MV304$13 (9)
/MV305$13 (9)
/MV307$13 (9)
/MV304$14 (9)
/MV305$14 (9)
/MV307$14 (9)
/MV304$15 (9)
/MV305$15 (9)
/MV307$15 (9)
/MV304$16 (9)
/MV305$16 (9)
/MV307$16 (9)
/MV304$17 (9)
/MV305$17 (9)
/MV307$17 (9)
/MV304$18 (9)
/MV305$18 (9)
/MV307$18 (9)
/MV304$19 (9)
/MV305$19 (9)
/MV307$19 (9)
/MV304$20 (9)
/MV305$20 (9)
/MV307$20 (9)
/MV312    (99)
/MV312A   (99)
/MV312B   (99)
/MV312C   (99)
/MV313    (9)
/MV313A   (9)
/MV313B   (9)
/MV313C   (9)
/MV362    (9)
/MV363    (99)
/MV367    (9)
/MV375A   (99)
/MV375B   (99)
/MV375C   (99)
/MV376    (99)
/MV376A   (9)
/MV384A   (9)
/MV384B   (9)
/MV384C   (9)
/MV396    (9)
/MV3B1$1  (9)
/MV3B2A$1 (9)
/MV3B2B$1 (9)
/MV3B2C$1 (9)
/MV3B2D$1 (9)
/MV3B2E$1 (9)
/MV3B2F$1 (9)
/MV3B2G$1 (9)
/MV3B2H$1 (9)
/MV3B2I$1 (9)
/MV3B2J$1 (9)
/MV3B2K$1 (9)
/MV3B2L$1 (9)
/MV3B2X$1 (9)
/MV3B2Z$1 (9)
/MV3B3A$1 (9)
/MV3B3B$1 (9)
/MV3B3C$1 (9)
/MV3B3D$1 (9)
/MV3B3E$1 (9)
/MV3B3F$1 (9)
/MV3B3G$1 (9)
/MV3B3H$1 (9)
/MV3B3I$1 (9)
/MV3B3J$1 (9)
/MV3B3K$1 (9)
/MV3B3L$1 (9)
/MV3B3M$1 (9)
/MV3B3N$1 (9)
/MV3B3X$1 (9)
/MV3B3Z$1 (9)
/MV3B1$2  (9)
/MV3B2A$2 (9)
/MV3B2B$2 (9)
/MV3B2C$2 (9)
/MV3B2D$2 (9)
/MV3B2E$2 (9)
/MV3B2F$2 (9)
/MV3B2G$2 (9)
/MV3B2H$2 (9)
/MV3B2I$2 (9)
/MV3B2J$2 (9)
/MV3B2K$2 (9)
/MV3B2L$2 (9)
/MV3B2X$2 (9)
/MV3B2Z$2 (9)
/MV3B3A$2 (9)
/MV3B3B$2 (9)
/MV3B3C$2 (9)
/MV3B3D$2 (9)
/MV3B3E$2 (9)
/MV3B3F$2 (9)
/MV3B3G$2 (9)
/MV3B3H$2 (9)
/MV3B3I$2 (9)
/MV3B3J$2 (9)
/MV3B3K$2 (9)
/MV3B3L$2 (9)
/MV3B3M$2 (9)
/MV3B3N$2 (9)
/MV3B3X$2 (9)
/MV3B3Z$2 (9)
/MV3B1$3  (9)
/MV3B2A$3 (9)
/MV3B2B$3 (9)
/MV3B2C$3 (9)
/MV3B2D$3 (9)
/MV3B2E$3 (9)
/MV3B2F$3 (9)
/MV3B2G$3 (9)
/MV3B2H$3 (9)
/MV3B2I$3 (9)
/MV3B2J$3 (9)
/MV3B2K$3 (9)
/MV3B2L$3 (9)
/MV3B2X$3 (9)
/MV3B2Z$3 (9)
/MV3B3A$3 (9)
/MV3B3B$3 (9)
/MV3B3C$3 (9)
/MV3B3D$3 (9)
/MV3B3E$3 (9)
/MV3B3F$3 (9)
/MV3B3G$3 (9)
/MV3B3H$3 (9)
/MV3B3I$3 (9)
/MV3B3J$3 (9)
/MV3B3K$3 (9)
/MV3B3L$3 (9)
/MV3B3M$3 (9)
/MV3B3N$3 (9)
/MV3B3X$3 (9)
/MV3B3Z$3 (9)
/MV3B1$4  (9)
/MV3B2A$4 (9)
/MV3B2B$4 (9)
/MV3B2C$4 (9)
/MV3B2D$4 (9)
/MV3B2E$4 (9)
/MV3B2F$4 (9)
/MV3B2G$4 (9)
/MV3B2H$4 (9)
/MV3B2I$4 (9)
/MV3B2J$4 (9)
/MV3B2K$4 (9)
/MV3B2L$4 (9)
/MV3B2X$4 (9)
/MV3B2Z$4 (9)
/MV3B3A$4 (9)
/MV3B3B$4 (9)
/MV3B3C$4 (9)
/MV3B3D$4 (9)
/MV3B3E$4 (9)
/MV3B3F$4 (9)
/MV3B3G$4 (9)
/MV3B3H$4 (9)
/MV3B3I$4 (9)
/MV3B3J$4 (9)
/MV3B3K$4 (9)
/MV3B3L$4 (9)
/MV3B3M$4 (9)
/MV3B3N$4 (9)
/MV3B3X$4 (9)
/MV3B3Z$4 (9)
/MV3B1$5  (9)
/MV3B2A$5 (9)
/MV3B2B$5 (9)
/MV3B2C$5 (9)
/MV3B2D$5 (9)
/MV3B2E$5 (9)
/MV3B2F$5 (9)
/MV3B2G$5 (9)
/MV3B2H$5 (9)
/MV3B2I$5 (9)
/MV3B2J$5 (9)
/MV3B2K$5 (9)
/MV3B2L$5 (9)
/MV3B2X$5 (9)
/MV3B2Z$5 (9)
/MV3B3A$5 (9)
/MV3B3B$5 (9)
/MV3B3C$5 (9)
/MV3B3D$5 (9)
/MV3B3E$5 (9)
/MV3B3F$5 (9)
/MV3B3G$5 (9)
/MV3B3H$5 (9)
/MV3B3I$5 (9)
/MV3B3J$5 (9)
/MV3B3K$5 (9)
/MV3B3L$5 (9)
/MV3B3M$5 (9)
/MV3B3N$5 (9)
/MV3B3X$5 (9)
/MV3B3Z$5 (9)
/MV3B11   (99)
/MV3B12A  (9)
/MV3B12B  (9)
/MV3B12C  (9)
/MV3B12D  (9)
/MV3B12E  (9)
/MV3B12F  (9)
/MV3B12G  (9)
/MV3B12H  (9)
/MV3B12X  (9)
/MV3B13   (9)
/MV3B14A  (9)
/MV3B14B  (9)
/MV3B14C  (9)
/MV3B14D  (9)
/MV3B14E  (9)
/MV3B14F  (9)
/MV3B14G  (9)
/MV3B14H  (9)
/MV3B14I  (9)
/MV3B14J  (9)
/MV3B14X  (9)
/MV3B15A  (9)
/MV3B15B  (9)
/MV3B15C  (9)
/MV3B15D  (9)
/MV3B15E  (9)
/MV3B15F  (9)
/MV3B15G  (9)
/MV3B15H  (9)
/MV3B15I  (9)
/MV3B15J  (9)
/MV3B15K  (9)
/MV3B15L  (9)
/MV3B15M  (9)
/MV3B15X  (9)
/MV3B15Y  (9)
/MV3B16   (99)
/MV3B17   (99)
/MV3B18   (999999)
/MV3B19   (999)
/MV3B20   (9)
/MV3B21A  (9)
/MV3B21B  (9)
/MV3B21C  (9)
/MV3B21D  (9)
/MV3B21E  (9)
/MV3B22   (9)
/MV3B23A  (9)
/MV3B23B  (9)
/MV3B23C  (9)
/MV3B23D  (9)
/MV3B23E  (9)
/MV3B23F  (9)
/MV3B23G  (9)
/MV3B23H  (9)
/MV3B23I  (9)
/MV3B23J  (9)
/MV3B23K  (9)
/MV3B23X  (9)
/MV3B24A  (9)
/MV3B24B  (9)
/MV3B24C  (9)
/MV3B24D  (9)
/MV3B24E  (9)
/MV3B24F  (9)
/MV3B24G  (9)
/MV3B24H  (9)
/MV3B24I  (9)
/MV3B24J  (9)
/MV3B24K  (9)
/MV3B24L  (9)
/MV3B24X  (9)
/MV3B25A  (9)
/MV3B25B  (9)
/MV3B25C  (9)
/MV3B25D  (9)
/MV501    (9)
/MV502    (9)
/MV503    (9)
/MV505    (99)
/MV505A   (99)
/MV505B   (99)
/MV525    (99)
/MV527    (999)
/MV531    (99)
/MV534    (9)
/MV534A   (9)
/MV535    (9)
/MV536    (9)
/MV538    (99)
/MV539    (9)
/MV602    (9)
/MV603    (999)
/MV604    (9)
/MV605    (9)
/MV610    (9)
/MV611    (9)
/MV612    (9)
/MV613    (99)
/MV616    (999)
/MV621    (9)
/MV627    (99)
/MV628    (99)
/MV629    (99)
/MV630A   (9)
/MV630B   (9)
/MV630C   (9)
/MV630D   (9)
/MV630E   (9)
/MV630F   (9)
/MV630G   (9)
/MV630H   (9)
/MV630I   (9)
/MV630J   (9)
/MV630K   (9)
/MV630L   (9)
/MV630M   (9)
/MV630N   (9)
/MV630O   (9)
/MV630X   (9)
/MV631    (9)
/MV633A   (9)
/MV633B   (9)
/MV633C   (9)
/MV633D   (9)
/MV633E   (9)
/MV633F   (9)
/MV633G   (9)
/MV634A   (9)
/MV634B   (9)
/MV634C   (9)
/MV634D   (9)
/MV635    (9)
/MV636    (9)
/MV637    (9)
/MV638    (99)
/MV641$1  (99)
/MV642$1  (9)
/MV643$1  (9)
/MV644$1  (9)
/MV645$1  (9)
/MV646$1  (9)
/MV647$1  (9)
/MV641$2  (99)
/MV642$2  (9)
/MV643$2  (9)
/MV644$2  (9)
/MV645$2  (9)
/MV646$2  (9)
/MV647$2  (9)
/MV641$3  (99)
/MV642$3  (9)
/MV643$3  (9)
/MV644$3  (9)
/MV645$3  (9)
/MV646$3  (9)
/MV647$3  (9)
/MV641$4  (99)
/MV642$4  (9)
/MV643$4  (9)
/MV644$4  (9)
/MV645$4  (9)
/MV646$4  (9)
/MV647$4  (9)
/MV641$5  (99)
/MV642$5  (9)
/MV643$5  (9)
/MV644$5  (9)
/MV645$5  (9)
/MV646$5  (9)
/MV647$5  (9)
/MV641$6  (99)
/MV642$6  (9)
/MV643$6  (9)
/MV644$6  (9)
/MV645$6  (9)
/MV646$6  (9)
/MV647$6  (9)
/MV641$7  (99)
/MV642$7  (9)
/MV643$7  (9)
/MV644$7  (9)
/MV645$7  (9)
/MV646$7  (9)
/MV647$7  (9)
/MV641$8  (99)
/MV642$8  (9)
/MV643$8  (9)
/MV644$8  (9)
/MV645$8  (9)
/MV646$8  (9)
/MV647$8  (9)
/MV648    (9)
/MV649A   (9)
/MV649B   (9)
/MV649C   (9)
/MV714    (9)
/MV716    (999)
/MV717    (99)
/MV719    (9)
/MV721    (9)
/MV731    (9)
/MV732    (9)
/MV733    (99)
/MV740    (9)
/MV741    (9)
/MV742    (9)
/MV743A   (9)
/MV743B   (9)
/MV743C   (9)
/MV743D   (9)
/MV743E   (9)
/MV743F   (9)
/MV743G   (9)
/MV744A   (9)
/MV744B   (9)
/MV744C   (9)
/MV744D   (9)
/MV744E   (9)
/MV745    (99)
/MV750    (9)
/MV751    (9)
/MV753    (9)
/MV754A   (9)
/MV754B   (9)
/MV754C   (9)
/MV754D   (9)
/MV754E   (9)
/MV754F   (9)
/MV754G   (9)
/MV754H   (9)
/MV754I   (9)
/MV754J   (9)
/MV754K   (9)
/MV754L   (9)
/MV754M   (9)
/MV754N   (9)
/MV754O   (9)
/MV754P   (9)
/MV754Q   (9)
/MV754R   (9)
/MV754S   (9)
/MV754T   (9)
/MV754U   (9)
/MV754V   (9)
/MV754X   (9)
/MV754Z   (9)
/MV754CP  (9)
/MV754DP  (9)
/MV754JP  (9)
/MV754WP  (9)
/MV756    (9)
/MV759A   (9)
/MV759B   (9)
/MV759C   (9)
/MV759D   (9)
/MV759E   (9)
/MV759F   (9)
/MV759G   (9)
/MV759H   (9)
/MV759I   (9)
/MV761    (9)
/MV761B   (9)
/MV761C   (9)
/MV761D   (9)
/MV762AA  (9)
/MV762AB  (9)
/MV762AC  (9)
/MV762AD  (9)
/MV762AE  (9)
/MV762AF  (9)
/MV762AG  (9)
/MV762AH  (9)
/MV762AI  (9)
/MV762AJ  (9)
/MV762AK  (9)
/MV762AL  (9)
/MV762AM  (9)
/MV762AN  (9)
/MV762AO  (9)
/MV762AP  (9)
/MV762AQ  (9)
/MV762AR  (9)
/MV762AS  (9)
/MV762AT  (9)
/MV762AU  (9)
/MV762AV  (9)
/MV762AW  (9)
/MV762AX  (9)
/MV762AZ  (9)
/MV762BA  (9)
/MV762BB  (9)
/MV762BC  (9)
/MV762BD  (9)
/MV762BE  (9)
/MV762BF  (9)
/MV762BG  (9)
/MV762BH  (9)
/MV762BI  (9)
/MV762BJ  (9)
/MV762BK  (9)
/MV762BL  (9)
/MV762BM  (9)
/MV762BN  (9)
/MV762BO  (9)
/MV762BP  (9)
/MV762BQ  (9)
/MV762BR  (9)
/MV762BS  (9)
/MV762BT  (9)
/MV762BU  (9)
/MV762BV  (9)
/MV762BW  (9)
/MV762BX  (9)
/MV762BZ  (9)
/MV763A   (9)
/MV763B   (9)
/MV763C   (9)
/MV763D   (9)
/MV763E   (9)
/MV763F   (9)
/MV763G   (9)
/MV765A   (9)
/MV765B   (9)
/MV765C   (9)
/MV766A   (99)
/MV766B   (99)
/MV767A   (99)
/MV767B   (99)
/MV767C   (99)
/MV768A   (999)
/MV768B   (999)
/MV768C   (999)
/MV769    (9)
/MV769A   (9)
/MV770    (9)
/MV770A   (9)
/MV770B   (9)
/MV770C   (9)
/MV770D   (9)
/MV770E   (9)
/MV770F   (9)
/MV770G   (9)
/MV770H   (9)
/MV770I   (9)
/MV771    (9)
/MV772    (9)
/MV773A   (9)
/MV773B   (9)
/MV773C   (9)
/MV773D   (9)
/MV773E   (9)
/MV773F   (9)
/MV773X   (9)
/MV774    (9)
/MV774A   (9)
/MV774B   (9)
/MV774C   (9)
/MV775    (9)
/MV776    (9)
/MV777    (9)
/MV778    (9)
/MV779    (9)
/MV780    (9)
/MV781    (9)
/MV782    (9)
/MV783    (9)
/MV784    (99)
/MV785    (9)
/MV785A   (9)
/MV785B   (9)
/MV785C   (9)
/MV785D   (9)
/MV785E   (9)
/MV785F   (9)
/MV785G   (9)
/MV785H   (9)
/MV785I   (9)
/MV785J   (9)
/MV785K   (9)
/MV785L   (9)
/MV785M   (9)
/MV785N   (9)
/MV785O   (9)
/MV785P   (9)
/MV785Q   (9)
/MV785X   (9)
/MV785Y   (9)
/MV785Z   (9)
/MV786A   (9)
/MV786B   (9)
/MV786C   (9)
/MV786D   (9)
/MV786E   (9)
/MV786F   (9)
/MV786G   (9)
/MV786H   (9)
/MV786I   (9)
/MV786J   (9)
/MV786K   (9)
/MV786L   (9)
/MV786M   (9)
/MV786N   (9)
/MV786O   (9)
/MV786P   (9)
/MV786Q   (9)
/MV786X   (9)
/MV786Y   (9)
/MV786Z   (9)
/MV787    (99)
/MV788    (99)
/MV789    (99)
/MV790    (9)
/MV791    (9)
/MV792    (999)
/SMLAN    (9)
/SMINTV   (9)
/SMRESP   (9)
/SMTRANS  (9)
/SM101T   (9)
/SM101H   (99)
/SM101M   (99)
/SM105MG  (99)
/SM105YG  (9999)
/SM109    (99)
/SM211M   (99)
/SM211Y   (9999)
/SM211MG  (99)
/SM211YG  (9999)
/SM214    (999)
/SM309    (99)
/SM310    (9)
/SM311    (9)
/SM312    (99)
/SM410MG  (99)
/SM410YG  (9999)
/SM512D   (9)
/SM512E   (9)
/SM518A   (9)
/SM518B   (9)
/SM518C   (9)
/SM518D   (9)
/SM606A   (9)
/SM606B   (9)
/SM606C   (9)
/SM606D   (9)
/SM606E   (9)
/SM606F   (9)
/SM606G   (9)
/SM606H   (9)
/SM606I   (9)
/SM606J   (9)
/SM606X   (9)
/SM613A   (9)
/SM613B   (9)
/SM613C   (9)
/SM613D   (9)
/SM613E   (9)
/SM613F   (9)
/SM613G   (9)
/SM613H   (9)
/SM613I   (9)
/SM613J   (9)
/SM613X   (9)
/SM701AA  (9)
/SM701AB  (9)
/SM701AC  (9)
/SM701AD  (9)
/SM701AE  (9)
/SM701AF  (9)
/SM701AG  (9)
/SM701AH  (9)
/SM701AI  (9)
/SM701AJ  (9)
/SM701AK  (9)
/SM701AX  (9)
/SM705    (9)
/SM708    (9)
/SM712A   (9)
/SM712B   (9)
/SM712C   (9)
/SM712D   (9)
/SM712Z   (9)
/SM733    (99)
/SM736H   (99)
/SM736M   (99)
.
VALUE LABELS
 MV013
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
/MV014
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV015
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
/MV023
     1 "Tigray, urban"
     2 "Tigray, rural"
     3 "Afar, urban"
     4 "Afar, rural"
     5 "Amhara, urban"
     6 "Amhara, rural"
     7 "Oromiya, urban"
     8 "Oromiya, rural"
     9 "Somali, urban"
    10 "Somali, rural"
    11 "Ben-Gumz, urban"
    12 "Ben-Gumz, rural"
    13 "SNNP, urban"
    14 "SNNP, rural"
    15 "Gambela, urban"
    16 "Gambela, rural"
    17 "Harrari, urban"
    18 "Harrari, rural"
    19 "Addis, urban"
    20 "Dire Dawa, urban"
    21 "Dire Dawa, rural"
/MV024
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harrari"
    14 "Addis"
    15 "Dire Dawa"
/MV025
     1 "Urban"
     2 "Rural"
/MV026
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV034$1
     0 "Wife not in HH"
/MV034$2
     0 "Wife not in HH"
/MV034$3
     0 "Wife not in HH"
/MV034$4
     0 "Wife not in HH"
/MV034$5
     0 "Wife not in HH"
/MV034$6
     0 "Wife not in HH"
/MV034$7
     0 "Wife not in HH"
/MV034$8
     0 "Wife not in HH"
/MV035
     0 "No wives/partners"
/MV803
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
/MV101
     1 "Tigray"
     2 "Afar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harrari"
    14 "Addis"
    15 "Dire Dawa"
/MV102
     1 "Urban"
     2 "Rural"
/MV103
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/MV104
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
/MV105
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/MV106
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/MV130
     1 "Orthodox"
     2 "Catholic"
     3 "Protestant"
     4 "Moslem"
     5 "Traditional"
     6 "Other"
/MV131
     1 "Affar"
     4 "Amharra"
    25 "Guragie"
    60 "Oromo"
    67 "Sidama"
    68 "Somalie"
    70 "Tigray (Tigraway)"
    72 "Welaita"
    96 "Other"
/MV133
    97 "Inconsistent"
/MV134
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV135
     1 "Usual resident"
     2 "Visitor"
/MV149
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
/MV150
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/MV151
     1 "Male"
     2 "Female"
/MV152
    97 "97+"
    98 "DK"
/MV155
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
/MV157
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
/MV158
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
/MV159
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
/MV213
     0 "No"
     1 "Yes"
     8 "Unsure"
/MV225
     1 "Then"
     2 "Later"
     3 "Not at all"
/MV301
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
/MV302
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
/M304A$01
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A01
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$01
     0 "No"
     1 "Yes"
/MV307$01
     0 "No"
     1 "Yes"
/M304A$02
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A02
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$02
     0 "No"
     1 "Yes"
/MV307$02
     0 "No"
     1 "Yes"
/M304A$03
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A03
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$03
     0 "No"
     1 "Yes"
/MV307$03
     0 "No"
     1 "Yes"
/M304A$04
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A04
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$04
     0 "No"
     1 "Yes"
/MV307$04
     0 "No"
     1 "Yes"
/M304A$05
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A05
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$05
     0 "No"
     1 "Yes"
/MV307$05
     0 "No"
     1 "Yes"
/M304A$06
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A06
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$06
     0 "No"
     1 "Yes"
/MV307$06
     0 "No"
     1 "Yes"
/M304A$07
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A07
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$07
     0 "No"
     1 "Yes"
/MV307$07
     0 "No"
     1 "Yes"
/M304A$08
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A08
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$08
     0 "No"
     1 "Yes"
/MV307$08
     0 "No"
     1 "Yes"
/M304A$09
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A09
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$09
     0 "No"
     1 "Yes"
/MV307$09
     0 "No"
     1 "Yes"
/M304A$10
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A10
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$10
     0 "No"
     1 "Yes"
/MV307$10
     0 "No"
     1 "Yes"
/M304A$11
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A11
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$11
     0 "No"
     1 "Yes"
/MV307$11
     0 "No"
     1 "Yes"
/M304A$12
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A12
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$12
     0 "No"
     1 "Yes"
/MV307$12
     0 "No"
     1 "Yes"
/M304A$13
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A13
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$13
     0 "No"
     1 "Yes"
/MV307$13
     0 "No"
     1 "Yes"
/M304A$14
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A14
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$14
     0 "No"
     1 "Yes"
/MV307$14
     0 "No"
     1 "Yes"
/M304A$15
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304A15
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$15
     0 "No"
     1 "Yes"
/MV307$15
     0 "No"
     1 "Yes"
/M304A$16
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$16
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$16
     0 "No"
     1 "Yes"
/MV307$16
     0 "No"
     1 "Yes"
/M304A$17
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$17
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$17
     0 "No"
     1 "Yes"
/MV307$17
     0 "No"
     1 "Yes"
/M304A$18
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$18
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$18
     0 "No"
     1 "Yes"
/MV307$18
     0 "No"
     1 "Yes"
/M304A$19
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$19
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$19
     0 "No"
     1 "Yes"
/MV307$19
     0 "No"
     1 "Yes"
/M304A$20
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$20
     0 "No"
     1 "Yes"
     8 "Not asked"
/MV305$20
     0 "No"
     1 "Yes"
/MV307$20
     0 "No"
     1 "Yes"
/MV312
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
/MV312A
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
/MV312B
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
/MV313
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
/MV313A
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
/MV313B
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
/MV361
     1 "Currently using"
     2 "Used in last 12 months"
     3 "Ever used"
     4 "Never used"
/MV362
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
/MV364
     1 "Using modern method"
     2 "Using traditional method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
/MV367
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
/MV376
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
/MV384A
     0 "No"
     1 "Yes"
/MV384B
     0 "No"
     1 "Yes"
/MV384C
     0 "No"
     1 "Yes"
/MV501
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
/MV502
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
/MV503
     1 "Once"
     2 "More than once"
/MV510
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV513
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
/MV525
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
/MV527
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
/MV531
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
/MV532
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
/MV534
     0 "No sexual partner"
     1 "Regular sexual partner"
     2 "Occasional sexual partner"
/MV535
     0 "No"
     1 "Formerly married"
     2 "Lived with a woman"
/MV536
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
/MV602
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infecund"
     6 "Never had sex"
     7 "Man declared infecund"
/MV603
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
/MV604
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
/MV605
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
/MV612
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/MV613
    95 "As God wishes"
    96 "Non-numeric response"
    98 "DK"
/MV614
     6 "6+"
     7 "Non-numeric response"
/MV616
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
/MV627
    95 "As God wishes"
    96 "Other"
    98 "DK"
/MV628
    95 "As God wishes"
    96 "Other"
    98 "DK"
/MV629
    95 "As God wishes"
    96 "Other"
    98 "DK"
/MV641$1
     0 "Wife not in HH"
/MV641$2
     0 "Wife not in HH"
/MV641$3
     0 "Wife not in HH"
/MV641$4
     0 "Wife not in HH"
/MV641$5
     0 "Wife not in HH"
/MV641$6
     0 "Wife not in HH"
/MV641$7
     0 "Wife not in HH"
/MV641$8
     0 "Wife not in HH"
/MV714
     0 "No"
     1 "Yes"
/MV716
     0 "Student, pensioners"
    11 "Legislators and senior officials"
    12 "Corporate managers"
    13 "Other general managers"
    21 "Physical, mathemat., engineering science prof."
    22 "Life science and health prof."
    23 "Teaching professionals"
    24 "Other assoc. professionals"
    31 "Physical and engineering science ass. prof."
    32 "Life science and health assoc. prof."
    33 "Teaching assoc. prof."
    34 "Other assoc. prof."
    41 "Office clerks"
    42 "Customer service clerk"
    51 "Personal and protective service workers"
    52 "Models, sales persons and demonstrators"
    61 "Market oriented skilled agric. and fisher workers"
    62 "Subsistence agric. and fisher workers"
    71 "Extraction and building trade workers"
    72 "Metal, machin. and rel. trade workers"
    73 "Precision, handicraft, printing and rel. workers"
    74 "Other craft and related trade workers"
    81 "Stationary plant and related workers"
    82 "Machine operators and assemblers"
    83 "Drivers and Mobil plant operators"
    91 "Sales and service elementary occupation"
    92 "Agric. and fishery and rel. workers"
    93 "Labourers in mining, construction, manuf. and transport"
    96 "Other"
/MV717
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
/MV731
     0 "No"
     1 "In the past year"
     2 "Currently working"
/MV744A
     0 "No"
     1 "Yes"
     8 "Don't know"
/MV744B
     0 "No"
     1 "Yes"
     8 "Don't know"
/MV744C
     0 "No"
     1 "Yes"
     8 "Don't know"
/MV744D
     0 "No"
     1 "Yes"
     8 "Don't know"
/MV744E
     0 "No"
     1 "Yes"
     8 "Don't know"
/MV750
     0 "No"
     1 "Yes"
     8 "DK"
/MV751
     0 "No"
     1 "Yes"
/MV753
     0 "No"
     1 "Yes"
     8 "DK"
/MV754B
     0 "No"
     1 "Abstain from sex"
     8 "DK"
/MV754C
     0 "No"
     1 "Condoms during sex"
     8 "DK"
/MV754D
     0 "No"
     1 "Only one sex partner"
     8 "DK"
/MV754E
     0 "No"
     1 "Avoid prostitutes"
     8 "DK"
/MV754F
     0 "No"
     1 "Avoid homosexuals"
     8 "DK"
/MV754G
     0 "No"
     1 "Avoid blood transfus"
     8 "DK"
/MV754H
     0 "No"
     1 "Avoid injections"
     8 "DK"
/MV754I
     0 "No"
     1 "Avoid kissing"
     8 "DK"
/MV754J
     0 "No"
     1 "Avoid mosquito bites"
     8 "DK"
/MV754K
     0 "No"
     1 "Seek trad. healing"
     8 "DK"
/MV754L
     0 "No"
     1 "Limit number of sex partners"
     8 "DK"
/MV754M
     0 "No"
     1 "Avoid partners who have many partners"
     8 "DK"
/MV754N
     0 "No"
     1 "Avoid sex with intravenous drug users"
     8 "DK"
/MV754O
     0 "No"
     1 "Avoid sharing razor blades with AIDS patient"
     8 "DK"
/MV754P
     0 "No"
     1 "Avoid sharing household utensils"
     8 "DK"
/MV754X
     0 "No"
     1 "Other responses"
     8 "DK"
/MV754Z
     0 "No: knows ways"
     1 "Yes: DK ways"
/MV754CP
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
/MV754DP
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partnr with no oth partner"
     8 "Don't know"
/MV756
     0 "No"
     1 "Yes"
     8 "DK"
/MV761
     0 "No"
     1 "Yes"
     8 "DK"
/MV761B
     0 "No"
     1 "Yes"
     8 "DK"
/MV761D
     0 "No"
     1 "Yes"
     8 "DK"
/MV763A
     0 "No"
     1 "Yes"
     8 "DK"
/MV763B
     0 "No"
     1 "Yes"
     8 "DK"
/MV763C
     0 "No"
     1 "Yes"
     8 "DK"
/MV765A
     0 "Did not use condom"
     1 "To prevent STD"
     2 "To avoid pregnancy"
     3 "Avoid both STD and pregnancy"
     4 "Does not trust partner"
     5 "Partner requested/insisted"
     6 "Other"
     8 "Don't know"
/MV765B
     0 "Did not use condom"
     1 "To prevent STD"
     2 "To avoid pregnancy"
     3 "Avoid both STD and pregnancy"
     4 "Does not trust partner"
     5 "Partner requested/insisted"
     6 "Other"
     8 "Don't know"
/MV766A
    98 "DK"
/MV766B
    98 "DK"
/MV767A
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
    96 "Other"
/MV767B
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
    96 "Other"
/MV768A
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
/MV768B
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
/MV770
     0 "No"
     1 "Yes"
/MV770A
     0 "No"
     1 "Clinic/hospital/private doctor"
/MV770C
     0 "No"
     1 "Shop/pharmacy"
/MV771
     0 "No"
     1 "Yes"
     2 "Some/not all"
     3 "No partner"
/MV772
     0 "No"
     1 "Yes"
     2 "Partner already infect"
     3 "Not having sex at the time"
/MV773A
     0 "No"
     1 "No sexual intercourse"
     2 "Partner already infected"
     3 "Not having sex at the time"
/MV773B
     0 "No"
     1 "Used condoms"
     2 "Partner already infected"
     3 "Not having sex at the time"
/MV773D
     0 "No"
     1 "CS: wash penis before sex"
     2 "Partner already infected"
     3 "Not having sex at the time"
/MV773E
     0 "No"
     1 "CS: Reduce frequency of sexual intercourse"
     2 "Partner already infected"
     3 "Not having sex at the time"
/MV773X
     0 "No"
     1 "Other"
/MV774
     0 "No"
     1 "Yes"
     8 "DK"
/MV774A
     0 "No"
     1 "Yes"
     8 "DK"
/MV774B
     0 "No"
     1 "Yes"
     8 "DK"
/MV774C
     0 "No"
     1 "Yes"
     8 "DK"
/MV775
     0 "No"
     1 "Yes"
     8 "DK"
/MV776
     0 "No"
     1 "Yes"
/MV777
     0 "No"
     1 "Yes"
     8 "DK"
/MV778
     0 "No"
     1 "Yes"
     8 "DK"
/MV781
     0 "No"
     1 "Yes"
/MV782
     0 "No"
     1 "Yes"
     8 "DK"
/MV785
     0 "No"
     1 "Yes"
/MV785A
     0 "No"
     1 "Abdominal pain"
/MV785B
     0 "No"
     1 "Genital discharge/dripping"
/MV785C
     0 "No"
     1 "Foul smelling discharge"
/MV785D
     0 "No"
     1 "Burning pain during urination"
/MV785E
     0 "No"
     1 "Redness/inflamation"
/MV785F
     0 "No"
     1 "Swelling"
/MV785G
     0 "No"
     1 "Sores/ulcers"
/MV785H
     0 "No"
     1 "Warts"
/MV785J
     0 "No"
     1 "Blood in urine"
/MV785K
     0 "No"
     1 "Weight loss"
/MV785L
     0 "No"
     1 "Impotence"
/MV785M
     0 "No"
     1 "Backpain"
/MV785N
     0 "No"
     1 "Problems walking"
/MV785O
     0 "No"
     1 "Sores / warts on face"
/MV785P
     0 "No"
     1 "Sores / warts on body"
/MV785X
     0 "No"
     1 "Other"
/MV785Y
     0 "Yes, has symptoms"
     1 "No symptoms"
/MV785Z
     0 "Knows symptoms"
     1 "Don't know symptoms"
/MV786A
     0 "No"
     1 "Abdominal pain"
/MV786B
     0 "No"
     1 "Genital discharge"
/MV786C
     0 "No"
     1 "Foul smelling discharge"
/MV786D
     0 "No"
     1 "Buring pain during urination"
/MV786E
     0 "No"
     1 "Redness/inflamation"
/MV786F
     0 "No"
     1 "Swelling"
/MV786G
     0 "No"
     1 "Sores/ulcers"
/MV786H
     0 "No"
     1 "Warts"
/MV786J
     0 "No"
     1 "Blood in urine"
/MV786K
     0 "No"
     1 "Weight loss"
/MV786L
     0 "No"
     1 "Hard to get pregnant"
/MV786M
     0 "No"
     1 "Backpain"
/MV786N
     0 "No"
     1 "Problems walking"
/MV786O
     0 "No"
     1 "Sores / warts on face"
/MV786P
     0 "No"
     1 "Sores / warts on body"
/MV786X
     0 "No"
     1 "Other"
/MV786Y
     0 "Yes has symptoms"
     1 "No symptoms"
/MV786Z
     0 "Knows symptoms"
     1 "Don't know symptoms"
/MV791
     0 "No"
     1 "Yes"
/MV792
   101 "One day"
   201 "One week"
   301 "One month"
   401 "One year"
   998 "Don't know"
/SMLAN
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
/SMINTV
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
/SMRESP
     1 "Amarigna"
     2 "Oromigna"
     3 "Tigrigna"
     4 "Somaligna"
     5 "Afarigna"
     6 "Other"
/SMTRANS
     0 "No"
     1 "Yes"
/SM101T
     1 "Morning"
     2 "Evening"
/SM101H
    97 "Inconsistent"
/SM101M
    97 "Inconsistent"
/SM105MG
    97 "Inconsistent"
    98 "DK month"
/SM105YG
  9997 "Inconsistent"
  9998 "DK year"
/SM211M
    97 "Inconsistent"
    98 "DK"
/SM211Y
  9997 "Inconsistent"
  9998 "DK"
/SM211MG
    97 "Inconsistent"
    98 "DK"
/SM211YG
  9997 "Inconsistent"
  9998 "DK"
/SM214
   101 "1 month"
   201 "1 year"
   998 "DK"
/SM309
     1 "Hiwot"
     2 "Sensations"
     3 "Durex"
     4 "Rose"
    95 "No brand name"
    96 "Other"
    98 "DK"
/SM310
     1 "More"
     2 "Same"
     3 "Fewer"
/SM311
     1 "Fear of getting AIDS"
     2 "Fear of getting other STD's"
     3 "Family planning"
     4 "Less expensive now"
     5 "More available now"
     6 "Increased sexual activity"
     7 "Other"
     8 "DK"
/SM312
    11 "Not married"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    41 "Knows no method"
    42 "Knows no source"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
/SM410MG
    97 "Inconsistent"
    98 "DK month"
/SM410YG
  9997 "Inconsistent"
  9998 "DK year"
/SM512D
     0 "No"
     1 "Yes"
/SM512E
     0 "No"
     1 "Yes"
/SM518A
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
/SM518B
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
/SM518C
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
/SM518D
     0 "Not present"
     1 "Yes - listened"
     2 "Yes - did not listen"
/SM606A
     0 "No"
     1 "Method used: female sterilization"
     8 "Don't know"
/SM606B
     0 "No"
     1 "Method used: male sterilization"
     8 "Don't know"
/SM606C
     0 "No"
     1 "Method used: pill"
     8 "Don't know"
/SM606D
     0 "No"
     1 "Method used: IUD"
     8 "Don't know"
/SM606E
     0 "No"
     1 "Method used: injections"
     8 "Don't know"
/SM606F
     0 "No"
     1 "Method used: implants"
     8 "Don't know"
/SM606G
     0 "No"
     1 "Method used: condom"
     8 "Don't know"
/SM606H
     0 "No"
     1 "Method used: periodic abstinence"
     8 "Don't know"
/SM606I
     0 "No"
     1 "Method used: periodic abstinence"
     8 "Don't know"
/SM606J
     0 "No"
     1 "Method used: withdrawal"
     8 "Don't know"
/SM606X
     0 "No"
     1 "Method used: other"
     8 "Don't know"
/SM613A
     0 "No"
     1 'Method last sex with "other" woman: female sterilization'
     8 "Don't know"
/SM613B
     0 "No"
     1 'Method last sex with "other" woman: male sterilization'
     8 "Don't know"
/SM613C
     0 "No"
     1 'Method last sex with "other" woman: pill'
     8 "Don't know"
/SM613D
     0 "No"
     1 'Method last sex with "other" woman: IUD'
     8 "Don't know"
/SM613E
     0 "No"
     1 'Method last sex with "other" woman: injections'
     8 "Don't know"
/SM613F
     0 "No"
     1 'Method last sex with "other" woman: implants'
     8 "Don't know"
/SM613G
     0 "No"
     1 'Method last sex with "other" woman: condom'
     8 "Don't know"
/SM613H
     0 "No"
     1 'Method last sex with "other" woman: diaphragm/foam/jelly'
     8 "Don't know"
/SM613I
     0 "No"
     1 'Method last sex with "other" woman: periodic abstinence'
     8 "Don't know"
/SM613J
     0 "No"
     1 'Method last sex with "other" woman: withdrawal'
     8 "Don't know"
/SM613X
     0 "No"
     1 'Method last sex with "other" woman: other'
     8 "Don't know"
/SM701AA
     0 "No"
     1 "Yes"
/SM701AB
     0 "No"
     1 "Yes"
/SM701AC
     0 "No"
     1 "Yes"
/SM701AD
     0 "No"
     1 "Yes"
/SM701AE
     0 "No"
     1 "Yes"
/SM701AF
     0 "No"
     1 "Yes"
/SM701AG
     0 "No"
     1 "Yes"
/SM701AH
     0 "No"
     1 "Yes"
/SM701AI
     0 "No"
     1 "Yes"
/SM701AJ
     0 "No"
     1 "Yes"
/SM701AK
     0 "No"
     1 "Yes"
/SM701AX
     0 "No"
     1 "Yes"
/SM705
     0 "No"
     1 "Yes"
     8 "DK"
/SM708
     1 "Decreases"
     2 "Increases"
     3 "No difference"
     8 "DK/Unsure"
/SM712A
     0 "No"
     1 "Yes"
/SM712B
     0 "No"
     1 "Yes"
/SM712C
     0 "No"
     1 "Yes"
/SM712D
     0 "No"
     1 "Yes"
/SM712Z
     0 "No"
     1 "Yes"
/SM733
    11 "Government hospital"
    12 "Government health center"
    13 "Government health station/clinic"
    14 "Health post"
    16 "Other public"
    21 "NGO health facility"
    26 "Other NGO"
    31 "Private hosp."
    32 "Private doctor"
    33 "Pharmacy"
    36 "Other private medical"
    41 "Work place facility"
    96 "Other"
/SM736T
     1 "Morning"
     2 "Evening"
/SM736H
    97 "Inconsistent"
/SM736M
    97 "Inconsistent"
.
