infix using ETPR41FL.dct

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv033    "Ultimate area selection prob."
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters -NA"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglobin"
label variable hv043    "Selection for women's status module"
label variable hv044    "Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator           -NA"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material         -NA"
label variable hv215    "Main roof material"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Have bednet for sleeping"
label variable hv228    "Children under 5 slept unde-NA"
label variable hv230    "Place for hand washing     -NA"
label variable hv231    "Items present: Water, tap  -NA"
label variable hv232    "Items present: soap/other c-NA"
label variable hv233    "Items present: Basin       -NA"
label variable hv234    "Test salt for Iodine       -NA"
label variable shintd   "Day of household interview - Gregorian calendar"
label variable shintm   "Month of household interview - Gregorian calendar"
label variable shinty   "Year of household interview - Gregorian calendar"
label variable shintc   "Date of HH interview (CMC) - Gregorian calendar"
label variable sh25e    "Household has an electric mitad"
label variable sh25f    "Household has a kerosene lamp/pressure lamp"
label variable sh25g    "Household has a bed/table"
label variable sh25aa   "Own house"
label variable sh25ab   "Crop land"
label variable sh25ac   "Cattle/camels"
label variable sh25ad   "Horse/mule/donkey"
label variable sh25ae   "Sheep/goats"
label variable sh25af   "Cash crops"
label variable sh27b    "Rooms for sleeping"
label variable sh28d    "Member owns a horse/mule"
label variable sh29a    "Treatment sick child"
label variable sh29b    "Immunization"
label variable sh29c    "Family planning"
label variable sh29d    "Prenatal/postnatal/delivery are"
label variable sh29e    "Information on STD/HIV/AIDS"
label variable sh29f    "Information on breastfeeding/infant feeding"
label variable sh29ba   "Facilities received services from: Government hospital"
label variable sh29bb   "Facilities received services from: Health center"
label variable sh29bc   "Facilities received services from: Health station/clinic"
label variable sh29bd   "Facilities received services from: Health post"
label variable sh29be   "Facilities received services from: Comm. based outlet"
label variable sh29bf   "Facilities received services from: Other government"
label variable sh29bg   "Facilities received services from: NGO health facility"
label variable sh29bh   "Facilities received services from: NGO comm. based outlet"
label variable sh29bi   "Facilities received services from: Other NGO"
label variable sh29bj   "Facilities received services from: Private hospital"
label variable sh29bk   "Facilities received services from: Private doctor/clinic"
label variable sh29bl   "Facilities received services from: Other private"
label variable sh29bm   "Facilities received services from: Kebele - during campaign"
label variable sh29bx   "Facilities received services from: Other source"
label variable sh29ca   "Bought drugs in last 12 months"
label variable sh29da   "Where bought drugs from - Pharmacy/Other medical facility"
label variable sh29db   "Where bought drugs from - Non medical facility"
label variable sh29ga   "Bednets have been treated"
label variable sh35     "Test salt for Iodine"
label variable hvidx    "Line number"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "Member still in school"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status     -NA"
label variable hv116    "Currently, formerly, never -NA"
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "Member attended school during previous school year"
label variable hv126    "Educational level during previous school year"
label variable hv127    "Grade of education during previous school year"
label variable hv128    "Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable idxh4    "Index to household schedule"
label variable sh14     "Able to read and write"
label variable ha0      "Index to household schedule"
label variable ha1      "Women's age in years"
label variable ha2      "Respondent's weight (kilos-1d)"
label variable ha3      "Respondent's height (cms-1d)"
label variable ha4      "Ht/A Percentile (resp.)"
label variable ha5      "Ht/A Standard deviations (resp"
label variable ha6      "Ht/A Percent ref. median (resp"
label variable ha11     "Wt/Ht Std deviations(resp) DHS"
label variable ha12     "Wt/Ht Percent ref. median (DHS"
label variable ha12a    "Wt/Ht Percent ref. median (Fog"
label variable ha12b    "Wt/Ht Percent ref. median (WHO"
label variable ha13     "Result of measurement of resp."
label variable ha32     "Date of birth (cmc)"
label variable ha33     "Completeness of information"
label variable ha35     "Smoking                    -NA"
label variable ha40     "Body mass index for respondent"
label variable ha41     "Rohrer's index for respondent"
label variable ha50     "Under age 18               -NA"
label variable ha51     "Line no. of parent/caretake-NA"
label variable ha52     "Read consent statement     -NA"
label variable ha53     "Hemoglobin level (g/dl - 1 -NA"
label variable ha54     "Currently pregnant         -NA"
label variable ha55     "Result of measuring (Hemogl-NA"
label variable ha56     "Hemoglobin level adjusted b-NA"
label variable ha57     "Anemia level               -NA"
label variable ha58     "Agrees to referral         -NA"
label variable hc0      "Index to household schedule"
label variable hc1      "Age in months"
label variable hc2      "Weight in kilograms (1 dec.)"
label variable hc3      "Height in centimeters (1 dec.)"
label variable hc4      "Ht/A Percentile"
label variable hc5      "Ht/A Standard deviations"
label variable hc6      "Ht/A Percent of ref. median"
label variable hc7      "Wt/A Percentile"
label variable hc8      "Wt/A Standard deviations"
label variable hc9      "Wt/A Percent of ref. median"
label variable hc10     "Wt/Ht Percentile"
label variable hc11     "Wt/Ht Standard deviations"
label variable hc12     "Wt/Ht Percent of ref. median"
label variable hc13     "Reason not measured"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth of child"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth of child"
label variable hc31     "Year of birth of child"
label variable hc32     "Date of birth (cmc)"
label variable hc33     "Completeness of information"
label variable hc51     "Line no. of parent/caretake-NA"
label variable hc52     "Read consent statement     -NA"
label variable hc53     "Hemoglobin level (g/dl - 1 -NA"
label variable hc55     "Result of measuring (Hemogl-NA"
label variable hc56     "Hemoglobin level adjusted b-NA"
label variable hc57     "Anemia level               -NA"
label variable hc58     "Agrees to referral         -NA"
label variable hc60     "Women's line number from women's questionnaire"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval"
label variable hc64     "Birth order number"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     1 "Tigray, urban"
     2 "Tigray, rural"
     3 "Afar, urban"
     4 "Afar, rural"
     5 "Amhara, urban"
     6 "Amhara, rural"
     7 "Oromiya, urban"
     8 "Oromiya, rural"
     9 "Somali, urban"
    10 "Somali, rural"
    11 "Ben-Gumz, urban"
    12 "Ben-Gumz, rural"
    13 "SNNP, urban"
    14 "SNNP, rural"
    15 "Gambela, urban"
    16 "Gambela, rural"
    17 "Harrari, urban"
    18 "Harrari, rural"
    19 "Addis, urban"
    20 "Dire Dawa, urban"
    21 "Dire Dawa, rural"
;
label define HV024   
     1 "Tigray"
     2 "Affar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harari"
    14 "Addis"
    15 "Dire Dawa"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV043   
     0 "Household not selected"
     1 "Household selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into compound"
    13 "Piped outside compound"
    20 "WATER FROM OPEN WELL"
    21 "Open well"
    22 "Open spring"
    23 "Covered well"
    24 "Covered spring"
    31 "River"
    32 "Pond/lake/dam"
    40 "SURFACE WATER"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define HV204   
   995 "One day or longer"
   996 "On premises"
   999 "Missing"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush toilet"
    20 "PIT TOILET LATRINE"
    21 "Traditional pit latrine"
    22 "Improved (ventilated) pit latrine"
    30 "NO FACILITY"
    31 "No facility, bush, field"
    96 "OTHER"
    99 "Missing"
;
label define HV206   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV207   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV208   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV210   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV211   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV212   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV213   
    10 "NATURAL FLOOR"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY FLOOR"
    21 "Wood planks"
    22 "Reed, bamboo"
    30 "FINISHED FLOOR"
    31 "Parquet, polished wood"
    32 "Vinyl sheets/tiles"
    33 "Cement"
    34 "Cement tiles/brick"
    35 "Carpet"
    96 "Other"
    99 "Missing"
;
label define HV215   
    10 "NATURAL"
    20 "RUDIMENTARY"
    21 "Wood or mulch"
    22 "Thatch"
    23 "Reed or bamboo"
    24 "Plastic sheet"
    27 "Mobile roofs of nomads"
    30 "FINISHED"
    31 "Corrugated iron"
    32 "Cement or concrete"
    96 "OTHER"
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
     9 "Missing"
;
label define HV220   
    97 "97+"
    98 "DK"
    99 "Missing"
;
label define HV221   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV225   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV226   
     1 "Electricity"
     2 "LPG, natural gas"
     3 "Biogas"
     4 "Kerosene"
     5 "Coal, lignite"
     6 "Charcoal"
     7 "Firewood, straw"
     8 "Dung"
     9 "Does not cook at home"
    96 "Other"
    99 "Missing"
;
label define HV227   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25F   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25G   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH25AF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH28D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29F   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BJ  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BK  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BL  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BM  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29BX  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29CA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29DA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29DB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH29GA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH35    
     1 "0 PPM (No Iodine)"
     2 "25 PPM"
     3 "50 PPM"
     4 "75 PPM"
     5 "100 PPM"
     9 "Missing"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define HV102   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV103   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV104   
     1 "Male"
     2 "Female"
     9 "Missing"
;
label define HV105   
    97 "97+"
    98 "DK"
    99 "Missing"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV107   
    98 "DK"
    99 "Missing"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV110   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV112   
     0 "Mother not in HH"
    99 "Missing"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HV114   
     0 "Father not in HH"
    99 "Missing"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
     9 "Missing"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV123   
    98 "DK"
    99 "Missing"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define HV125   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV127   
    98 "DK"
    99 "Missing"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
     9 "Missing"
;
label define SH14    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define HA4     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HA5     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HA11    
  9998 "Flagged cases"
  9999 "Missing"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     9 "Missing"
;
label define HA33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HA40    
  9998 "Flagged cases"
  9999 "Missing"
;
label define HA41    
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC4     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC5     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC7     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC8     
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC10    
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC11    
  9998 "Flagged cases"
  9999 "Missing"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     9 "Missing"
;
label define HC15    
     1 "Lying"
     2 "Standing"
     9 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
     9 "Missing"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv043    HV043   
label values hv044    HV044   
label values hv201    HV201   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values sh25e    SH25E   
label values sh25f    SH25F   
label values sh25g    SH25G   
label values sh25aa   SH25AA  
label values sh25ab   SH25AB  
label values sh25ac   SH25AC  
label values sh25ad   SH25AD  
label values sh25ae   SH25AE  
label values sh25af   SH25AF  
label values sh28d    SH28D   
label values sh29a    SH29A   
label values sh29b    SH29B   
label values sh29c    SH29C   
label values sh29d    SH29D   
label values sh29e    SH29E   
label values sh29f    SH29F   
label values sh29ba   SH29BA  
label values sh29bb   SH29BB  
label values sh29bc   SH29BC  
label values sh29bd   SH29BD  
label values sh29be   SH29BE  
label values sh29bf   SH29BF  
label values sh29bg   SH29BG  
label values sh29bh   SH29BH  
label values sh29bi   SH29BI  
label values sh29bj   SH29BJ  
label values sh29bk   SH29BK  
label values sh29bl   SH29BL  
label values sh29bm   SH29BM  
label values sh29bx   SH29BX  
label values sh29ca   SH29CA  
label values sh29da   SH29DA  
label values sh29db   SH29DB  
label values sh29ga   SH29GA  
label values sh35     SH35    
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv110    HV110   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values sh14     SH14    
label values ha4      HA4     
label values ha5      HA5     
label values ha11     HA11    
label values ha13     HA13    
label values ha33     HA33    
label values ha40     HA40    
label values ha41     HA41    
label values hc4      HC4     
label values hc5      HC5     
label values hc7      HC7     
label values hc8      HC8     
label values hc10     HC10    
label values hc11     HC11    
label values hc13     HC13    
label values hc15     HC15    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc60     HC60    
label values hc61     HC61    
