DATA LIST FILE='ETHR41FL.DAT' RECORDS=1
/
 HHID        1-12   (A)
 HV000      13-15   (A)
 HV001      16-23  
 HV002      24-27  
 HV003      28-30  
 HV004      31-34  
 HV005      35-42  
 HV006      43-44  
 HV007      45-48  
 HV008      49-52  
 HV009      53-54  
 HV010      55-56  
 HV011      57-58  
 HV012      59-60  
 HV013      61-62  
 HV014      63-64  
 HV015      65-65  
 HV016      66-67  
 HV017      68-68  
 HV018      69-71  
 HV019      72-73  
 HV020      74-74  
 HV021      75-78  
 HV022      79-82  
 HV023      83-84  
 HV024      85-86  
 HV025      87-87  
 HV026      88-88  
 HV027      89-89  
 HV028      90-97  
 HV030      98-100 
 HV031     101-103 
 HV032     104-105 
 HV033     106-113 
 HV035     114-115 
 HV040     116-119 
 HV041     120-121 
 HV042     122-122 
 HV043     123-123 
 HV044     124-124 
 HV201     125-126 
 HV204     127-129 
 HV205     130-131 
 HV206     132-132 
 HV207     133-133 
 HV208     134-134 
 HV209     135-135 
 HV210     136-136 
 HV211     137-137 
 HV212     138-138 
 HV213     139-140 
 HV214     141-142 
 HV215     143-144 
 HV217     145-145 
 HV218     146-147 
 HV219     148-148 
 HV220     149-150 
 HV221     151-151 
 HV225     152-152 
 HV226     153-154 
 HV227     155-155 
 HV228     156-156 
 HV230     157-157 
 HV231     158-158 
 HV232     159-159 
 HV233     160-160 
 HV234     161-163 
 HVIDX$01  164-165 
 HV101$01  166-167 
 HV102$01  168-168 
 HV103$01  169-169 
 HV104$01  170-170 
 HV105$01  171-172 
 HV106$01  173-173 
 HV107$01  174-175 
 HV108$01  176-177 
 HV109$01  178-178 
 HV110$01  179-179 
 HV111$01  180-180 
 HV112$01  181-182 
 HV113$01  183-183 
 HV114$01  184-185 
 HV115$01  186-186 
 HV116$01  187-187 
 HV117$01  188-188 
 HV118$01  189-189 
 HV120$01  190-190 
 HV121$01  191-191 
 HV122$01  192-192 
 HV123$01  193-194 
 HV124$01  195-196 
 HV125$01  197-197 
 HV126$01  198-198 
 HV127$01  199-200 
 HV128$01  201-202 
 HV129$01  203-203 
 HVIDX$02  204-205 
 HV101$02  206-207 
 HV102$02  208-208 
 HV103$02  209-209 
 HV104$02  210-210 
 HV105$02  211-212 
 HV106$02  213-213 
 HV107$02  214-215 
 HV108$02  216-217 
 HV109$02  218-218 
 HV110$02  219-219 
 HV111$02  220-220 
 HV112$02  221-222 
 HV113$02  223-223 
 HV114$02  224-225 
 HV115$02  226-226 
 HV116$02  227-227 
 HV117$02  228-228 
 HV118$02  229-229 
 HV120$02  230-230 
 HV121$02  231-231 
 HV122$02  232-232 
 HV123$02  233-234 
 HV124$02  235-236 
 HV125$02  237-237 
 HV126$02  238-238 
 HV127$02  239-240 
 HV128$02  241-242 
 HV129$02  243-243 
 HVIDX$03  244-245 
 HV101$03  246-247 
 HV102$03  248-248 
 HV103$03  249-249 
 HV104$03  250-250 
 HV105$03  251-252 
 HV106$03  253-253 
 HV107$03  254-255 
 HV108$03  256-257 
 HV109$03  258-258 
 HV110$03  259-259 
 HV111$03  260-260 
 HV112$03  261-262 
 HV113$03  263-263 
 HV114$03  264-265 
 HV115$03  266-266 
 HV116$03  267-267 
 HV117$03  268-268 
 HV118$03  269-269 
 HV120$03  270-270 
 HV121$03  271-271 
 HV122$03  272-272 
 HV123$03  273-274 
 HV124$03  275-276 
 HV125$03  277-277 
 HV126$03  278-278 
 HV127$03  279-280 
 HV128$03  281-282 
 HV129$03  283-283 
 HVIDX$04  284-285 
 HV101$04  286-287 
 HV102$04  288-288 
 HV103$04  289-289 
 HV104$04  290-290 
 HV105$04  291-292 
 HV106$04  293-293 
 HV107$04  294-295 
 HV108$04  296-297 
 HV109$04  298-298 
 HV110$04  299-299 
 HV111$04  300-300 
 HV112$04  301-302 
 HV113$04  303-303 
 HV114$04  304-305 
 HV115$04  306-306 
 HV116$04  307-307 
 HV117$04  308-308 
 HV118$04  309-309 
 HV120$04  310-310 
 HV121$04  311-311 
 HV122$04  312-312 
 HV123$04  313-314 
 HV124$04  315-316 
 HV125$04  317-317 
 HV126$04  318-318 
 HV127$04  319-320 
 HV128$04  321-322 
 HV129$04  323-323 
 HVIDX$05  324-325 
 HV101$05  326-327 
 HV102$05  328-328 
 HV103$05  329-329 
 HV104$05  330-330 
 HV105$05  331-332 
 HV106$05  333-333 
 HV107$05  334-335 
 HV108$05  336-337 
 HV109$05  338-338 
 HV110$05  339-339 
 HV111$05  340-340 
 HV112$05  341-342 
 HV113$05  343-343 
 HV114$05  344-345 
 HV115$05  346-346 
 HV116$05  347-347 
 HV117$05  348-348 
 HV118$05  349-349 
 HV120$05  350-350 
 HV121$05  351-351 
 HV122$05  352-352 
 HV123$05  353-354 
 HV124$05  355-356 
 HV125$05  357-357 
 HV126$05  358-358 
 HV127$05  359-360 
 HV128$05  361-362 
 HV129$05  363-363 
 HVIDX$06  364-365 
 HV101$06  366-367 
 HV102$06  368-368 
 HV103$06  369-369 
 HV104$06  370-370 
 HV105$06  371-372 
 HV106$06  373-373 
 HV107$06  374-375 
 HV108$06  376-377 
 HV109$06  378-378 
 HV110$06  379-379 
 HV111$06  380-380 
 HV112$06  381-382 
 HV113$06  383-383 
 HV114$06  384-385 
 HV115$06  386-386 
 HV116$06  387-387 
 HV117$06  388-388 
 HV118$06  389-389 
 HV120$06  390-390 
 HV121$06  391-391 
 HV122$06  392-392 
 HV123$06  393-394 
 HV124$06  395-396 
 HV125$06  397-397 
 HV126$06  398-398 
 HV127$06  399-400 
 HV128$06  401-402 
 HV129$06  403-403 
 HVIDX$07  404-405 
 HV101$07  406-407 
 HV102$07  408-408 
 HV103$07  409-409 
 HV104$07  410-410 
 HV105$07  411-412 
 HV106$07  413-413 
 HV107$07  414-415 
 HV108$07  416-417 
 HV109$07  418-418 
 HV110$07  419-419 
 HV111$07  420-420 
 HV112$07  421-422 
 HV113$07  423-423 
 HV114$07  424-425 
 HV115$07  426-426 
 HV116$07  427-427 
 HV117$07  428-428 
 HV118$07  429-429 
 HV120$07  430-430 
 HV121$07  431-431 
 HV122$07  432-432 
 HV123$07  433-434 
 HV124$07  435-436 
 HV125$07  437-437 
 HV126$07  438-438 
 HV127$07  439-440 
 HV128$07  441-442 
 HV129$07  443-443 
 HVIDX$08  444-445 
 HV101$08  446-447 
 HV102$08  448-448 
 HV103$08  449-449 
 HV104$08  450-450 
 HV105$08  451-452 
 HV106$08  453-453 
 HV107$08  454-455 
 HV108$08  456-457 
 HV109$08  458-458 
 HV110$08  459-459 
 HV111$08  460-460 
 HV112$08  461-462 
 HV113$08  463-463 
 HV114$08  464-465 
 HV115$08  466-466 
 HV116$08  467-467 
 HV117$08  468-468 
 HV118$08  469-469 
 HV120$08  470-470 
 HV121$08  471-471 
 HV122$08  472-472 
 HV123$08  473-474 
 HV124$08  475-476 
 HV125$08  477-477 
 HV126$08  478-478 
 HV127$08  479-480 
 HV128$08  481-482 
 HV129$08  483-483 
 HVIDX$09  484-485 
 HV101$09  486-487 
 HV102$09  488-488 
 HV103$09  489-489 
 HV104$09  490-490 
 HV105$09  491-492 
 HV106$09  493-493 
 HV107$09  494-495 
 HV108$09  496-497 
 HV109$09  498-498 
 HV110$09  499-499 
 HV111$09  500-500 
 HV112$09  501-502 
 HV113$09  503-503 
 HV114$09  504-505 
 HV115$09  506-506 
 HV116$09  507-507 
 HV117$09  508-508 
 HV118$09  509-509 
 HV120$09  510-510 
 HV121$09  511-511 
 HV122$09  512-512 
 HV123$09  513-514 
 HV124$09  515-516 
 HV125$09  517-517 
 HV126$09  518-518 
 HV127$09  519-520 
 HV128$09  521-522 
 HV129$09  523-523 
 HVIDX$10  524-525 
 HV101$10  526-527 
 HV102$10  528-528 
 HV103$10  529-529 
 HV104$10  530-530 
 HV105$10  531-532 
 HV106$10  533-533 
 HV107$10  534-535 
 HV108$10  536-537 
 HV109$10  538-538 
 HV110$10  539-539 
 HV111$10  540-540 
 HV112$10  541-542 
 HV113$10  543-543 
 HV114$10  544-545 
 HV115$10  546-546 
 HV116$10  547-547 
 HV117$10  548-548 
 HV118$10  549-549 
 HV120$10  550-550 
 HV121$10  551-551 
 HV122$10  552-552 
 HV123$10  553-554 
 HV124$10  555-556 
 HV125$10  557-557 
 HV126$10  558-558 
 HV127$10  559-560 
 HV128$10  561-562 
 HV129$10  563-563 
 HVIDX$11  564-565 
 HV101$11  566-567 
 HV102$11  568-568 
 HV103$11  569-569 
 HV104$11  570-570 
 HV105$11  571-572 
 HV106$11  573-573 
 HV107$11  574-575 
 HV108$11  576-577 
 HV109$11  578-578 
 HV110$11  579-579 
 HV111$11  580-580 
 HV112$11  581-582 
 HV113$11  583-583 
 HV114$11  584-585 
 HV115$11  586-586 
 HV116$11  587-587 
 HV117$11  588-588 
 HV118$11  589-589 
 HV120$11  590-590 
 HV121$11  591-591 
 HV122$11  592-592 
 HV123$11  593-594 
 HV124$11  595-596 
 HV125$11  597-597 
 HV126$11  598-598 
 HV127$11  599-600 
 HV128$11  601-602 
 HV129$11  603-603 
 HVIDX$12  604-605 
 HV101$12  606-607 
 HV102$12  608-608 
 HV103$12  609-609 
 HV104$12  610-610 
 HV105$12  611-612 
 HV106$12  613-613 
 HV107$12  614-615 
 HV108$12  616-617 
 HV109$12  618-618 
 HV110$12  619-619 
 HV111$12  620-620 
 HV112$12  621-622 
 HV113$12  623-623 
 HV114$12  624-625 
 HV115$12  626-626 
 HV116$12  627-627 
 HV117$12  628-628 
 HV118$12  629-629 
 HV120$12  630-630 
 HV121$12  631-631 
 HV122$12  632-632 
 HV123$12  633-634 
 HV124$12  635-636 
 HV125$12  637-637 
 HV126$12  638-638 
 HV127$12  639-640 
 HV128$12  641-642 
 HV129$12  643-643 
 HVIDX$13  644-645 
 HV101$13  646-647 
 HV102$13  648-648 
 HV103$13  649-649 
 HV104$13  650-650 
 HV105$13  651-652 
 HV106$13  653-653 
 HV107$13  654-655 
 HV108$13  656-657 
 HV109$13  658-658 
 HV110$13  659-659 
 HV111$13  660-660 
 HV112$13  661-662 
 HV113$13  663-663 
 HV114$13  664-665 
 HV115$13  666-666 
 HV116$13  667-667 
 HV117$13  668-668 
 HV118$13  669-669 
 HV120$13  670-670 
 HV121$13  671-671 
 HV122$13  672-672 
 HV123$13  673-674 
 HV124$13  675-676 
 HV125$13  677-677 
 HV126$13  678-678 
 HV127$13  679-680 
 HV128$13  681-682 
 HV129$13  683-683 
 HVIDX$14  684-685 
 HV101$14  686-687 
 HV102$14  688-688 
 HV103$14  689-689 
 HV104$14  690-690 
 HV105$14  691-692 
 HV106$14  693-693 
 HV107$14  694-695 
 HV108$14  696-697 
 HV109$14  698-698 
 HV110$14  699-699 
 HV111$14  700-700 
 HV112$14  701-702 
 HV113$14  703-703 
 HV114$14  704-705 
 HV115$14  706-706 
 HV116$14  707-707 
 HV117$14  708-708 
 HV118$14  709-709 
 HV120$14  710-710 
 HV121$14  711-711 
 HV122$14  712-712 
 HV123$14  713-714 
 HV124$14  715-716 
 HV125$14  717-717 
 HV126$14  718-718 
 HV127$14  719-720 
 HV128$14  721-722 
 HV129$14  723-723 
 HVIDX$15  724-725 
 HV101$15  726-727 
 HV102$15  728-728 
 HV103$15  729-729 
 HV104$15  730-730 
 HV105$15  731-732 
 HV106$15  733-733 
 HV107$15  734-735 
 HV108$15  736-737 
 HV109$15  738-738 
 HV110$15  739-739 
 HV111$15  740-740 
 HV112$15  741-742 
 HV113$15  743-743 
 HV114$15  744-745 
 HV115$15  746-746 
 HV116$15  747-747 
 HV117$15  748-748 
 HV118$15  749-749 
 HV120$15  750-750 
 HV121$15  751-751 
 HV122$15  752-752 
 HV123$15  753-754 
 HV124$15  755-756 
 HV125$15  757-757 
 HV126$15  758-758 
 HV127$15  759-760 
 HV128$15  761-762 
 HV129$15  763-763 
 HVIDX$16  764-765 
 HV101$16  766-767 
 HV102$16  768-768 
 HV103$16  769-769 
 HV104$16  770-770 
 HV105$16  771-772 
 HV106$16  773-773 
 HV107$16  774-775 
 HV108$16  776-777 
 HV109$16  778-778 
 HV110$16  779-779 
 HV111$16  780-780 
 HV112$16  781-782 
 HV113$16  783-783 
 HV114$16  784-785 
 HV115$16  786-786 
 HV116$16  787-787 
 HV117$16  788-788 
 HV118$16  789-789 
 HV120$16  790-790 
 HV121$16  791-791 
 HV122$16  792-792 
 HV123$16  793-794 
 HV124$16  795-796 
 HV125$16  797-797 
 HV126$16  798-798 
 HV127$16  799-800 
 HV128$16  801-802 
 HV129$16  803-803 
 HVIDX$17  804-805 
 HV101$17  806-807 
 HV102$17  808-808 
 HV103$17  809-809 
 HV104$17  810-810 
 HV105$17  811-812 
 HV106$17  813-813 
 HV107$17  814-815 
 HV108$17  816-817 
 HV109$17  818-818 
 HV110$17  819-819 
 HV111$17  820-820 
 HV112$17  821-822 
 HV113$17  823-823 
 HV114$17  824-825 
 HV115$17  826-826 
 HV116$17  827-827 
 HV117$17  828-828 
 HV118$17  829-829 
 HV120$17  830-830 
 HV121$17  831-831 
 HV122$17  832-832 
 HV123$17  833-834 
 HV124$17  835-836 
 HV125$17  837-837 
 HV126$17  838-838 
 HV127$17  839-840 
 HV128$17  841-842 
 HV129$17  843-843 
 HVIDX$18  844-845 
 HV101$18  846-847 
 HV102$18  848-848 
 HV103$18  849-849 
 HV104$18  850-850 
 HV105$18  851-852 
 HV106$18  853-853 
 HV107$18  854-855 
 HV108$18  856-857 
 HV109$18  858-858 
 HV110$18  859-859 
 HV111$18  860-860 
 HV112$18  861-862 
 HV113$18  863-863 
 HV114$18  864-865 
 HV115$18  866-866 
 HV116$18  867-867 
 HV117$18  868-868 
 HV118$18  869-869 
 HV120$18  870-870 
 HV121$18  871-871 
 HV122$18  872-872 
 HV123$18  873-874 
 HV124$18  875-876 
 HV125$18  877-877 
 HV126$18  878-878 
 HV127$18  879-880 
 HV128$18  881-882 
 HV129$18  883-883 
 HVIDX$19  884-885 
 HV101$19  886-887 
 HV102$19  888-888 
 HV103$19  889-889 
 HV104$19  890-890 
 HV105$19  891-892 
 HV106$19  893-893 
 HV107$19  894-895 
 HV108$19  896-897 
 HV109$19  898-898 
 HV110$19  899-899 
 HV111$19  900-900 
 HV112$19  901-902 
 HV113$19  903-903 
 HV114$19  904-905 
 HV115$19  906-906 
 HV116$19  907-907 
 HV117$19  908-908 
 HV118$19  909-909 
 HV120$19  910-910 
 HV121$19  911-911 
 HV122$19  912-912 
 HV123$19  913-914 
 HV124$19  915-916 
 HV125$19  917-917 
 HV126$19  918-918 
 HV127$19  919-920 
 HV128$19  921-922 
 HV129$19  923-923 
 HVIDX$20  924-925 
 HV101$20  926-927 
 HV102$20  928-928 
 HV103$20  929-929 
 HV104$20  930-930 
 HV105$20  931-932 
 HV106$20  933-933 
 HV107$20  934-935 
 HV108$20  936-937 
 HV109$20  938-938 
 HV110$20  939-939 
 HV111$20  940-940 
 HV112$20  941-942 
 HV113$20  943-943 
 HV114$20  944-945 
 HV115$20  946-946 
 HV116$20  947-947 
 HV117$20  948-948 
 HV118$20  949-949 
 HV120$20  950-950 
 HV121$20  951-951 
 HV122$20  952-952 
 HV123$20  953-954 
 HV124$20  955-956 
 HV125$20  957-957 
 HV126$20  958-958 
 HV127$20  959-960 
 HV128$20  961-962 
 HV129$20  963-963 
 SHINTD    964-965 
 SHINTM    966-967 
 SHINTY    968-971 
 SHINTC    972-975 
 SH25E     976-976 
 SH25F     977-977 
 SH25G     978-978 
 SH25AA    979-979 
 SH25AB    980-980 
 SH25AC    981-981 
 SH25AD    982-982 
 SH25AE    983-983 
 SH25AF    984-984 
 SH27B     985-986 
 SH28D     987-987 
 SH29A     988-988 
 SH29B     989-989 
 SH29C     990-990 
 SH29D     991-991 
 SH29E     992-992 
 SH29F     993-993 
 SH29BA    994-994 
 SH29BB    995-995 
 SH29BC    996-996 
 SH29BD    997-997 
 SH29BE    998-998 
 SH29BF    999-999 
 SH29BG   1000-1000
 SH29BH   1001-1001
 SH29BI   1002-1002
 SH29BJ   1003-1003
 SH29BK   1004-1004
 SH29BL   1005-1005
 SH29BM   1006-1006
 SH29BX   1007-1007
 SH29CA   1008-1008
 SH29DA   1009-1009
 SH29DB   1010-1010
 SH29GA   1011-1011
 SH35     1012-1012
 IDXH4$01 1013-1014
 SH14$01  1015-1015
 IDXH4$02 1016-1017
 SH14$02  1018-1018
 IDXH4$03 1019-1020
 SH14$03  1021-1021
 IDXH4$04 1022-1023
 SH14$04  1024-1024
 IDXH4$05 1025-1026
 SH14$05  1027-1027
 IDXH4$06 1028-1029
 SH14$06  1030-1030
 IDXH4$07 1031-1032
 SH14$07  1033-1033
 IDXH4$08 1034-1035
 SH14$08  1036-1036
 IDXH4$09 1037-1038
 SH14$09  1039-1039
 IDXH4$10 1040-1041
 SH14$10  1042-1042
 IDXH4$11 1043-1044
 SH14$11  1045-1045
 IDXH4$12 1046-1047
 SH14$12  1048-1048
 IDXH4$13 1049-1050
 SH14$13  1051-1051
 IDXH4$14 1052-1053
 SH14$14  1054-1054
 IDXH4$15 1055-1056
 SH14$15  1057-1057
 IDXH4$16 1058-1059
 SH14$16  1060-1060
 IDXH4$17 1061-1062
 SH14$17  1063-1063
 IDXH4$18 1064-1065
 SH14$18  1066-1066
 IDXH4$19 1067-1068
 SH14$19  1069-1069
 IDXH4$20 1070-1071
 SH14$20  1072-1072
 HA0$1    1073-1074
 HA1$1    1075-1076
 HA2$1    1077-1080
 HA3$1    1081-1084
 HA4$1    1085-1088
 HA5$1    1089-1092
 HA6$1    1093-1097
 HA11$1   1098-1101
 HA12$1   1102-1106
 HA12A$1  1107-1111
 HA12B$1  1112-1116
 HA13$1   1117-1117
 HA32$1   1118-1121
 HA33$1   1122-1122
 HA35$1   1123-1123
 HA40$1   1124-1127
 HA41$1   1128-1131
 HA50$1   1132-1132
 HA51$1   1133-1134
 HA52$1   1135-1135
 HA53$1   1136-1138
 HA54$1   1139-1139
 HA55$1   1140-1140
 HA56$1   1141-1143
 HA57$1   1144-1144
 HA58$1   1145-1145
 HA0$2    1146-1147
 HA1$2    1148-1149
 HA2$2    1150-1153
 HA3$2    1154-1157
 HA4$2    1158-1161
 HA5$2    1162-1165
 HA6$2    1166-1170
 HA11$2   1171-1174
 HA12$2   1175-1179
 HA12A$2  1180-1184
 HA12B$2  1185-1189
 HA13$2   1190-1190
 HA32$2   1191-1194
 HA33$2   1195-1195
 HA35$2   1196-1196
 HA40$2   1197-1200
 HA41$2   1201-1204
 HA50$2   1205-1205
 HA51$2   1206-1207
 HA52$2   1208-1208
 HA53$2   1209-1211
 HA54$2   1212-1212
 HA55$2   1213-1213
 HA56$2   1214-1216
 HA57$2   1217-1217
 HA58$2   1218-1218
 HA0$3    1219-1220
 HA1$3    1221-1222
 HA2$3    1223-1226
 HA3$3    1227-1230
 HA4$3    1231-1234
 HA5$3    1235-1238
 HA6$3    1239-1243
 HA11$3   1244-1247
 HA12$3   1248-1252
 HA12A$3  1253-1257
 HA12B$3  1258-1262
 HA13$3   1263-1263
 HA32$3   1264-1267
 HA33$3   1268-1268
 HA35$3   1269-1269
 HA40$3   1270-1273
 HA41$3   1274-1277
 HA50$3   1278-1278
 HA51$3   1279-1280
 HA52$3   1281-1281
 HA53$3   1282-1284
 HA54$3   1285-1285
 HA55$3   1286-1286
 HA56$3   1287-1289
 HA57$3   1290-1290
 HA58$3   1291-1291
 HA0$4    1292-1293
 HA1$4    1294-1295
 HA2$4    1296-1299
 HA3$4    1300-1303
 HA4$4    1304-1307
 HA5$4    1308-1311
 HA6$4    1312-1316
 HA11$4   1317-1320
 HA12$4   1321-1325
 HA12A$4  1326-1330
 HA12B$4  1331-1335
 HA13$4   1336-1336
 HA32$4   1337-1340
 HA33$4   1341-1341
 HA35$4   1342-1342
 HA40$4   1343-1346
 HA41$4   1347-1350
 HA50$4   1351-1351
 HA51$4   1352-1353
 HA52$4   1354-1354
 HA53$4   1355-1357
 HA54$4   1358-1358
 HA55$4   1359-1359
 HA56$4   1360-1362
 HA57$4   1363-1363
 HA58$4   1364-1364
 HA0$5    1365-1366
 HA1$5    1367-1368
 HA2$5    1369-1372
 HA3$5    1373-1376
 HA4$5    1377-1380
 HA5$5    1381-1384
 HA6$5    1385-1389
 HA11$5   1390-1393
 HA12$5   1394-1398
 HA12A$5  1399-1403
 HA12B$5  1404-1408
 HA13$5   1409-1409
 HA32$5   1410-1413
 HA33$5   1414-1414
 HA35$5   1415-1415
 HA40$5   1416-1419
 HA41$5   1420-1423
 HA50$5   1424-1424
 HA51$5   1425-1426
 HA52$5   1427-1427
 HA53$5   1428-1430
 HA54$5   1431-1431
 HA55$5   1432-1432
 HA56$5   1433-1435
 HA57$5   1436-1436
 HA58$5   1437-1437
 HA0$6    1438-1439
 HA1$6    1440-1441
 HA2$6    1442-1445
 HA3$6    1446-1449
 HA4$6    1450-1453
 HA5$6    1454-1457
 HA6$6    1458-1462
 HA11$6   1463-1466
 HA12$6   1467-1471
 HA12A$6  1472-1476
 HA12B$6  1477-1481
 HA13$6   1482-1482
 HA32$6   1483-1486
 HA33$6   1487-1487
 HA35$6   1488-1488
 HA40$6   1489-1492
 HA41$6   1493-1496
 HA50$6   1497-1497
 HA51$6   1498-1499
 HA52$6   1500-1500
 HA53$6   1501-1503
 HA54$6   1504-1504
 HA55$6   1505-1505
 HA56$6   1506-1508
 HA57$6   1509-1509
 HA58$6   1510-1510
 HA0$7    1511-1512
 HA1$7    1513-1514
 HA2$7    1515-1518
 HA3$7    1519-1522
 HA4$7    1523-1526
 HA5$7    1527-1530
 HA6$7    1531-1535
 HA11$7   1536-1539
 HA12$7   1540-1544
 HA12A$7  1545-1549
 HA12B$7  1550-1554
 HA13$7   1555-1555
 HA32$7   1556-1559
 HA33$7   1560-1560
 HA35$7   1561-1561
 HA40$7   1562-1565
 HA41$7   1566-1569
 HA50$7   1570-1570
 HA51$7   1571-1572
 HA52$7   1573-1573
 HA53$7   1574-1576
 HA54$7   1577-1577
 HA55$7   1578-1578
 HA56$7   1579-1581
 HA57$7   1582-1582
 HA58$7   1583-1583
 HA0$8    1584-1585
 HA1$8    1586-1587
 HA2$8    1588-1591
 HA3$8    1592-1595
 HA4$8    1596-1599
 HA5$8    1600-1603
 HA6$8    1604-1608
 HA11$8   1609-1612
 HA12$8   1613-1617
 HA12A$8  1618-1622
 HA12B$8  1623-1627
 HA13$8   1628-1628
 HA32$8   1629-1632
 HA33$8   1633-1633
 HA35$8   1634-1634
 HA40$8   1635-1638
 HA41$8   1639-1642
 HA50$8   1643-1643
 HA51$8   1644-1645
 HA52$8   1646-1646
 HA53$8   1647-1649
 HA54$8   1650-1650
 HA55$8   1651-1651
 HA56$8   1652-1654
 HA57$8   1655-1655
 HA58$8   1656-1656
 HC0$1    1657-1658
 HC1$1    1659-1660
 HC2$1    1661-1664
 HC3$1    1665-1668
 HC4$1    1669-1672
 HC5$1    1673-1676
 HC6$1    1677-1681
 HC7$1    1682-1685
 HC8$1    1686-1689
 HC9$1    1690-1694
 HC10$1   1695-1698
 HC11$1   1699-1702
 HC12$1   1703-1707
 HC13$1   1708-1708
 HC15$1   1709-1709
 HC16$1   1710-1711
 HC17$1   1712-1713
 HC18$1   1714-1715
 HC19$1   1716-1719
 HC27$1   1720-1720
 HC30$1   1721-1722
 HC31$1   1723-1726
 HC32$1   1727-1730
 HC33$1   1731-1731
 HC51$1   1732-1733
 HC52$1   1734-1734
 HC53$1   1735-1737
 HC55$1   1738-1738
 HC56$1   1739-1742
 HC57$1   1743-1743
 HC58$1   1744-1744
 HC60$1   1745-1747
 HC61$1   1748-1748
 HC62$1   1749-1750
 HC63$1   1751-1753
 HC64$1   1754-1755
 HC0$2    1756-1757
 HC1$2    1758-1759
 HC2$2    1760-1763
 HC3$2    1764-1767
 HC4$2    1768-1771
 HC5$2    1772-1775
 HC6$2    1776-1780
 HC7$2    1781-1784
 HC8$2    1785-1788
 HC9$2    1789-1793
 HC10$2   1794-1797
 HC11$2   1798-1801
 HC12$2   1802-1806
 HC13$2   1807-1807
 HC15$2   1808-1808
 HC16$2   1809-1810
 HC17$2   1811-1812
 HC18$2   1813-1814
 HC19$2   1815-1818
 HC27$2   1819-1819
 HC30$2   1820-1821
 HC31$2   1822-1825
 HC32$2   1826-1829
 HC33$2   1830-1830
 HC51$2   1831-1832
 HC52$2   1833-1833
 HC53$2   1834-1836
 HC55$2   1837-1837
 HC56$2   1838-1841
 HC57$2   1842-1842
 HC58$2   1843-1843
 HC60$2   1844-1846
 HC61$2   1847-1847
 HC62$2   1848-1849
 HC63$2   1850-1852
 HC64$2   1853-1854
 HC0$3    1855-1856
 HC1$3    1857-1858
 HC2$3    1859-1862
 HC3$3    1863-1866
 HC4$3    1867-1870
 HC5$3    1871-1874
 HC6$3    1875-1879
 HC7$3    1880-1883
 HC8$3    1884-1887
 HC9$3    1888-1892
 HC10$3   1893-1896
 HC11$3   1897-1900
 HC12$3   1901-1905
 HC13$3   1906-1906
 HC15$3   1907-1907
 HC16$3   1908-1909
 HC17$3   1910-1911
 HC18$3   1912-1913
 HC19$3   1914-1917
 HC27$3   1918-1918
 HC30$3   1919-1920
 HC31$3   1921-1924
 HC32$3   1925-1928
 HC33$3   1929-1929
 HC51$3   1930-1931
 HC52$3   1932-1932
 HC53$3   1933-1935
 HC55$3   1936-1936
 HC56$3   1937-1940
 HC57$3   1941-1941
 HC58$3   1942-1942
 HC60$3   1943-1945
 HC61$3   1946-1946
 HC62$3   1947-1948
 HC63$3   1949-1951
 HC64$3   1952-1953
 HC0$4    1954-1955
 HC1$4    1956-1957
 HC2$4    1958-1961
 HC3$4    1962-1965
 HC4$4    1966-1969
 HC5$4    1970-1973
 HC6$4    1974-1978
 HC7$4    1979-1982
 HC8$4    1983-1986
 HC9$4    1987-1991
 HC10$4   1992-1995
 HC11$4   1996-1999
 HC12$4   2000-2004
 HC13$4   2005-2005
 HC15$4   2006-2006
 HC16$4   2007-2008
 HC17$4   2009-2010
 HC18$4   2011-2012
 HC19$4   2013-2016
 HC27$4   2017-2017
 HC30$4   2018-2019
 HC31$4   2020-2023
 HC32$4   2024-2027
 HC33$4   2028-2028
 HC51$4   2029-2030
 HC52$4   2031-2031
 HC53$4   2032-2034
 HC55$4   2035-2035
 HC56$4   2036-2039
 HC57$4   2040-2040
 HC58$4   2041-2041
 HC60$4   2042-2044
 HC61$4   2045-2045
 HC62$4   2046-2047
 HC63$4   2048-2050
 HC64$4   2051-2052
 HC0$5    2053-2054
 HC1$5    2055-2056
 HC2$5    2057-2060
 HC3$5    2061-2064
 HC4$5    2065-2068
 HC5$5    2069-2072
 HC6$5    2073-2077
 HC7$5    2078-2081
 HC8$5    2082-2085
 HC9$5    2086-2090
 HC10$5   2091-2094
 HC11$5   2095-2098
 HC12$5   2099-2103
 HC13$5   2104-2104
 HC15$5   2105-2105
 HC16$5   2106-2107
 HC17$5   2108-2109
 HC18$5   2110-2111
 HC19$5   2112-2115
 HC27$5   2116-2116
 HC30$5   2117-2118
 HC31$5   2119-2122
 HC32$5   2123-2126
 HC33$5   2127-2127
 HC51$5   2128-2129
 HC52$5   2130-2130
 HC53$5   2131-2133
 HC55$5   2134-2134
 HC56$5   2135-2138
 HC57$5   2139-2139
 HC58$5   2140-2140
 HC60$5   2141-2143
 HC61$5   2144-2144
 HC62$5   2145-2146
 HC63$5   2147-2149
 HC64$5   2150-2151
 HC0$6    2152-2153
 HC1$6    2154-2155
 HC2$6    2156-2159
 HC3$6    2160-2163
 HC4$6    2164-2167
 HC5$6    2168-2171
 HC6$6    2172-2176
 HC7$6    2177-2180
 HC8$6    2181-2184
 HC9$6    2185-2189
 HC10$6   2190-2193
 HC11$6   2194-2197
 HC12$6   2198-2202
 HC13$6   2203-2203
 HC15$6   2204-2204
 HC16$6   2205-2206
 HC17$6   2207-2208
 HC18$6   2209-2210
 HC19$6   2211-2214
 HC27$6   2215-2215
 HC30$6   2216-2217
 HC31$6   2218-2221
 HC32$6   2222-2225
 HC33$6   2226-2226
 HC51$6   2227-2228
 HC52$6   2229-2229
 HC53$6   2230-2232
 HC55$6   2233-2233
 HC56$6   2234-2237
 HC57$6   2238-2238
 HC58$6   2239-2239
 HC60$6   2240-2242
 HC61$6   2243-2243
 HC62$6   2244-2245
 HC63$6   2246-2248
 HC64$6   2249-2250
.
VARIABLE LABELS
 HHID     "Case Identification"
/HV000    "Country code and phase"
/HV001    "Cluster number"
/HV002    "Household number"
/HV003    "Respondent's line number"
/HV004    "Ultimate area unit"
/HV005    "Sample weight"
/HV006    "Month of interview"
/HV007    "Year of interview"
/HV008    "Date of interview (CMC)"
/HV009    "Number of household members"
/HV010    "Number of eligible women in HH"
/HV011    "Number of eligible men in HH"
/HV012    "Number of de jure members"
/HV013    "Number of de facto members"
/HV014    "Number of children 5 and under"
/HV015    "Result of household interview"
/HV016    "Day of interview"
/HV017    "Number of visits"
/HV018    "Interviewer identification"
/HV019    "Keyer identification"
/HV020    "Ever-married sample"
/HV021    "Primary sampling unit"
/HV022    "Sample stratum number"
/HV023    "Sample domain"
/HV024    "Region"
/HV025    "Type of place of residence"
/HV026    "Place of residence"
/HV027    "Selection for male/husb. int."
/HV028    "Sample weight for male subsamp"
/HV030    "Field supervisor"
/HV031    "Field editor"
/HV032    "Office editor"
/HV033    "Ultimate area selection prob."
/HV035    "Number of eligible children for height & weight"
/HV040    "Cluster altitude in meters -NA"
/HV041    "Total adults measured"
/HV042    "Selection for hemoglobin"
/HV043    "Selection for women's status module"
/HV044    "Selection for domestic violence module"
/HV201    "Source of drinking water"
/HV204    "Time to get to water source"
/HV205    "Type of toilet facility"
/HV206    "Has electricity"
/HV207    "Has radio"
/HV208    "Has television"
/HV209    "Has refrigerator           -NA"
/HV210    "Has bicycle"
/HV211    "Has motorcycle/scooter"
/HV212    "Has car/truck"
/HV213    "Main floor material"
/HV214    "Main wall material         -NA"
/HV215    "Main roof material"
/HV217    "Relationship structure"
/HV218    "Line number of head of househ."
/HV219    "Sex of head of household"
/HV220    "Age of head of household"
/HV221    "Has telephone"
/HV225    "Share toilet with other households"
/HV226    "Type of cooking fuel"
/HV227    "Have bednet for sleeping"
/HV228    "Children under 5 slept unde-NA"
/HV230    "Place for hand washing     -NA"
/HV231    "Items present: Water, tap  -NA"
/HV232    "Items present: soap/other c-NA"
/HV233    "Items present: Basin       -NA"
/HV234    "Test salt for Iodine       -NA"
/HVIDX$01 "Line number"
/HV101$01 "Relationship to head"
/HV102$01 "Usual resident"
/HV103$01 "Slept last night"
/HV104$01 "Sex of household member"
/HV105$01 "Age of household members"
/HV106$01 "Highest educational level"
/HV107$01 "Highest year of education"
/HV108$01 "Education in single years"
/HV109$01 "Educational attainment"
/HV110$01 "Member still in school"
/HV111$01 "Mother alive"
/HV112$01 "Mother's line number"
/HV113$01 "Father alive"
/HV114$01 "Father's line number"
/HV115$01 "Current marital status     -NA"
/HV116$01 "Currently, formerly, never -NA"
/HV117$01 "Eligibility for female interview"
/HV118$01 "Eligibility for male interview"
/HV120$01 "Children eligibility for height/weight and hemoglobin"
/HV121$01 "Member attended school during current school year"
/HV122$01 "Educational level during current school year"
/HV123$01 "Grade of education during current school year"
/HV124$01 "Education in single years - current school year"
/HV125$01 "Member attended school during previous school year"
/HV126$01 "Educational level during previous school year"
/HV127$01 "Grade of education during previous school year"
/HV128$01 "Education in single years - previous school year"
/HV129$01 "School attendance status"
/HVIDX$02 "Line number"
/HV101$02 "Relationship to head"
/HV102$02 "Usual resident"
/HV103$02 "Slept last night"
/HV104$02 "Sex of household member"
/HV105$02 "Age of household members"
/HV106$02 "Highest educational level"
/HV107$02 "Highest year of education"
/HV108$02 "Education in single years"
/HV109$02 "Educational attainment"
/HV110$02 "Member still in school"
/HV111$02 "Mother alive"
/HV112$02 "Mother's line number"
/HV113$02 "Father alive"
/HV114$02 "Father's line number"
/HV115$02 "Current marital status     -NA"
/HV116$02 "Currently, formerly, never -NA"
/HV117$02 "Eligibility for female interview"
/HV118$02 "Eligibility for male interview"
/HV120$02 "Children eligibility for height/weight and hemoglobin"
/HV121$02 "Member attended school during current school year"
/HV122$02 "Educational level during current school year"
/HV123$02 "Grade of education during current school year"
/HV124$02 "Education in single years - current school year"
/HV125$02 "Member attended school during previous school year"
/HV126$02 "Educational level during previous school year"
/HV127$02 "Grade of education during previous school year"
/HV128$02 "Education in single years - previous school year"
/HV129$02 "School attendance status"
/HVIDX$03 "Line number"
/HV101$03 "Relationship to head"
/HV102$03 "Usual resident"
/HV103$03 "Slept last night"
/HV104$03 "Sex of household member"
/HV105$03 "Age of household members"
/HV106$03 "Highest educational level"
/HV107$03 "Highest year of education"
/HV108$03 "Education in single years"
/HV109$03 "Educational attainment"
/HV110$03 "Member still in school"
/HV111$03 "Mother alive"
/HV112$03 "Mother's line number"
/HV113$03 "Father alive"
/HV114$03 "Father's line number"
/HV115$03 "Current marital status     -NA"
/HV116$03 "Currently, formerly, never -NA"
/HV117$03 "Eligibility for female interview"
/HV118$03 "Eligibility for male interview"
/HV120$03 "Children eligibility for height/weight and hemoglobin"
/HV121$03 "Member attended school during current school year"
/HV122$03 "Educational level during current school year"
/HV123$03 "Grade of education during current school year"
/HV124$03 "Education in single years - current school year"
/HV125$03 "Member attended school during previous school year"
/HV126$03 "Educational level during previous school year"
/HV127$03 "Grade of education during previous school year"
/HV128$03 "Education in single years - previous school year"
/HV129$03 "School attendance status"
/HVIDX$04 "Line number"
/HV101$04 "Relationship to head"
/HV102$04 "Usual resident"
/HV103$04 "Slept last night"
/HV104$04 "Sex of household member"
/HV105$04 "Age of household members"
/HV106$04 "Highest educational level"
/HV107$04 "Highest year of education"
/HV108$04 "Education in single years"
/HV109$04 "Educational attainment"
/HV110$04 "Member still in school"
/HV111$04 "Mother alive"
/HV112$04 "Mother's line number"
/HV113$04 "Father alive"
/HV114$04 "Father's line number"
/HV115$04 "Current marital status     -NA"
/HV116$04 "Currently, formerly, never -NA"
/HV117$04 "Eligibility for female interview"
/HV118$04 "Eligibility for male interview"
/HV120$04 "Children eligibility for height/weight and hemoglobin"
/HV121$04 "Member attended school during current school year"
/HV122$04 "Educational level during current school year"
/HV123$04 "Grade of education during current school year"
/HV124$04 "Education in single years - current school year"
/HV125$04 "Member attended school during previous school year"
/HV126$04 "Educational level during previous school year"
/HV127$04 "Grade of education during previous school year"
/HV128$04 "Education in single years - previous school year"
/HV129$04 "School attendance status"
/HVIDX$05 "Line number"
/HV101$05 "Relationship to head"
/HV102$05 "Usual resident"
/HV103$05 "Slept last night"
/HV104$05 "Sex of household member"
/HV105$05 "Age of household members"
/HV106$05 "Highest educational level"
/HV107$05 "Highest year of education"
/HV108$05 "Education in single years"
/HV109$05 "Educational attainment"
/HV110$05 "Member still in school"
/HV111$05 "Mother alive"
/HV112$05 "Mother's line number"
/HV113$05 "Father alive"
/HV114$05 "Father's line number"
/HV115$05 "Current marital status     -NA"
/HV116$05 "Currently, formerly, never -NA"
/HV117$05 "Eligibility for female interview"
/HV118$05 "Eligibility for male interview"
/HV120$05 "Children eligibility for height/weight and hemoglobin"
/HV121$05 "Member attended school during current school year"
/HV122$05 "Educational level during current school year"
/HV123$05 "Grade of education during current school year"
/HV124$05 "Education in single years - current school year"
/HV125$05 "Member attended school during previous school year"
/HV126$05 "Educational level during previous school year"
/HV127$05 "Grade of education during previous school year"
/HV128$05 "Education in single years - previous school year"
/HV129$05 "School attendance status"
/HVIDX$06 "Line number"
/HV101$06 "Relationship to head"
/HV102$06 "Usual resident"
/HV103$06 "Slept last night"
/HV104$06 "Sex of household member"
/HV105$06 "Age of household members"
/HV106$06 "Highest educational level"
/HV107$06 "Highest year of education"
/HV108$06 "Education in single years"
/HV109$06 "Educational attainment"
/HV110$06 "Member still in school"
/HV111$06 "Mother alive"
/HV112$06 "Mother's line number"
/HV113$06 "Father alive"
/HV114$06 "Father's line number"
/HV115$06 "Current marital status     -NA"
/HV116$06 "Currently, formerly, never -NA"
/HV117$06 "Eligibility for female interview"
/HV118$06 "Eligibility for male interview"
/HV120$06 "Children eligibility for height/weight and hemoglobin"
/HV121$06 "Member attended school during current school year"
/HV122$06 "Educational level during current school year"
/HV123$06 "Grade of education during current school year"
/HV124$06 "Education in single years - current school year"
/HV125$06 "Member attended school during previous school year"
/HV126$06 "Educational level during previous school year"
/HV127$06 "Grade of education during previous school year"
/HV128$06 "Education in single years - previous school year"
/HV129$06 "School attendance status"
/HVIDX$07 "Line number"
/HV101$07 "Relationship to head"
/HV102$07 "Usual resident"
/HV103$07 "Slept last night"
/HV104$07 "Sex of household member"
/HV105$07 "Age of household members"
/HV106$07 "Highest educational level"
/HV107$07 "Highest year of education"
/HV108$07 "Education in single years"
/HV109$07 "Educational attainment"
/HV110$07 "Member still in school"
/HV111$07 "Mother alive"
/HV112$07 "Mother's line number"
/HV113$07 "Father alive"
/HV114$07 "Father's line number"
/HV115$07 "Current marital status     -NA"
/HV116$07 "Currently, formerly, never -NA"
/HV117$07 "Eligibility for female interview"
/HV118$07 "Eligibility for male interview"
/HV120$07 "Children eligibility for height/weight and hemoglobin"
/HV121$07 "Member attended school during current school year"
/HV122$07 "Educational level during current school year"
/HV123$07 "Grade of education during current school year"
/HV124$07 "Education in single years - current school year"
/HV125$07 "Member attended school during previous school year"
/HV126$07 "Educational level during previous school year"
/HV127$07 "Grade of education during previous school year"
/HV128$07 "Education in single years - previous school year"
/HV129$07 "School attendance status"
/HVIDX$08 "Line number"
/HV101$08 "Relationship to head"
/HV102$08 "Usual resident"
/HV103$08 "Slept last night"
/HV104$08 "Sex of household member"
/HV105$08 "Age of household members"
/HV106$08 "Highest educational level"
/HV107$08 "Highest year of education"
/HV108$08 "Education in single years"
/HV109$08 "Educational attainment"
/HV110$08 "Member still in school"
/HV111$08 "Mother alive"
/HV112$08 "Mother's line number"
/HV113$08 "Father alive"
/HV114$08 "Father's line number"
/HV115$08 "Current marital status     -NA"
/HV116$08 "Currently, formerly, never -NA"
/HV117$08 "Eligibility for female interview"
/HV118$08 "Eligibility for male interview"
/HV120$08 "Children eligibility for height/weight and hemoglobin"
/HV121$08 "Member attended school during current school year"
/HV122$08 "Educational level during current school year"
/HV123$08 "Grade of education during current school year"
/HV124$08 "Education in single years - current school year"
/HV125$08 "Member attended school during previous school year"
/HV126$08 "Educational level during previous school year"
/HV127$08 "Grade of education during previous school year"
/HV128$08 "Education in single years - previous school year"
/HV129$08 "School attendance status"
/HVIDX$09 "Line number"
/HV101$09 "Relationship to head"
/HV102$09 "Usual resident"
/HV103$09 "Slept last night"
/HV104$09 "Sex of household member"
/HV105$09 "Age of household members"
/HV106$09 "Highest educational level"
/HV107$09 "Highest year of education"
/HV108$09 "Education in single years"
/HV109$09 "Educational attainment"
/HV110$09 "Member still in school"
/HV111$09 "Mother alive"
/HV112$09 "Mother's line number"
/HV113$09 "Father alive"
/HV114$09 "Father's line number"
/HV115$09 "Current marital status     -NA"
/HV116$09 "Currently, formerly, never -NA"
/HV117$09 "Eligibility for female interview"
/HV118$09 "Eligibility for male interview"
/HV120$09 "Children eligibility for height/weight and hemoglobin"
/HV121$09 "Member attended school during current school year"
/HV122$09 "Educational level during current school year"
/HV123$09 "Grade of education during current school year"
/HV124$09 "Education in single years - current school year"
/HV125$09 "Member attended school during previous school year"
/HV126$09 "Educational level during previous school year"
/HV127$09 "Grade of education during previous school year"
/HV128$09 "Education in single years - previous school year"
/HV129$09 "School attendance status"
/HVIDX$10 "Line number"
/HV101$10 "Relationship to head"
/HV102$10 "Usual resident"
/HV103$10 "Slept last night"
/HV104$10 "Sex of household member"
/HV105$10 "Age of household members"
/HV106$10 "Highest educational level"
/HV107$10 "Highest year of education"
/HV108$10 "Education in single years"
/HV109$10 "Educational attainment"
/HV110$10 "Member still in school"
/HV111$10 "Mother alive"
/HV112$10 "Mother's line number"
/HV113$10 "Father alive"
/HV114$10 "Father's line number"
/HV115$10 "Current marital status     -NA"
/HV116$10 "Currently, formerly, never -NA"
/HV117$10 "Eligibility for female interview"
/HV118$10 "Eligibility for male interview"
/HV120$10 "Children eligibility for height/weight and hemoglobin"
/HV121$10 "Member attended school during current school year"
/HV122$10 "Educational level during current school year"
/HV123$10 "Grade of education during current school year"
/HV124$10 "Education in single years - current school year"
/HV125$10 "Member attended school during previous school year"
/HV126$10 "Educational level during previous school year"
/HV127$10 "Grade of education during previous school year"
/HV128$10 "Education in single years - previous school year"
/HV129$10 "School attendance status"
/HVIDX$11 "Line number"
/HV101$11 "Relationship to head"
/HV102$11 "Usual resident"
/HV103$11 "Slept last night"
/HV104$11 "Sex of household member"
/HV105$11 "Age of household members"
/HV106$11 "Highest educational level"
/HV107$11 "Highest year of education"
/HV108$11 "Education in single years"
/HV109$11 "Educational attainment"
/HV110$11 "Member still in school"
/HV111$11 "Mother alive"
/HV112$11 "Mother's line number"
/HV113$11 "Father alive"
/HV114$11 "Father's line number"
/HV115$11 "Current marital status     -NA"
/HV116$11 "Currently, formerly, never -NA"
/HV117$11 "Eligibility for female interview"
/HV118$11 "Eligibility for male interview"
/HV120$11 "Children eligibility for height/weight and hemoglobin"
/HV121$11 "Member attended school during current school year"
/HV122$11 "Educational level during current school year"
/HV123$11 "Grade of education during current school year"
/HV124$11 "Education in single years - current school year"
/HV125$11 "Member attended school during previous school year"
/HV126$11 "Educational level during previous school year"
/HV127$11 "Grade of education during previous school year"
/HV128$11 "Education in single years - previous school year"
/HV129$11 "School attendance status"
/HVIDX$12 "Line number"
/HV101$12 "Relationship to head"
/HV102$12 "Usual resident"
/HV103$12 "Slept last night"
/HV104$12 "Sex of household member"
/HV105$12 "Age of household members"
/HV106$12 "Highest educational level"
/HV107$12 "Highest year of education"
/HV108$12 "Education in single years"
/HV109$12 "Educational attainment"
/HV110$12 "Member still in school"
/HV111$12 "Mother alive"
/HV112$12 "Mother's line number"
/HV113$12 "Father alive"
/HV114$12 "Father's line number"
/HV115$12 "Current marital status     -NA"
/HV116$12 "Currently, formerly, never -NA"
/HV117$12 "Eligibility for female interview"
/HV118$12 "Eligibility for male interview"
/HV120$12 "Children eligibility for height/weight and hemoglobin"
/HV121$12 "Member attended school during current school year"
/HV122$12 "Educational level during current school year"
/HV123$12 "Grade of education during current school year"
/HV124$12 "Education in single years - current school year"
/HV125$12 "Member attended school during previous school year"
/HV126$12 "Educational level during previous school year"
/HV127$12 "Grade of education during previous school year"
/HV128$12 "Education in single years - previous school year"
/HV129$12 "School attendance status"
/HVIDX$13 "Line number"
/HV101$13 "Relationship to head"
/HV102$13 "Usual resident"
/HV103$13 "Slept last night"
/HV104$13 "Sex of household member"
/HV105$13 "Age of household members"
/HV106$13 "Highest educational level"
/HV107$13 "Highest year of education"
/HV108$13 "Education in single years"
/HV109$13 "Educational attainment"
/HV110$13 "Member still in school"
/HV111$13 "Mother alive"
/HV112$13 "Mother's line number"
/HV113$13 "Father alive"
/HV114$13 "Father's line number"
/HV115$13 "Current marital status     -NA"
/HV116$13 "Currently, formerly, never -NA"
/HV117$13 "Eligibility for female interview"
/HV118$13 "Eligibility for male interview"
/HV120$13 "Children eligibility for height/weight and hemoglobin"
/HV121$13 "Member attended school during current school year"
/HV122$13 "Educational level during current school year"
/HV123$13 "Grade of education during current school year"
/HV124$13 "Education in single years - current school year"
/HV125$13 "Member attended school during previous school year"
/HV126$13 "Educational level during previous school year"
/HV127$13 "Grade of education during previous school year"
/HV128$13 "Education in single years - previous school year"
/HV129$13 "School attendance status"
/HVIDX$14 "Line number"
/HV101$14 "Relationship to head"
/HV102$14 "Usual resident"
/HV103$14 "Slept last night"
/HV104$14 "Sex of household member"
/HV105$14 "Age of household members"
/HV106$14 "Highest educational level"
/HV107$14 "Highest year of education"
/HV108$14 "Education in single years"
/HV109$14 "Educational attainment"
/HV110$14 "Member still in school"
/HV111$14 "Mother alive"
/HV112$14 "Mother's line number"
/HV113$14 "Father alive"
/HV114$14 "Father's line number"
/HV115$14 "Current marital status     -NA"
/HV116$14 "Currently, formerly, never -NA"
/HV117$14 "Eligibility for female interview"
/HV118$14 "Eligibility for male interview"
/HV120$14 "Children eligibility for height/weight and hemoglobin"
/HV121$14 "Member attended school during current school year"
/HV122$14 "Educational level during current school year"
/HV123$14 "Grade of education during current school year"
/HV124$14 "Education in single years - current school year"
/HV125$14 "Member attended school during previous school year"
/HV126$14 "Educational level during previous school year"
/HV127$14 "Grade of education during previous school year"
/HV128$14 "Education in single years - previous school year"
/HV129$14 "School attendance status"
/HVIDX$15 "Line number"
/HV101$15 "Relationship to head"
/HV102$15 "Usual resident"
/HV103$15 "Slept last night"
/HV104$15 "Sex of household member"
/HV105$15 "Age of household members"
/HV106$15 "Highest educational level"
/HV107$15 "Highest year of education"
/HV108$15 "Education in single years"
/HV109$15 "Educational attainment"
/HV110$15 "Member still in school"
/HV111$15 "Mother alive"
/HV112$15 "Mother's line number"
/HV113$15 "Father alive"
/HV114$15 "Father's line number"
/HV115$15 "Current marital status     -NA"
/HV116$15 "Currently, formerly, never -NA"
/HV117$15 "Eligibility for female interview"
/HV118$15 "Eligibility for male interview"
/HV120$15 "Children eligibility for height/weight and hemoglobin"
/HV121$15 "Member attended school during current school year"
/HV122$15 "Educational level during current school year"
/HV123$15 "Grade of education during current school year"
/HV124$15 "Education in single years - current school year"
/HV125$15 "Member attended school during previous school year"
/HV126$15 "Educational level during previous school year"
/HV127$15 "Grade of education during previous school year"
/HV128$15 "Education in single years - previous school year"
/HV129$15 "School attendance status"
/HVIDX$16 "Line number"
/HV101$16 "Relationship to head"
/HV102$16 "Usual resident"
/HV103$16 "Slept last night"
/HV104$16 "Sex of household member"
/HV105$16 "Age of household members"
/HV106$16 "Highest educational level"
/HV107$16 "Highest year of education"
/HV108$16 "Education in single years"
/HV109$16 "Educational attainment"
/HV110$16 "Member still in school"
/HV111$16 "Mother alive"
/HV112$16 "Mother's line number"
/HV113$16 "Father alive"
/HV114$16 "Father's line number"
/HV115$16 "Current marital status     -NA"
/HV116$16 "Currently, formerly, never -NA"
/HV117$16 "Eligibility for female interview"
/HV118$16 "Eligibility for male interview"
/HV120$16 "Children eligibility for height/weight and hemoglobin"
/HV121$16 "Member attended school during current school year"
/HV122$16 "Educational level during current school year"
/HV123$16 "Grade of education during current school year"
/HV124$16 "Education in single years - current school year"
/HV125$16 "Member attended school during previous school year"
/HV126$16 "Educational level during previous school year"
/HV127$16 "Grade of education during previous school year"
/HV128$16 "Education in single years - previous school year"
/HV129$16 "School attendance status"
/HVIDX$17 "Line number"
/HV101$17 "Relationship to head"
/HV102$17 "Usual resident"
/HV103$17 "Slept last night"
/HV104$17 "Sex of household member"
/HV105$17 "Age of household members"
/HV106$17 "Highest educational level"
/HV107$17 "Highest year of education"
/HV108$17 "Education in single years"
/HV109$17 "Educational attainment"
/HV110$17 "Member still in school"
/HV111$17 "Mother alive"
/HV112$17 "Mother's line number"
/HV113$17 "Father alive"
/HV114$17 "Father's line number"
/HV115$17 "Current marital status     -NA"
/HV116$17 "Currently, formerly, never -NA"
/HV117$17 "Eligibility for female interview"
/HV118$17 "Eligibility for male interview"
/HV120$17 "Children eligibility for height/weight and hemoglobin"
/HV121$17 "Member attended school during current school year"
/HV122$17 "Educational level during current school year"
/HV123$17 "Grade of education during current school year"
/HV124$17 "Education in single years - current school year"
/HV125$17 "Member attended school during previous school year"
/HV126$17 "Educational level during previous school year"
/HV127$17 "Grade of education during previous school year"
/HV128$17 "Education in single years - previous school year"
/HV129$17 "School attendance status"
/HVIDX$18 "Line number"
/HV101$18 "Relationship to head"
/HV102$18 "Usual resident"
/HV103$18 "Slept last night"
/HV104$18 "Sex of household member"
/HV105$18 "Age of household members"
/HV106$18 "Highest educational level"
/HV107$18 "Highest year of education"
/HV108$18 "Education in single years"
/HV109$18 "Educational attainment"
/HV110$18 "Member still in school"
/HV111$18 "Mother alive"
/HV112$18 "Mother's line number"
/HV113$18 "Father alive"
/HV114$18 "Father's line number"
/HV115$18 "Current marital status     -NA"
/HV116$18 "Currently, formerly, never -NA"
/HV117$18 "Eligibility for female interview"
/HV118$18 "Eligibility for male interview"
/HV120$18 "Children eligibility for height/weight and hemoglobin"
/HV121$18 "Member attended school during current school year"
/HV122$18 "Educational level during current school year"
/HV123$18 "Grade of education during current school year"
/HV124$18 "Education in single years - current school year"
/HV125$18 "Member attended school during previous school year"
/HV126$18 "Educational level during previous school year"
/HV127$18 "Grade of education during previous school year"
/HV128$18 "Education in single years - previous school year"
/HV129$18 "School attendance status"
/HVIDX$19 "Line number"
/HV101$19 "Relationship to head"
/HV102$19 "Usual resident"
/HV103$19 "Slept last night"
/HV104$19 "Sex of household member"
/HV105$19 "Age of household members"
/HV106$19 "Highest educational level"
/HV107$19 "Highest year of education"
/HV108$19 "Education in single years"
/HV109$19 "Educational attainment"
/HV110$19 "Member still in school"
/HV111$19 "Mother alive"
/HV112$19 "Mother's line number"
/HV113$19 "Father alive"
/HV114$19 "Father's line number"
/HV115$19 "Current marital status     -NA"
/HV116$19 "Currently, formerly, never -NA"
/HV117$19 "Eligibility for female interview"
/HV118$19 "Eligibility for male interview"
/HV120$19 "Children eligibility for height/weight and hemoglobin"
/HV121$19 "Member attended school during current school year"
/HV122$19 "Educational level during current school year"
/HV123$19 "Grade of education during current school year"
/HV124$19 "Education in single years - current school year"
/HV125$19 "Member attended school during previous school year"
/HV126$19 "Educational level during previous school year"
/HV127$19 "Grade of education during previous school year"
/HV128$19 "Education in single years - previous school year"
/HV129$19 "School attendance status"
/HVIDX$20 "Line number"
/HV101$20 "Relationship to head"
/HV102$20 "Usual resident"
/HV103$20 "Slept last night"
/HV104$20 "Sex of household member"
/HV105$20 "Age of household members"
/HV106$20 "Highest educational level"
/HV107$20 "Highest year of education"
/HV108$20 "Education in single years"
/HV109$20 "Educational attainment"
/HV110$20 "Member still in school"
/HV111$20 "Mother alive"
/HV112$20 "Mother's line number"
/HV113$20 "Father alive"
/HV114$20 "Father's line number"
/HV115$20 "Current marital status     -NA"
/HV116$20 "Currently, formerly, never -NA"
/HV117$20 "Eligibility for female interview"
/HV118$20 "Eligibility for male interview"
/HV120$20 "Children eligibility for height/weight and hemoglobin"
/HV121$20 "Member attended school during current school year"
/HV122$20 "Educational level during current school year"
/HV123$20 "Grade of education during current school year"
/HV124$20 "Education in single years - current school year"
/HV125$20 "Member attended school during previous school year"
/HV126$20 "Educational level during previous school year"
/HV127$20 "Grade of education during previous school year"
/HV128$20 "Education in single years - previous school year"
/HV129$20 "School attendance status"
/SHINTD   "Day of household interview - Gregorian calendar"
/SHINTM   "Month of household interview - Gregorian calendar"
/SHINTY   "Year of household interview - Gregorian calendar"
/SHINTC   "Date of HH interview (CMC) - Gregorian calendar"
/SH25E    "Household has an electric mitad"
/SH25F    "Household has a kerosene lamp/pressure lamp"
/SH25G    "Household has a bed/table"
/SH25AA   "Own house"
/SH25AB   "Crop land"
/SH25AC   "Cattle/camels"
/SH25AD   "Horse/mule/donkey"
/SH25AE   "Sheep/goats"
/SH25AF   "Cash crops"
/SH27B    "Rooms for sleeping"
/SH28D    "Member owns a horse/mule"
/SH29A    "Treatment sick child"
/SH29B    "Immunization"
/SH29C    "Family planning"
/SH29D    "Prenatal/postnatal/delivery are"
/SH29E    "Information on STD/HIV/AIDS"
/SH29F    "Information on breastfeeding/infant feeding"
/SH29BA   "Facilities received services from: Government hospital"
/SH29BB   "Facilities received services from: Health center"
/SH29BC   "Facilities received services from: Health station/clinic"
/SH29BD   "Facilities received services from: Health post"
/SH29BE   "Facilities received services from: Comm. based outlet"
/SH29BF   "Facilities received services from: Other government"
/SH29BG   "Facilities received services from: NGO health facility"
/SH29BH   "Facilities received services from: NGO comm. based outlet"
/SH29BI   "Facilities received services from: Other NGO"
/SH29BJ   "Facilities received services from: Private hospital"
/SH29BK   "Facilities received services from: Private doctor/clinic"
/SH29BL   "Facilities received services from: Other private"
/SH29BM   "Facilities received services from: Kebele - during campaign"
/SH29BX   "Facilities received services from: Other source"
/SH29CA   "Bought drugs in last 12 months"
/SH29DA   "Where bought drugs from - Pharmacy/Other medical facility"
/SH29DB   "Where bought drugs from - Non medical facility"
/SH29GA   "Bednets have been treated"
/SH35     "Test salt for Iodine"
/IDXH4$01 "Index to household schedule"
/SH14$01  "Able to read and write"
/IDXH4$02 "Index to household schedule"
/SH14$02  "Able to read and write"
/IDXH4$03 "Index to household schedule"
/SH14$03  "Able to read and write"
/IDXH4$04 "Index to household schedule"
/SH14$04  "Able to read and write"
/IDXH4$05 "Index to household schedule"
/SH14$05  "Able to read and write"
/IDXH4$06 "Index to household schedule"
/SH14$06  "Able to read and write"
/IDXH4$07 "Index to household schedule"
/SH14$07  "Able to read and write"
/IDXH4$08 "Index to household schedule"
/SH14$08  "Able to read and write"
/IDXH4$09 "Index to household schedule"
/SH14$09  "Able to read and write"
/IDXH4$10 "Index to household schedule"
/SH14$10  "Able to read and write"
/IDXH4$11 "Index to household schedule"
/SH14$11  "Able to read and write"
/IDXH4$12 "Index to household schedule"
/SH14$12  "Able to read and write"
/IDXH4$13 "Index to household schedule"
/SH14$13  "Able to read and write"
/IDXH4$14 "Index to household schedule"
/SH14$14  "Able to read and write"
/IDXH4$15 "Index to household schedule"
/SH14$15  "Able to read and write"
/IDXH4$16 "Index to household schedule"
/SH14$16  "Able to read and write"
/IDXH4$17 "Index to household schedule"
/SH14$17  "Able to read and write"
/IDXH4$18 "Index to household schedule"
/SH14$18  "Able to read and write"
/IDXH4$19 "Index to household schedule"
/SH14$19  "Able to read and write"
/IDXH4$20 "Index to household schedule"
/SH14$20  "Able to read and write"
/HA0$1    "Index to household schedule"
/HA1$1    "Women's age in years"
/HA2$1    "Respondent's weight (kilos-1d)"
/HA3$1    "Respondent's height (cms-1d)"
/HA4$1    "Ht/A Percentile (resp.)"
/HA5$1    "Ht/A Standard deviations (resp"
/HA6$1    "Ht/A Percent ref. median (resp"
/HA11$1   "Wt/Ht Std deviations(resp) DHS"
/HA12$1   "Wt/Ht Percent ref. median (DHS"
/HA12A$1  "Wt/Ht Percent ref. median (Fog"
/HA12B$1  "Wt/Ht Percent ref. median (WHO"
/HA13$1   "Result of measurement of resp."
/HA32$1   "Date of birth (cmc)"
/HA33$1   "Completeness of information"
/HA35$1   "Smoking                    -NA"
/HA40$1   "Body mass index for respondent"
/HA41$1   "Rohrer's index for respondent"
/HA50$1   "Under age 18               -NA"
/HA51$1   "Line no. of parent/caretake-NA"
/HA52$1   "Read consent statement     -NA"
/HA53$1   "Hemoglobin level (g/dl - 1 -NA"
/HA54$1   "Currently pregnant         -NA"
/HA55$1   "Result of measuring (Hemogl-NA"
/HA56$1   "Hemoglobin level adjusted b-NA"
/HA57$1   "Anemia level               -NA"
/HA58$1   "Agrees to referral         -NA"
/HA0$2    "Index to household schedule"
/HA1$2    "Women's age in years"
/HA2$2    "Respondent's weight (kilos-1d)"
/HA3$2    "Respondent's height (cms-1d)"
/HA4$2    "Ht/A Percentile (resp.)"
/HA5$2    "Ht/A Standard deviations (resp"
/HA6$2    "Ht/A Percent ref. median (resp"
/HA11$2   "Wt/Ht Std deviations(resp) DHS"
/HA12$2   "Wt/Ht Percent ref. median (DHS"
/HA12A$2  "Wt/Ht Percent ref. median (Fog"
/HA12B$2  "Wt/Ht Percent ref. median (WHO"
/HA13$2   "Result of measurement of resp."
/HA32$2   "Date of birth (cmc)"
/HA33$2   "Completeness of information"
/HA35$2   "Smoking                    -NA"
/HA40$2   "Body mass index for respondent"
/HA41$2   "Rohrer's index for respondent"
/HA50$2   "Under age 18               -NA"
/HA51$2   "Line no. of parent/caretake-NA"
/HA52$2   "Read consent statement     -NA"
/HA53$2   "Hemoglobin level (g/dl - 1 -NA"
/HA54$2   "Currently pregnant         -NA"
/HA55$2   "Result of measuring (Hemogl-NA"
/HA56$2   "Hemoglobin level adjusted b-NA"
/HA57$2   "Anemia level               -NA"
/HA58$2   "Agrees to referral         -NA"
/HA0$3    "Index to household schedule"
/HA1$3    "Women's age in years"
/HA2$3    "Respondent's weight (kilos-1d)"
/HA3$3    "Respondent's height (cms-1d)"
/HA4$3    "Ht/A Percentile (resp.)"
/HA5$3    "Ht/A Standard deviations (resp"
/HA6$3    "Ht/A Percent ref. median (resp"
/HA11$3   "Wt/Ht Std deviations(resp) DHS"
/HA12$3   "Wt/Ht Percent ref. median (DHS"
/HA12A$3  "Wt/Ht Percent ref. median (Fog"
/HA12B$3  "Wt/Ht Percent ref. median (WHO"
/HA13$3   "Result of measurement of resp."
/HA32$3   "Date of birth (cmc)"
/HA33$3   "Completeness of information"
/HA35$3   "Smoking                    -NA"
/HA40$3   "Body mass index for respondent"
/HA41$3   "Rohrer's index for respondent"
/HA50$3   "Under age 18               -NA"
/HA51$3   "Line no. of parent/caretake-NA"
/HA52$3   "Read consent statement     -NA"
/HA53$3   "Hemoglobin level (g/dl - 1 -NA"
/HA54$3   "Currently pregnant         -NA"
/HA55$3   "Result of measuring (Hemogl-NA"
/HA56$3   "Hemoglobin level adjusted b-NA"
/HA57$3   "Anemia level               -NA"
/HA58$3   "Agrees to referral         -NA"
/HA0$4    "Index to household schedule"
/HA1$4    "Women's age in years"
/HA2$4    "Respondent's weight (kilos-1d)"
/HA3$4    "Respondent's height (cms-1d)"
/HA4$4    "Ht/A Percentile (resp.)"
/HA5$4    "Ht/A Standard deviations (resp"
/HA6$4    "Ht/A Percent ref. median (resp"
/HA11$4   "Wt/Ht Std deviations(resp) DHS"
/HA12$4   "Wt/Ht Percent ref. median (DHS"
/HA12A$4  "Wt/Ht Percent ref. median (Fog"
/HA12B$4  "Wt/Ht Percent ref. median (WHO"
/HA13$4   "Result of measurement of resp."
/HA32$4   "Date of birth (cmc)"
/HA33$4   "Completeness of information"
/HA35$4   "Smoking                    -NA"
/HA40$4   "Body mass index for respondent"
/HA41$4   "Rohrer's index for respondent"
/HA50$4   "Under age 18               -NA"
/HA51$4   "Line no. of parent/caretake-NA"
/HA52$4   "Read consent statement     -NA"
/HA53$4   "Hemoglobin level (g/dl - 1 -NA"
/HA54$4   "Currently pregnant         -NA"
/HA55$4   "Result of measuring (Hemogl-NA"
/HA56$4   "Hemoglobin level adjusted b-NA"
/HA57$4   "Anemia level               -NA"
/HA58$4   "Agrees to referral         -NA"
/HA0$5    "Index to household schedule"
/HA1$5    "Women's age in years"
/HA2$5    "Respondent's weight (kilos-1d)"
/HA3$5    "Respondent's height (cms-1d)"
/HA4$5    "Ht/A Percentile (resp.)"
/HA5$5    "Ht/A Standard deviations (resp"
/HA6$5    "Ht/A Percent ref. median (resp"
/HA11$5   "Wt/Ht Std deviations(resp) DHS"
/HA12$5   "Wt/Ht Percent ref. median (DHS"
/HA12A$5  "Wt/Ht Percent ref. median (Fog"
/HA12B$5  "Wt/Ht Percent ref. median (WHO"
/HA13$5   "Result of measurement of resp."
/HA32$5   "Date of birth (cmc)"
/HA33$5   "Completeness of information"
/HA35$5   "Smoking                    -NA"
/HA40$5   "Body mass index for respondent"
/HA41$5   "Rohrer's index for respondent"
/HA50$5   "Under age 18               -NA"
/HA51$5   "Line no. of parent/caretake-NA"
/HA52$5   "Read consent statement     -NA"
/HA53$5   "Hemoglobin level (g/dl - 1 -NA"
/HA54$5   "Currently pregnant         -NA"
/HA55$5   "Result of measuring (Hemogl-NA"
/HA56$5   "Hemoglobin level adjusted b-NA"
/HA57$5   "Anemia level               -NA"
/HA58$5   "Agrees to referral         -NA"
/HA0$6    "Index to household schedule"
/HA1$6    "Women's age in years"
/HA2$6    "Respondent's weight (kilos-1d)"
/HA3$6    "Respondent's height (cms-1d)"
/HA4$6    "Ht/A Percentile (resp.)"
/HA5$6    "Ht/A Standard deviations (resp"
/HA6$6    "Ht/A Percent ref. median (resp"
/HA11$6   "Wt/Ht Std deviations(resp) DHS"
/HA12$6   "Wt/Ht Percent ref. median (DHS"
/HA12A$6  "Wt/Ht Percent ref. median (Fog"
/HA12B$6  "Wt/Ht Percent ref. median (WHO"
/HA13$6   "Result of measurement of resp."
/HA32$6   "Date of birth (cmc)"
/HA33$6   "Completeness of information"
/HA35$6   "Smoking                    -NA"
/HA40$6   "Body mass index for respondent"
/HA41$6   "Rohrer's index for respondent"
/HA50$6   "Under age 18               -NA"
/HA51$6   "Line no. of parent/caretake-NA"
/HA52$6   "Read consent statement     -NA"
/HA53$6   "Hemoglobin level (g/dl - 1 -NA"
/HA54$6   "Currently pregnant         -NA"
/HA55$6   "Result of measuring (Hemogl-NA"
/HA56$6   "Hemoglobin level adjusted b-NA"
/HA57$6   "Anemia level               -NA"
/HA58$6   "Agrees to referral         -NA"
/HA0$7    "Index to household schedule"
/HA1$7    "Women's age in years"
/HA2$7    "Respondent's weight (kilos-1d)"
/HA3$7    "Respondent's height (cms-1d)"
/HA4$7    "Ht/A Percentile (resp.)"
/HA5$7    "Ht/A Standard deviations (resp"
/HA6$7    "Ht/A Percent ref. median (resp"
/HA11$7   "Wt/Ht Std deviations(resp) DHS"
/HA12$7   "Wt/Ht Percent ref. median (DHS"
/HA12A$7  "Wt/Ht Percent ref. median (Fog"
/HA12B$7  "Wt/Ht Percent ref. median (WHO"
/HA13$7   "Result of measurement of resp."
/HA32$7   "Date of birth (cmc)"
/HA33$7   "Completeness of information"
/HA35$7   "Smoking                    -NA"
/HA40$7   "Body mass index for respondent"
/HA41$7   "Rohrer's index for respondent"
/HA50$7   "Under age 18               -NA"
/HA51$7   "Line no. of parent/caretake-NA"
/HA52$7   "Read consent statement     -NA"
/HA53$7   "Hemoglobin level (g/dl - 1 -NA"
/HA54$7   "Currently pregnant         -NA"
/HA55$7   "Result of measuring (Hemogl-NA"
/HA56$7   "Hemoglobin level adjusted b-NA"
/HA57$7   "Anemia level               -NA"
/HA58$7   "Agrees to referral         -NA"
/HA0$8    "Index to household schedule"
/HA1$8    "Women's age in years"
/HA2$8    "Respondent's weight (kilos-1d)"
/HA3$8    "Respondent's height (cms-1d)"
/HA4$8    "Ht/A Percentile (resp.)"
/HA5$8    "Ht/A Standard deviations (resp"
/HA6$8    "Ht/A Percent ref. median (resp"
/HA11$8   "Wt/Ht Std deviations(resp) DHS"
/HA12$8   "Wt/Ht Percent ref. median (DHS"
/HA12A$8  "Wt/Ht Percent ref. median (Fog"
/HA12B$8  "Wt/Ht Percent ref. median (WHO"
/HA13$8   "Result of measurement of resp."
/HA32$8   "Date of birth (cmc)"
/HA33$8   "Completeness of information"
/HA35$8   "Smoking                    -NA"
/HA40$8   "Body mass index for respondent"
/HA41$8   "Rohrer's index for respondent"
/HA50$8   "Under age 18               -NA"
/HA51$8   "Line no. of parent/caretake-NA"
/HA52$8   "Read consent statement     -NA"
/HA53$8   "Hemoglobin level (g/dl - 1 -NA"
/HA54$8   "Currently pregnant         -NA"
/HA55$8   "Result of measuring (Hemogl-NA"
/HA56$8   "Hemoglobin level adjusted b-NA"
/HA57$8   "Anemia level               -NA"
/HA58$8   "Agrees to referral         -NA"
/HC0$1    "Index to household schedule"
/HC1$1    "Age in months"
/HC2$1    "Weight in kilograms (1 dec.)"
/HC3$1    "Height in centimeters (1 dec.)"
/HC4$1    "Ht/A Percentile"
/HC5$1    "Ht/A Standard deviations"
/HC6$1    "Ht/A Percent of ref. median"
/HC7$1    "Wt/A Percentile"
/HC8$1    "Wt/A Standard deviations"
/HC9$1    "Wt/A Percent of ref. median"
/HC10$1   "Wt/Ht Percentile"
/HC11$1   "Wt/Ht Standard deviations"
/HC12$1   "Wt/Ht Percent of ref. median"
/HC13$1   "Reason not measured"
/HC15$1   "Height: lying or standing"
/HC16$1   "Day of birth of child"
/HC17$1   "Date measured (day)"
/HC18$1   "Date measured (month)"
/HC19$1   "Date measured (year)"
/HC27$1   "Sex"
/HC30$1   "Month of birth of child"
/HC31$1   "Year of birth of child"
/HC32$1   "Date of birth (cmc)"
/HC33$1   "Completeness of information"
/HC51$1   "Line no. of parent/caretake-NA"
/HC52$1   "Read consent statement     -NA"
/HC53$1   "Hemoglobin level (g/dl - 1 -NA"
/HC55$1   "Result of measuring (Hemogl-NA"
/HC56$1   "Hemoglobin level adjusted b-NA"
/HC57$1   "Anemia level               -NA"
/HC58$1   "Agrees to referral         -NA"
/HC60$1   "Women's line number from women's questionnaire"
/HC61$1   "Mother's highest educational level"
/HC62$1   "Mother's highest year of education"
/HC63$1   "Preceding birth interval"
/HC64$1   "Birth order number"
/HC0$2    "Index to household schedule"
/HC1$2    "Age in months"
/HC2$2    "Weight in kilograms (1 dec.)"
/HC3$2    "Height in centimeters (1 dec.)"
/HC4$2    "Ht/A Percentile"
/HC5$2    "Ht/A Standard deviations"
/HC6$2    "Ht/A Percent of ref. median"
/HC7$2    "Wt/A Percentile"
/HC8$2    "Wt/A Standard deviations"
/HC9$2    "Wt/A Percent of ref. median"
/HC10$2   "Wt/Ht Percentile"
/HC11$2   "Wt/Ht Standard deviations"
/HC12$2   "Wt/Ht Percent of ref. median"
/HC13$2   "Reason not measured"
/HC15$2   "Height: lying or standing"
/HC16$2   "Day of birth of child"
/HC17$2   "Date measured (day)"
/HC18$2   "Date measured (month)"
/HC19$2   "Date measured (year)"
/HC27$2   "Sex"
/HC30$2   "Month of birth of child"
/HC31$2   "Year of birth of child"
/HC32$2   "Date of birth (cmc)"
/HC33$2   "Completeness of information"
/HC51$2   "Line no. of parent/caretake-NA"
/HC52$2   "Read consent statement     -NA"
/HC53$2   "Hemoglobin level (g/dl - 1 -NA"
/HC55$2   "Result of measuring (Hemogl-NA"
/HC56$2   "Hemoglobin level adjusted b-NA"
/HC57$2   "Anemia level               -NA"
/HC58$2   "Agrees to referral         -NA"
/HC60$2   "Women's line number from women's questionnaire"
/HC61$2   "Mother's highest educational level"
/HC62$2   "Mother's highest year of education"
/HC63$2   "Preceding birth interval"
/HC64$2   "Birth order number"
/HC0$3    "Index to household schedule"
/HC1$3    "Age in months"
/HC2$3    "Weight in kilograms (1 dec.)"
/HC3$3    "Height in centimeters (1 dec.)"
/HC4$3    "Ht/A Percentile"
/HC5$3    "Ht/A Standard deviations"
/HC6$3    "Ht/A Percent of ref. median"
/HC7$3    "Wt/A Percentile"
/HC8$3    "Wt/A Standard deviations"
/HC9$3    "Wt/A Percent of ref. median"
/HC10$3   "Wt/Ht Percentile"
/HC11$3   "Wt/Ht Standard deviations"
/HC12$3   "Wt/Ht Percent of ref. median"
/HC13$3   "Reason not measured"
/HC15$3   "Height: lying or standing"
/HC16$3   "Day of birth of child"
/HC17$3   "Date measured (day)"
/HC18$3   "Date measured (month)"
/HC19$3   "Date measured (year)"
/HC27$3   "Sex"
/HC30$3   "Month of birth of child"
/HC31$3   "Year of birth of child"
/HC32$3   "Date of birth (cmc)"
/HC33$3   "Completeness of information"
/HC51$3   "Line no. of parent/caretake-NA"
/HC52$3   "Read consent statement     -NA"
/HC53$3   "Hemoglobin level (g/dl - 1 -NA"
/HC55$3   "Result of measuring (Hemogl-NA"
/HC56$3   "Hemoglobin level adjusted b-NA"
/HC57$3   "Anemia level               -NA"
/HC58$3   "Agrees to referral         -NA"
/HC60$3   "Women's line number from women's questionnaire"
/HC61$3   "Mother's highest educational level"
/HC62$3   "Mother's highest year of education"
/HC63$3   "Preceding birth interval"
/HC64$3   "Birth order number"
/HC0$4    "Index to household schedule"
/HC1$4    "Age in months"
/HC2$4    "Weight in kilograms (1 dec.)"
/HC3$4    "Height in centimeters (1 dec.)"
/HC4$4    "Ht/A Percentile"
/HC5$4    "Ht/A Standard deviations"
/HC6$4    "Ht/A Percent of ref. median"
/HC7$4    "Wt/A Percentile"
/HC8$4    "Wt/A Standard deviations"
/HC9$4    "Wt/A Percent of ref. median"
/HC10$4   "Wt/Ht Percentile"
/HC11$4   "Wt/Ht Standard deviations"
/HC12$4   "Wt/Ht Percent of ref. median"
/HC13$4   "Reason not measured"
/HC15$4   "Height: lying or standing"
/HC16$4   "Day of birth of child"
/HC17$4   "Date measured (day)"
/HC18$4   "Date measured (month)"
/HC19$4   "Date measured (year)"
/HC27$4   "Sex"
/HC30$4   "Month of birth of child"
/HC31$4   "Year of birth of child"
/HC32$4   "Date of birth (cmc)"
/HC33$4   "Completeness of information"
/HC51$4   "Line no. of parent/caretake-NA"
/HC52$4   "Read consent statement     -NA"
/HC53$4   "Hemoglobin level (g/dl - 1 -NA"
/HC55$4   "Result of measuring (Hemogl-NA"
/HC56$4   "Hemoglobin level adjusted b-NA"
/HC57$4   "Anemia level               -NA"
/HC58$4   "Agrees to referral         -NA"
/HC60$4   "Women's line number from women's questionnaire"
/HC61$4   "Mother's highest educational level"
/HC62$4   "Mother's highest year of education"
/HC63$4   "Preceding birth interval"
/HC64$4   "Birth order number"
/HC0$5    "Index to household schedule"
/HC1$5    "Age in months"
/HC2$5    "Weight in kilograms (1 dec.)"
/HC3$5    "Height in centimeters (1 dec.)"
/HC4$5    "Ht/A Percentile"
/HC5$5    "Ht/A Standard deviations"
/HC6$5    "Ht/A Percent of ref. median"
/HC7$5    "Wt/A Percentile"
/HC8$5    "Wt/A Standard deviations"
/HC9$5    "Wt/A Percent of ref. median"
/HC10$5   "Wt/Ht Percentile"
/HC11$5   "Wt/Ht Standard deviations"
/HC12$5   "Wt/Ht Percent of ref. median"
/HC13$5   "Reason not measured"
/HC15$5   "Height: lying or standing"
/HC16$5   "Day of birth of child"
/HC17$5   "Date measured (day)"
/HC18$5   "Date measured (month)"
/HC19$5   "Date measured (year)"
/HC27$5   "Sex"
/HC30$5   "Month of birth of child"
/HC31$5   "Year of birth of child"
/HC32$5   "Date of birth (cmc)"
/HC33$5   "Completeness of information"
/HC51$5   "Line no. of parent/caretake-NA"
/HC52$5   "Read consent statement     -NA"
/HC53$5   "Hemoglobin level (g/dl - 1 -NA"
/HC55$5   "Result of measuring (Hemogl-NA"
/HC56$5   "Hemoglobin level adjusted b-NA"
/HC57$5   "Anemia level               -NA"
/HC58$5   "Agrees to referral         -NA"
/HC60$5   "Women's line number from women's questionnaire"
/HC61$5   "Mother's highest educational level"
/HC62$5   "Mother's highest year of education"
/HC63$5   "Preceding birth interval"
/HC64$5   "Birth order number"
/HC0$6    "Index to household schedule"
/HC1$6    "Age in months"
/HC2$6    "Weight in kilograms (1 dec.)"
/HC3$6    "Height in centimeters (1 dec.)"
/HC4$6    "Ht/A Percentile"
/HC5$6    "Ht/A Standard deviations"
/HC6$6    "Ht/A Percent of ref. median"
/HC7$6    "Wt/A Percentile"
/HC8$6    "Wt/A Standard deviations"
/HC9$6    "Wt/A Percent of ref. median"
/HC10$6   "Wt/Ht Percentile"
/HC11$6   "Wt/Ht Standard deviations"
/HC12$6   "Wt/Ht Percent of ref. median"
/HC13$6   "Reason not measured"
/HC15$6   "Height: lying or standing"
/HC16$6   "Day of birth of child"
/HC17$6   "Date measured (day)"
/HC18$6   "Date measured (month)"
/HC19$6   "Date measured (year)"
/HC27$6   "Sex"
/HC30$6   "Month of birth of child"
/HC31$6   "Year of birth of child"
/HC32$6   "Date of birth (cmc)"
/HC33$6   "Completeness of information"
/HC51$6   "Line no. of parent/caretake-NA"
/HC52$6   "Read consent statement     -NA"
/HC53$6   "Hemoglobin level (g/dl - 1 -NA"
/HC55$6   "Result of measuring (Hemogl-NA"
/HC56$6   "Hemoglobin level adjusted b-NA"
/HC57$6   "Anemia level               -NA"
/HC58$6   "Agrees to referral         -NA"
/HC60$6   "Women's line number from women's questionnaire"
/HC61$6   "Mother's highest educational level"
/HC62$6   "Mother's highest year of education"
/HC63$6   "Preceding birth interval"
/HC64$6   "Birth order number"
.
MISSING VALUE
 HV018    (999)
/HV019    (99)
/HV026    (9)
/HV030    (999)
/HV031    (999)
/HV032    (99)
/HV201    (99)
/HV204    (999)
/HV205    (99)
/HV206    (9)
/HV207    (9)
/HV208    (9)
/HV209    (9)
/HV210    (9)
/HV211    (9)
/HV212    (9)
/HV213    (99)
/HV214    (99)
/HV215    (99)
/HV219    (9)
/HV220    (99)
/HV221    (9)
/HV225    (9)
/HV226    (99)
/HV227    (9)
/HV228    (9)
/HV230    (9)
/HV231    (9)
/HV232    (9)
/HV233    (9)
/HV234    (999)
/HV101$01 (99)
/HV102$01 (9)
/HV103$01 (9)
/HV104$01 (9)
/HV105$01 (99)
/HV106$01 (9)
/HV107$01 (99)
/HV108$01 (99)
/HV109$01 (9)
/HV110$01 (9)
/HV111$01 (9)
/HV112$01 (99)
/HV113$01 (9)
/HV114$01 (99)
/HV115$01 (9)
/HV116$01 (9)
/HV121$01 (9)
/HV122$01 (9)
/HV123$01 (99)
/HV124$01 (99)
/HV125$01 (9)
/HV126$01 (9)
/HV127$01 (99)
/HV128$01 (99)
/HV129$01 (9)
/HV101$02 (99)
/HV102$02 (9)
/HV103$02 (9)
/HV104$02 (9)
/HV105$02 (99)
/HV106$02 (9)
/HV107$02 (99)
/HV108$02 (99)
/HV109$02 (9)
/HV110$02 (9)
/HV111$02 (9)
/HV112$02 (99)
/HV113$02 (9)
/HV114$02 (99)
/HV115$02 (9)
/HV116$02 (9)
/HV121$02 (9)
/HV122$02 (9)
/HV123$02 (99)
/HV124$02 (99)
/HV125$02 (9)
/HV126$02 (9)
/HV127$02 (99)
/HV128$02 (99)
/HV129$02 (9)
/HV101$03 (99)
/HV102$03 (9)
/HV103$03 (9)
/HV104$03 (9)
/HV105$03 (99)
/HV106$03 (9)
/HV107$03 (99)
/HV108$03 (99)
/HV109$03 (9)
/HV110$03 (9)
/HV111$03 (9)
/HV112$03 (99)
/HV113$03 (9)
/HV114$03 (99)
/HV115$03 (9)
/HV116$03 (9)
/HV121$03 (9)
/HV122$03 (9)
/HV123$03 (99)
/HV124$03 (99)
/HV125$03 (9)
/HV126$03 (9)
/HV127$03 (99)
/HV128$03 (99)
/HV129$03 (9)
/HV101$04 (99)
/HV102$04 (9)
/HV103$04 (9)
/HV104$04 (9)
/HV105$04 (99)
/HV106$04 (9)
/HV107$04 (99)
/HV108$04 (99)
/HV109$04 (9)
/HV110$04 (9)
/HV111$04 (9)
/HV112$04 (99)
/HV113$04 (9)
/HV114$04 (99)
/HV115$04 (9)
/HV116$04 (9)
/HV121$04 (9)
/HV122$04 (9)
/HV123$04 (99)
/HV124$04 (99)
/HV125$04 (9)
/HV126$04 (9)
/HV127$04 (99)
/HV128$04 (99)
/HV129$04 (9)
/HV101$05 (99)
/HV102$05 (9)
/HV103$05 (9)
/HV104$05 (9)
/HV105$05 (99)
/HV106$05 (9)
/HV107$05 (99)
/HV108$05 (99)
/HV109$05 (9)
/HV110$05 (9)
/HV111$05 (9)
/HV112$05 (99)
/HV113$05 (9)
/HV114$05 (99)
/HV115$05 (9)
/HV116$05 (9)
/HV121$05 (9)
/HV122$05 (9)
/HV123$05 (99)
/HV124$05 (99)
/HV125$05 (9)
/HV126$05 (9)
/HV127$05 (99)
/HV128$05 (99)
/HV129$05 (9)
/HV101$06 (99)
/HV102$06 (9)
/HV103$06 (9)
/HV104$06 (9)
/HV105$06 (99)
/HV106$06 (9)
/HV107$06 (99)
/HV108$06 (99)
/HV109$06 (9)
/HV110$06 (9)
/HV111$06 (9)
/HV112$06 (99)
/HV113$06 (9)
/HV114$06 (99)
/HV115$06 (9)
/HV116$06 (9)
/HV121$06 (9)
/HV122$06 (9)
/HV123$06 (99)
/HV124$06 (99)
/HV125$06 (9)
/HV126$06 (9)
/HV127$06 (99)
/HV128$06 (99)
/HV129$06 (9)
/HV101$07 (99)
/HV102$07 (9)
/HV103$07 (9)
/HV104$07 (9)
/HV105$07 (99)
/HV106$07 (9)
/HV107$07 (99)
/HV108$07 (99)
/HV109$07 (9)
/HV110$07 (9)
/HV111$07 (9)
/HV112$07 (99)
/HV113$07 (9)
/HV114$07 (99)
/HV115$07 (9)
/HV116$07 (9)
/HV121$07 (9)
/HV122$07 (9)
/HV123$07 (99)
/HV124$07 (99)
/HV125$07 (9)
/HV126$07 (9)
/HV127$07 (99)
/HV128$07 (99)
/HV129$07 (9)
/HV101$08 (99)
/HV102$08 (9)
/HV103$08 (9)
/HV104$08 (9)
/HV105$08 (99)
/HV106$08 (9)
/HV107$08 (99)
/HV108$08 (99)
/HV109$08 (9)
/HV110$08 (9)
/HV111$08 (9)
/HV112$08 (99)
/HV113$08 (9)
/HV114$08 (99)
/HV115$08 (9)
/HV116$08 (9)
/HV121$08 (9)
/HV122$08 (9)
/HV123$08 (99)
/HV124$08 (99)
/HV125$08 (9)
/HV126$08 (9)
/HV127$08 (99)
/HV128$08 (99)
/HV129$08 (9)
/HV101$09 (99)
/HV102$09 (9)
/HV103$09 (9)
/HV104$09 (9)
/HV105$09 (99)
/HV106$09 (9)
/HV107$09 (99)
/HV108$09 (99)
/HV109$09 (9)
/HV110$09 (9)
/HV111$09 (9)
/HV112$09 (99)
/HV113$09 (9)
/HV114$09 (99)
/HV115$09 (9)
/HV116$09 (9)
/HV121$09 (9)
/HV122$09 (9)
/HV123$09 (99)
/HV124$09 (99)
/HV125$09 (9)
/HV126$09 (9)
/HV127$09 (99)
/HV128$09 (99)
/HV129$09 (9)
/HV101$10 (99)
/HV102$10 (9)
/HV103$10 (9)
/HV104$10 (9)
/HV105$10 (99)
/HV106$10 (9)
/HV107$10 (99)
/HV108$10 (99)
/HV109$10 (9)
/HV110$10 (9)
/HV111$10 (9)
/HV112$10 (99)
/HV113$10 (9)
/HV114$10 (99)
/HV115$10 (9)
/HV116$10 (9)
/HV121$10 (9)
/HV122$10 (9)
/HV123$10 (99)
/HV124$10 (99)
/HV125$10 (9)
/HV126$10 (9)
/HV127$10 (99)
/HV128$10 (99)
/HV129$10 (9)
/HV101$11 (99)
/HV102$11 (9)
/HV103$11 (9)
/HV104$11 (9)
/HV105$11 (99)
/HV106$11 (9)
/HV107$11 (99)
/HV108$11 (99)
/HV109$11 (9)
/HV110$11 (9)
/HV111$11 (9)
/HV112$11 (99)
/HV113$11 (9)
/HV114$11 (99)
/HV115$11 (9)
/HV116$11 (9)
/HV121$11 (9)
/HV122$11 (9)
/HV123$11 (99)
/HV124$11 (99)
/HV125$11 (9)
/HV126$11 (9)
/HV127$11 (99)
/HV128$11 (99)
/HV129$11 (9)
/HV101$12 (99)
/HV102$12 (9)
/HV103$12 (9)
/HV104$12 (9)
/HV105$12 (99)
/HV106$12 (9)
/HV107$12 (99)
/HV108$12 (99)
/HV109$12 (9)
/HV110$12 (9)
/HV111$12 (9)
/HV112$12 (99)
/HV113$12 (9)
/HV114$12 (99)
/HV115$12 (9)
/HV116$12 (9)
/HV121$12 (9)
/HV122$12 (9)
/HV123$12 (99)
/HV124$12 (99)
/HV125$12 (9)
/HV126$12 (9)
/HV127$12 (99)
/HV128$12 (99)
/HV129$12 (9)
/HV101$13 (99)
/HV102$13 (9)
/HV103$13 (9)
/HV104$13 (9)
/HV105$13 (99)
/HV106$13 (9)
/HV107$13 (99)
/HV108$13 (99)
/HV109$13 (9)
/HV110$13 (9)
/HV111$13 (9)
/HV112$13 (99)
/HV113$13 (9)
/HV114$13 (99)
/HV115$13 (9)
/HV116$13 (9)
/HV121$13 (9)
/HV122$13 (9)
/HV123$13 (99)
/HV124$13 (99)
/HV125$13 (9)
/HV126$13 (9)
/HV127$13 (99)
/HV128$13 (99)
/HV129$13 (9)
/HV101$14 (99)
/HV102$14 (9)
/HV103$14 (9)
/HV104$14 (9)
/HV105$14 (99)
/HV106$14 (9)
/HV107$14 (99)
/HV108$14 (99)
/HV109$14 (9)
/HV110$14 (9)
/HV111$14 (9)
/HV112$14 (99)
/HV113$14 (9)
/HV114$14 (99)
/HV115$14 (9)
/HV116$14 (9)
/HV121$14 (9)
/HV122$14 (9)
/HV123$14 (99)
/HV124$14 (99)
/HV125$14 (9)
/HV126$14 (9)
/HV127$14 (99)
/HV128$14 (99)
/HV129$14 (9)
/HV101$15 (99)
/HV102$15 (9)
/HV103$15 (9)
/HV104$15 (9)
/HV105$15 (99)
/HV106$15 (9)
/HV107$15 (99)
/HV108$15 (99)
/HV109$15 (9)
/HV110$15 (9)
/HV111$15 (9)
/HV112$15 (99)
/HV113$15 (9)
/HV114$15 (99)
/HV115$15 (9)
/HV116$15 (9)
/HV121$15 (9)
/HV122$15 (9)
/HV123$15 (99)
/HV124$15 (99)
/HV125$15 (9)
/HV126$15 (9)
/HV127$15 (99)
/HV128$15 (99)
/HV129$15 (9)
/HV101$16 (99)
/HV102$16 (9)
/HV103$16 (9)
/HV104$16 (9)
/HV105$16 (99)
/HV106$16 (9)
/HV107$16 (99)
/HV108$16 (99)
/HV109$16 (9)
/HV110$16 (9)
/HV111$16 (9)
/HV112$16 (99)
/HV113$16 (9)
/HV114$16 (99)
/HV115$16 (9)
/HV116$16 (9)
/HV121$16 (9)
/HV122$16 (9)
/HV123$16 (99)
/HV124$16 (99)
/HV125$16 (9)
/HV126$16 (9)
/HV127$16 (99)
/HV128$16 (99)
/HV129$16 (9)
/HV101$17 (99)
/HV102$17 (9)
/HV103$17 (9)
/HV104$17 (9)
/HV105$17 (99)
/HV106$17 (9)
/HV107$17 (99)
/HV108$17 (99)
/HV109$17 (9)
/HV110$17 (9)
/HV111$17 (9)
/HV112$17 (99)
/HV113$17 (9)
/HV114$17 (99)
/HV115$17 (9)
/HV116$17 (9)
/HV121$17 (9)
/HV122$17 (9)
/HV123$17 (99)
/HV124$17 (99)
/HV125$17 (9)
/HV126$17 (9)
/HV127$17 (99)
/HV128$17 (99)
/HV129$17 (9)
/HV101$18 (99)
/HV102$18 (9)
/HV103$18 (9)
/HV104$18 (9)
/HV105$18 (99)
/HV106$18 (9)
/HV107$18 (99)
/HV108$18 (99)
/HV109$18 (9)
/HV110$18 (9)
/HV111$18 (9)
/HV112$18 (99)
/HV113$18 (9)
/HV114$18 (99)
/HV115$18 (9)
/HV116$18 (9)
/HV121$18 (9)
/HV122$18 (9)
/HV123$18 (99)
/HV124$18 (99)
/HV125$18 (9)
/HV126$18 (9)
/HV127$18 (99)
/HV128$18 (99)
/HV129$18 (9)
/HV101$19 (99)
/HV102$19 (9)
/HV103$19 (9)
/HV104$19 (9)
/HV105$19 (99)
/HV106$19 (9)
/HV107$19 (99)
/HV108$19 (99)
/HV109$19 (9)
/HV110$19 (9)
/HV111$19 (9)
/HV112$19 (99)
/HV113$19 (9)
/HV114$19 (99)
/HV115$19 (9)
/HV116$19 (9)
/HV121$19 (9)
/HV122$19 (9)
/HV123$19 (99)
/HV124$19 (99)
/HV125$19 (9)
/HV126$19 (9)
/HV127$19 (99)
/HV128$19 (99)
/HV129$19 (9)
/HV101$20 (99)
/HV102$20 (9)
/HV103$20 (9)
/HV104$20 (9)
/HV105$20 (99)
/HV106$20 (9)
/HV107$20 (99)
/HV108$20 (99)
/HV109$20 (9)
/HV110$20 (9)
/HV111$20 (9)
/HV112$20 (99)
/HV113$20 (9)
/HV114$20 (99)
/HV115$20 (9)
/HV116$20 (9)
/HV121$20 (9)
/HV122$20 (9)
/HV123$20 (99)
/HV124$20 (99)
/HV125$20 (9)
/HV126$20 (9)
/HV127$20 (99)
/HV128$20 (99)
/HV129$20 (9)
/SH25E    (9)
/SH25F    (9)
/SH25G    (9)
/SH25AA   (9)
/SH25AB   (9)
/SH25AC   (9)
/SH25AD   (9)
/SH25AE   (9)
/SH25AF   (9)
/SH27B    (99)
/SH28D    (9)
/SH29A    (9)
/SH29B    (9)
/SH29C    (9)
/SH29D    (9)
/SH29E    (9)
/SH29F    (9)
/SH29BA   (9)
/SH29BB   (9)
/SH29BC   (9)
/SH29BD   (9)
/SH29BE   (9)
/SH29BF   (9)
/SH29BG   (9)
/SH29BH   (9)
/SH29BI   (9)
/SH29BJ   (9)
/SH29BK   (9)
/SH29BL   (9)
/SH29BM   (9)
/SH29BX   (9)
/SH29CA   (9)
/SH29DA   (9)
/SH29DB   (9)
/SH29GA   (9)
/SH35     (9)
/SH14$01  (9)
/SH14$02  (9)
/SH14$03  (9)
/SH14$04  (9)
/SH14$05  (9)
/SH14$06  (9)
/SH14$07  (9)
/SH14$08  (9)
/SH14$09  (9)
/SH14$10  (9)
/SH14$11  (9)
/SH14$12  (9)
/SH14$13  (9)
/SH14$14  (9)
/SH14$15  (9)
/SH14$16  (9)
/SH14$17  (9)
/SH14$18  (9)
/SH14$19  (9)
/SH14$20  (9)
/HA2$1    (9999)
/HA3$1    (9999)
/HA4$1    (9999)
/HA5$1    (9999)
/HA6$1    (99999)
/HA11$1   (9999)
/HA12$1   (99999)
/HA12A$1  (99999)
/HA12B$1  (99999)
/HA13$1   (9)
/HA35$1   (9)
/HA40$1   (9999)
/HA41$1   (9999)
/HA50$1   (9)
/HA52$1   (9)
/HA53$1   (999)
/HA54$1   (9)
/HA55$1   (9)
/HA56$1   (999)
/HA57$1   (9)
/HA58$1   (9)
/HA2$2    (9999)
/HA3$2    (9999)
/HA4$2    (9999)
/HA5$2    (9999)
/HA6$2    (99999)
/HA11$2   (9999)
/HA12$2   (99999)
/HA12A$2  (99999)
/HA12B$2  (99999)
/HA13$2   (9)
/HA35$2   (9)
/HA40$2   (9999)
/HA41$2   (9999)
/HA50$2   (9)
/HA52$2   (9)
/HA53$2   (999)
/HA54$2   (9)
/HA55$2   (9)
/HA56$2   (999)
/HA57$2   (9)
/HA58$2   (9)
/HA2$3    (9999)
/HA3$3    (9999)
/HA4$3    (9999)
/HA5$3    (9999)
/HA6$3    (99999)
/HA11$3   (9999)
/HA12$3   (99999)
/HA12A$3  (99999)
/HA12B$3  (99999)
/HA13$3   (9)
/HA35$3   (9)
/HA40$3   (9999)
/HA41$3   (9999)
/HA50$3   (9)
/HA52$3   (9)
/HA53$3   (999)
/HA54$3   (9)
/HA55$3   (9)
/HA56$3   (999)
/HA57$3   (9)
/HA58$3   (9)
/HA2$4    (9999)
/HA3$4    (9999)
/HA4$4    (9999)
/HA5$4    (9999)
/HA6$4    (99999)
/HA11$4   (9999)
/HA12$4   (99999)
/HA12A$4  (99999)
/HA12B$4  (99999)
/HA13$4   (9)
/HA35$4   (9)
/HA40$4   (9999)
/HA41$4   (9999)
/HA50$4   (9)
/HA52$4   (9)
/HA53$4   (999)
/HA54$4   (9)
/HA55$4   (9)
/HA56$4   (999)
/HA57$4   (9)
/HA58$4   (9)
/HA2$5    (9999)
/HA3$5    (9999)
/HA4$5    (9999)
/HA5$5    (9999)
/HA6$5    (99999)
/HA11$5   (9999)
/HA12$5   (99999)
/HA12A$5  (99999)
/HA12B$5  (99999)
/HA13$5   (9)
/HA35$5   (9)
/HA40$5   (9999)
/HA41$5   (9999)
/HA50$5   (9)
/HA52$5   (9)
/HA53$5   (999)
/HA54$5   (9)
/HA55$5   (9)
/HA56$5   (999)
/HA57$5   (9)
/HA58$5   (9)
/HA2$6    (9999)
/HA3$6    (9999)
/HA4$6    (9999)
/HA5$6    (9999)
/HA6$6    (99999)
/HA11$6   (9999)
/HA12$6   (99999)
/HA12A$6  (99999)
/HA12B$6  (99999)
/HA13$6   (9)
/HA35$6   (9)
/HA40$6   (9999)
/HA41$6   (9999)
/HA50$6   (9)
/HA52$6   (9)
/HA53$6   (999)
/HA54$6   (9)
/HA55$6   (9)
/HA56$6   (999)
/HA57$6   (9)
/HA58$6   (9)
/HA2$7    (9999)
/HA3$7    (9999)
/HA4$7    (9999)
/HA5$7    (9999)
/HA6$7    (99999)
/HA11$7   (9999)
/HA12$7   (99999)
/HA12A$7  (99999)
/HA12B$7  (99999)
/HA13$7   (9)
/HA35$7   (9)
/HA40$7   (9999)
/HA41$7   (9999)
/HA50$7   (9)
/HA52$7   (9)
/HA53$7   (999)
/HA54$7   (9)
/HA55$7   (9)
/HA56$7   (999)
/HA57$7   (9)
/HA58$7   (9)
/HA2$8    (9999)
/HA3$8    (9999)
/HA4$8    (9999)
/HA5$8    (9999)
/HA6$8    (99999)
/HA11$8   (9999)
/HA12$8   (99999)
/HA12A$8  (99999)
/HA12B$8  (99999)
/HA13$8   (9)
/HA35$8   (9)
/HA40$8   (9999)
/HA41$8   (9999)
/HA50$8   (9)
/HA52$8   (9)
/HA53$8   (999)
/HA54$8   (9)
/HA55$8   (9)
/HA56$8   (999)
/HA57$8   (9)
/HA58$8   (9)
/HC2$1    (9999)
/HC3$1    (9999)
/HC4$1    (9999)
/HC5$1    (9999)
/HC6$1    (99999)
/HC7$1    (9999)
/HC8$1    (9999)
/HC9$1    (99999)
/HC10$1   (9999)
/HC11$1   (9999)
/HC12$1   (99999)
/HC13$1   (9)
/HC15$1   (9)
/HC16$1   (99)
/HC27$1   (9)
/HC30$1   (99)
/HC31$1   (9999)
/HC52$1   (9)
/HC53$1   (999)
/HC55$1   (9)
/HC56$1   (9999)
/HC57$1   (9)
/HC58$1   (9)
/HC61$1   (9)
/HC62$1   (99)
/HC63$1   (999)
/HC64$1   (99)
/HC2$2    (9999)
/HC3$2    (9999)
/HC4$2    (9999)
/HC5$2    (9999)
/HC6$2    (99999)
/HC7$2    (9999)
/HC8$2    (9999)
/HC9$2    (99999)
/HC10$2   (9999)
/HC11$2   (9999)
/HC12$2   (99999)
/HC13$2   (9)
/HC15$2   (9)
/HC16$2   (99)
/HC27$2   (9)
/HC30$2   (99)
/HC31$2   (9999)
/HC52$2   (9)
/HC53$2   (999)
/HC55$2   (9)
/HC56$2   (9999)
/HC57$2   (9)
/HC58$2   (9)
/HC61$2   (9)
/HC62$2   (99)
/HC63$2   (999)
/HC64$2   (99)
/HC2$3    (9999)
/HC3$3    (9999)
/HC4$3    (9999)
/HC5$3    (9999)
/HC6$3    (99999)
/HC7$3    (9999)
/HC8$3    (9999)
/HC9$3    (99999)
/HC10$3   (9999)
/HC11$3   (9999)
/HC12$3   (99999)
/HC13$3   (9)
/HC15$3   (9)
/HC16$3   (99)
/HC27$3   (9)
/HC30$3   (99)
/HC31$3   (9999)
/HC52$3   (9)
/HC53$3   (999)
/HC55$3   (9)
/HC56$3   (9999)
/HC57$3   (9)
/HC58$3   (9)
/HC61$3   (9)
/HC62$3   (99)
/HC63$3   (999)
/HC64$3   (99)
/HC2$4    (9999)
/HC3$4    (9999)
/HC4$4    (9999)
/HC5$4    (9999)
/HC6$4    (99999)
/HC7$4    (9999)
/HC8$4    (9999)
/HC9$4    (99999)
/HC10$4   (9999)
/HC11$4   (9999)
/HC12$4   (99999)
/HC13$4   (9)
/HC15$4   (9)
/HC16$4   (99)
/HC27$4   (9)
/HC30$4   (99)
/HC31$4   (9999)
/HC52$4   (9)
/HC53$4   (999)
/HC55$4   (9)
/HC56$4   (9999)
/HC57$4   (9)
/HC58$4   (9)
/HC61$4   (9)
/HC62$4   (99)
/HC63$4   (999)
/HC64$4   (99)
/HC2$5    (9999)
/HC3$5    (9999)
/HC4$5    (9999)
/HC5$5    (9999)
/HC6$5    (99999)
/HC7$5    (9999)
/HC8$5    (9999)
/HC9$5    (99999)
/HC10$5   (9999)
/HC11$5   (9999)
/HC12$5   (99999)
/HC13$5   (9)
/HC15$5   (9)
/HC16$5   (99)
/HC27$5   (9)
/HC30$5   (99)
/HC31$5   (9999)
/HC52$5   (9)
/HC53$5   (999)
/HC55$5   (9)
/HC56$5   (9999)
/HC57$5   (9)
/HC58$5   (9)
/HC61$5   (9)
/HC62$5   (99)
/HC63$5   (999)
/HC64$5   (99)
/HC2$6    (9999)
/HC3$6    (9999)
/HC4$6    (9999)
/HC5$6    (9999)
/HC6$6    (99999)
/HC7$6    (9999)
/HC8$6    (9999)
/HC9$6    (99999)
/HC10$6   (9999)
/HC11$6   (9999)
/HC12$6   (99999)
/HC13$6   (9)
/HC15$6   (9)
/HC16$6   (99)
/HC27$6   (9)
/HC30$6   (99)
/HC31$6   (9999)
/HC52$6   (9)
/HC53$6   (999)
/HC55$6   (9)
/HC56$6   (9999)
/HC57$6   (9)
/HC58$6   (9)
/HC61$6   (9)
/HC62$6   (99)
/HC63$6   (999)
/HC64$6   (99)
.
VALUE LABELS
 HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
/HV020   
     0 "All woman sample"
     1 "Ever married sample"
/HV023   
     1 "Tigray, urban"
     2 "Tigray, rural"
     3 "Afar, urban"
     4 "Afar, rural"
     5 "Amhara, urban"
     6 "Amhara, rural"
     7 "Oromiya, urban"
     8 "Oromiya, rural"
     9 "Somali, urban"
    10 "Somali, rural"
    11 "Ben-Gumz, urban"
    12 "Ben-Gumz, rural"
    13 "SNNP, urban"
    14 "SNNP, rural"
    15 "Gambela, urban"
    16 "Gambela, rural"
    17 "Harrari, urban"
    18 "Harrari, rural"
    19 "Addis, urban"
    20 "Dire Dawa, urban"
    21 "Dire Dawa, rural"
/HV024   
     1 "Tigray"
     2 "Affar"
     3 "Amhara"
     4 "Oromiya"
     5 "Somali"
     6 "Ben-Gumz"
     7 "SNNP"
    12 "Gambela"
    13 "Harari"
    14 "Addis"
    15 "Dire Dawa"
/HV025   
     1 "Urban"
     2 "Rural"
/HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
/HV042   
     0 "Not selected"
     1 "Selected"
/HV043   
     0 "Household not selected"
     1 "Household selected"
/HV044   
     0 "Household not selected"
     1 "Household selected"
/HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into compound"
    13 "Piped outside compound"
    20 "WATER FROM OPEN WELL"
    21 "Open well"
    22 "Open spring"
    23 "Covered well"
    24 "Covered spring"
    31 "River"
    32 "Pond/lake/dam"
    40 "SURFACE WATER"
    41 "Rainwater"
    96 "Other"
/HV204   
   995 "One day or longer"
   996 "On premises"
/HV205   
    10 "FLUSH TOILET"
    11 "Flush toilet"
    20 "PIT TOILET LATRINE"
    21 "Traditional pit latrine"
    22 "Improved (ventilated) pit latrine"
    30 "NO FACILITY"
    31 "No facility, bush, field"
    96 "OTHER"
/HV206   
     0 "No"
     1 "Yes"
/HV207   
     0 "No"
     1 "Yes"
/HV208   
     0 "No"
     1 "Yes"
/HV210   
     0 "No"
     1 "Yes"
/HV211   
     0 "No"
     1 "Yes"
/HV212   
     0 "No"
     1 "Yes"
/HV213   
    10 "NATURAL FLOOR"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY FLOOR"
    21 "Wood planks"
    22 "Reed, bamboo"
    30 "FINISHED FLOOR"
    31 "Parquet, polished wood"
    32 "Vinyl sheets/tiles"
    33 "Cement"
    34 "Cement tiles/brick"
    35 "Carpet"
    96 "Other"
/HV215   
    10 "NATURAL"
    20 "RUDIMENTARY"
    21 "Wood or mulch"
    22 "Thatch"
    23 "Reed or bamboo"
    24 "Plastic sheet"
    27 "Mobile roofs of nomads"
    30 "FINISHED"
    31 "Corrugated iron"
    32 "Cement or concrete"
    96 "OTHER"
/HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
/HV219   
     1 "Male"
     2 "Female"
/HV220   
    97 "97+"
    98 "DK"
/HV221   
     0 "No"
     1 "Yes"
/HV225   
     0 "No"
     1 "Yes"
/HV226   
     1 "Electricity"
     2 "LPG, natural gas"
     3 "Biogas"
     4 "Kerosene"
     5 "Coal, lignite"
     6 "Charcoal"
     7 "Firewood, straw"
     8 "Dung"
     9 "Does not cook at home"
    96 "Other"
/HV227   
     0 "No"
     1 "Yes"
/HV101$01
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$01
     0 "No"
     1 "Yes"
/HV103$01
     0 "No"
     1 "Yes"
/HV104$01
     1 "Male"
     2 "Female"
/HV105$01
    97 "97+"
    98 "DK"
/HV106$01
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$01
    98 "DK"
/HV108$01
    97 "Inconsistent"
    98 "DK"
/HV109$01
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$01
     0 "No"
     1 "Yes"
/HV111$01
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$01
     0 "Mother not in HH"
/HV113$01
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$01
     0 "Father not in HH"
/HV117$01
     0 "Not eligible"
     1 "Eligible"
/HV118$01
     0 "Not eligible"
     1 "Eligible"
/HV120$01
     0 "Not eligible"
     1 "Eligible"
/HV121$01
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$01
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$01
    98 "DK"
/HV124$01
    97 "Inconsistent"
    98 "DK"
/HV125$01
     0 "No"
     1 "Yes"
/HV126$01
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$01
    98 "DK"
/HV128$01
    97 "Inconsistent"
    98 "DK"
/HV129$01
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$02
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$02
     0 "No"
     1 "Yes"
/HV103$02
     0 "No"
     1 "Yes"
/HV104$02
     1 "Male"
     2 "Female"
/HV105$02
    97 "97+"
    98 "DK"
/HV106$02
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$02
    98 "DK"
/HV108$02
    97 "Inconsistent"
    98 "DK"
/HV109$02
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$02
     0 "No"
     1 "Yes"
/HV111$02
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$02
     0 "Mother not in HH"
/HV113$02
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$02
     0 "Father not in HH"
/HV117$02
     0 "Not eligible"
     1 "Eligible"
/HV118$02
     0 "Not eligible"
     1 "Eligible"
/HV120$02
     0 "Not eligible"
     1 "Eligible"
/HV121$02
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$02
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$02
    98 "DK"
/HV124$02
    97 "Inconsistent"
    98 "DK"
/HV125$02
     0 "No"
     1 "Yes"
/HV126$02
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$02
    98 "DK"
/HV128$02
    97 "Inconsistent"
    98 "DK"
/HV129$02
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$03
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$03
     0 "No"
     1 "Yes"
/HV103$03
     0 "No"
     1 "Yes"
/HV104$03
     1 "Male"
     2 "Female"
/HV105$03
    97 "97+"
    98 "DK"
/HV106$03
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$03
    98 "DK"
/HV108$03
    97 "Inconsistent"
    98 "DK"
/HV109$03
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$03
     0 "No"
     1 "Yes"
/HV111$03
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$03
     0 "Mother not in HH"
/HV113$03
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$03
     0 "Father not in HH"
/HV117$03
     0 "Not eligible"
     1 "Eligible"
/HV118$03
     0 "Not eligible"
     1 "Eligible"
/HV120$03
     0 "Not eligible"
     1 "Eligible"
/HV121$03
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$03
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$03
    98 "DK"
/HV124$03
    97 "Inconsistent"
    98 "DK"
/HV125$03
     0 "No"
     1 "Yes"
/HV126$03
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$03
    98 "DK"
/HV128$03
    97 "Inconsistent"
    98 "DK"
/HV129$03
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$04
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$04
     0 "No"
     1 "Yes"
/HV103$04
     0 "No"
     1 "Yes"
/HV104$04
     1 "Male"
     2 "Female"
/HV105$04
    97 "97+"
    98 "DK"
/HV106$04
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$04
    98 "DK"
/HV108$04
    97 "Inconsistent"
    98 "DK"
/HV109$04
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$04
     0 "No"
     1 "Yes"
/HV111$04
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$04
     0 "Mother not in HH"
/HV113$04
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$04
     0 "Father not in HH"
/HV117$04
     0 "Not eligible"
     1 "Eligible"
/HV118$04
     0 "Not eligible"
     1 "Eligible"
/HV120$04
     0 "Not eligible"
     1 "Eligible"
/HV121$04
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$04
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$04
    98 "DK"
/HV124$04
    97 "Inconsistent"
    98 "DK"
/HV125$04
     0 "No"
     1 "Yes"
/HV126$04
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$04
    98 "DK"
/HV128$04
    97 "Inconsistent"
    98 "DK"
/HV129$04
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$05
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$05
     0 "No"
     1 "Yes"
/HV103$05
     0 "No"
     1 "Yes"
/HV104$05
     1 "Male"
     2 "Female"
/HV105$05
    97 "97+"
    98 "DK"
/HV106$05
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$05
    98 "DK"
/HV108$05
    97 "Inconsistent"
    98 "DK"
/HV109$05
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$05
     0 "No"
     1 "Yes"
/HV111$05
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$05
     0 "Mother not in HH"
/HV113$05
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$05
     0 "Father not in HH"
/HV117$05
     0 "Not eligible"
     1 "Eligible"
/HV118$05
     0 "Not eligible"
     1 "Eligible"
/HV120$05
     0 "Not eligible"
     1 "Eligible"
/HV121$05
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$05
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$05
    98 "DK"
/HV124$05
    97 "Inconsistent"
    98 "DK"
/HV125$05
     0 "No"
     1 "Yes"
/HV126$05
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$05
    98 "DK"
/HV128$05
    97 "Inconsistent"
    98 "DK"
/HV129$05
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$06
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$06
     0 "No"
     1 "Yes"
/HV103$06
     0 "No"
     1 "Yes"
/HV104$06
     1 "Male"
     2 "Female"
/HV105$06
    97 "97+"
    98 "DK"
/HV106$06
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$06
    98 "DK"
/HV108$06
    97 "Inconsistent"
    98 "DK"
/HV109$06
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$06
     0 "No"
     1 "Yes"
/HV111$06
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$06
     0 "Mother not in HH"
/HV113$06
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$06
     0 "Father not in HH"
/HV117$06
     0 "Not eligible"
     1 "Eligible"
/HV118$06
     0 "Not eligible"
     1 "Eligible"
/HV120$06
     0 "Not eligible"
     1 "Eligible"
/HV121$06
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$06
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$06
    98 "DK"
/HV124$06
    97 "Inconsistent"
    98 "DK"
/HV125$06
     0 "No"
     1 "Yes"
/HV126$06
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$06
    98 "DK"
/HV128$06
    97 "Inconsistent"
    98 "DK"
/HV129$06
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$07
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$07
     0 "No"
     1 "Yes"
/HV103$07
     0 "No"
     1 "Yes"
/HV104$07
     1 "Male"
     2 "Female"
/HV105$07
    97 "97+"
    98 "DK"
/HV106$07
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$07
    98 "DK"
/HV108$07
    97 "Inconsistent"
    98 "DK"
/HV109$07
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$07
     0 "No"
     1 "Yes"
/HV111$07
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$07
     0 "Mother not in HH"
/HV113$07
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$07
     0 "Father not in HH"
/HV117$07
     0 "Not eligible"
     1 "Eligible"
/HV118$07
     0 "Not eligible"
     1 "Eligible"
/HV120$07
     0 "Not eligible"
     1 "Eligible"
/HV121$07
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$07
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$07
    98 "DK"
/HV124$07
    97 "Inconsistent"
    98 "DK"
/HV125$07
     0 "No"
     1 "Yes"
/HV126$07
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$07
    98 "DK"
/HV128$07
    97 "Inconsistent"
    98 "DK"
/HV129$07
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$08
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$08
     0 "No"
     1 "Yes"
/HV103$08
     0 "No"
     1 "Yes"
/HV104$08
     1 "Male"
     2 "Female"
/HV105$08
    97 "97+"
    98 "DK"
/HV106$08
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$08
    98 "DK"
/HV108$08
    97 "Inconsistent"
    98 "DK"
/HV109$08
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$08
     0 "No"
     1 "Yes"
/HV111$08
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$08
     0 "Mother not in HH"
/HV113$08
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$08
     0 "Father not in HH"
/HV117$08
     0 "Not eligible"
     1 "Eligible"
/HV118$08
     0 "Not eligible"
     1 "Eligible"
/HV120$08
     0 "Not eligible"
     1 "Eligible"
/HV121$08
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$08
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$08
    98 "DK"
/HV124$08
    97 "Inconsistent"
    98 "DK"
/HV125$08
     0 "No"
     1 "Yes"
/HV126$08
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$08
    98 "DK"
/HV128$08
    97 "Inconsistent"
    98 "DK"
/HV129$08
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$09
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$09
     0 "No"
     1 "Yes"
/HV103$09
     0 "No"
     1 "Yes"
/HV104$09
     1 "Male"
     2 "Female"
/HV105$09
    97 "97+"
    98 "DK"
/HV106$09
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$09
    98 "DK"
/HV108$09
    97 "Inconsistent"
    98 "DK"
/HV109$09
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$09
     0 "No"
     1 "Yes"
/HV111$09
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$09
     0 "Mother not in HH"
/HV113$09
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$09
     0 "Father not in HH"
/HV117$09
     0 "Not eligible"
     1 "Eligible"
/HV118$09
     0 "Not eligible"
     1 "Eligible"
/HV120$09
     0 "Not eligible"
     1 "Eligible"
/HV121$09
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$09
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$09
    98 "DK"
/HV124$09
    97 "Inconsistent"
    98 "DK"
/HV125$09
     0 "No"
     1 "Yes"
/HV126$09
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$09
    98 "DK"
/HV128$09
    97 "Inconsistent"
    98 "DK"
/HV129$09
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$10
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$10
     0 "No"
     1 "Yes"
/HV103$10
     0 "No"
     1 "Yes"
/HV104$10
     1 "Male"
     2 "Female"
/HV105$10
    97 "97+"
    98 "DK"
/HV106$10
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$10
    98 "DK"
/HV108$10
    97 "Inconsistent"
    98 "DK"
/HV109$10
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$10
     0 "No"
     1 "Yes"
/HV111$10
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$10
     0 "Mother not in HH"
/HV113$10
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$10
     0 "Father not in HH"
/HV117$10
     0 "Not eligible"
     1 "Eligible"
/HV118$10
     0 "Not eligible"
     1 "Eligible"
/HV120$10
     0 "Not eligible"
     1 "Eligible"
/HV121$10
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$10
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$10
    98 "DK"
/HV124$10
    97 "Inconsistent"
    98 "DK"
/HV125$10
     0 "No"
     1 "Yes"
/HV126$10
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$10
    98 "DK"
/HV128$10
    97 "Inconsistent"
    98 "DK"
/HV129$10
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$11
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$11
     0 "No"
     1 "Yes"
/HV103$11
     0 "No"
     1 "Yes"
/HV104$11
     1 "Male"
     2 "Female"
/HV105$11
    97 "97+"
    98 "DK"
/HV106$11
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$11
    98 "DK"
/HV108$11
    97 "Inconsistent"
    98 "DK"
/HV109$11
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$11
     0 "No"
     1 "Yes"
/HV111$11
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$11
     0 "Mother not in HH"
/HV113$11
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$11
     0 "Father not in HH"
/HV117$11
     0 "Not eligible"
     1 "Eligible"
/HV118$11
     0 "Not eligible"
     1 "Eligible"
/HV120$11
     0 "Not eligible"
     1 "Eligible"
/HV121$11
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$11
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$11
    98 "DK"
/HV124$11
    97 "Inconsistent"
    98 "DK"
/HV125$11
     0 "No"
     1 "Yes"
/HV126$11
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$11
    98 "DK"
/HV128$11
    97 "Inconsistent"
    98 "DK"
/HV129$11
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$12
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$12
     0 "No"
     1 "Yes"
/HV103$12
     0 "No"
     1 "Yes"
/HV104$12
     1 "Male"
     2 "Female"
/HV105$12
    97 "97+"
    98 "DK"
/HV106$12
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$12
    98 "DK"
/HV108$12
    97 "Inconsistent"
    98 "DK"
/HV109$12
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$12
     0 "No"
     1 "Yes"
/HV111$12
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$12
     0 "Mother not in HH"
/HV113$12
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$12
     0 "Father not in HH"
/HV117$12
     0 "Not eligible"
     1 "Eligible"
/HV118$12
     0 "Not eligible"
     1 "Eligible"
/HV120$12
     0 "Not eligible"
     1 "Eligible"
/HV121$12
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$12
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$12
    98 "DK"
/HV124$12
    97 "Inconsistent"
    98 "DK"
/HV125$12
     0 "No"
     1 "Yes"
/HV126$12
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$12
    98 "DK"
/HV128$12
    97 "Inconsistent"
    98 "DK"
/HV129$12
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$13
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$13
     0 "No"
     1 "Yes"
/HV103$13
     0 "No"
     1 "Yes"
/HV104$13
     1 "Male"
     2 "Female"
/HV105$13
    97 "97+"
    98 "DK"
/HV106$13
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$13
    98 "DK"
/HV108$13
    97 "Inconsistent"
    98 "DK"
/HV109$13
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$13
     0 "No"
     1 "Yes"
/HV111$13
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$13
     0 "Mother not in HH"
/HV113$13
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$13
     0 "Father not in HH"
/HV117$13
     0 "Not eligible"
     1 "Eligible"
/HV118$13
     0 "Not eligible"
     1 "Eligible"
/HV120$13
     0 "Not eligible"
     1 "Eligible"
/HV121$13
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$13
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$13
    98 "DK"
/HV124$13
    97 "Inconsistent"
    98 "DK"
/HV125$13
     0 "No"
     1 "Yes"
/HV126$13
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$13
    98 "DK"
/HV128$13
    97 "Inconsistent"
    98 "DK"
/HV129$13
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$14
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$14
     0 "No"
     1 "Yes"
/HV103$14
     0 "No"
     1 "Yes"
/HV104$14
     1 "Male"
     2 "Female"
/HV105$14
    97 "97+"
    98 "DK"
/HV106$14
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$14
    98 "DK"
/HV108$14
    97 "Inconsistent"
    98 "DK"
/HV109$14
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$14
     0 "No"
     1 "Yes"
/HV111$14
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$14
     0 "Mother not in HH"
/HV113$14
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$14
     0 "Father not in HH"
/HV117$14
     0 "Not eligible"
     1 "Eligible"
/HV118$14
     0 "Not eligible"
     1 "Eligible"
/HV120$14
     0 "Not eligible"
     1 "Eligible"
/HV121$14
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$14
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$14
    98 "DK"
/HV124$14
    97 "Inconsistent"
    98 "DK"
/HV125$14
     0 "No"
     1 "Yes"
/HV126$14
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$14
    98 "DK"
/HV128$14
    97 "Inconsistent"
    98 "DK"
/HV129$14
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$15
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$15
     0 "No"
     1 "Yes"
/HV103$15
     0 "No"
     1 "Yes"
/HV104$15
     1 "Male"
     2 "Female"
/HV105$15
    97 "97+"
    98 "DK"
/HV106$15
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$15
    98 "DK"
/HV108$15
    97 "Inconsistent"
    98 "DK"
/HV109$15
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$15
     0 "No"
     1 "Yes"
/HV111$15
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$15
     0 "Mother not in HH"
/HV113$15
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$15
     0 "Father not in HH"
/HV117$15
     0 "Not eligible"
     1 "Eligible"
/HV118$15
     0 "Not eligible"
     1 "Eligible"
/HV120$15
     0 "Not eligible"
     1 "Eligible"
/HV121$15
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$15
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$15
    98 "DK"
/HV124$15
    97 "Inconsistent"
    98 "DK"
/HV125$15
     0 "No"
     1 "Yes"
/HV126$15
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$15
    98 "DK"
/HV128$15
    97 "Inconsistent"
    98 "DK"
/HV129$15
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$16
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$16
     0 "No"
     1 "Yes"
/HV103$16
     0 "No"
     1 "Yes"
/HV104$16
     1 "Male"
     2 "Female"
/HV105$16
    97 "97+"
    98 "DK"
/HV106$16
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$16
    98 "DK"
/HV108$16
    97 "Inconsistent"
    98 "DK"
/HV109$16
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$16
     0 "No"
     1 "Yes"
/HV111$16
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$16
     0 "Mother not in HH"
/HV113$16
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$16
     0 "Father not in HH"
/HV117$16
     0 "Not eligible"
     1 "Eligible"
/HV118$16
     0 "Not eligible"
     1 "Eligible"
/HV120$16
     0 "Not eligible"
     1 "Eligible"
/HV121$16
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$16
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$16
    98 "DK"
/HV124$16
    97 "Inconsistent"
    98 "DK"
/HV125$16
     0 "No"
     1 "Yes"
/HV126$16
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$16
    98 "DK"
/HV128$16
    97 "Inconsistent"
    98 "DK"
/HV129$16
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$17
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$17
     0 "No"
     1 "Yes"
/HV103$17
     0 "No"
     1 "Yes"
/HV104$17
     1 "Male"
     2 "Female"
/HV105$17
    97 "97+"
    98 "DK"
/HV106$17
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$17
    98 "DK"
/HV108$17
    97 "Inconsistent"
    98 "DK"
/HV109$17
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$17
     0 "No"
     1 "Yes"
/HV111$17
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$17
     0 "Mother not in HH"
/HV113$17
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$17
     0 "Father not in HH"
/HV117$17
     0 "Not eligible"
     1 "Eligible"
/HV118$17
     0 "Not eligible"
     1 "Eligible"
/HV120$17
     0 "Not eligible"
     1 "Eligible"
/HV121$17
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$17
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$17
    98 "DK"
/HV124$17
    97 "Inconsistent"
    98 "DK"
/HV125$17
     0 "No"
     1 "Yes"
/HV126$17
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$17
    98 "DK"
/HV128$17
    97 "Inconsistent"
    98 "DK"
/HV129$17
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$18
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$18
     0 "No"
     1 "Yes"
/HV103$18
     0 "No"
     1 "Yes"
/HV104$18
     1 "Male"
     2 "Female"
/HV105$18
    97 "97+"
    98 "DK"
/HV106$18
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$18
    98 "DK"
/HV108$18
    97 "Inconsistent"
    98 "DK"
/HV109$18
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$18
     0 "No"
     1 "Yes"
/HV111$18
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$18
     0 "Mother not in HH"
/HV113$18
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$18
     0 "Father not in HH"
/HV117$18
     0 "Not eligible"
     1 "Eligible"
/HV118$18
     0 "Not eligible"
     1 "Eligible"
/HV120$18
     0 "Not eligible"
     1 "Eligible"
/HV121$18
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$18
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$18
    98 "DK"
/HV124$18
    97 "Inconsistent"
    98 "DK"
/HV125$18
     0 "No"
     1 "Yes"
/HV126$18
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$18
    98 "DK"
/HV128$18
    97 "Inconsistent"
    98 "DK"
/HV129$18
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$19
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$19
     0 "No"
     1 "Yes"
/HV103$19
     0 "No"
     1 "Yes"
/HV104$19
     1 "Male"
     2 "Female"
/HV105$19
    97 "97+"
    98 "DK"
/HV106$19
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$19
    98 "DK"
/HV108$19
    97 "Inconsistent"
    98 "DK"
/HV109$19
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$19
     0 "No"
     1 "Yes"
/HV111$19
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$19
     0 "Mother not in HH"
/HV113$19
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$19
     0 "Father not in HH"
/HV117$19
     0 "Not eligible"
     1 "Eligible"
/HV118$19
     0 "Not eligible"
     1 "Eligible"
/HV120$19
     0 "Not eligible"
     1 "Eligible"
/HV121$19
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$19
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$19
    98 "DK"
/HV124$19
    97 "Inconsistent"
    98 "DK"
/HV125$19
     0 "No"
     1 "Yes"
/HV126$19
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$19
    98 "DK"
/HV128$19
    97 "Inconsistent"
    98 "DK"
/HV129$19
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/HV101$20
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$20
     0 "No"
     1 "Yes"
/HV103$20
     0 "No"
     1 "Yes"
/HV104$20
     1 "Male"
     2 "Female"
/HV105$20
    97 "97+"
    98 "DK"
/HV106$20
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$20
    98 "DK"
/HV108$20
    97 "Inconsistent"
    98 "DK"
/HV109$20
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$20
     0 "No"
     1 "Yes"
/HV111$20
     0 "No"
     1 "Yes"
     8 "DK"
/HV112$20
     0 "Mother not in HH"
/HV113$20
     0 "No"
     1 "Yes"
     8 "DK"
/HV114$20
     0 "Father not in HH"
/HV117$20
     0 "Not eligible"
     1 "Eligible"
/HV118$20
     0 "Not eligible"
     1 "Eligible"
/HV120$20
     0 "Not eligible"
     1 "Eligible"
/HV121$20
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
/HV122$20
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV123$20
    98 "DK"
/HV124$20
    97 "Inconsistent"
    98 "DK"
/HV125$20
     0 "No"
     1 "Yes"
/HV126$20
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV127$20
    98 "DK"
/HV128$20
    97 "Inconsistent"
    98 "DK"
/HV129$20
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
/SH25E   
     0 "No"
     1 "Yes"
/SH25F   
     0 "No"
     1 "Yes"
/SH25G   
     0 "No"
     1 "Yes"
/SH25AA  
     0 "No"
     1 "Yes"
/SH25AB  
     0 "No"
     1 "Yes"
/SH25AC  
     0 "No"
     1 "Yes"
/SH25AD  
     0 "No"
     1 "Yes"
/SH25AE  
     0 "No"
     1 "Yes"
/SH25AF  
     0 "No"
     1 "Yes"
/SH28D   
     0 "No"
     1 "Yes"
/SH29A   
     0 "No"
     1 "Yes"
/SH29B   
     0 "No"
     1 "Yes"
/SH29C   
     0 "No"
     1 "Yes"
/SH29D   
     0 "No"
     1 "Yes"
/SH29E   
     0 "No"
     1 "Yes"
/SH29F   
     0 "No"
     1 "Yes"
/SH29BA  
     0 "No"
     1 "Yes"
/SH29BB  
     0 "No"
     1 "Yes"
/SH29BC  
     0 "No"
     1 "Yes"
/SH29BD  
     0 "No"
     1 "Yes"
/SH29BE  
     0 "No"
     1 "Yes"
/SH29BF  
     0 "No"
     1 "Yes"
/SH29BG  
     0 "No"
     1 "Yes"
/SH29BH  
     0 "No"
     1 "Yes"
/SH29BI  
     0 "No"
     1 "Yes"
/SH29BJ  
     0 "No"
     1 "Yes"
/SH29BK  
     0 "No"
     1 "Yes"
/SH29BL  
     0 "No"
     1 "Yes"
/SH29BM  
     0 "No"
     1 "Yes"
/SH29BX  
     0 "No"
     1 "Yes"
/SH29CA  
     0 "No"
     1 "Yes"
/SH29DA  
     0 "No"
     1 "Yes"
/SH29DB  
     0 "No"
     1 "Yes"
/SH29GA  
     0 "No"
     1 "Yes"
/SH35    
     1 "0 PPM (No Iodine)"
     2 "25 PPM"
     3 "50 PPM"
     4 "75 PPM"
     5 "100 PPM"
/SH14$01 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$02 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$03 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$04 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$05 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$06 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$07 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$08 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$09 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$10 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$11 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$12 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$13 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$14 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$15 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$16 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$17 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$18 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$19 
     0 "No"
     1 "Yes"
     8 "DK"
/SH14$20 
     0 "No"
     1 "Yes"
     8 "DK"
/HA4$1   
  9998 "Flagged cases"
/HA5$1   
  9998 "Flagged cases"
/HA6$1   
 99998 "Flagged cases"
/HA11$1  
  9998 "Flagged cases"
/HA12$1  
 99998 "Flagged cases"
/HA12A$1 
 99998 "Flagged cases"
/HA12B$1 
 99998 "Flagged cases"
/HA13$1  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$1  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$1  
  9998 "Flagged cases"
/HA41$1  
  9998 "Flagged cases"
/HA4$2   
  9998 "Flagged cases"
/HA5$2   
  9998 "Flagged cases"
/HA6$2   
 99998 "Flagged cases"
/HA11$2  
  9998 "Flagged cases"
/HA12$2  
 99998 "Flagged cases"
/HA12A$2 
 99998 "Flagged cases"
/HA12B$2 
 99998 "Flagged cases"
/HA13$2  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$2  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$2  
  9998 "Flagged cases"
/HA41$2  
  9998 "Flagged cases"
/HA4$3   
  9998 "Flagged cases"
/HA5$3   
  9998 "Flagged cases"
/HA6$3   
 99998 "Flagged cases"
/HA11$3  
  9998 "Flagged cases"
/HA12$3  
 99998 "Flagged cases"
/HA12A$3 
 99998 "Flagged cases"
/HA12B$3 
 99998 "Flagged cases"
/HA13$3  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$3  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$3  
  9998 "Flagged cases"
/HA41$3  
  9998 "Flagged cases"
/HA4$4   
  9998 "Flagged cases"
/HA5$4   
  9998 "Flagged cases"
/HA6$4   
 99998 "Flagged cases"
/HA11$4  
  9998 "Flagged cases"
/HA12$4  
 99998 "Flagged cases"
/HA12A$4 
 99998 "Flagged cases"
/HA12B$4 
 99998 "Flagged cases"
/HA13$4  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$4  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$4  
  9998 "Flagged cases"
/HA41$4  
  9998 "Flagged cases"
/HA4$5   
  9998 "Flagged cases"
/HA5$5   
  9998 "Flagged cases"
/HA6$5   
 99998 "Flagged cases"
/HA11$5  
  9998 "Flagged cases"
/HA12$5  
 99998 "Flagged cases"
/HA12A$5 
 99998 "Flagged cases"
/HA12B$5 
 99998 "Flagged cases"
/HA13$5  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$5  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$5  
  9998 "Flagged cases"
/HA41$5  
  9998 "Flagged cases"
/HA4$6   
  9998 "Flagged cases"
/HA5$6   
  9998 "Flagged cases"
/HA6$6   
 99998 "Flagged cases"
/HA11$6  
  9998 "Flagged cases"
/HA12$6  
 99998 "Flagged cases"
/HA12A$6 
 99998 "Flagged cases"
/HA12B$6 
 99998 "Flagged cases"
/HA13$6  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$6  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$6  
  9998 "Flagged cases"
/HA41$6  
  9998 "Flagged cases"
/HA4$7   
  9998 "Flagged cases"
/HA5$7   
  9998 "Flagged cases"
/HA6$7   
 99998 "Flagged cases"
/HA11$7  
  9998 "Flagged cases"
/HA12$7  
 99998 "Flagged cases"
/HA12A$7 
 99998 "Flagged cases"
/HA12B$7 
 99998 "Flagged cases"
/HA13$7  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$7  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$7  
  9998 "Flagged cases"
/HA41$7  
  9998 "Flagged cases"
/HA4$8   
  9998 "Flagged cases"
/HA5$8   
  9998 "Flagged cases"
/HA6$8   
 99998 "Flagged cases"
/HA11$8  
  9998 "Flagged cases"
/HA12$8  
 99998 "Flagged cases"
/HA12A$8 
 99998 "Flagged cases"
/HA12B$8 
 99998 "Flagged cases"
/HA13$8  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HA33$8  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HA40$8  
  9998 "Flagged cases"
/HA41$8  
  9998 "Flagged cases"
/HC4$1   
  9998 "Flagged cases"
/HC5$1   
  9998 "Flagged cases"
/HC6$1   
 99998 "Flagged cases"
/HC7$1   
  9998 "Flagged cases"
/HC8$1   
  9998 "Flagged cases"
/HC9$1   
 99998 "Flagged cases"
/HC10$1  
  9998 "Flagged cases"
/HC11$1  
  9998 "Flagged cases"
/HC12$1  
 99998 "Flagged cases"
/HC13$1  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$1  
     1 "Lying"
     2 "Standing"
/HC27$1  
     1 "Male"
     2 "Female"
/HC30$1  
    97 "Inconsistent"
    98 "DK"
/HC31$1  
  9997 "Inconsistent"
  9998 "DK"
/HC33$1  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$1  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$1  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/HC4$2   
  9998 "Flagged cases"
/HC5$2   
  9998 "Flagged cases"
/HC6$2   
 99998 "Flagged cases"
/HC7$2   
  9998 "Flagged cases"
/HC8$2   
  9998 "Flagged cases"
/HC9$2   
 99998 "Flagged cases"
/HC10$2  
  9998 "Flagged cases"
/HC11$2  
  9998 "Flagged cases"
/HC12$2  
 99998 "Flagged cases"
/HC13$2  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$2  
     1 "Lying"
     2 "Standing"
/HC27$2  
     1 "Male"
     2 "Female"
/HC30$2  
    97 "Inconsistent"
    98 "DK"
/HC31$2  
  9997 "Inconsistent"
  9998 "DK"
/HC33$2  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$2  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$2  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/HC4$3   
  9998 "Flagged cases"
/HC5$3   
  9998 "Flagged cases"
/HC6$3   
 99998 "Flagged cases"
/HC7$3   
  9998 "Flagged cases"
/HC8$3   
  9998 "Flagged cases"
/HC9$3   
 99998 "Flagged cases"
/HC10$3  
  9998 "Flagged cases"
/HC11$3  
  9998 "Flagged cases"
/HC12$3  
 99998 "Flagged cases"
/HC13$3  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$3  
     1 "Lying"
     2 "Standing"
/HC27$3  
     1 "Male"
     2 "Female"
/HC30$3  
    97 "Inconsistent"
    98 "DK"
/HC31$3  
  9997 "Inconsistent"
  9998 "DK"
/HC33$3  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$3  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$3  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/HC4$4   
  9998 "Flagged cases"
/HC5$4   
  9998 "Flagged cases"
/HC6$4   
 99998 "Flagged cases"
/HC7$4   
  9998 "Flagged cases"
/HC8$4   
  9998 "Flagged cases"
/HC9$4   
 99998 "Flagged cases"
/HC10$4  
  9998 "Flagged cases"
/HC11$4  
  9998 "Flagged cases"
/HC12$4  
 99998 "Flagged cases"
/HC13$4  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$4  
     1 "Lying"
     2 "Standing"
/HC27$4  
     1 "Male"
     2 "Female"
/HC30$4  
    97 "Inconsistent"
    98 "DK"
/HC31$4  
  9997 "Inconsistent"
  9998 "DK"
/HC33$4  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$4  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$4  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/HC4$5   
  9998 "Flagged cases"
/HC5$5   
  9998 "Flagged cases"
/HC6$5   
 99998 "Flagged cases"
/HC7$5   
  9998 "Flagged cases"
/HC8$5   
  9998 "Flagged cases"
/HC9$5   
 99998 "Flagged cases"
/HC10$5  
  9998 "Flagged cases"
/HC11$5  
  9998 "Flagged cases"
/HC12$5  
 99998 "Flagged cases"
/HC13$5  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$5  
     1 "Lying"
     2 "Standing"
/HC27$5  
     1 "Male"
     2 "Female"
/HC30$5  
    97 "Inconsistent"
    98 "DK"
/HC31$5  
  9997 "Inconsistent"
  9998 "DK"
/HC33$5  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$5  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$5  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/HC4$6   
  9998 "Flagged cases"
/HC5$6   
  9998 "Flagged cases"
/HC6$6   
 99998 "Flagged cases"
/HC7$6   
  9998 "Flagged cases"
/HC8$6   
  9998 "Flagged cases"
/HC9$6   
 99998 "Flagged cases"
/HC10$6  
  9998 "Flagged cases"
/HC11$6  
  9998 "Flagged cases"
/HC12$6  
 99998 "Flagged cases"
/HC13$6  
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
/HC15$6  
     1 "Lying"
     2 "Standing"
/HC27$6  
     1 "Male"
     2 "Female"
/HC30$6  
    97 "Inconsistent"
    98 "DK"
/HC31$6  
  9997 "Inconsistent"
  9998 "DK"
/HC33$6  
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
/HC60$6  
   993 "Mother not de facto"
   994 "Incomplete women's interview"
   995 "Not in household"
/HC61$6  
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
.
